// This file is generated by AI.

// 光标定位对话的规则测试。
//
// 后端给出的 `SayLine.line` 是语句**首行**行号且从 0 起算, `lineCount` 是它占据的行数
// (WebGAL 语句可以跨行)。配音卡必须按 `[line, line + lineCount)` 区间判定, 只比较
// 行号相等会出现两类错乱: 光标停在续行时被当成"不在对话上", 或落到相邻的非对话行上。

import { describe, expect, it } from 'vitest';

import type { SayLine } from '../src/commands/voice';
import { dialogueAtLine, isDialogueLine } from '../src/voice/types';

/** 构造一条对话 (只关心定位相关的字段) */
function say(line: number, lineCount = 1, text = '台词'): SayLine {
  return {
    line,
    lineCount,
    speaker: '爱音',
    speakerInherited: false,
    text,
    vocal: null,
    figureId: null,
    figureSide: null,
    hash: `${line}-${text}`,
  };
}

/*
 * 一份手写的小场景 (0 起算行号):
 *   0  changeBg:bg.png;
 *   1  爱音:第一句;
 *   2  爱音:跨行第一段
 *   3       跨行第二段;
 *   4  changeFigure:aina.png;
 *   5  :旁白;
 */
const scene: SayLine[] = [say(1, 1, '第一句'), say(2, 2, '跨行第一段'), say(5, 1, '旁白')];

describe('dialogueAtLine', () => {
  it('命中语句首行', () => {
    expect(dialogueAtLine(scene, 1)?.text).toBe('第一句');
  });

  it('命中跨行语句的续行', () => {
    expect(dialogueAtLine(scene, 2)?.text).toBe('跨行第一段');
    expect(dialogueAtLine(scene, 3)?.text).toBe('跨行第一段');
  });

  it('停在演出语句上返回 null', () => {
    expect(dialogueAtLine(scene, 0)).toBeNull();
    expect(dialogueAtLine(scene, 4)).toBeNull();
  });

  it('越过最后一条语句返回 null', () => {
    expect(dialogueAtLine(scene, 6)).toBeNull();
    expect(dialogueAtLine(scene, 99)).toBeNull();
  });

  it('空列表与非法行号返回 null', () => {
    expect(dialogueAtLine([], 0)).toBeNull();
    expect(dialogueAtLine(scene, -1)).toBeNull();
  });

  it('语句在场景末尾跨行时仍能命中续行', () => {
    const tail = [say(0), say(3, 3, '结尾跨行')];
    expect(dialogueAtLine(tail, 3)?.text).toBe('结尾跨行');
    expect(dialogueAtLine(tail, 5)?.text).toBe('结尾跨行');
    expect(dialogueAtLine(tail, 6)).toBeNull();
  });

  it('按二分定位到的是最后一条首行不大于该行的语句', () => {
    const many = Array.from({ length: 40 }, (_, index) => say(index * 2, 1, `第${index}句`));
    expect(dialogueAtLine(many, 0)?.text).toBe('第0句');
    expect(dialogueAtLine(many, 20)?.text).toBe('第10句');
    expect(dialogueAtLine(many, 21)).toBeNull();
    expect(dialogueAtLine(many, 78)?.text).toBe('第39句');
  });

  it('lineCount 缺省或非法时按 1 行处理', () => {
    const broken = [{ ...say(4), lineCount: 0 }, { ...say(6), lineCount: undefined as unknown as number }];
    expect(dialogueAtLine(broken, 4)?.line).toBe(4);
    expect(dialogueAtLine(broken, 5)).toBeNull();
    expect(dialogueAtLine(broken, 6)?.line).toBe(6);
  });
});

describe('isDialogueLine', () => {
  it('与 dialogueAtLine 同义', () => {
    expect(isDialogueLine(scene, 1)).toBe(true);
    expect(isDialogueLine(scene, 3)).toBe(true);
    expect(isDialogueLine(scene, 4)).toBe(false);
  });
});
