// This file is generated by AI.

// 对话者到角色的静默匹配测试。
//
// 匹配失败只是"下拉框没选中", 但错误匹配会让整段对话用错音色, 因此这里重点覆盖:
// 立绘优先、别名、旁白继承、显式空说话者 (旁白) 不继承。

import { describe, expect, it } from 'vitest';

import type { Character, SayLine } from '../src/commands/voice';
import { figureIdsBySpeaker, matchCharacter, matchScene, type MatchContext } from '../src/voice/match';

function say(line: number, speaker: string | null, text: string, figureId: string | null = null): SayLine {
  return {
    line,
    speaker,
    speakerInherited: false,
    text,
    vocal: null,
    figureId,
    figureSide: null,
    hash: `h${line}`,
  };
}

function character(id: string, name: string, aliases: string[] = [], enabled = true): Character {
  return {
    id,
    name,
    aliases,
    description: '',
    language: 'auto',
    references: [],
    model: null,
    starred: false,
    enabled,
    createdAt: 0,
    updatedAt: 0,
  };
}

const anon = character('anon', '千早爱音', ['anon']);
const soyo = character('soyo', '长崎素世', ['soyo']);

function context(characters: Character[], dialogues: SayLine[], overrides: Record<string, string> = {}): MatchContext {
  return {
    characters,
    overrides,
    resolved: {},
    figureIds: figureIdsBySpeaker(dialogues),
  };
}

describe('figureIdsBySpeaker', () => {
  it('按归一化说话者收集立绘 id', () => {
    const map = figureIdsBySpeaker([say(0, '千早爱音', 'a', 'anon'), say(1, ' 千早爱音 ', 'b', 'anon-2')]);
    expect(map.get('千早爱音')).toEqual(new Set(['anon', 'anon-2']));
  });

  it('无立绘或无说话者的行不参与', () => {
    const map = figureIdsBySpeaker([say(0, '爱音', 'a'), say(1, null, 'b', 'anon')]);
    expect(map.size).toBe(0);
  });
});

describe('matchCharacter', () => {
  it('按立绘 id 命中角色别名', () => {
    const dialogues = [say(0, '千早爱音', '内容', 'anon')];
    const result = matchCharacter(dialogues[0], context([anon, soyo], dialogues));
    expect(result).toEqual({ characterId: 'anon', reason: 'figureId' });
  });

  it('按名称精确匹配', () => {
    const line = say(0, '长崎素世', '内容');
    expect(matchCharacter(line, context([anon, soyo], [line]))).toEqual({
      characterId: 'soyo',
      reason: 'name',
    });
  });

  it('按别名精确匹配', () => {
    const line = say(0, 'anon', '内容');
    expect(matchCharacter(line, context([anon], [line]))).toEqual({
      characterId: 'anon',
      reason: 'alias',
    });
  });

  it('忽略大小写与空白差异', () => {
    const line = say(0, '  ANON ', '内容');
    expect(matchCharacter(line, context([anon], [line])).characterId).toBe('anon');
  });

  it('人工覆盖优先于自动匹配', () => {
    const line = say(0, '千早爱音', '内容', 'anon');
    const result = matchCharacter(line, context([anon, soyo], [line], { 千早爱音: 'soyo' }));
    expect(result).toEqual({ characterId: 'soyo', reason: 'override' });
  });

  it('覆盖指向已删除或未启用的角色时回退到自动匹配', () => {
    const disabled = { ...soyo, enabled: false };
    const line = say(0, '长崎素世', '内容');
    const result = matchCharacter(line, context([anon, disabled], [line], { 长崎素世: 'soyo' }));
    expect(result.reason).toBe('none');
  });

  it('旁白不按说话者匹配', () => {
    const line = say(0, null, '旁白内容');
    expect(matchCharacter(line, context([anon], [line]))).toEqual({
      characterId: null,
      reason: 'narration',
    });
  });

  it('无任何线索时返回 none', () => {
    const line = say(0, '路人甲', '内容');
    expect(matchCharacter(line, context([anon, soyo], [line]))).toEqual({
      characterId: null,
      reason: 'none',
    });
  });
});

describe('matchScene', () => {
  it('按顺序匹配整场景, 并在换人后继续匹配', () => {
    const dialogues = [
      say(0, '千早爱音', '你爱我吗？', 'anon'),
      say(1, '长崎素世', '唉？', 'soyo'),
      say(2, '千早爱音', '回答我。', 'anon'),
    ];
    const matches = matchScene(dialogues, [anon, soyo]);
    expect(matches.get(0)?.characterId).toBe('anon');
    expect(matches.get(1)?.characterId).toBe('soyo');
    expect(matches.get(2)?.characterId).toBe('anon');
  });

  it('旁白人工覆盖应用到显式旁白行', () => {
    const dialogues = [say(0, null, '第一段旁白'), say(1, '千早爱音', '台词', 'anon'), say(2, null, '第二段旁白')];
    const matches = matchScene(dialogues, [anon, soyo], { '': 'soyo' });
    expect(matches.get(0)).toEqual({ characterId: 'soyo', reason: 'override' });
    expect(matches.get(1)?.characterId).toBe('anon');
    // 显式旁白同样使用覆盖
    expect(matches.get(2)).toEqual({ characterId: 'soyo', reason: 'override' });
  });

  it('省略说话者的旁白行沿用上一条旁白的角色', () => {
    // 第 1 行是显式旁白 (可指定角色), 第 2 行是省略说话者的裸行
    const explicitNarration: SayLine = { ...say(0, null, '第一段旁白'), speakerInherited: false };
    const inheritedNarration: SayLine = { ...say(1, null, '第二段旁白'), speakerInherited: true };
    const matches = matchScene([explicitNarration, inheritedNarration], [anon, soyo], { '': 'soyo' });
    expect(matches.get(0)).toEqual({ characterId: 'soyo', reason: 'override' });
    expect(matches.get(1)).toEqual({ characterId: 'soyo', reason: 'narration' });
  });

  it('旁白在选择角色之前保持未指定', () => {
    const dialogues = [say(0, null, '旁白'), say(1, null, '旁白2')];
    const matches = matchScene(dialogues, [anon]);
    expect(matches.get(0)?.characterId).toBeNull();
    expect(matches.get(1)?.characterId).toBeNull();
  });

  it('未启用角色不参与匹配但仍占位', () => {
    const disabled = { ...anon, enabled: false };
    const dialogues = [say(0, '千早爱音', '内容', 'anon')];
    expect(matchScene(dialogues, [disabled]).get(0)?.characterId).toBeNull();
  });
});
