// This file is generated by AI.

// 预处理流水线: 将无格式小说文本转换为中间格式文本。
//
// 阶段: 全角转半角 → 英文标点转中文 → 空格规范 → 对话识别/引号规范化 → 断句。
// 全部确定性、幂等, 便于 golden 测试。

import { parse } from './model';
import {
  isOpeningQuote,
  normalizePunctuation,
  normalizeSpaces,
  pairQuotes,
  stripTrailingCloseQuotes,
  toHalfWidth,
  type Reporter,
} from './text';

export interface Warning {
  /** 原始文本中的段落行号 (0 基), -1 表示无法定位。 */
  line: number;
  message: string;
}

export interface PreprocessResult {
  intermediate: string;
  warnings: Warning[];
}

type Unit = { kind: 'narration'; text: string } | { kind: 'dialogue'; text: string };

// -------- 对话识别 --------

function isDialogueStartLine(line: string): boolean {
  const t = line.trim();
  return t.length > 0 && isOpeningQuote(t[0]);
}

/** 该行是否已闭合对话 (首对引号成对)。 */
function closesDialogue(line: string): boolean {
  const { pairs } = pairQuotes(line.trim(), () => {});
  return pairs.length > 0 && pairs[0].close >= 0;
}

/**
 * 处理对话块: 返回对话单元与可能的旁白尾单元。
 * 若首行即闭合 (如 `“那是……？”她指着…`), 拆出对话内容与旁白尾;
 * 否则为跨行对话, 去掉每行前导引号、末行闭引号后合并。
 */
function processDialogueBlock(paras: string[], report: Reporter): Unit[] {
  const first = paras[0];
  // 仅探测首行是否闭合, 不产生警告 (未闭合是跨行对话的正常形态)。
  const firstResult = pairQuotes(first, () => {});
  const firstPair = firstResult.pairs[0];

  if (firstPair && firstPair.close >= 0) {
    // 第一行即闭合: 整行走「旁白+对话」提取 (可含多个对话与旁白尾)。
    return extractDialogues(first, report);
  }

  // 跨行: 去掉每行前导引号 (续行标记), 去掉末行闭引号, 规范化句内引号。
  const bodies = paras.map((p) => p.slice(1));
  bodies[bodies.length - 1] = stripTrailingCloseQuotes(bodies[bodies.length - 1]);
  const body = bodies.join('\n');
  const { text } = pairQuotes(body, report);
  return [{ kind: 'dialogue', text }];
}

/** 去掉引语前缀 (句首连接性标点、句末引导标点)。 */
function cleanLeadIn(lead: string): string {
  return lead
    .trim()
    .replace(/^[，。；、：]+/, '')
    .replace(/[：，、]+$/, '')
    .trim();
}

function endsWithPunct(s: string): boolean {
  return s.length > 0 && /[，。！？；：、]$/.test(s);
}

/**
 * 从一段文本中提取「旁白 + 对话」单元序列。
 * 对话判定: 引号跨度位于段首或前有标点 (用户规则); 其余文字为旁白。
 * 对话内容再次配对以将内层引号提升为双引号。
 */
function extractDialogues(text: string, report: Reporter): Unit[] {
  const units: Unit[] = [];
  let rest = text.trim();
  while (rest !== '') {
    const { text: norm, pairs } = pairQuotes(rest, report);
    const first = pairs[0];
    if (!first) {
      units.push({ kind: 'narration', text: norm });
      break;
    }
    const lead = norm.slice(0, first.open).trim();
    const isDialogue = first.depth === 0 && (lead === '' || endsWithPunct(lead));
    if (!isDialogue) {
      units.push({ kind: 'narration', text: norm });
      break;
    }
    if (lead !== '') {
      const cleaned = cleanLeadIn(lead);
      if (cleaned !== '') units.push({ kind: 'narration', text: cleaned });
    }
    const rawContent = first.close >= 0 ? norm.slice(first.open + 1, first.close) : norm.slice(first.open + 1);
    const { text: content } = pairQuotes(rawContent, report);
    units.push({ kind: 'dialogue', text: content });
    rest = first.close >= 0 ? norm.slice(first.close + 1) : '';
  }
  return units;
}

// -------- 断句 --------

const HARD_END = new Set(['。', '！', '？', '…']);
const SOFT_END = new Set(['；']);

function isSentenceEnd(ch: string): boolean {
  return HARD_END.has(ch) || SOFT_END.has(ch);
}

/** 合并过短相邻句 (长度和 < 5)。 */
function mergeShort(parts: string[]): string[] {
  const out: string[] = [];
  for (const part of parts) {
    if (out.length > 0 && out[out.length - 1].length + part.length < 5) {
      out[out.length - 1] += part;
    } else {
      out.push(part);
    }
  }
  return out;
}

const LONG_THRESHOLD = 30;

/** 找最接近中点的逗号下标, 无逗号返回 -1。 */
function bestComma(s: string): number {
  let best = -1;
  let bestDist = Infinity;
  const mid = s.length / 2;
  for (let i = 0; i < s.length; i++) {
    if (s[i] === '，') {
      const d = Math.abs(i - mid);
      if (d < bestDist) {
        bestDist = d;
        best = i;
      }
    }
  }
  return best;
}

/** 超长句 (超过 30 字): 仅在靠近中点的逗号处断开, 无逗号则保持整句。 */
function splitLong(s: string): string[] {
  const parts: string[] = [];
  const rec = (t: string) => {
    const trimmed = t.trim();
    if (trimmed.length <= LONG_THRESHOLD) {
      parts.push(trimmed);
      return;
    }
    const comma = bestComma(trimmed);
    if (comma >= 0) {
      rec(trimmed.slice(0, comma));
      rec(trimmed.slice(comma + 1));
    } else {
      parts.push(trimmed);
    }
  };
  rec(s);
  return parts;
}

function cleanSentence(s: string): string {
  return s.trim().replace(/[，：；、]+$/, '');
}

/** 单段断句: 引号内标点不参与断句, 一级断点硬结束/分号, 再合并短句、切分长句。 */
function segmentParagraph(p: string): string[] {
  const { pairs } = pairQuotes(p, () => {});
  const inside = new Array<boolean>(p.length).fill(false);
  for (const q of pairs) {
    const end = q.close >= 0 ? q.close : p.length - 1;
    for (let k = q.open; k <= end; k++) inside[k] = true;
  }

  const raw: string[] = [];
  let cur = '';
  for (let i = 0; i < p.length; i++) {
    const ch = p[i];
    if (isSentenceEnd(ch) && !inside[i]) {
      // 收集连续的表结束标点 (如 `……？` / `！！`), 作为一个结束单元整体断句。
      let j = i;
      while (j < p.length && isSentenceEnd(p[j]) && !inside[j]) j++;
      const run = p.slice(i, j);
      // 分号为软断点, 本身被丢弃。
      cur += run.replace(/；/g, '');
      raw.push(cur);
      cur = '';
      i = j - 1;
      continue;
    }
    cur += ch;
  }
  if (cur.trim() !== '') raw.push(cur);

  const merged = mergeShort(raw.map((s) => s.trim()).filter((s) => s !== ''));
  const balanced = merged.flatMap(splitLong);
  return balanced.map(cleanSentence).filter((s) => s !== '');
}

function segmentSentences(text: string): string[] {
  const paras = text.split('\n').filter((p) => p.trim() !== '');
  return paras.flatMap(segmentParagraph);
}

// -------- 主流程 --------

/** 将无格式小说文本预处理为中间格式文本。 */
export function preprocess(raw: string): PreprocessResult {
  const warnings: Warning[] = [];

  // 1. 逐段规范化 (引号留待对话识别阶段)。
  const rawLines = raw.split(/\r?\n/);
  const normLines: string[] = [];
  for (const line of rawLines) {
    normLines.push(normalizeSpaces(normalizePunctuation(toHalfWidth(line))));
  }

  // 2. 识别对话块并拆分为单元, 逐段输出 (每段前附 `;` 注释行: 原句 + 警告)。
  const out: string[] = [];
  let i = 0;
  while (i < normLines.length) {
    const line = normLines[i];
    if (line.trim() === '') {
      i++;
      continue;
    }

    const paraWarnings: string[] = [];
    const report: Reporter = (message) => paraWarnings.push(message);
    // 记录本段「原句」(原始文本), 供注释行使用。
    const rawPara = rawLines[i].trim();

    const paraLines: string[] = [];
    if (isDialogueStartLine(line)) {
      let j = i;
      const paras: string[] = [];
      while (j < normLines.length && normLines[j].trim() !== '' && isDialogueStartLine(normLines[j])) {
        paras.push(normLines[j].trim());
        j++;
        // 该行已闭合对话则对话块到此为止 (后续引号行为独立对话)。
        if (closesDialogue(normLines[j - 1])) break;
      }
      for (const unit of processDialogueBlock(paras, report)) appendUnit(paraLines, unit);
      i = j;
    } else {
      for (const unit of extractDialogues(line, report)) appendUnit(paraLines, unit);
      i++;
    }

    if (paraLines.length > 0) {
      // 注释行保留「原句」(原始文本) 与警告, 供人工核对; 生成脚本时忽略。
      // 警告的行号指向注释行 (与可见文本对齐)。
      const commentLine = out.length;
      const comment = `; ${rawPara}${paraWarnings.length > 0 ? ` [警告：${paraWarnings.join('；')}]` : ''}`;
      out.push(comment, ...paraLines);
      for (const message of paraWarnings) warnings.push({ line: commentLine, message });
    }
  }

  return { intermediate: out.join('\n'), warnings };
}

/** 将单元断句并格式化为中间格式行 (对话首句 `%:`, 其余跟随; 旁白 `:`)。 */
function appendUnit(target: string[], unit: Unit): void {
  const sentences = segmentSentences(unit.text);
  if (unit.kind === 'dialogue') {
    sentences.forEach((s, k) => target.push(k === 0 ? `%:${s}` : s));
  } else {
    sentences.forEach((s) => target.push(`:${s}`));
  }
}

/** 便捷入口: 预处理并直接解析为模型。 */
export function preprocessToModel(raw: string): { model: ReturnType<typeof parse>['model']; warnings: Warning[] } {
  const { intermediate, warnings } = preprocess(raw);
  const { model } = parse(intermediate);
  return { model, warnings };
}
