// This file is generated by AI.

// 纯文本规范化: 全角转半角、英文标点转中文、空格规范、引号配对。
// 均为无副作用的纯函数, 可独立单测。

/** 报告回调: 用于收集低置信度/异常情况 (供 UI 渲染为提示)。 */
export type Reporter = (message: string) => void;

// -------- 字符分类 --------

type Cat = 'han' | 'punct' | 'space' | 'other';

const HAN_RE = /[\u3400-\u4dbf\u4e00-\u9fff\uF900-\uFAFF]/;
const CJK_PUNCT_RE =
  /[\u3000-\u303F\uFF00-\uFFEF\u2014\u2026\u2018\u2019\u201C\u201D\u00B7\u2013\uFE10-\uFE19\uFE30-\uFE4F]/;

function category(ch: string): Cat {
  if (ch === ' ') return 'space';
  if (HAN_RE.test(ch)) return 'han';
  if (CJK_PUNCT_RE.test(ch)) return 'punct';
  return 'other';
}

function isDigit(ch: string): boolean {
  return ch >= '0' && ch <= '9';
}

// -------- 全角转半角 (仅字母与数字) --------

export function toHalfWidth(text: string): string {
  let out = '';
  for (const ch of text) {
    const cp = ch.codePointAt(0)!;
    if (cp >= 0xff01 && cp <= 0xff5e) {
      const half = String.fromCodePoint(cp - 0xfee0);
      if (/[0-9A-Za-z]/.test(half)) {
        out += half;
        continue;
      }
    }
    out += ch;
  }
  return out;
}

// -------- 英文标点转中文 --------

// URL / 邮箱整体识别, 内部标点不转换。
const PROTECTED_RE = /(?:https?:\/\/|www\.)[^\s，。；：？！（）\u3000]+|[\w.+-]+@[\w-]+\.[A-Za-z]{2,}/g;

function mapPunct(ch: string): string {
  switch (ch) {
    case ',':
      return '，';
    case ';':
      return '；';
    case ':':
      return '：';
    case '?':
      return '？';
    case '!':
      return '！';
    case '(':
      return '（';
    case ')':
      return '）';
    case '．':
      return '。';
    default:
      return ch;
  }
}

/** 是否为「连续非中文块」成员 (字母/数字/半角符号/半角标点, 与中文及其中文标点相对)。 */
function isNonChinese(ch: string): boolean {
  return !HAN_RE.test(ch) && !CJK_PUNCT_RE.test(ch) && !/\s/.test(ch);
}

/** 英文标点转中文, 保护小数点 `.`、URL/邮箱, 以及「连续非中文块」 (字符与标点混合, 如 `assa!!!!!`)。 */
export function normalizePunctuation(text: string): string {
  const spans: Array<[number, number]> = [];
  for (const m of text.matchAll(PROTECTED_RE)) {
    spans.push([m.index ?? 0, (m.index ?? 0) + m[0].length]);
  }

  let out = '';
  let i = 0;
  while (i < text.length) {
    const span = spans.find(([s, e]) => i >= s && i < e);
    if (span) {
      out += text.slice(i, span[1]);
      i = span[1];
      continue;
    }
    const ch = text[i];

    // 连续非中文块 (如 `123abc%&*` / `assa!!!!!`): 整体保留, 不逐字转换。
    if (isNonChinese(ch)) {
      let j = i;
      while (j < text.length && isNonChinese(text[j])) j++;
      if (j - i >= 2) {
        const run = text.slice(i, j);
        // 纯点号串仍规范为省略号, 其余保持原样。
        out += run === '.'.repeat(j - i) ? '……' : run;
        i = j;
        continue;
      }
    }

    if (ch === '.') {
      const prev = out.length > 0 ? out[out.length - 1] : '';
      const next = text[i + 1] ?? '';
      out += isDigit(prev) && isDigit(next) ? '.' : '。';
      i++;
      continue;
    }
    out += mapPunct(ch);
    i++;
  }
  return out;
}

// -------- 空格规范 --------

/**
 * 清理空格并按脚本族在「连续中文」与「连续非中文」之间插入单个空格。
 * 中文标点作为独立一类, 与两侧都不加空格。
 */
export function normalizeSpaces(text: string): string {
  const collapsed = text.replace(/[\s\u3000]+/g, ' ').trim();
  let out = '';
  for (let i = 0; i < collapsed.length; i++) {
    const ch = collapsed[i];
    out += ch;
    if (i + 1 >= collapsed.length) continue;
    const next = collapsed[i + 1];
    const a = category(ch);
    const b = category(next);
    if ((a === 'han' && b === 'other') || (a === 'other' && b === 'han')) out += ' ';
  }
  return out;
}

// -------- 引号配对 --------

const OPEN_GLYPHS = new Set(['"', "'", '“', '‘', '「', '『', '〝', '‹']);
const CLOSE_GLYPHS = new Set(['"', "'", '”', '’', '」', '』', '〞', '›']);
const OPEN_ONLY = new Set(['“', '‘', '「', '『', '〝', '‹']);
const CLOSE_ONLY = new Set(['”', '’', '」', '』', '〞', '›']);

export interface QuotePair {
  /** 输出文本中的开引号下标。 */
  open: number;
  /** 输出文本中的闭引号下标 (-1 表示未闭合)。 */
  close: number;
  /** 嵌套深度 (0 = 最外层)。 */
  depth: number;
}

export interface PairQuotesResult {
  /** 规范化后的文本 (外层双引号、内层单引号交替)。 */
  text: string;
  pairs: QuotePair[];
}

function prevNonSpace(chars: string[], from: number): string | null {
  for (let i = from - 1; i >= 0; i--) {
    if (chars[i] !== ' ') return chars[i];
  }
  return null;
}

function nextNonSpace(chars: string[], from: number): string | null {
  for (let i = from; i < chars.length; i++) {
    if (chars[i] !== ' ') return chars[i];
  }
  return null;
}

function isSpaceOrPunct(ch: string): boolean {
  return ch === ' ' || category(ch) === 'punct';
}

function isWordChar(ch: string | null): boolean {
  return ch !== null && /[0-9A-Za-z]/.test(ch);
}

/** 该字形是否可作为开引号 (含直引号)。 */
export function isOpeningQuote(ch: string): boolean {
  return OPEN_GLYPHS.has(ch);
}

/** 去掉字符串末尾连续的闭引号字形 (含直引号)。 */
export function stripTrailingCloseQuotes(s: string): string {
  return s.replace(/["'”’」』〞›]+$/, '');
}

/**
 * 将混合的引号字形 (直引号、弯引号、直角引号等) 配对并规范化为
 * 外层 `“”`、内层 `‘’` 交替。返回规范化文本与每对引号的位置。
 */
export function pairQuotes(text: string, report: Reporter): PairQuotesResult {
  const out: string[] = [];
  const pairs: QuotePair[] = [];
  const openStack: number[] = [];
  const src = Array.from(text);
  // 输出文本的 UTF-16 单元偏移 (surrogate pair 占 2 个单元, 保证切片定位正确)。
  let pos = 0;

  for (let i = 0; i < src.length; i++) {
    const ch = src[i];
    const isOpenGlyph = OPEN_GLYPHS.has(ch);
    const isCloseGlyph = CLOSE_GLYPHS.has(ch);
    if (!isOpenGlyph && !isCloseGlyph) {
      out.push(ch);
      pos += ch.length;
      continue;
    }

    const prev = prevNonSpace(out, out.length);
    const next = nextNonSpace(src, i + 1);

    // 英文所有格撇号 (It's / don't) 不视为引号。
    if (ch === "'" && isWordChar(prev) && isWordChar(next)) {
      out.push("'");
      pos += 1;
      continue;
    }

    let open: boolean;
    if (openStack.length === 0) {
      open = true;
      if (CLOSE_ONLY.has(ch)) report('孤立闭合引号 (已按开引号处理)');
    } else if (CLOSE_ONLY.has(ch)) {
      open = false;
    } else if (OPEN_ONLY.has(ch)) {
      open = true;
    } else {
      // 直引号: 依据前后文判定开/闭; 两词字符之间 (歧义) 倾向闭合。
      const prevOpen = prev === null || isSpaceOrPunct(prev) || OPEN_ONLY.has(prev);
      const nextClose = next === null || isSpaceOrPunct(next) || CLOSE_ONLY.has(next);
      open = prevOpen && !nextClose;
    }

    if (open) {
      const depth = openStack.length;
      openStack.push(pairs.length);
      pairs.push({ open: pos, close: -1, depth });
      out.push(depth % 2 === 0 ? '“' : '‘');
      pos += 1;
    } else {
      const pairIndex = openStack.pop();
      if (pairIndex === undefined) {
        out.push('”');
        pos += 1;
        continue;
      }
      pairs[pairIndex].close = pos;
      out.push(pairs[pairIndex].depth % 2 === 0 ? '”' : '’');
      pos += 1;
    }
  }

  if (openStack.length > 0) report('存在未闭合引号');
  return { text: out.join(''), pairs };
}
