// This file is generated by AI.

use ranked_count::Counter;

#[test]
fn iter_by_value_and_count_ordering() {
    let mut c = Counter::new();
    c.insert_to("a", 5);
    c.insert_to("b", 2);
    c.insert_to("c", 2);
    assert_eq!(
        c.iter_by_count().map(|(v, _)| *v).collect::<Vec<_>>(),
        vec!["a", "b", "c"]
    );
    assert_eq!(
        c.iter_by_value().map(|(v, _)| *v).collect::<Vec<_>>(),
        vec!["a", "b", "c"]
    );
}

#[test]
fn iter_consistency() {
    let mut c = Counter::new();
    for i in 0..10 {
        c.insertn(i, (i % 3) + 1);
    }
    let first: Vec<_> = c.iter_by_value().collect();
    let second: Vec<_> = c.iter_by_value().collect();
    assert_eq!(first, second);
}

#[test]
fn extend_and_from_iter() {
    let items = vec!["x", "y", "x", "z", "y", "x"];
    let c: Counter<&str> = items.into_iter().collect();
    assert_eq!(c.get(&"x"), 3);
    assert_eq!(c.get(&"y"), 2);
    assert_eq!(c.get(&"z"), 1);

    let mut c2: Counter<&str> = Counter::new();
    c2.extend(vec![("a", 2), ("b", 1)]);
    assert_eq!(c2.get(&"a"), 2);
    assert_eq!(c2.get(&"b"), 1);
}
