[package]
name = "webgal-ink"
version = "0.1.0"
edition = "2021"
readme.workspace = true
description = "轻量级 WebGAL 脚本编辑器"

authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "webgal_ink_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
webgal-language-server.workspace = true
webgal-snapshot.workspace = true

serde.workspace = true
serde_json.workspace = true

percent-encoding.workspace = true

tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-fs = { version = "2", features = ["watch"] }
tauri-plugin-dialog = "2"
tower = { workspace = true, features = ["util"] }
tower-http = { workspace = true, features = ["fs"] }
tower-lsp.workspace = true
axum = { version = "0.8", features = ["ws"] }
futures-util.workspace = true
async-tungstenite.workspace = true
ws_stream_tungstenite.workspace = true
tokio = { workspace = true, features = [
    "rt",
    "macros",
    "sync",
    "net",
    "io-util",
    "fs",
] }
tokio-util.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }
