// This file is generated by AI.

//! 游戏配置服务: 读取并解析 `<project>/game/config.txt`。

use std::{fs, path::Path, path::PathBuf};

use serde::Serialize;
use webgal_language_core::resource::Config;

/// 单条游戏配置项。
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct GameConfigEntry {
    pub name: String,
    pub value: String,
    pub comment: String,
}

/// [`read_game_config`] 的返回结果。
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct GameConfigReadResult {
    /// config.txt 是否存在
    pub exists: bool,
    /// 按文件顺序的配置项 (仅 `name` 与 `value` 都非空的配置行)
    pub entries: Vec<GameConfigEntry>,
}

/// 返回 `<project>/game/config.txt` 路径。
pub(crate) fn game_config_path(project_path: &Path) -> PathBuf {
    project_path.join("game").join("config.txt")
}

/// 读取并解析指定工程根目录下的 `game/config.txt`。
///
/// * 文件不存在 (或不是文件) 时返回 `exists: false` 与空列表, 而不是错误;
/// * 读取失败时返回包含底层错误信息的错误。
pub(crate) fn read_game_config_at(project_path: &Path) -> Result<GameConfigReadResult, String> {
    let path = game_config_path(project_path);
    if !path.is_file() {
        return Ok(GameConfigReadResult {
            exists: false,
            entries: vec![],
        });
    }

    let text =
        fs::read_to_string(&path).map_err(|error| format!("读取 config.txt 失败: {error}"))?;
    let config = Config::from_str(&text);
    let entries = config
        .iter()
        .filter(|item| item.is_config())
        .map(|item| GameConfigEntry {
            name: item.name.clone(),
            value: item.value.clone(),
            comment: item.comment.clone(),
        })
        .collect();

    Ok(GameConfigReadResult {
        exists: true,
        entries,
    })
}

/// 读取并解析 `<project_path>/game/config.txt`。
#[tauri::command]
pub fn read_game_config(project_path: String) -> Result<GameConfigReadResult, String> {
    read_game_config_at(Path::new(&project_path))
}

#[cfg(test)]
mod tests {
    use std::sync::atomic::{AtomicU64, Ordering};

    use super::*;

    /// 进程内唯一的计数器, 避免并行测试复用同一临时目录。
    static COUNTER: AtomicU64 = AtomicU64::new(0);

    /// 创建唯一临时工程目录, 返回 `(临时根目录, 工程目录)`。
    fn make_project() -> (PathBuf, PathBuf) {
        let unique = COUNTER.fetch_add(1, Ordering::Relaxed);
        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .expect("system clock before unix epoch")
            .as_nanos();
        let root = std::env::temp_dir().join(format!(
            "webgal-ink-game-config-{}-{nanos}-{unique}",
            std::process::id()
        ));
        let project = root.join("project");
        fs::create_dir_all(project.join("game")).expect("create temp project dir");
        (root, project)
    }

    /// 写入 `game/config.txt`。
    fn write_config(project: &Path, text: &str) {
        fs::write(game_config_path(project), text).expect("write temp config.txt");
    }

    #[test]
    fn missing_file_is_not_an_error() {
        let (root, project) = make_project();
        fs::remove_file(game_config_path(&project)).ok();

        let result = read_game_config_at(&project).expect("missing file should be Ok");
        assert!(!result.exists);
        assert!(result.entries.is_empty());

        // 目录同样视为不存在, 而不是读取失败。
        fs::remove_dir_all(game_config_path(&project)).ok();
        fs::create_dir_all(game_config_path(&project)).expect("create dir instead of file");
        let result = read_game_config_at(&project).expect("directory should be Ok");
        assert!(!result.exists);
        assert!(result.entries.is_empty());

        fs::remove_dir_all(&root).expect("cleanup temp dir");
    }

    #[test]
    fn parses_configs_in_file_order_and_skips_non_config_lines() {
        let (root, project) = make_project();
        write_config(
            &project,
            "\
Game_name:test;
; comment only line

Game_key:abc; inline comment
Game_language:zh_CN;
",
        );

        let result = read_game_config_at(&project).expect("read config");
        assert!(result.exists);
        assert_eq!(
            result.entries,
            vec![
                GameConfigEntry {
                    name: "Game_name".to_string(),
                    value: "test".to_string(),
                    comment: String::new(),
                },
                GameConfigEntry {
                    name: "Game_key".to_string(),
                    value: "abc".to_string(),
                    comment: "inline comment".to_string(),
                },
                GameConfigEntry {
                    name: "Game_language".to_string(),
                    value: "zh_CN".to_string(),
                    comment: String::new(),
                },
            ]
        );

        fs::remove_dir_all(&root).expect("cleanup temp dir");
    }

    #[test]
    fn duplicate_keys_are_kept_in_file_order() {
        let (root, project) = make_project();
        write_config(
            &project,
            "\
key1:1;
key2:2;
key1:3;
",
        );

        let result = read_game_config_at(&project).expect("read config");
        // 两处 key1 都保留且顺序与文件一致; 调用方应取 "最后" 一次出现,
        // 与 `Config::get_config` 的从后往前查找行为保持一致。
        let names: Vec<_> = result.entries.iter().map(|e| e.name.as_str()).collect();
        assert_eq!(names, vec!["key1", "key2", "key1"]);
        assert_eq!(result.entries[0].value, "1");
        assert_eq!(result.entries[2].value, "3");

        let config = Config::from_str("key1:1;\nkey2:2;\nkey1:3;\n");
        let (index, item) = config.get_config("key1").expect("key1 exists");
        assert_eq!(index, 2);
        assert_eq!(item.value, "3");

        fs::remove_dir_all(&root).expect("cleanup temp dir");
    }

    #[test]
    fn parses_crlf_utf8_file() {
        let (root, project) = make_project();
        write_config(
            &project,
            "Game_name:测试游戏;\r\nGame_key:abc; 备注\r\n\r\n; 注释\r\n",
        );

        let result = read_game_config_at(&project).expect("read config");
        assert!(result.exists);
        assert_eq!(
            result.entries,
            vec![
                GameConfigEntry {
                    name: "Game_name".to_string(),
                    value: "测试游戏".to_string(),
                    comment: String::new(),
                },
                GameConfigEntry {
                    name: "Game_key".to_string(),
                    value: "abc".to_string(),
                    comment: "备注".to_string(),
                },
            ]
        );

        fs::remove_dir_all(&root).expect("cleanup temp dir");
    }

    #[test]
    fn game_config_path_joins_project_dir() {
        let project = Path::new("D:/games/my-project");
        assert_eq!(
            game_config_path(project),
            PathBuf::from("D:/games/my-project/game/config.txt")
        );
    }
}
