// This file is generated by AI.

//! Git 版本管理服务: 基于 `git2` 提供面向普通用户的简化 git 能力。
//!
//! 所有命令以项目根目录为仓库根, 路径一律使用仓库相对路径 (正斜杠分隔)。
//! 操作在后台线程执行, 避免阻塞 Tauri IPC。

use std::{collections::HashMap, path::Path, sync::Once};

use git2::{
    build::CheckoutBuilder, Commit, Delta, Diff, DiffDelta, DiffLine, DiffOptions, Index, Oid,
    Repository, Signature, Status, StatusOptions, Tree,
};
use serde::Serialize;

/// 在后台线程执行阻塞的 git 操作
async fn blocking<T, F>(f: F) -> Result<T, String>
where
    T: Send + 'static,
    F: FnOnce() -> Result<T, String> + Send + 'static,
{
    tauri::async_runtime::spawn_blocking(f)
        .await
        .map_err(|e| e.to_string())?
}

/// 关闭 libgit2 的仓库所有权校验 (全局一次性).
///
/// 该校验 (CVE-2022-24765) 在 Windows 上对部分路径 (如非 ASCII 路径) 会误报
/// "repository path ... is not owned by current user". 编辑器仅操作用户本地打开的
/// 项目, 不涉及不可信远程仓库, 可安全关闭.
static DISABLE_OWNER_CHECK: Once = Once::new();

fn ensure_owner_check_disabled() {
    DISABLE_OWNER_CHECK.call_once(|| unsafe {
        let _ = git2::opts::set_verify_owner_validation(false);
    });
}

// -------- 类型定义 --------

/// 仓库整体状态
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct RepoStatus {
    /// 是否已初始化 git 仓库
    pub initialized: bool,
    /// 当前分支名 (无提交时为 None)
    pub branch: Option<String>,
    /// 已暂存的文件
    pub staged: Vec<FileStatus>,
    /// 未暂存 / 未跟踪的文件
    pub unstaged: Vec<FileStatus>,
    /// 已解析的提交身份 (本地/全局配置均缺失时为 None)
    pub identity: Option<Identity>,
}

/// 单个文件的变更状态
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct FileStatus {
    /// 仓库相对路径 (正斜杠)
    pub path: String,
    /// 更改类型: M 修改 / A 新增(暂存) / U 未跟踪 / R 重命名 / D 删除 / T 类型变更
    pub status: char,
    /// 新增行数
    pub additions: u64,
    /// 删除行数
    pub deletions: u64,
}

/// 提交身份
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Identity {
    pub name: String,
    pub email: String,
}

/// 提交记录
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CommitInfo {
    pub id: String,
    pub short_id: String,
    /// 首行摘要
    pub summary: String,
    /// 完整提交信息
    pub message: String,
    pub author: String,
    /// 提交时间 (Unix 秒)
    pub time: i64,
    pub additions: u64,
    pub deletions: u64,
}

/// 某个提交内变更的文件
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CommitFile {
    pub path: String,
    pub status: char,
    pub additions: u64,
    pub deletions: u64,
}

/// 文件差异 (供 Monaco DiffEditor 使用)
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct FileDiff {
    pub original: String,
    pub modified: String,
    pub original_label: String,
    pub modified_label: String,
    /// 是否为二进制文件 (无法以文本展示差异)
    pub binary: bool,
}

/// 编辑器行内差异标记: 单行变更 (供行号旁色块使用)
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct InlineChange {
    /// 1-based 新侧行号 (删除行为插入边界行)
    pub line: u32,
    /// 'A' 新增 / 'M' 修改 / 'D' 删除
    pub kind: char,
}

/// 差异区域中的一行 (旧 '-' / 新 '+')
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct DiffRow {
    /// '+' 新增 / '-' 删除
    pub kind: char,
    pub text: String,
}

/// 内联差异区域 (供行号旁色块就地展开使用)
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct InlineRegion {
    pub rows: Vec<DiffRow>,
    /// 插入锚点: 该连续差异块的末行新行号 (在其后插入), 删除块为其边界行
    pub anchor: u32,
}

// -------- 工具函数 --------

fn open_repo(path: &str) -> Result<Repository, String> {
    ensure_owner_check_disabled();
    Repository::open(Path::new(path)).map_err(|e| e.to_string())
}

fn head_tree(repo: &Repository) -> Option<Tree<'_>> {
    repo.head().ok()?.peel_to_tree().ok()
}

/// 从树读取某路径的 blob 内容
fn tree_blob(repo: &Repository, tree: &Tree<'_>, path: &str) -> Option<Vec<u8>> {
    let entry = tree.get_path(Path::new(path)).ok()?;
    let object = entry.to_object(repo).ok()?;
    Some(object.peel_to_blob().ok()?.content().to_vec())
}

/// 从索引读取某路径的 blob 内容
fn index_blob(repo: &Repository, index: &Index, path: &str) -> Option<Vec<u8>> {
    let entry = index.get_path(Path::new(path), 0)?;
    let object = repo.find_object(entry.id, None).ok()?;
    Some(object.peel_to_blob().ok()?.content().to_vec())
}

fn is_binary(bytes: &[u8]) -> bool {
    bytes.contains(&0)
}

/// 统计每个文件的新增 / 删除行数
fn per_file_stats(diff: &Diff<'_>) -> HashMap<String, (u64, u64)> {
    let mut map: HashMap<String, (u64, u64)> = HashMap::new();
    let _ = diff.foreach(
        &mut |_delta: DiffDelta<'_>, _progress: f32| true,
        None,
        None,
        Some(
            &mut |delta: DiffDelta<'_>, _hunk: Option<git2::DiffHunk<'_>>, line: DiffLine<'_>| {
                let path = delta.new_file().path().or_else(|| delta.old_file().path());
                if let Some(path) = path {
                    let entry = map.entry(path.to_string_lossy().into_owned()).or_default();
                    match line.origin() {
                        '+' => entry.0 += 1,
                        '-' => entry.1 += 1,
                        _ => {}
                    }
                }
                true
            },
        ),
    );
    map
}

/// 从状态位提取索引(暂存)侧类型
fn index_letter(status: Status) -> Option<char> {
    if status.intersects(Status::INDEX_DELETED) {
        Some('D')
    } else if status.intersects(Status::INDEX_RENAMED) {
        Some('R')
    } else if status.intersects(Status::INDEX_NEW) {
        Some('A')
    } else if status.intersects(Status::INDEX_TYPECHANGE) {
        Some('T')
    } else if status.intersects(Status::INDEX_MODIFIED) {
        Some('M')
    } else {
        None
    }
}

/// 从状态位提取工作区(未暂存)侧类型
fn worktree_letter(status: Status) -> Option<char> {
    if status.intersects(Status::WT_DELETED) {
        Some('D')
    } else if status.intersects(Status::WT_RENAMED) {
        Some('R')
    } else if status.intersects(Status::WT_NEW) {
        Some('U')
    } else if status.intersects(Status::WT_TYPECHANGE) {
        Some('T')
    } else if status.intersects(Status::WT_MODIFIED) {
        Some('M')
    } else {
        None
    }
}

/// 计算仓库状态 (分支 / 暂存 / 未暂存 / 身份)
fn compute_status(repo: &Repository) -> Result<RepoStatus, String> {
    let mut options = StatusOptions::new();
    options
        .include_untracked(true)
        .recurse_untracked_dirs(true)
        .renames_head_to_index(true)
        .renames_index_to_workdir(true);
    let statuses = repo
        .statuses(Some(&mut options))
        .map_err(|e| e.to_string())?;

    // 暂存 / 未暂存差异 (用于行数统计)
    let index = repo.index().map_err(|e| e.to_string())?;
    let head_tree = head_tree(repo);

    let mut staged_stats = HashMap::new();
    if let Ok(diff) = repo.diff_tree_to_index(head_tree.as_ref(), Some(&index), None) {
        staged_stats = per_file_stats(&diff);
    }

    let mut unstaged_stats = HashMap::new();
    let mut diff_opts = DiffOptions::new();
    diff_opts
        .include_untracked(true)
        .recurse_untracked_dirs(true)
        .include_unmodified(false);
    if let Ok(diff) = repo.diff_index_to_workdir(Some(&index), Some(&mut diff_opts)) {
        unstaged_stats = per_file_stats(&diff);
    }

    let mut staged = Vec::new();
    let mut unstaged = Vec::new();
    for entry in statuses.iter() {
        if let Some(path) = entry.path() {
            if let Some(status) = index_letter(entry.status()) {
                let (additions, deletions) = staged_stats.get(path).copied().unwrap_or((0, 0));
                staged.push(FileStatus {
                    path: path.to_string(),
                    status,
                    additions,
                    deletions,
                });
            }
            if let Some(status) = worktree_letter(entry.status()) {
                let (additions, deletions) = unstaged_stats.get(path).copied().unwrap_or((0, 0));
                unstaged.push(FileStatus {
                    path: path.to_string(),
                    status,
                    additions,
                    deletions,
                });
            }
        }
    }

    let branch = repo
        .head()
        .ok()
        .and_then(|h| h.shorthand().map(str::to_string));

    let identity = repo.config().ok().and_then(|config| {
        let name = config.get_string("user.name").ok()?;
        let email = config.get_string("user.email").ok()?;
        Some(Identity { name, email })
    });

    Ok(RepoStatus {
        initialized: true,
        branch,
        staged,
        unstaged,
        identity,
    })
}

/// 提交身份 (供提交前检查)
fn commit_signature(repo: &Repository) -> Result<Signature<'static>, String> {
    let config = repo.config().map_err(|e| e.to_string())?;
    let name = config
        .get_string("user.name")
        .map_err(|_| "缺少提交作者姓名 (user.name)")?;
    let email = config
        .get_string("user.email")
        .map_err(|_| "缺少提交作者邮箱 (user.email)")?;
    Signature::now(&name, &email).map_err(|e| e.to_string())
}

// -------- 命令 --------

/// 查询仓库状态; 未初始化时返回 `initialized: false`
#[tauri::command]
pub async fn git_status(path: String) -> Result<RepoStatus, String> {
    blocking(move || {
        ensure_owner_check_disabled();
        // 以项目目录本身作为仓库根: 若项目不是独立 git 仓库则视为未初始化
        // (避免发现上级目录的 .git 而误判).
        let repo = match Repository::open(Path::new(&path)) {
            Ok(repo) => repo,
            Err(_) => {
                return Ok(RepoStatus {
                    initialized: false,
                    branch: None,
                    staged: Vec::new(),
                    unstaged: Vec::new(),
                    identity: None,
                })
            }
        };
        compute_status(&repo)
    })
    .await
}

/// 初始化仓库并写入 .gitignore
#[tauri::command]
pub async fn git_init(path: String, gitignore: String) -> Result<(), String> {
    blocking(move || {
        ensure_owner_check_disabled();
        Repository::init(Path::new(&path)).map_err(|e| e.to_string())?;
        std::fs::write(Path::new(&path).join(".gitignore"), gitignore).map_err(|e| e.to_string())
    })
    .await
}

/// 写入本地提交身份 (user.name / user.email)
#[tauri::command]
pub async fn git_set_identity(path: String, name: String, email: String) -> Result<(), String> {
    blocking(move || {
        let repo = open_repo(&path)?;
        let mut config = repo.config().map_err(|e| e.to_string())?;
        config
            .set_str("user.name", &name)
            .map_err(|e| e.to_string())?;
        config
            .set_str("user.email", &email)
            .map_err(|e| e.to_string())?;
        Ok(())
    })
    .await
}

/// 暂存指定文件
#[tauri::command]
pub async fn git_stage(path: String, files: Vec<String>) -> Result<(), String> {
    blocking(move || {
        let repo = open_repo(&path)?;
        let mut index = repo.index().map_err(|e| e.to_string())?;
        let pathspecs: Vec<String> = files.iter().map(|f| f.to_string()).collect();
        index
            .add_all(
                pathspecs.iter().map(|s| s.as_str()),
                git2::IndexAddOption::DEFAULT,
                None,
            )
            .map_err(|e| e.to_string())?;
        index.write().map_err(|e| e.to_string())
    })
    .await
}

/// 暂存全部更改
#[tauri::command]
pub async fn git_stage_all(path: String) -> Result<(), String> {
    blocking(move || {
        let repo = open_repo(&path)?;
        let mut index = repo.index().map_err(|e| e.to_string())?;
        index
            .add_all(["*"].iter().copied(), git2::IndexAddOption::DEFAULT, None)
            .map_err(|e| e.to_string())?;
        index.write().map_err(|e| e.to_string())
    })
    .await
}

/// 取消暂存指定文件 (改动保留在工作区)
#[tauri::command]
pub async fn git_unstage(path: String, files: Vec<String>) -> Result<(), String> {
    blocking(move || {
        let repo = open_repo(&path)?;
        let head_oid = repo
            .head()
            .ok()
            .and_then(|h| h.peel_to_commit().ok())
            .map(|c| c.id());
        match head_oid {
            Some(oid) => {
                let obj = repo.find_object(oid, None).map_err(|e| e.to_string())?;
                let specs: Vec<&Path> = files.iter().map(|f| Path::new(f.as_str())).collect();
                repo.reset_default(Some(&obj), &specs)
                    .map_err(|e| e.to_string())
            }
            None => {
                // 无提交: 从索引移除即取消暂存
                let mut index = repo.index().map_err(|e| e.to_string())?;
                for f in &files {
                    index.remove_path(Path::new(f)).map_err(|e| e.to_string())?;
                }
                index.write().map_err(|e| e.to_string())
            }
        }
    })
    .await
}

/// 取消全部暂存
#[tauri::command]
pub async fn git_unstage_all(path: String) -> Result<(), String> {
    blocking(move || {
        let repo = open_repo(&path)?;
        let head_oid = repo
            .head()
            .ok()
            .and_then(|h| h.peel_to_commit().ok())
            .map(|c| c.id());
        match head_oid {
            Some(oid) => {
                let obj = repo.find_object(oid, None).map_err(|e| e.to_string())?;
                repo.reset_default(Some(&obj), &[] as &[&Path])
                    .map_err(|e| e.to_string())
            }
            None => {
                let mut index = repo.index().map_err(|e| e.to_string())?;
                index.clear().map_err(|e| e.to_string())?;
                index.write().map_err(|e| e.to_string())
            }
        }
    })
    .await
}

/// 丢弃指定文件的工作区改动 (还原到索引/HEAD, 未跟踪文件删除)
#[tauri::command]
pub async fn git_discard(path: String, files: Vec<String>) -> Result<(), String> {
    blocking(move || {
        let repo = open_repo(&path)?;
        let mut index = repo.index().map_err(|e| e.to_string())?;
        let head_tree = head_tree(&repo);
        let workdir = repo.workdir().ok_or("仓库无工作目录")?;

        let mut tracked: Vec<String> = Vec::new();
        for f in &files {
            let in_index = index.get_path(Path::new(f), 0).is_some();
            let in_head = head_tree
                .as_ref()
                .and_then(|t| t.get_path(Path::new(f)).ok())
                .is_some();
            if in_index || in_head {
                tracked.push(f.clone());
            } else {
                // 未跟踪文件: 直接删除
                let _ = std::fs::remove_file(workdir.join(f));
            }
        }

        if tracked.is_empty() {
            return Ok(());
        }

        let mut opts = CheckoutBuilder::new();
        opts.force();
        for f in &tracked {
            opts.path(Path::new(f));
        }
        repo.checkout_index(Some(&mut index), Some(&mut opts))
            .map_err(|e| e.to_string())
    })
    .await
}

/// 丢弃全部未暂存改动 (还原工作区到索引, 删除未跟踪文件)
#[tauri::command]
pub async fn git_discard_all(path: String) -> Result<(), String> {
    blocking(move || {
        let repo = open_repo(&path)?;
        let mut index = repo.index().map_err(|e| e.to_string())?;
        let workdir = repo.workdir().ok_or("仓库无工作目录")?;

        // 删除所有未跟踪文件
        let mut options = StatusOptions::new();
        options.include_untracked(true).recurse_untracked_dirs(true);
        for entry in repo
            .statuses(Some(&mut options))
            .map_err(|e| e.to_string())?
            .iter()
        {
            if entry.status().intersects(Status::WT_NEW) {
                if let Some(p) = entry.path() {
                    let _ = std::fs::remove_file(workdir.join(p));
                }
            }
        }

        let mut opts = CheckoutBuilder::new();
        opts.force();
        repo.checkout_index(Some(&mut index), Some(&mut opts))
            .map_err(|e| e.to_string())
    })
    .await
}

/// 提交已暂存更改
#[tauri::command]
pub async fn git_commit(path: String, message: String) -> Result<String, String> {
    blocking(move || {
        let repo = open_repo(&path)?;
        let signature = commit_signature(&repo)?;
        let mut index = repo.index().map_err(|e| e.to_string())?;
        let tree_id = index.write_tree().map_err(|e| e.to_string())?;
        let tree = repo.find_tree(tree_id).map_err(|e| e.to_string())?;

        let head_commit = repo.head().ok().and_then(|h| h.peel_to_commit().ok());
        let parents: Vec<Commit<'_>> = match head_commit {
            Some(c) => vec![c],
            None => Vec::new(),
        };
        let parent_refs: Vec<&Commit<'_>> = parents.iter().collect();

        let id = repo
            .commit(
                Some("HEAD"),
                &signature,
                &signature,
                &message,
                &tree,
                &parent_refs,
            )
            .map_err(|e| e.to_string())?;
        Ok(id.to_string())
    })
    .await
}

/// 读取提交历史 (从 HEAD 沿父链)
#[tauri::command]
pub async fn git_log(path: String) -> Result<Vec<CommitInfo>, String> {
    blocking(move || {
        let repo = open_repo(&path)?;
        // 空仓库 (unborn HEAD, 尚无提交) 时返回空历史
        let has_commit = repo
            .head()
            .ok()
            .and_then(|h| h.peel_to_commit().ok())
            .is_some();
        if !has_commit {
            return Ok(Vec::new());
        }

        let mut revwalk = repo.revwalk().map_err(|e| e.to_string())?;
        revwalk.push_head().map_err(|e| e.to_string())?;

        let mut commits = Vec::new();
        for oid in revwalk {
            let oid = oid.map_err(|e| e.to_string())?;
            let commit = repo.find_commit(oid).map_err(|e| e.to_string())?;
            let parent_tree = commit.parent(0).ok().and_then(|p| p.tree().ok());
            let tree = commit.tree().map_err(|e| e.to_string())?;

            let (additions, deletions) = match parent_tree {
                Some(parent) => repo
                    .diff_tree_to_tree(Some(&parent), Some(&tree), None)
                    .map(|d| {
                        d.stats()
                            .map(|s| (s.insertions() as u64, s.deletions() as u64))
                    })
                    .unwrap_or(Ok((0, 0)))
                    .unwrap_or((0, 0)),
                // 首个提交: 与空树比较, 所有行均为新增
                None => repo
                    .diff_tree_to_tree(None, Some(&tree), None)
                    .map(|d| {
                        d.stats()
                            .map(|s| (s.insertions() as u64, s.deletions() as u64))
                    })
                    .unwrap_or(Ok((0, 0)))
                    .unwrap_or((0, 0)),
            };

            let summary = commit.summary().unwrap_or("").to_string();
            commits.push(CommitInfo {
                id: oid.to_string(),
                short_id: oid.to_string()[..7.min(oid.to_string().len())].to_string(),
                summary: summary.clone(),
                message: commit.message().unwrap_or("").to_string(),
                author: commit.author().name().unwrap_or("").to_string(),
                time: commit.time().seconds(),
                additions,
                deletions,
            });
        }
        Ok(commits)
    })
    .await
}

/// 读取某个提交内变更的文件列表
#[tauri::command]
pub async fn git_commit_files(path: String, commit_id: String) -> Result<Vec<CommitFile>, String> {
    blocking(move || {
        let repo = open_repo(&path)?;
        let oid = Oid::from_str(&commit_id).map_err(|e| e.to_string())?;
        let commit = repo.find_commit(oid).map_err(|e| e.to_string())?;
        let tree = commit.tree().map_err(|e| e.to_string())?;
        let parent_tree = commit.parent(0).ok().and_then(|p| p.tree().ok());

        let diff = repo
            .diff_tree_to_tree(parent_tree.as_ref(), Some(&tree), None)
            .map_err(|e| e.to_string())?;
        let stats = per_file_stats(&diff);

        let mut files = Vec::new();
        for delta in diff.deltas() {
            let path = delta
                .new_file()
                .path()
                .or_else(|| delta.old_file().path())
                .map(|p| p.to_string_lossy().into_owned())
                .unwrap_or_default();
            let status = delta.status();
            let letter = match status {
                Delta::Deleted => 'D',
                Delta::Renamed => 'R',
                Delta::Added => 'A',
                Delta::Typechange => 'T',
                _ => 'M',
            };
            let (additions, deletions) = stats.get(&path).copied().unwrap_or((0, 0));
            files.push(CommitFile {
                path,
                status: letter,
                additions,
                deletions,
            });
        }
        Ok(files)
    })
    .await
}

/// 读取工作区文件差异 (stage = staged 已暂存 / unstaged 未暂存)
#[tauri::command]
pub async fn git_diff(path: String, file: String, stage: String) -> Result<FileDiff, String> {
    blocking(move || {
        let repo = open_repo(&path)?;
        let index = repo.index().map_err(|e| e.to_string())?;
        let head_tree = head_tree(&repo);
        let workdir = repo.workdir().ok_or("仓库无工作目录")?;

        let (original, modified, original_label, modified_label) = match stage.as_str() {
            "staged" => {
                let old = head_tree
                    .as_ref()
                    .and_then(|t| tree_blob(&repo, t, &file))
                    .unwrap_or_default();
                let new = index_blob(&repo, &index, &file).unwrap_or_default();
                (old, new, "HEAD（已提交）".to_string(), "已暂存".to_string())
            }
            _ => {
                let old = index_blob(&repo, &index, &file).unwrap_or_default();
                let new = std::fs::read(workdir.join(&file)).unwrap_or_default();
                (old, new, "已暂存 / HEAD".to_string(), "工作区".to_string())
            }
        };

        let binary = is_binary(&original) || is_binary(&modified);
        Ok(FileDiff {
            original: String::from_utf8_lossy(&original).into_owned(),
            modified: String::from_utf8_lossy(&modified).into_owned(),
            original_label,
            modified_label,
            binary,
        })
    })
    .await
}

/// 读取某个提交内某文件与其父提交的差异
#[tauri::command]
pub async fn git_commit_diff(
    path: String,
    file: String,
    commit_id: String,
) -> Result<FileDiff, String> {
    blocking(move || {
        let repo = open_repo(&path)?;
        let oid = Oid::from_str(&commit_id).map_err(|e| e.to_string())?;
        let commit = repo.find_commit(oid).map_err(|e| e.to_string())?;
        let tree = commit.tree().map_err(|e| e.to_string())?;
        let parent_tree = commit.parent(0).ok().and_then(|p| p.tree().ok());

        let original = parent_tree
            .as_ref()
            .and_then(|t| tree_blob(&repo, t, &file))
            .unwrap_or_default();
        let modified = tree_blob(&repo, &tree, &file).unwrap_or_default();
        let parent_label = commit
            .parent(0)
            .ok()
            .map(|p| p.id().to_string()[..7.min(p.id().to_string().len())].to_string())
            .unwrap_or_else(|| "空".to_string());

        let binary = is_binary(&original) || is_binary(&modified);
        Ok(FileDiff {
            original: String::from_utf8_lossy(&original).into_owned(),
            modified: String::from_utf8_lossy(&modified).into_owned(),
            original_label: parent_label,
            modified_label: commit.id().to_string()[..7.min(commit.id().to_string().len())]
                .to_string(),
            binary,
        })
    })
    .await
}

/// 将指定文件从某提交还原到项目中
#[tauri::command]
pub async fn git_restore(
    path: String,
    files: Vec<String>,
    commit_id: String,
) -> Result<(), String> {
    blocking(move || {
        let repo = open_repo(&path)?;
        let oid = Oid::from_str(&commit_id).map_err(|e| e.to_string())?;
        let commit = repo.find_commit(oid).map_err(|e| e.to_string())?;
        let tree = commit.tree().map_err(|e| e.to_string())?;
        let obj = tree.into_object();

        let mut opts = CheckoutBuilder::new();
        opts.force();
        for f in &files {
            opts.path(Path::new(f));
        }
        repo.checkout_tree(&obj, Some(&mut opts))
            .map_err(|e| e.to_string())
    })
    .await
}

/// 将某提交的全部文件还原到项目中
#[tauri::command]
pub async fn git_restore_all(path: String, commit_id: String) -> Result<(), String> {
    blocking(move || {
        let repo = open_repo(&path)?;
        let oid = Oid::from_str(&commit_id).map_err(|e| e.to_string())?;
        let commit = repo.find_commit(oid).map_err(|e| e.to_string())?;
        let tree = commit.tree().map_err(|e| e.to_string())?;
        let obj = tree.into_object();

        let mut opts = CheckoutBuilder::new();
        opts.force();
        repo.checkout_tree(&obj, Some(&mut opts))
            .map_err(|e| e.to_string())
    })
    .await
}

/// 读取工作区文件相对索引的逐行变更 (供编辑器行内差异标记)
///
/// 按 git diff 的"删除后紧邻新增"配对语义分类:
/// * 替换行 ('-' 紧邻 '+' 且个数匹配) -> 'M' 修改;
/// * 纯插入 (无相邻删除) -> 'A' 新增;
/// * 纯删除块 -> 'D' (标记在其上方最后一行, 即删除发生处).
#[tauri::command]
pub async fn git_file_changes(path: String, file: String) -> Result<Vec<InlineChange>, String> {
    blocking(move || {
        let repo = open_repo(&path)?;
        let index = repo.index().map_err(|e| e.to_string())?;
        let mut diff_opts = DiffOptions::new();
        diff_opts.pathspec(file.clone());

        let diff = repo
            .diff_index_to_workdir(Some(&index), Some(&mut diff_opts))
            .map_err(|e| e.to_string())?;

        let mut changes = Vec::new();
        for delta_idx in 0..diff.deltas().len() {
            let Some(patch) =
                git2::Patch::from_diff(&diff, delta_idx).map_err(|e| e.to_string())?
            else {
                continue;
            };
            for hunk_idx in 0..patch.num_hunks() {
                let (_hunk, line_count) = patch.hunk(hunk_idx).map_err(|e| e.to_string())?;
                // 收集本 hunk 的真实行: (origin, new_lineno).
                // 过滤文件末尾无换行的 EOF 伪行 (origin '=' / '<' / '>'), 它们常夹在
                // 删除行与新增行之间, 干扰"修改/新增"配对与删除边界判定.
                let mut lines: Vec<(char, Option<u32>)> = Vec::with_capacity(line_count);
                for li in 0..line_count {
                    let line = patch
                        .line_in_hunk(hunk_idx, li)
                        .map_err(|e| e.to_string())?;
                    let origin = line.origin();
                    if matches!(origin, ' ' | '+' | '-') {
                        lines.push((origin, line.new_lineno()));
                    }
                }

                let n = lines.len();
                let mut i = 0;
                while i < n {
                    match lines[i].0 {
                        // 上下文: 跳过
                        ' ' => i += 1,
                        // 新增 / 修改
                        '+' => {
                            // 紧邻本 '+' 运行之前是否有 '-' 运行 (即替换), 及删除个数
                            let mut minus = 0;
                            let mut k = i;
                            while k > 0 && lines[k - 1].0 == '-' {
                                minus += 1;
                                k -= 1;
                            }
                            let mut j = i;
                            let mut idx = 0usize;
                            while j < n && lines[j].0 == '+' {
                                let kind = if idx < minus { 'M' } else { 'A' };
                                if let Some(line) = lines[j].1 {
                                    changes.push(InlineChange { line, kind });
                                }
                                idx += 1;
                                j += 1;
                            }
                            i = j;
                        }
                        // 删除
                        '-' => {
                            let mut j = i;
                            while j < n && lines[j].0 == '-' {
                                j += 1;
                            }
                            // 若其后紧跟新增 (替换), 则不单独标记删除; 否则为纯删除块
                            let replaced = j < n && lines[j].0 == '+';
                            if !replaced {
                                // 标记在删除块上方最后一行; 文件开头无前行则取 1
                                let boundary =
                                    lines[..i].iter().rev().find_map(|(_, nl)| *nl).unwrap_or(1);
                                changes.push(InlineChange {
                                    line: boundary,
                                    kind: 'D',
                                });
                            }
                            i = j;
                        }
                        _ => i += 1,
                    }
                }
            }
        }
        Ok(changes)
    })
    .await
}

/// 读取工作区文件中包含指定行 (新侧行号) 的连续差异块, 用于色块就地展开。
///
/// 只返回命中行所在的那一段连续变更 (旧 '-' / 新 '+', 不含相邻的其它差异块与上下文),
/// 并给出插入锚点 `anchor` (该块末行新行号, 删除块为其边界行)。
#[tauri::command]
pub async fn git_file_region(
    path: String,
    file: String,
    line: u32,
) -> Result<Option<InlineRegion>, String> {
    blocking(move || {
        let repo = open_repo(&path)?;
        let index = repo.index().map_err(|e| e.to_string())?;
        let mut diff_opts = DiffOptions::new();
        diff_opts.pathspec(file.clone());

        let diff = repo
            .diff_index_to_workdir(Some(&index), Some(&mut diff_opts))
            .map_err(|e| e.to_string())?;

        // 收集本文件全部差异行 (去掉 EOF 伪行), 按文件顺序
        let mut flat: Vec<(char, Option<u32>, String)> = Vec::new();
        for delta_idx in 0..diff.deltas().len() {
            let Some(patch) =
                git2::Patch::from_diff(&diff, delta_idx).map_err(|e| e.to_string())?
            else {
                continue;
            };
            for hunk_idx in 0..patch.num_hunks() {
                let (_hunk, line_count) = patch.hunk(hunk_idx).map_err(|e| e.to_string())?;
                for li in 0..line_count {
                    let dl = patch
                        .line_in_hunk(hunk_idx, li)
                        .map_err(|e| e.to_string())?;
                    let origin = dl.origin();
                    if !matches!(origin, ' ' | '+' | '-') {
                        continue;
                    }
                    let text = String::from_utf8_lossy(dl.content())
                        .trim_end_matches(['\n', '\r'])
                        .to_string();
                    flat.push((origin, dl.new_lineno(), text));
                }
            }
        }

        // 按连续 "-/+" 运行切分为差异块 (上下文行分隔)
        struct Block {
            min_new: u32,
            max_new: u32,
            anchor: u32,
            rows: Vec<DiffRow>,
        }
        let mut blocks: Vec<Block> = Vec::new();
        let mut last_ctx_new: Option<u32> = None;
        let mut i = 0;
        let n = flat.len();
        while i < n {
            let (origin, nl, _) = &flat[i];
            if *origin == ' ' {
                if let Some(x) = *nl {
                    last_ctx_new = Some(x);
                }
                i += 1;
                continue;
            }
            // 一段连续变更运行
            let mut rows: Vec<DiffRow> = Vec::new();
            let mut min_new: Option<u32> = None;
            let mut max_new: Option<u32> = None;
            let mut has_add = false;
            while i < n && flat[i].0 != ' ' {
                let (o, ln, text) = &flat[i];
                rows.push(DiffRow {
                    kind: *o,
                    text: text.clone(),
                });
                if *o == '+' {
                    has_add = true;
                    if let Some(x) = *ln {
                        min_new = Some(min_new.map_or(x, |m| m.min(x)));
                        max_new = Some(max_new.map_or(x, |m| m.max(x)));
                    }
                }
                i += 1;
            }
            if has_add {
                let min_new = min_new.unwrap_or(1);
                let max_new = max_new.unwrap_or(min_new);
                blocks.push(Block {
                    min_new,
                    max_new,
                    anchor: max_new,
                    rows,
                });
            } else {
                // 纯删除块: 标记落在其上方边界行
                let boundary = last_ctx_new.unwrap_or(1);
                blocks.push(Block {
                    min_new: boundary,
                    max_new: boundary,
                    anchor: boundary,
                    rows,
                });
            }
        }

        // 取新侧行号区间距离 `line` 最近的块
        let mut best: Option<(i64, InlineRegion)> = None;
        for block in blocks {
            let dist = if line < block.min_new {
                (block.min_new - line) as i64
            } else if line > block.max_new {
                (line - block.max_new) as i64
            } else {
                0
            };
            let region = InlineRegion {
                rows: block.rows,
                anchor: block.anchor,
            };
            if best.as_ref().is_none_or(|(d, _)| dist < *d) {
                best = Some((dist, region));
            }
        }
        Ok(best.map(|(_, region)| region))
    })
    .await
}
