// This file is generated by AI.

//! GPT-SoVITS 配音工作流服务。
//!
//! 由若干职责单一的模块组成:
//! * [`launcher`] - 启动/停止本地 GPT-SoVITS 整合包 (内置 runtime / 外部 Python / 自定义命令);
//! * [`gsov`] - GPT-SoVITS HTTP API 客户端与就绪探针;
//! * [`scene`] - 场景对话抽取与配音引用改写;
//! * [`audio`] - 参考音频校验/裁剪与内容哈希;
//! * [`library`] - 角色库 (模型 + 参考音频) 的读写与导入导出;
//! * [`realign`] - 配音历史与场景对话的重新对齐;
//! * [`wav`] - WAV 读写 (基于 `hound`)。
//!
//! 进程生命周期与编辑器内已有的 LSP / 预览服务器一致: 由 `lib.rs` 在退出时统一收尸。

use std::{
    cmp::Reverse,
    path::{Path, PathBuf},
    sync::Arc,
};

use serde::{Deserialize, Serialize};
use tauri::{ipc::Channel, Manager};
use tokio::{
    io::{AsyncBufReadExt, BufReader},
    process::{Child, Command},
    sync::Mutex,
};

use crate::service::voice::launcher::{CondaEnv, DetectedRuntime, LaunchConfig, LineSplitter};

pub mod audio;
pub mod gsov;
pub mod launcher;
pub mod library;
pub mod realign;
pub mod scene;
pub mod wav;

/// GSOV 服务状态
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub enum GsvStatus {
    /// 未启动
    Stopped,
    /// 进程已拉起, 模型仍在加载
    Starting,
    /// API 已可服务
    Ready,
    /// 启动失败或进程异常退出
    Error,
}

/// 推送给前端的事件
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase", tag = "type")]
pub enum VoiceEvent {
    /// GSOV 进程输出的一行日志
    Log { line: String },
    /// 状态变化
    Status {
        status: GsvStatus,
        detail: Option<String>,
    },
}

/// GSOV 进程与状态
pub struct VoiceState {
    config: Mutex<Option<LaunchConfig>>,
    child: Mutex<Option<Child>>,
    status: Mutex<GsvStatus>,
    detail: Mutex<Option<String>>,
    logs: Mutex<Vec<String>>,
}

/// 日志缓冲区上限 (行)
const LOG_LIMIT: usize = 500;

impl Default for VoiceState {
    fn default() -> Self {
        Self {
            config: Mutex::new(None),
            child: Mutex::new(None),
            status: Mutex::new(GsvStatus::Stopped),
            detail: Mutex::new(None),
            logs: Mutex::new(Vec::new()),
        }
    }
}

impl VoiceState {
    async fn set_status(
        &self,
        status: GsvStatus,
        detail: Option<String>,
        channel: Option<&Channel<VoiceEvent>>,
    ) {
        *self.status.lock().await = status;
        *self.detail.lock().await = detail.clone();
        if let Some(channel) = channel {
            let _ = channel.send(VoiceEvent::Status { status, detail });
        }
    }

    async fn push_log(&self, line: String, channel: Option<&Channel<VoiceEvent>>) {
        {
            let mut logs = self.logs.lock().await;
            if logs.len() >= LOG_LIMIT {
                logs.remove(0);
            }
            logs.push(line.clone());
        }
        if let Some(channel) = channel {
            let _ = channel.send(VoiceEvent::Log { line });
        }
    }

    /// 关闭 GSOV 进程 (优先优雅退出, 超时后强杀)
    pub async fn shutdown(&self) {
        let mut guard = self.child.lock().await;
        let Some(mut child) = guard.take() else {
            return;
        };
        if let Some(config) = self.config.lock().await.clone() {
            let client = gsov::GsvClient::new(&config.host, config.port);
            let _ =
                tokio::time::timeout(std::time::Duration::from_secs(2), client.shutdown()).await;
        }
        // 给服务端一点时间自行退出 (它会落盘推理配置)
        let exited = tokio::time::timeout(std::time::Duration::from_secs(3), child.wait())
            .await
            .is_ok();
        if !exited {
            let _ = child.kill().await;
            let _ = child.wait().await;
        }
        *self.status.lock().await = GsvStatus::Stopped;
    }
}

// -------- 命令: 启动器 --------

/// 探测整合包目录
#[tauri::command]
pub async fn voice_detect_runtime(root: String) -> DetectedRuntime {
    launcher::detect(Path::new(&root))
}

/// 探测整合包目录并返回默认启动配置
#[tauri::command]
pub async fn voice_default_launch_config(root: String) -> Result<LaunchConfig, String> {
    let path = PathBuf::from(&root);
    let detected = launcher::detect(&path);
    if !detected.valid {
        return Err(detected
            .issues
            .first()
            .cloned()
            .unwrap_or_else(|| "不是有效的 GPT-SoVITS 整合包目录".into()));
    }
    Ok(launcher::default_config(&path, &detected))
}

/// 列出本机可用的 conda 环境 (供"从 conda 启动"选择)
#[tauri::command]
pub async fn voice_list_conda_envs() -> Vec<CondaEnv> {
    launcher::list_conda_envs()
}

/// 扫描整合包内的 v4 权重, 给出可配对的模型候选
#[tauri::command]
pub async fn voice_list_models(root: String) -> Result<Vec<launcher::ModelCandidate>, String> {
    Ok(launcher::scan_models(Path::new(&root)))
}

/// 启动 GSOV 服务
#[tauri::command]
pub async fn voice_launch(
    state: tauri::State<'_, Arc<VoiceState>>,
    config: LaunchConfig,
    on_event: Channel<VoiceEvent>,
) -> Result<(), String> {
    state.shutdown().await;

    let command = config.build_command();
    if !Path::new(&command.cwd).is_dir() {
        return Err(format!("工作目录不存在: {}", command.cwd.display()));
    }

    let mut process = Command::new(&command.program);
    process
        .args(&command.args)
        .current_dir(&command.cwd)
        // 统一 UTF-8 输出; 关闭 coloredlogs 的自动安装钩子, 保证日志可预测
        .env("PYTHONIOENCODING", "utf-8")
        .env("PYTHONUTF8", "1")
        .env("HF_HUB_OFFLINE", "1")
        .env("COLOREDLOGS_AUTO_INSTALL", "0")
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .kill_on_drop(true);

    let mut child = process
        .spawn()
        .map_err(|error| format!("无法启动 GSOV 进程 ({}): {error}", command.program))?;

    // 日志读取: 两个流共用一个切分器, 保证进度条不会被拆成两半
    let splitter = Arc::new(std::sync::Mutex::new(LineSplitter::new()));
    let state_arc: Arc<VoiceState> = state.inner().clone();

    if let Some(stdout) = child.stdout.take() {
        spawn_log_reader(
            stdout,
            splitter.clone(),
            state_arc.clone(),
            on_event.clone(),
        );
    }
    if let Some(stderr) = child.stderr.take() {
        spawn_log_reader(
            stderr,
            splitter.clone(),
            state_arc.clone(),
            on_event.clone(),
        );
    }

    *state.config.lock().await = Some(config.clone());
    *state.child.lock().await = Some(child);
    state
        .set_status(GsvStatus::Starting, None, Some(&on_event))
        .await;
    state
        .push_log(
            format!("$ {} {}", command.program, command.args.join(" ")),
            Some(&on_event),
        )
        .await;

    Ok(())
}

fn spawn_log_reader<R>(
    reader: R,
    splitter: Arc<std::sync::Mutex<LineSplitter>>,
    state: Arc<VoiceState>,
    channel: Channel<VoiceEvent>,
) where
    R: tokio::io::AsyncRead + Unpin + Send + 'static,
{
    tauri::async_runtime::spawn(async move {
        let mut lines = BufReader::new(reader).lines();
        while let Ok(Some(line)) = lines.next_line().await {
            let split = splitter
                .lock()
                .map(|mut s| s.push(&line))
                .unwrap_or_default();
            for entry in split {
                state.push_log(entry, Some(&channel)).await;
            }
        }
        // 进程结束时交出缓冲区残留 (无换行结尾的最后一行)
        let tail = splitter.lock().map(|mut s| s.flush()).unwrap_or_default();
        if let Some(line) = tail {
            state.push_log(line, Some(&channel)).await;
        }
    });
}

/// 停止 GSOV 服务
#[tauri::command]
pub async fn voice_shutdown(state: tauri::State<'_, Arc<VoiceState>>) -> Result<(), String> {
    state.shutdown().await;
    Ok(())
}

/// 服务状态快照
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct VoiceStatus {
    pub status: GsvStatus,
    pub detail: Option<String>,
    pub base_url: Option<String>,
}

/// 查询当前状态 (不主动探测)
#[tauri::command]
pub async fn voice_status(state: tauri::State<'_, Arc<VoiceState>>) -> Result<VoiceStatus, String> {
    let config = state.config.lock().await.clone();
    Ok(VoiceStatus {
        status: *state.status.lock().await,
        detail: state.detail.lock().await.clone(),
        base_url: config.map(|config| format!("http://{}:{}", config.host, config.port)),
    })
}

/// 取走日志缓冲 (总控台打开时补全历史日志)
#[tauri::command]
pub async fn voice_take_logs(
    state: tauri::State<'_, Arc<VoiceState>>,
) -> Result<Vec<String>, String> {
    let mut logs = state.logs.lock().await;
    Ok(std::mem::take(&mut *logs))
}

/// 就绪探测: 命中后状态置为 `Ready`
#[tauri::command]
pub async fn voice_probe(
    state: tauri::State<'_, Arc<VoiceState>>,
    host: Option<String>,
    port: Option<u16>,
) -> Result<bool, String> {
    let config = state.config.lock().await.clone();
    let host = host
        .or_else(|| config.as_ref().map(|config| config.host.clone()))
        .unwrap_or_else(|| launcher::DEFAULT_HOST.to_string());
    let port = port
        .or_else(|| config.as_ref().map(|config| config.port))
        .unwrap_or(launcher::DEFAULT_PORT);

    // 进程已退出时直接判定失败, 避免前端无限等待
    {
        let mut guard = state.child.lock().await;
        if let Some(child) = guard.as_mut() {
            if let Ok(Some(status)) = child.try_wait() {
                let detail = format!("GSOV 进程已退出 ({status})");
                *guard = None;
                drop(guard);
                let state_arc: Arc<VoiceState> = state.inner().clone();
                state_arc
                    .set_status(GsvStatus::Error, Some(detail.clone()), None)
                    .await;
                return Err(detail);
            }
        }
    }

    let client = gsov::GsvClient::new(&host, port);
    match client.probe().await {
        Ok(()) => {
            let state_arc: Arc<VoiceState> = state.inner().clone();
            state_arc.set_status(GsvStatus::Ready, None, None).await;
            Ok(true)
        }
        Err(error) => {
            // 仅保留诊断信息, 状态仍为 Starting (由前端决定何时判超时)
            *state.detail.lock().await = Some(error.to_string());
            Ok(false)
        }
    }
}

// -------- 命令: 推理 --------

/// 一次配音生成的入参
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SynthesizeRequest {
    /// 待合成文本 (来自场景对话)
    pub text: String,
    /// 文本语言码
    pub text_lang: String,
    /// 参考音频在服务端本机可见的绝对路径
    pub ref_audio_path: String,
    /// 参考文本 (v4 必需, 且须与音频逐字一致)
    pub prompt_text: String,
    /// 参考文本语言码
    pub prompt_lang: String,
    /// 采样步数: 测试 4 / 正式 32
    pub sample_steps: u32,
    pub temperature: f32,
    pub speed_factor: f32,
    pub top_k: u32,
    pub top_p: f32,
    pub repetition_penalty: f32,
    /// 文本切分方式 (默认 cut5)
    #[serde(default)]
    pub text_split_method: Option<String>,
    /// 随机种子; `-1` 表示由服务端随机
    #[serde(default)]
    pub seed: Option<i64>,
}

/// 推理结果: 已落盘的缓存条目
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SynthesizeResult {
    pub entry: CacheEntry,
    /// 服务端返回的音频时长 (秒)
    pub duration: f64,
    pub sample_rate: u32,
}

/// 执行一次配音生成, 并把结果写入内容寻址的本地缓存。
///
/// 调用方 (**前端队列**) 必须保证串行: GSOV 后端为单进程单 worker 且持有全局
/// prompt 缓存, 并发请求会互相干扰。
#[tauri::command]
pub async fn voice_synthesize(
    app: tauri::AppHandle,
    state: tauri::State<'_, Arc<VoiceState>>,
    request: SynthesizeRequest,
) -> Result<SynthesizeResult, String> {
    if !gsov::SAMPLE_STEPS.contains(&request.sample_steps) {
        return Err(format!(
            "采样步数 {} 不受 v4 模型支持 (仅 {:?})",
            request.sample_steps,
            gsov::SAMPLE_STEPS
        ));
    }
    if request.prompt_text.trim().is_empty() {
        return Err("参考文本不可为空 (v4 模型必需)".into());
    }
    if !Path::new(&request.ref_audio_path).is_file() {
        return Err(format!("参考音频不存在: {}", request.ref_audio_path));
    }

    let config = state
        .config
        .lock()
        .await
        .clone()
        .ok_or_else(|| "GSOV 尚未配置启动参数".to_string())?;

    let mut tts = gsov::TtsRequest::new(
        request.text,
        request.text_lang,
        request.ref_audio_path,
        request.prompt_text,
        request.prompt_lang,
    );
    tts.sample_steps = request.sample_steps;
    tts.temperature = request.temperature;
    tts.speed_factor = request.speed_factor;
    tts.top_k = request.top_k;
    tts.top_p = request.top_p;
    tts.repetition_penalty = request.repetition_penalty;
    if let Some(method) = request.text_split_method {
        tts.text_split_method = method;
    }
    if let Some(seed) = request.seed {
        tts.seed = seed;
    }

    let client = gsov::GsvClient::new(&config.host, config.port);
    let bytes = client
        .synthesize(&tts)
        .await
        .map_err(|error| error.to_string())?;

    // 先在临时目录落盘再入库, 保证缓存只出现完整文件
    let root = cache_root(&app)?;
    std::fs::create_dir_all(&root).map_err(|error| error.to_string())?;
    let staging = root.join("staging.wav");
    std::fs::write(&staging, &bytes).map_err(|error| format!("写入配音缓存失败: {error}"))?;

    let probe = audio::probe(&staging)?;
    if probe.duration <= 0.0 {
        let _ = std::fs::remove_file(&staging);
        return Err("服务端返回了空音频".into());
    }

    let hash = audio::hash_file(&staging)?;
    let target = root.join(format!("{hash}.wav"));
    if target.is_file() {
        let _ = std::fs::remove_file(&staging);
    } else {
        std::fs::rename(&staging, &target).map_err(|error| format!("写入配音缓存失败: {error}"))?;
    }

    let size = std::fs::metadata(&target)
        .map_err(|error| error.to_string())?
        .len();
    Ok(SynthesizeResult {
        entry: CacheEntry {
            hash,
            path: target.display().to_string(),
            size,
            modified_at: library::now_millis(),
        },
        duration: probe.duration,
        sample_rate: probe.sample_rate,
    })
}

/// 显式切换 GSOV 权重。
///
/// 刻意设计为用户显式触发: 服务端切换权重会重载模型并落盘配置, 属于高代价操作。
/// 队列通过按角色分组让同角色任务连续执行, 从而避免频繁切换。
#[tauri::command]
pub async fn voice_set_model(
    state: tauri::State<'_, Arc<VoiceState>>,
    gpt_weights: Option<String>,
    sovits_weights: Option<String>,
) -> Result<(), String> {
    let config = state
        .config
        .lock()
        .await
        .clone()
        .ok_or_else(|| "GSOV 尚未配置启动参数".to_string())?;
    let client = gsov::GsvClient::new(&config.host, config.port);
    if let Some(path) = gpt_weights {
        client
            .set_gpt_weights(&path)
            .await
            .map_err(|error| format!("切换 GPT 权重失败: {error}"))?;
    }
    if let Some(path) = sovits_weights {
        client
            .set_sovits_weights(&path)
            .await
            .map_err(|error| format!("切换 SoVITS 权重失败: {error}"))?;
    }
    Ok(())
}

// -------- 命令: 场景 --------

/// 解析场景中的对话语句
#[tauri::command]
pub async fn voice_parse_scene(content: String) -> Result<Vec<scene::SayLine>, String> {
    Ok(scene::parse_say_lines(&content))
}

/// 改写若干条语句的配音引用。
///
/// 任何一条校验失败都会整体回滚 (返回 `Err`), 避免场景被部分改写。
#[tauri::command]
pub async fn voice_apply_lines(
    content: String,
    edits: Vec<scene::LineEdit>,
) -> Result<Vec<scene::LineEditResult>, String> {
    if edits.is_empty() {
        return Ok(Vec::new());
    }

    // 统一按 LF 切分 (编辑器内容已是 LF; 磁盘读取时由调用方做行尾归一)
    let mut lines: Vec<String> = content.split('\n').map(str::to_string).collect();
    let mut results = Vec::new();

    for edit in &edits {
        let current = lines
            .get(edit.line)
            .ok_or_else(|| format!("第 {} 行已不存在, 场景可能已被修改", edit.line + 1))?;

        if let Some(expect) = &edit.expect {
            if current.trim_end() != expect.trim_end() {
                return Err(format!(
                    "第 {} 行的内容与预期不符, 场景可能已被修改",
                    edit.line + 1
                ));
            }
        }

        let rewritten = scene::rewrite_line(current, edit.vocal.as_deref())?;
        lines[edit.line] = rewritten.clone();
        results.push(scene::LineEditResult {
            line: edit.line,
            text: rewritten,
        });
    }

    Ok(results)
}

/// 生成改写后的完整场景内容 (供前端一次性写回编辑器)
#[tauri::command]
pub async fn voice_apply_scene(
    content: String,
    edits: Vec<scene::LineEdit>,
) -> Result<String, String> {
    let mut lines: Vec<String> = content.split('\n').map(str::to_string).collect();
    for edit in &edits {
        let current = lines
            .get(edit.line)
            .ok_or_else(|| format!("第 {} 行已不存在, 场景可能已被修改", edit.line + 1))?;
        if let Some(expect) = &edit.expect {
            if current.trim_end() != expect.trim_end() {
                return Err(format!(
                    "第 {} 行的内容与预期不符, 场景可能已被修改",
                    edit.line + 1
                ));
            }
        }
        lines[edit.line] = scene::rewrite_line(current, edit.vocal.as_deref())?;
    }
    Ok(lines.join("\n"))
}

// -------- 命令: 音频 --------

/// 音频属性
#[tauri::command]
pub async fn voice_probe_audio(path: String) -> Result<audio::AudioInfo, String> {
    audio::probe(Path::new(&path))
}

/// 裁剪建议
#[tauri::command]
pub async fn voice_trim_suggestion(path: String) -> Result<audio::TrimSuggestion, String> {
    audio::trim_suggestion(Path::new(&path))
}

/// 波形包络
#[tauri::command]
pub async fn voice_waveform(path: String) -> Result<audio::Waveform, String> {
    audio::waveform(Path::new(&path))
}

/// 规范化参考音频到指定路径
#[tauri::command]
pub async fn voice_normalize_reference(
    source: String,
    destination: String,
    start: Option<f64>,
    end: Option<f64>,
) -> Result<audio::NormalizedRef, String> {
    let range = match (start, end) {
        (Some(start), Some(end)) => Some((start, end)),
        _ => None,
    };
    audio::normalize_reference(Path::new(&source), Path::new(&destination), range)
}

/// 把音频读为 data URL (供前端试听; 参考音频体积很小, 无需额外 HTTP 服务)
#[tauri::command]
pub async fn voice_read_audio(path: String) -> Result<String, String> {
    let bytes = std::fs::read(&path).map_err(|error| format!("读取音频失败: {error}"))?;
    if bytes.len() > 32 * 1024 * 1024 {
        return Err("音频文件过大, 无法在编辑器内试听".into());
    }
    Ok(format!("data:audio/wav;base64,{}", base64_encode(&bytes)))
}

/// 标准 base64 编码 (避免为一次试听引入依赖)
fn base64_encode(bytes: &[u8]) -> String {
    const TABLE: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = String::with_capacity(bytes.len().div_ceil(3) * 4);
    for chunk in bytes.chunks(3) {
        let byte0 = chunk[0] as u32;
        let byte1 = chunk.get(1).copied().unwrap_or(0) as u32;
        let byte2 = chunk.get(2).copied().unwrap_or(0) as u32;
        let triple = (byte0 << 16) | (byte1 << 8) | byte2;
        out.push(TABLE[(triple >> 18) as usize & 0x3F] as char);
        out.push(TABLE[(triple >> 12) as usize & 0x3F] as char);
        out.push(if chunk.len() > 1 {
            TABLE[(triple >> 6) as usize & 0x3F] as char
        } else {
            '='
        });
        out.push(if chunk.len() > 2 {
            TABLE[triple as usize & 0x3F] as char
        } else {
            '='
        });
    }
    out
}

// -------- 命令: 角色库 --------

/// 角色库根目录: `<appdata>/characters`
pub fn characters_root(app: &tauri::AppHandle) -> Result<PathBuf, String> {
    let dir = app
        .path()
        .app_data_dir()
        .map_err(|error| format!("无法定位应用数据目录: {error}"))?;
    Ok(dir.join("characters"))
}

/// 配音缓存根目录: `<appdata>/tts`
pub fn cache_root(app: &tauri::AppHandle) -> Result<PathBuf, String> {
    let dir = app
        .path()
        .app_data_dir()
        .map_err(|error| format!("无法定位应用数据目录: {error}"))?;
    Ok(dir.join("tts"))
}

fn library_of(app: &tauri::AppHandle) -> Result<library::Library, String> {
    Ok(library::Library::new(characters_root(app)?))
}

/// 列出全部角色
#[tauri::command]
pub async fn voice_list_characters(
    app: tauri::AppHandle,
) -> Result<Vec<library::Character>, String> {
    library_of(&app)?.list().map_err(|error| error.to_string())
}

/// 读取单个角色
#[tauri::command]
pub async fn voice_load_character(
    app: tauri::AppHandle,
    id: String,
) -> Result<library::Character, String> {
    library_of(&app)?
        .load(&id)
        .map_err(|error| error.to_string())
}

/// 保存角色 (新建或更新)。`previous_id` 给出改名前的 id (未改名时省略)。
#[tauri::command]
pub async fn voice_save_character(
    app: tauri::AppHandle,
    character: library::Character,
    previous_id: Option<String>,
) -> Result<library::Character, String> {
    library_of(&app)?
        .save_as(previous_id.as_deref(), character)
        .map_err(|error| error.to_string())
}

/// 按**字段**修改角色 (服务端读-改-写)。
///
/// 这是界面上所有角色修改的入口: 只发送要改的字段, 因此勾选"参与配音"不会顺手
/// 把星标/模型等其它字段回写成前端那份可能过时的快照。
#[tauri::command]
pub async fn voice_update_character(
    app: tauri::AppHandle,
    id: String,
    patch: library::CharacterPatch,
) -> Result<library::Character, String> {
    library_of(&app)?
        .patch(&id, patch)
        .map_err(|error| error.to_string())
}

/// 删除角色
#[tauri::command]
pub async fn voice_remove_character(app: tauri::AppHandle, id: String) -> Result<(), String> {
    library_of(&app)?
        .remove(&id)
        .map_err(|error| error.to_string())
}

/// 新建角色的入参
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NewCharacter {
    pub name: String,
    #[serde(default)]
    pub description: String,
    #[serde(default = "default_language")]
    pub language: String,
}

fn default_language() -> String {
    "auto".into()
}

/// 新建角色 (自动生成不与现有角色冲突的 id)
#[tauri::command]
pub async fn voice_create_character(
    app: tauri::AppHandle,
    input: NewCharacter,
) -> Result<library::Character, String> {
    let name = input.name.trim();
    if name.is_empty() {
        return Err("角色名不可为空".into());
    }
    let library = library_of(&app)?;
    let root = characters_root(&app)?;
    std::fs::create_dir_all(&root).map_err(|error| error.to_string())?;
    let id = library::unique_id(&root, name);
    let now = library::now_millis();
    let character = library::Character {
        id,
        name: name.to_string(),
        description: input.description,
        language: input.language,
        references: Vec::new(),
        model: None,
        starred: false,
        enabled: true,
        created_at: now,
        updated_at: now,
    };
    library.save(character).map_err(|error| error.to_string())
}

/// 添加参考音频的入参
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ReferenceInput {
    /// 源音频路径 (任意用户可见位置, 会被拷贝进角色库)
    pub source: String,
    /// 参考文本 (v4 必需, 且须与音频逐字一致)
    pub text: String,
    /// 语言码
    pub language: String,
    /// 风格标签 (v0.5 仅 Ink 内部使用)
    #[serde(default)]
    pub tags: Vec<String>,
    /// 裁剪区间起点 (秒); 与 `end` 同时给出才生效
    #[serde(default)]
    pub start: Option<f64>,
    /// 裁剪区间终点 (秒)
    #[serde(default)]
    pub end: Option<f64>,
}

/// 添加参考音频: 规范化 (3~10 秒约束) 后纳入角色库
#[tauri::command]
pub async fn voice_add_reference(
    app: tauri::AppHandle,
    id: String,
    input: ReferenceInput,
) -> Result<library::Character, String> {
    let library = library_of(&app)?;
    let mut character = library.load(&id).map_err(|error| error.to_string())?;

    let dir = characters_root(&app)?.join(&id);
    std::fs::create_dir_all(&dir).map_err(|error| error.to_string())?;
    let staged = dir.join("staged.wav");

    let range = match (input.start, input.end) {
        (Some(start), Some(end)) => Some((start, end)),
        _ => None,
    };
    audio::normalize_reference(Path::new(&input.source), &staged, range)?;

    let reference = library
        .adopt_reference(&id, &staged, input.text, input.language, input.tags)
        .map_err(|error| error.to_string())?;
    let _ = std::fs::remove_file(&staged);

    character.references.push(reference);
    library.save(character).map_err(|error| error.to_string())
}

/// 移除参考音频 (仅当库内无其他条目引用同一文件时才删除文件)
#[tauri::command]
pub async fn voice_remove_reference(
    app: tauri::AppHandle,
    id: String,
    hash: String,
) -> Result<library::Character, String> {
    let library = library_of(&app)?;
    let mut character = library.load(&id).map_err(|error| error.to_string())?;
    let removed: Vec<_> = character
        .references
        .iter()
        .filter(|reference| reference.hash == hash)
        .map(|reference| reference.file.clone())
        .collect();
    character
        .references
        .retain(|reference| reference.hash != hash);

    for file in removed {
        let still_used = character
            .references
            .iter()
            .any(|reference| reference.file == file);
        library
            .drop_reference_file(&id, &file, still_used)
            .map_err(|error| error.to_string())?;
    }
    library.save(character).map_err(|error| error.to_string())
}

/// 导出角色为 zip
#[tauri::command]
pub async fn voice_export_character(
    app: tauri::AppHandle,
    id: String,
    destination: String,
) -> Result<(), String> {
    library_of(&app)?
        .export_zip(&id, Path::new(&destination))
        .map_err(|error| error.to_string())
}

/// 从 zip 导入角色
#[tauri::command]
pub async fn voice_import_character(
    app: tauri::AppHandle,
    source: String,
) -> Result<library::Character, String> {
    library_of(&app)?
        .import_zip(Path::new(&source))
        .map_err(|error| error.to_string())
}

/// 单个角色最多导入的参考音频条数。
///
/// 之前是 48, 结果"导入 109 条"会被硬截断成 48 条并静默丢掉 61 条 —— 用户看到的
/// 是"跳过 61 条"却不知道那是上限。真实语料每个角色上百条很常见, 因此这里放宽到
/// 一个不会误伤的量级; 过长的音频由规范化流程自动裁剪, 不再丢数据。
const LIST_IMPORT_LIMIT: usize = 5000;

/// 从 GPT-SoVITS 切片产物 (`.list` 清单 + 音频目录) 批量导入角色与参考音频。
///
/// 用户分别提供**清单文件**与**音频目录** (两者位置无关)。
#[tauri::command]
pub async fn voice_import_characters_from_list(
    app: tauri::AppHandle,
    list_path: String,
    audio_dir: String,
) -> Result<library::ListImportReport, String> {
    let library = library_of(&app)?;
    tauri::async_runtime::spawn_blocking(move || {
        library
            .import_from_list(
                Path::new(&list_path),
                Path::new(&audio_dir),
                LIST_IMPORT_LIMIT,
            )
            .map_err(|error| error.to_string())
    })
    .await
    .map_err(|error| error.to_string())?
}

// -------- 命令: 配音缓存 --------

/// 缓存条目元信息
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CacheEntry {
    pub hash: String,
    pub path: String,
    pub size: u64,
    pub modified_at: i64,
}

/// 列出配音缓存
#[tauri::command]
pub async fn voice_list_cache(app: tauri::AppHandle) -> Result<Vec<CacheEntry>, String> {
    let root = cache_root(&app)?;
    let mut entries = Vec::new();
    if !root.is_dir() {
        return Ok(entries);
    }
    for entry in std::fs::read_dir(&root).map_err(|error| error.to_string())? {
        let entry = entry.map_err(|error| error.to_string())?;
        let path = entry.path();
        if path.extension().and_then(|ext| ext.to_str()) != Some("wav") {
            continue;
        }
        let metadata = entry.metadata().map_err(|error| error.to_string())?;
        let hash = path
            .file_stem()
            .and_then(|stem| stem.to_str())
            .unwrap_or_default()
            .to_string();
        let modified_at = metadata
            .modified()
            .ok()
            .and_then(|time| time.duration_since(std::time::UNIX_EPOCH).ok())
            .map(|duration| duration.as_millis() as i64)
            .unwrap_or_default();
        entries.push(CacheEntry {
            hash,
            path: path.display().to_string(),
            size: metadata.len(),
            modified_at,
        });
    }
    entries.sort_by_key(|b| Reverse(b.modified_at));
    Ok(entries)
}

/// 把一段音频写入缓存 (以内容哈希命名), 返回缓存路径与哈希
#[tauri::command]
pub async fn voice_store_cache(
    app: tauri::AppHandle,
    source: String,
) -> Result<CacheEntry, String> {
    let root = cache_root(&app)?;
    std::fs::create_dir_all(&root).map_err(|error| error.to_string())?;
    let hash = audio::hash_file(Path::new(&source))?;
    let target = root.join(format!("{hash}.wav"));
    if !target.is_file() {
        std::fs::copy(&source, &target).map_err(|error| format!("写入配音缓存失败: {error}"))?;
    }
    let metadata = std::fs::metadata(&target).map_err(|error| error.to_string())?;
    Ok(CacheEntry {
        hash,
        path: target.display().to_string(),
        size: metadata.len(),
        modified_at: library::now_millis(),
    })
}

/// 删除缓存条目
#[tauri::command]
pub async fn voice_drop_cache(app: tauri::AppHandle, hashes: Vec<String>) -> Result<usize, String> {
    let root = cache_root(&app)?;
    let mut removed = 0;
    for hash in hashes {
        // 只接受纯十六进制哈希, 防止路径穿越
        if hash.is_empty() || !hash.chars().all(|ch| ch.is_ascii_hexdigit()) {
            continue;
        }
        let path = root.join(format!("{hash}.wav"));
        if path.is_file() {
            std::fs::remove_file(&path).map_err(|error| error.to_string())?;
            removed += 1;
        }
    }
    Ok(removed)
}

// -------- 命令: 项目引用扫描与历史对齐 --------

/// 一条配音引用
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct VocalReference {
    /// `-vocal=` 的值 (相对 `game/vocal/`)
    pub vocal: String,
    /// 项目内绝对路径
    pub path: String,
    pub scene: String,
    pub line: usize,
    /// 文件是否存在
    pub exists: bool,
}

/// 扫描项目中全部 `-vocal=` 引用。
///
/// 用于判断某段配音是否被其他语句/场景引用, 从而安全地清理缓存。
/// 前端应在用户打开清理入口时按需调用 (而不是常驻维护引用计数:
/// 用户可能在普通编辑器里手改、git 切分支, 增量计数必然漂移)。
#[tauri::command]
pub async fn voice_scan_references(project: String) -> Result<Vec<VocalReference>, String> {
    let scene_dir = Path::new(&project).join("game").join("scene");
    if !scene_dir.is_dir() {
        return Err(format!("场景目录不存在: {}", scene_dir.display()));
    }
    let mut references = Vec::new();

    let entries = walkdir::WalkDir::new(&scene_dir)
        .into_iter()
        .filter_map(Result::ok)
        .filter(|entry| entry.file_type().is_file())
        .filter(|entry| entry.path().extension().and_then(|ext| ext.to_str()) == Some("txt"));

    for entry in entries {
        let path = entry.path();
        let Ok(text) = std::fs::read_to_string(path) else {
            continue;
        };
        let scene = path
            .strip_prefix(&scene_dir)
            .unwrap_or(path)
            .to_string_lossy()
            .replace('\\', "/");
        for line in scene::parse_say_lines(&text) {
            let Some(vocal) = line.vocal else {
                continue;
            };
            let file = library::resolve_audio_path(Path::new(&project), &vocal);
            references.push(VocalReference {
                path: file.display().to_string(),
                exists: file.is_file(),
                vocal,
                scene: scene.clone(),
                line: line.line,
            });
        }
    }
    Ok(references)
}

/// 历史对齐请求
#[tauri::command]
pub async fn voice_realign(
    history: Vec<realign::HistoryKey>,
    dialogues: Vec<realign::DialogueKey>,
) -> Result<realign::AlignmentReport, String> {
    Ok(realign::align(&history, &dialogues))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn base64_matches_known_vectors() {
        assert_eq!(base64_encode(b""), "");
        assert_eq!(base64_encode(b"f"), "Zg==");
        assert_eq!(base64_encode(b"fo"), "Zm8=");
        assert_eq!(base64_encode(b"foo"), "Zm9v");
        assert_eq!(base64_encode(b"foob"), "Zm9vYg==");
        assert_eq!(base64_encode(b"fooba"), "Zm9vYmE=");
        assert_eq!(base64_encode(b"foobar"), "Zm9vYmFy");
    }

    #[test]
    fn base64_handles_binary() {
        let bytes: Vec<u8> = (0..=255u8).collect();
        let encoded = base64_encode(&bytes);
        // 256 字节 -> 344 个字符 (含 1 个 '=')
        assert_eq!(encoded.len(), 344);
        assert!(encoded.ends_with('='));
        assert!(encoded
            .chars()
            .all(|ch| ch.is_ascii_alphanumeric() || ch == '+' || ch == '/' || ch == '='));
    }

    #[tokio::test]
    async fn shutdown_without_process_is_noop() {
        let state = VoiceState::default();
        state.shutdown().await;
        assert_eq!(*state.status.lock().await, GsvStatus::Stopped);
    }

    #[tokio::test]
    async fn log_buffer_is_bounded() {
        let state = VoiceState::default();
        for index in 0..(LOG_LIMIT + 50) {
            state.push_log(format!("line {index}"), None).await;
        }
        let logs = state.logs.lock().await;
        assert_eq!(logs.len(), LOG_LIMIT);
        assert!(logs
            .last()
            .unwrap()
            .ends_with(&format!("{}", LOG_LIMIT + 49)));
    }
}
