// This file is generated by AI.

// 行级差异 (纯函数): 用来算"本步相对开始时改了什么"。
//
// 做法是标准的 LCS 对齐 + 间隙按位置配对: 两侧都有的行算「改写」(M), 只有右侧的算
// 「新增」(A), 只有左侧的算「删除」(D) —— 与 git 的"改动块"看法一致, 因此可以直接喂给
// `editor/diff-gutter` 画成色块。

/** 一条行改动 */
export interface LineChange {
  /** **改动后**文本里的 1 基行号 (删除没有对应的新行, 锚在它被删掉的位置) */
  line: number;
  kind: LineChangeKind;
}

export type LineChangeKind = 'A' | 'M' | 'D';

/**
 * LCS 动态规划的格子上限。
 *
 * 差异要随输入实时重算 (第 2 步边打字边更新色块), 所以必须有上限: 超过就放弃对齐, 退化成
 * 整段按位置配对 —— 结果仍是合理的近似, 而代价固定为 O(n + m), 不会在长文上卡住输入。
 */
const LCS_CELL_BUDGET = 250_000;

const LINE_BREAK = /\r?\n/;

/** 拆行: 空文本没有行, 结尾换行也不算多出一行 (免得它跟对面配成一次假改动)。 */
function splitLines(text: string): string[] {
  if (text === '') return [];
  const lines = text.split(LINE_BREAK);
  if (lines.length > 1 && lines[lines.length - 1] === '') lines.pop();
  return lines;
}

/** 两侧顺序一致的公共行 (锚点); 超出预算时返回 null 表示放弃对齐。 */
function lcsAnchors(before: string[], after: string[]): Array<[number, number]> | null {
  const n = before.length;
  const m = after.length;
  if (n * m > LCS_CELL_BUDGET) return null;

  // dp[i][j] = before[i..] 与 after[j..] 的最长公共子序列长度, 从右下往左上推。
  const width = m + 1;
  const dp = new Uint32Array((n + 1) * width);
  for (let i = n - 1; i >= 0; i--) {
    const row = i * width;
    const next = row + width;
    for (let j = m - 1; j >= 0; j--) {
      dp[row + j] = before[i] === after[j] ? dp[next + j + 1] + 1 : Math.max(dp[next + j], dp[row + j + 1]);
    }
  }

  const anchors: Array<[number, number]> = [];
  let i = 0;
  let j = 0;
  while (i < n && j < m) {
    if (before[i] === after[j]) {
      anchors.push([i, j]);
      i++;
      j++;
    } else if (dp[(i + 1) * width + j] >= dp[i * width + j + 1]) {
      i++;
    } else {
      j++;
    }
  }
  return anchors;
}

/**
 * 计算 `beforeText` → `afterText` 的行改动。
 *
 * `line` 一律取**改动后**文本的行号, 这样可以直接当成 Monaco 装饰的行号使用;
 * 删除锚在它被删掉的位置 (那一段新文本之后的行)。
 */
export function diffLines(beforeText: string, afterText: string): LineChange[] {
  const before = splitLines(beforeText);
  const after = splitLines(afterText);

  // 先掐掉公共前后缀: 长文里通常一刀就砍掉大半, 也免得它们白占 LCS 的格子。
  let head = 0;
  while (head < before.length && head < after.length && before[head] === after[head]) head++;
  let tail = 0;
  while (
    tail < before.length - head &&
    tail < after.length - head &&
    before[before.length - 1 - tail] === after[after.length - 1 - tail]
  ) {
    tail++;
  }

  const a = before.slice(head, before.length - tail);
  const b = after.slice(head, after.length - tail);
  const anchors = lcsAnchors(a, b) ?? [];

  const changes: LineChange[] = [];
  let i = 0;
  let j = 0;

  /** 同一行上重复的同类改动只留一条 (多个删除会锚在同一行上) */
  const push = (line: number, kind: LineChangeKind) => {
    const last = changes[changes.length - 1];
    if (last && last.line === line && last.kind === kind) return;
    changes.push({ line, kind });
  };

  /** 处理两个锚点之间没对齐上的区间 [i, iEnd) × [j, jEnd) */
  const flushGap = (iEnd: number, jEnd: number) => {
    const removed = iEnd - i;
    const added = jEnd - j;
    const paired = Math.min(removed, added);
    for (let k = 0; k < paired; k++) push(head + j + k + 1, 'M');
    for (let k = paired; k < added; k++) push(head + j + k + 1, 'A');
    // 删除没有对应的新行: 锚在这一段新文本之后, 也就是它被删掉的位置
    for (let k = paired; k < removed; k++) push(head + jEnd + 1, 'D');
    i = iEnd;
    j = jEnd;
  };

  for (const [anchorBefore, anchorAfter] of anchors) {
    flushGap(anchorBefore, anchorAfter);
    i = anchorBefore + 1;
    j = anchorAfter + 1;
  }
  flushGap(a.length, b.length);

  return changes;
}
