// This file is generated by AI.

use std::ops::Range;

use json_language_service::{TokenType, highlight};

fn collect_highlights(s: &str) -> Vec<(Range<usize>, TokenType)> {
    let mut result = Vec::new();
    highlight(s, |range, ty| result.push((range, ty)));
    result
}

#[test]
fn highlight_empty() {
    let highlights = collect_highlights("");
    assert!(highlights.is_empty());
}

#[test]
fn highlight_number() {
    let highlights = collect_highlights("123");
    assert_eq!(highlights, vec![(0..3, TokenType::Number)]);
}

#[test]
fn highlight_string() {
    let highlights = collect_highlights("\"hello\"");
    assert_eq!(highlights, vec![(0..7, TokenType::String)]);
}

#[test]
fn highlight_keyword() {
    let highlights = collect_highlights("true");
    assert_eq!(highlights, vec![(0..4, TokenType::Keyword)]);

    let highlights = collect_highlights("false");
    assert_eq!(highlights, vec![(0..5, TokenType::Keyword)]);

    let highlights = collect_highlights("null");
    assert_eq!(highlights, vec![(0..4, TokenType::Keyword)]);
}

#[test]
fn highlight_object() {
    let s = r#"{"key": 123}"#;
    let highlights = collect_highlights(s);
    let expected = vec![
        (0..1, TokenType::Operator),   // {
        (1..6, TokenType::String),     // "key"
        (6..8, TokenType::Operator),   // ": "
        (8..11, TokenType::Number),    // 123
        (11..12, TokenType::Operator), // }
    ];
    assert_eq!(highlights, expected);
}

#[test]
fn highlight_nested_object() {
    let s = r#"{"a": {"b": true}}"#;
    let highlights = collect_highlights(s);
    let expected = vec![
        (0..1, TokenType::Operator),   // {
        (1..4, TokenType::String),     // "a"
        (4..7, TokenType::Operator),   // ": {"
        (7..10, TokenType::String),    // "b"
        (10..12, TokenType::Operator), // ": "
        (12..16, TokenType::Keyword),  // true
        (16..18, TokenType::Operator), // 合并连续的 "}}"
    ];
    assert_eq!(highlights, expected);
}

#[test]
fn highlight_array() {
    let s = r#"[1, "two", 3]"#;
    let highlights = collect_highlights(s);
    let expected = vec![
        (0..1, TokenType::Operator),   // [
        (1..2, TokenType::Number),     // 1
        (2..4, TokenType::Operator),   // ", "
        (4..9, TokenType::String),     // "two"
        (9..11, TokenType::Operator),  // ", "
        (11..12, TokenType::Number),   // 3
        (12..13, TokenType::Operator), // ]
    ];
    assert_eq!(highlights, expected);
}

#[test]
fn highlight_mixed() {
    let s = r#"{"name": "John", "age": 30, "active": true}"#;
    let highlights = collect_highlights(s);
    let types: Vec<TokenType> = highlights.iter().map(|(_, ty)| *ty).collect();
    let expected_types = vec![
        TokenType::Operator, // {
        TokenType::String,   // "name"
        TokenType::Operator, // ": "
        TokenType::String,   // "John"
        TokenType::Operator, // ", "
        TokenType::String,   // "age"
        TokenType::Operator, // ": "
        TokenType::Number,   // 30
        TokenType::Operator, // ", "
        TokenType::String,   // "active"
        TokenType::Operator, // ": "
        TokenType::Keyword,  // true
        TokenType::Operator, // }
    ];
    assert_eq!(types, expected_types);
}

#[test]
fn highlight_partial_object() {
    let s = r#"{"key": "#;
    let highlights = collect_highlights(s);
    let expected = vec![
        (0..1, TokenType::Operator), // {
        (1..6, TokenType::String),   // "key"
        (6..8, TokenType::Operator), // ": "
    ];
    assert_eq!(highlights, expected);
}
