// This file is generated by AI.

//! 配音历史的持久化。
//!
//! 历史项的结构属于界面 (`HistoryEntry`: 参数快照、状态、音频哈希……), 后端**不解释**
//! 它: 前端把整份历史序列化成 JSON 交给这里落盘, 读回时原样返回。这样界面调整历史项
//! 字段时不需要同步改 Rust 结构 (改一处漏一处才是真正的坏味道)。
//!
//! 目录布局 (位于应用用户数据目录):
//! ```text
//! <appdata>/voice-history/<场景路径哈希>.json
//! ```
//!
//! 用**场景路径的哈希**作文件名而不是路径本身: 场景路径里有中文、空格与分隔符, 直接
//! 拿来当文件名在跨平台上很容易出问题 (Windows 保留字符、路径长度上限)。
//! 内容里另外记了一份原始 `scenePath`, 便于人工排查。

use std::path::PathBuf;

use serde::{Deserialize, Serialize};

/// 落盘的历史文件
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct HistoryFile {
    /// 场景文件的绝对路径 (仅用于人工排查)
    pub scene_path: String,
    /// 写入时刻 (Unix 毫秒)
    pub saved_at: i64,
    /// 历史条目 (界面结构, 原样存取)
    pub entries: serde_json::Value,
}

/// 场景路径的稳定哈希 (FNV-1a 64, 十六进制)
///
/// 归一化 (统一分隔符 + 小写) 后再算: 同一个文件因为分隔符或大小写写法不同而算出两个
/// 哈希, 会让历史莫名其妙地"丢了"。
pub fn hash_scene_path(scene_path: &str) -> String {
    let normalized = scene_path.trim().replace('\\', "/").to_lowercase();
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for byte in normalized.as_bytes() {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
    }
    format!("{hash:016x}")
}

/// 配音历史仓库
#[derive(Debug, Clone)]
pub struct HistoryStore {
    root: PathBuf,
}

impl HistoryStore {
    pub fn new(root: impl Into<PathBuf>) -> Self {
        Self { root: root.into() }
    }

    pub fn file_for(&self, scene_path: &str) -> PathBuf {
        self.root
            .join(format!("{}.json", hash_scene_path(scene_path)))
    }

    /// 读取某场景的历史 (不存在时返回 `None`)
    pub fn read(&self, scene_path: &str) -> Result<Option<HistoryFile>, String> {
        let path = self.file_for(scene_path);
        if !path.is_file() {
            return Ok(None);
        }
        let text = std::fs::read_to_string(&path).map_err(|error| error.to_string())?;
        // 解析失败不该让配音卡打不开: 当成"没有历史", 并把坏文件留在原处
        Ok(serde_json::from_str(&text).ok())
    }

    /// 写入某场景的历史
    pub fn write(&self, scene_path: &str, entries: serde_json::Value) -> Result<(), String> {
        std::fs::create_dir_all(&self.root).map_err(|error| error.to_string())?;
        let file = HistoryFile {
            scene_path: scene_path.to_string(),
            saved_at: crate::service::voice::library::now_millis(),
            entries,
        };
        let text = serde_json::to_string_pretty(&file).map_err(|error| error.to_string())?;
        // 先写临时文件再改名: 中途崩溃/断电不会留下半截 JSON, 把历史读坏
        let target = self.file_for(scene_path);
        let temp = self
            .root
            .join(format!(".{}.tmp", hash_scene_path(scene_path)));
        std::fs::write(&temp, text).map_err(|error| error.to_string())?;
        std::fs::rename(&temp, &target).map_err(|error| error.to_string())
    }

    /// 删除某场景的历史文件
    pub fn remove(&self, scene_path: &str) -> Result<(), String> {
        let path = self.file_for(scene_path);
        if path.is_file() {
            std::fs::remove_file(&path).map_err(|error| error.to_string())?;
        }
        Ok(())
    }

    #[cfg(test)]
    pub fn root(&self) -> &std::path::Path {
        &self.root
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temp_store(name: &str) -> HistoryStore {
        let root = std::env::temp_dir()
            .join("webgal-ink-history-test")
            .join(name);
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(&root).unwrap();
        HistoryStore::new(root)
    }

    #[test]
    fn hash_is_stable_across_separators_and_case() {
        let a = hash_scene_path(r"C:\Games\Demo\game\scene\1.txt");
        let b = hash_scene_path("C:/Games/Demo/game/scene/1.txt");
        let c = hash_scene_path("c:/games/DEMO/game/scene/1.txt");
        assert_eq!(a, b);
        assert_eq!(a, c);
        // 不同文件不能撞在一起
        assert_ne!(a, hash_scene_path("C:/Games/Demo/game/scene/2.txt"));
        // 文件名安全 (纯十六进制)
        assert!(a.chars().all(|ch| ch.is_ascii_hexdigit()));
    }

    #[test]
    fn write_then_read_roundtrip() {
        let store = temp_store("roundtrip");
        let scene = r"C:\project\game\scene\1.txt";
        assert!(store.read(scene).unwrap().is_none());

        store
            .write(scene, serde_json::json!([{ "id": "a", "text": "你好" }]))
            .unwrap();
        let loaded = store.read(scene).unwrap().expect("应当读到");
        assert_eq!(loaded.scene_path, scene);
        assert_eq!(loaded.entries[0]["text"], "你好");

        // 再写一次覆盖旧内容, 且不留下临时文件
        store.write(scene, serde_json::json!([])).unwrap();
        assert!(store
            .read(scene)
            .unwrap()
            .unwrap()
            .entries
            .as_array()
            .unwrap()
            .is_empty());
        let leftovers: Vec<_> = std::fs::read_dir(store.root())
            .unwrap()
            .filter_map(std::result::Result::ok)
            .filter(|entry| entry.file_name().to_string_lossy().ends_with(".tmp"))
            .collect();
        assert!(leftovers.is_empty());
    }

    #[test]
    fn broken_file_reads_as_missing() {
        let store = temp_store("broken");
        let scene = "C:/project/game/scene/1.txt";
        store.write(scene, serde_json::json!([])).unwrap();
        std::fs::write(store.file_for(scene), "{ 半截").unwrap();
        assert!(store.read(scene).unwrap().is_none());
    }

    #[test]
    fn remove_deletes_only_that_scene() {
        let store = temp_store("remove");
        let a = "C:/project/game/scene/1.txt";
        let b = "C:/project/game/scene/2.txt";
        store.write(a, serde_json::json!([])).unwrap();
        store.write(b, serde_json::json!([])).unwrap();
        store.remove(a).unwrap();
        assert!(store.read(a).unwrap().is_none());
        assert!(store.read(b).unwrap().is_some());
        // 重复删除不报错
        store.remove(a).unwrap();
    }
}
