// This file is generated by AI.

//! 角色库: GSOV 模型 + 参考音频组合的本地持久化。
//!
//! 目录布局 (位于应用用户数据目录):
//! ```text
//! <appdata>/characters/index.json          角色索引 (轻量列表, 避免逐个读取)
//! <appdata>/characters/<id>.json           单个角色完整配置
//! <appdata>/characters/<id>/ref_<hash>.wav 参考音频工作副本 (内容寻址)
//! ```
//!
//! 参考音频一律**拷贝**进库内, 不引用用户原位置: 用户移动或删除原文件不影响配音,
//! 且同内容音频天然去重 (文件名即内容哈希)。

use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

/// 母语/语言码 (与 GSOV `text_lang` 一致)
pub type LanguageCode = String;

/// 风格标签 (v0.5 仅 Ink 内部使用, v0.6 将承载更多语义)
pub type StyleTag = String;

/// 参考音频条目
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ReferenceAudio {
    /// 库内文件名 (`ref_<hash>.wav`)
    pub file: String,
    /// 内容哈希 (前 16 位)
    pub hash: String,
    /// 时长 (秒)
    pub duration: f64,
    /// 采样率
    pub sample_rate: u32,
    /// 参考文本 (GSOV 在使用 vocoder 的 v3/v4 上要求非空, 且须与音频逐字一致)
    pub text: String,
    /// 语言码
    pub language: LanguageCode,
    /// 风格标签
    pub tags: Vec<StyleTag>,
    /// 添加时间 (Unix 毫秒)
    pub created_at: i64,
}

/// 角色
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Character {
    pub id: String,
    pub name: String,
    /// 别名 (参与场景对话者自动匹配)
    pub aliases: Vec<String>,
    #[serde(default)]
    pub description: String,
    /// 默认语言 (配音文本语言)
    pub language: LanguageCode,
    /// 参考音频列表
    #[serde(default)]
    pub references: Vec<ReferenceAudio>,
    /// 本地记录的 GSOV 模型路径 (不参与导出: 跨机器/容器无意义)
    #[serde(default)]
    pub model: Option<ModelChoice>,
    /// 是否星标 (在选择列表靠前展示)
    #[serde(default)]
    pub starred: bool,
    /// 是否启用 (参与自动匹配)
    #[serde(default = "default_enabled")]
    pub enabled: bool,
    pub created_at: i64,
    pub updated_at: i64,
}

fn default_enabled() -> bool {
    true
}

/// 本地模型选择
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ModelChoice {
    /// GPT (T2S) 权重路径 (服务端本地路径)
    #[serde(default)]
    pub gpt_weights: Option<String>,
    /// SoVITS 权重路径 (服务端本地路径)
    #[serde(default)]
    pub sovits_weights: Option<String>,
}

/// 导出用清单 (不含模型选择)
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CharacterManifest {
    /// 固定为 1, 便于后续演进
    pub version: u32,
    pub name: String,
    pub aliases: Vec<String>,
    #[serde(default)]
    pub description: String,
    pub language: LanguageCode,
    pub references: Vec<ReferenceAudio>,
}

#[derive(Debug, thiserror::Error)]
pub enum LibraryError {
    #[error("读写角色库失败: {0}")]
    Io(#[from] std::io::Error),
    #[error("解析角色配置失败: {0}")]
    Json(#[from] serde_json::Error),
    #[error("打包/解包失败: {0}")]
    Zip(#[from] zip::result::ZipError),
    #[error("音频处理失败: {0}")]
    Audio(String),
    #[error("{0}")]
    Invalid(String),
}

type Result<T> = std::result::Result<T, LibraryError>;

/// 当前 Unix 毫秒时间戳
pub fn now_millis() -> i64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|duration| duration.as_millis() as i64)
        .unwrap_or_default()
}

/// 角色库
#[derive(Debug, Clone)]
pub struct Library {
    root: PathBuf,
}

impl Library {
    pub fn new(root: impl Into<PathBuf>) -> Self {
        Self { root: root.into() }
    }

    fn character_dir(&self, id: &str) -> PathBuf {
        self.root.join(id)
    }

    /// 角色库根目录 (仅测试使用)
    #[cfg(test)]
    pub fn root(&self) -> &Path {
        &self.root
    }

    fn character_file(&self, id: &str) -> PathBuf {
        self.root.join(format!("{id}.json"))
    }

    /// 列出全部角色 (完整配置, 按星标/更新时间排序)
    pub fn list(&self) -> Result<Vec<Character>> {
        let mut characters = Vec::new();
        if !self.root.is_dir() {
            return Ok(characters);
        }
        for entry in std::fs::read_dir(&self.root)? {
            let entry = entry?;
            let path = entry.path();
            if path.extension().and_then(|ext| ext.to_str()) != Some("json") || path.ends_with("index.json") {
                continue;
            }
            match std::fs::read_to_string(&path).map_err(LibraryError::from).and_then(|text| {
                serde_json::from_str::<Character>(&text).map_err(LibraryError::from)
            }) {
                Ok(character) => characters.push(character),
                Err(error) => eprintln!("跳过无法解析的角色配置 {}: {error}", path.display()),
            }
        }
        characters.sort_by(|a, b| {
            b.starred
                .cmp(&a.starred)
                .then(b.updated_at.cmp(&a.updated_at))
                .then(a.name.cmp(&b.name))
        });
        Ok(characters)
    }

    /// 读取单个角色
    pub fn load(&self, id: &str) -> Result<Character> {
        let path = self.character_file(id);
        if !path.is_file() {
            return Err(LibraryError::Invalid(format!("角色 {id} 不存在")));
        }
        let text = std::fs::read_to_string(path)?;
        Ok(serde_json::from_str(&text)?)
    }

    /// 写入单个角色 (保持 id 不变, 更新时间戳)
    pub fn save(&self, mut character: Character) -> Result<Character> {
        if character.id.trim().is_empty() {
            return Err(LibraryError::Invalid("角色 id 不可为空".into()));
        }
        std::fs::create_dir_all(&self.root)?;
        character.updated_at = now_millis();
        let text = serde_json::to_string_pretty(&character)?;
        std::fs::write(self.character_file(&character.id), text)?;
        Ok(character)
    }

    /// 删除角色及其参考音频目录
    pub fn remove(&self, id: &str) -> Result<()> {
        let file = self.character_file(id);
        if file.is_file() {
            std::fs::remove_file(file)?;
        }
        let dir = self.character_dir(id);
        if dir.is_dir() {
            std::fs::remove_dir_all(dir)?;
        }
        Ok(())
    }

    /// 参考音频的绝对路径
    pub fn reference_path(&self, id: &str, file: &str) -> PathBuf {
        self.character_dir(id).join(file)
    }

    /// 把一份已经规范化好的参考音频纳入角色库 (内容寻址, 同内容自动复用)
    pub fn adopt_reference(
        &self,
        id: &str,
        source: &Path,
        text: String,
        language: LanguageCode,
        tags: Vec<StyleTag>,
    ) -> Result<ReferenceAudio> {
        let dir = self.character_dir(id);
        std::fs::create_dir_all(&dir)?;

        let hash = super::audio::hash_file(source).map_err(LibraryError::Audio)?;
        let file_name = format!("ref_{hash}.wav");
        let target = dir.join(&file_name);
        if !target.is_file() {
            std::fs::copy(source, &target)?;
        }

        let probe = super::audio::probe(&target).map_err(LibraryError::Audio)?;
        Ok(ReferenceAudio {
            file: file_name,
            hash,
            duration: probe.duration,
            sample_rate: probe.sample_rate,
            text,
            language,
            tags,
            created_at: now_millis(),
        })
    }

    /// 删除参考音频文件 (若库内已无其他条目引用同一文件)
    pub fn drop_reference_file(&self, id: &str, file: &str, still_used: bool) -> Result<()> {
        if still_used {
            return Ok(());
        }
        let path = self.reference_path(id, file);
        if path.is_file() {
            std::fs::remove_file(path)?;
        }
        Ok(())
    }

    /// 导出角色为 zip 压缩包 (清单 + 参考音频, 不含模型选择)
    pub fn export_zip(&self, id: &str, destination: &Path) -> Result<()> {
        use std::io::Write;
        use zip::write::SimpleFileOptions;

        let character = self.load(id)?;
        let manifest = CharacterManifest {
            version: 1,
            name: character.name.clone(),
            aliases: character.aliases.clone(),
            description: character.description.clone(),
            language: character.language.clone(),
            references: character.references.clone(),
        };

        if let Some(parent) = destination.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let file = std::fs::File::create(destination)?;
        let mut writer = zip::ZipWriter::new(file);
        let options = SimpleFileOptions::default().compression_method(zip::CompressionMethod::Deflated);

        writer.start_file("character.json", options)?;
        writer.write_all(serde_json::to_string_pretty(&manifest)?.as_bytes())?;

        for reference in &character.references {
            let path = self.reference_path(id, &reference.file);
            if !path.is_file() {
                continue;
            }
            let bytes = std::fs::read(&path)?;
            writer.start_file(format!("audio/{}", reference.file), options)?;
            writer.write_all(&bytes)?;
        }
        writer.finish()?;
        Ok(())
    }

    /// 从 zip 压缩包导入角色, 返回导入后的角色
    pub fn import_zip(&self, source: &Path) -> Result<Character> {
        use std::io::Read;

        let file = std::fs::File::open(source)?;
        let mut archive = zip::ZipArchive::new(file)?;

        let manifest: CharacterManifest = {
            let mut entry = archive
                .by_name("character.json")
                .map_err(|_| LibraryError::Invalid("压缩包内缺少 character.json".into()))?;
            let mut text = String::new();
            entry.read_to_string(&mut text)?;
            serde_json::from_str(&text)?
        };

        let id = unique_id(&self.root, &manifest.name);
        let dir = self.character_dir(&id);
        std::fs::create_dir_all(&dir)?;

        let mut references = Vec::new();
        for reference in manifest.references {
            let zip_name = format!("audio/{}", reference.file);
            let mut entry = match archive.by_name(&zip_name) {
                Ok(entry) => entry,
                Err(_) => continue,
            };
            let mut bytes = Vec::new();
            entry.read_to_end(&mut bytes)?;

            // 以实际内容重新计算哈希, 防止清单被篡改或文件名与内容不符
            let target = dir.join(&reference.file);
            std::fs::write(&target, &bytes)?;
            let hash = super::audio::hash_file(&target).map_err(LibraryError::Audio)?;
            let probe = super::audio::probe(&target).map_err(LibraryError::Audio)?;
            if probe.too_short || probe.too_long {
                // 导入的参考音频不满足 GSOV 时长约束时直接拒绝, 避免生成阶段才报错
                let _ = std::fs::remove_file(&target);
                return Err(LibraryError::Invalid(format!(
                    "参考音频 {} 时长为 {:.2}s, 不在 3~10s 范围内",
                    reference.file, probe.duration
                )));
            }
            references.push(ReferenceAudio {
                file: format!("ref_{hash}.wav"),
                hash,
                duration: probe.duration,
                sample_rate: probe.sample_rate,
                ..reference
            });
        }

        let now = now_millis();
        let character = Character {
            id,
            name: manifest.name,
            aliases: manifest.aliases,
            description: manifest.description,
            language: manifest.language,
            references,
            model: None,
            starred: false,
            enabled: true,
            created_at: now,
            updated_at: now,
        };
        self.save(character)
    }
}

/// 依据角色名生成库内唯一 id
pub fn unique_id(root: &Path, name: &str) -> String {
    let base = slugify(name);
    let base = if base.is_empty() { "character".to_string() } else { base };
    if !root.join(format!("{base}.json")).exists() {
        return base;
    }
    for suffix in 2..1000 {
        let candidate = format!("{base}-{suffix}");
        if !root.join(format!("{candidate}.json")).exists() {
            return candidate;
        }
    }
    format!("{base}-{}", now_millis())
}

/// 生成可用作文件名/id 的 slug (保留中日韩字符, 其余折叠为 `-`)
pub fn slugify(name: &str) -> String {
    let mut out = String::new();
    let mut last_dash = false;
    for ch in name.trim().chars() {
        if ch.is_alphanumeric() {
            out.push(ch);
            last_dash = false;
        } else if !last_dash && !out.is_empty() {
            out.push('-');
            last_dash = true;
        }
    }
    out.trim_matches('-').to_string()
}

#[cfg(test)]
mod tests {
    // This module is generated by AI.

    use super::*;
    use crate::service::voice::wav;

    fn temp_library(name: &str) -> Library {
        let root = std::env::temp_dir().join("webgal-ink-library-test").join(name);
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(&root).unwrap();
        Library::new(root)
    }

    fn write_reference(dir: &Path, file: &str, seconds: f64) -> PathBuf {
        let sample_rate = 16000u32;
        let frames = (seconds * sample_rate as f64) as usize;
        let samples: Vec<f32> = (0..frames)
            .map(|i| (i as f32 / sample_rate as f32 * 440.0 * std::f32::consts::TAU).sin() * 0.5)
            .collect();
        let path = dir.join(file);
        wav::write_mono_16(&path, sample_rate, &samples).unwrap();
        path
    }

    fn character(id: &str, name: &str) -> Character {
        let now = now_millis();
        Character {
            id: id.into(),
            name: name.into(),
            aliases: vec!["anon".into()],
            description: String::new(),
            language: "auto".into(),
            references: Vec::new(),
            model: None,
            starred: false,
            enabled: true,
            created_at: now,
            updated_at: now,
        }
    }

    #[test]
    fn save_then_load_roundtrip() {
        let library = temp_library("roundtrip");
        let saved = library.save(character("anon", "千早爱音")).unwrap();
        assert!(saved.updated_at >= saved.created_at);
        let loaded = library.load("anon").unwrap();
        assert_eq!(loaded.name, "千早爱音");
        assert_eq!(loaded.aliases, vec!["anon".to_string()]);
        assert!(loaded.enabled);
    }

    #[test]
    fn list_sorts_starred_first() {
        let library = temp_library("sort");
        library.save(character("a", "甲")).unwrap();
        let mut starred = character("b", "乙");
        starred.starred = true;
        library.save(starred).unwrap();
        let list = library.list().unwrap();
        assert_eq!(list[0].id, "b");
        assert_eq!(list[1].id, "a");
    }

    #[test]
    fn adopt_reference_is_content_addressed_and_deduped() {
        let library = temp_library("adopt");
        library.save(character("anon", "千早爱音")).unwrap();
        let source_dir = library.root().join("incoming");
        std::fs::create_dir_all(&source_dir).unwrap();
        let first = write_reference(&source_dir, "a.wav", 4.0);

        let adopted = library
            .adopt_reference("anon", &first, "参考文本".into(), "zh".into(), vec!["平静".into()])
            .unwrap();
        assert!(adopted.file.starts_with("ref_"));
        assert_eq!(adopted.text, "参考文本");
        assert!((adopted.duration - 4.0).abs() < 0.05);

        // 同内容再次加入 -> 复用同一个文件, 不产生新副本
        let adopted_again = library
            .adopt_reference("anon", &first, "另一段文本".into(), "zh".into(), vec![])
            .unwrap();
        assert_eq!(adopted.file, adopted_again.file);
        let files: Vec<_> = std::fs::read_dir(library.reference_path("anon", ""))
            .unwrap()
            .filter_map(|entry| entry.ok())
            .filter(|entry| entry.file_name().to_string_lossy().starts_with("ref_"))
            .collect();
        assert_eq!(files.len(), 1);
    }

    #[test]
    fn remove_deletes_character_and_audio() {
        let library = temp_library("remove");
        library.save(character("anon", "千早爱音")).unwrap();
        let source_dir = library.root().join("incoming-remove");
        std::fs::create_dir_all(&source_dir).unwrap();
        let source = write_reference(&source_dir, "a.wav", 4.0);
        let adopted = library
            .adopt_reference("anon", &source, "文本".into(), "zh".into(), vec![])
            .unwrap();
        let audio = library.reference_path("anon", &adopted.file);
        assert!(audio.is_file());

        library.remove("anon").unwrap();
        assert!(!library.character_file("anon").exists());
        assert!(!audio.exists());
        assert!(library.list().unwrap().is_empty());
    }

    #[test]
    fn export_then_import_roundtrip() {
        let library = temp_library("zip");
        library.save(character("anon", "千早爱音")).unwrap();
        let source_dir = library.root().join("incoming-zip");
        std::fs::create_dir_all(&source_dir).unwrap();
        let source = write_reference(&source_dir, "a.wav", 4.0);
        let adopted = library
            .adopt_reference("anon", &source, "参考文本".into(), "zh".into(), vec!["活泼".into()])
            .unwrap();

        let mut with_ref = library.load("anon").unwrap();
        with_ref.references.push(adopted);
        with_ref.model = Some(ModelChoice {
            gpt_weights: Some("GPT_weights_v4/anon-e15.ckpt".into()),
            sovits_weights: Some("SoVITS_weights_v4/anon.pth".into()),
        });
        library.save(with_ref).unwrap();

        let zip_path = library.root().join("export.zip");
        library.export_zip("anon", &zip_path).unwrap();
        assert!(zip_path.is_file());

        // 导入到另一个库
        let other = temp_library("zip-target");
        let imported = other.import_zip(&zip_path).unwrap();
        assert_eq!(imported.name, "千早爱音");
        assert_eq!(imported.aliases, vec!["anon".to_string()]);
        assert_eq!(imported.references.len(), 1);
        assert_eq!(imported.references[0].text, "参考文本");
        assert_eq!(imported.references[0].tags, vec!["活泼".to_string()]);
        // 模型选择不参与导入
        assert!(imported.model.is_none());
        assert!(other.reference_path(&imported.id, &imported.references[0].file).is_file());
    }

    #[test]
    fn import_rejects_reference_out_of_duration_range() {
        let library = temp_library("zip-bad-duration");
        library.save(character("anon", "千早爱音")).unwrap();
        let source_dir = library.root().join("incoming-bad");
        std::fs::create_dir_all(&source_dir).unwrap();
        let short = write_reference(&source_dir, "short.wav", 1.0);
        let adopted = library
            .adopt_reference("anon", &short, "文本".into(), "zh".into(), vec![])
            .unwrap();
        let mut with_ref = library.load("anon").unwrap();
        with_ref.references.push(adopted);
        library.save(with_ref).unwrap();

        let zip_path = library.root().join("export-bad.zip");
        library.export_zip("anon", &zip_path).unwrap();

        let other = temp_library("zip-bad-target");
        let error = other.import_zip(&zip_path).unwrap_err();
        assert!(error.to_string().contains("不在 3~10s 范围内"), "{error}");
    }

    #[test]
    fn import_without_manifest_fails() {
        use std::io::Write;
        let library = temp_library("zip-no-manifest");
        let zip_path = library.root().join("empty.zip");
        let file = std::fs::File::create(&zip_path).unwrap();
        let mut writer = zip::ZipWriter::new(file);
        writer
            .start_file("readme.txt", zip::write::SimpleFileOptions::default())
            .unwrap();
        writer.write_all(b"nothing here").unwrap();
        writer.finish().unwrap();

        let error = library.import_zip(&zip_path).unwrap_err();
        assert!(error.to_string().contains("character.json"), "{error}");
    }

    #[test]
    fn slugify_keeps_cjk_and_folds_symbols() {
        assert_eq!(slugify("千早爱音"), "千早爱音");
        assert_eq!(slugify("素世（不夹）"), "素世-不夹");
        assert_eq!(slugify("  A B / C  "), "A-B-C");
        assert_eq!(slugify("《》"), "");
    }

    #[test]
    fn unique_id_avoids_collision() {
        let library = temp_library("unique");
        library.save(character("anon", "anon")).unwrap();
        let id = unique_id(library.root(), "anon");
        assert_eq!(id, "anon-2");
    }

    #[test]
    fn list_reports_adopted_references() {
        let library = temp_library("list-references");
        library.save(character("anon", "千早爱音")).unwrap();
        let source_dir = library.root().join("incoming-sum");
        std::fs::create_dir_all(&source_dir).unwrap();
        let source = write_reference(&source_dir, "a.wav", 4.0);
        let adopted = library
            .adopt_reference("anon", &source, "文本".into(), "zh".into(), vec![])
            .unwrap();
        let mut with_ref = library.load("anon").unwrap();
        with_ref.references.push(adopted);
        library.save(with_ref).unwrap();

        let list = library.list().unwrap();
        assert_eq!(list.len(), 1);
        assert_eq!(list[0].references.len(), 1);
        assert_eq!(list[0].aliases, vec!["anon".to_string()]);
    }
}
