// This file is generated by AI.

//! 场景对话抽取。
//!
//! GPT-SoVITS 配音只关心对话语句, 且必须拿到**行号**以便回写。因此这里不走
//! [`webgal_language_core::sentence::Scene`] 的整体解析 (不提供行号), 而是逐行
//! [`Sentence::from_str`], 跳过非对话语句。
//!
//! WebGAL 允许省略对话者: 形如 `还没回答。;` 的一行继承其上一条显式说话者语句。
//! 该语法糖在 `Sentence` 层表现为 `speaker = None`, 归属者需由本模块回溯补齐。
//! 补齐后的归属者参与内容哈希, 因此上游说话者行被删除时, 受影响对话的哈希会变化,
//! 前端以此识别 "身份不稳定" 的历史项。

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use webgal_language_core::element::{FigureId, FontSize};
use webgal_language_core::sentence::{SaySentence, Sentence, SentenceInfo};

/// 语句身份哈希长度
const HASH_LEN: usize = 12;

/// 一条对话语句
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SayLine {
    /// 行号 (0 起)
    pub line: usize,
    /// 对话者 (已回溯补齐省略语法; 旁白为 `None`)
    pub speaker: Option<String>,
    /// 对话者是否由上游语句继承而来
    pub speaker_inherited: bool,
    /// 对话内容 (`|` 拼接的多段)
    pub text: String,
    /// 现有配音引用 (`-vocal=` 的值, 相对 `game/vocal/`)
    pub vocal: Option<String>,
    /// 立绘 id (`-figureId=` 的值)
    pub figure_id: Option<String>,
    /// 立绘位置 (`left` / `center` / `right`, 由 `-left` 等参数糖给出)
    pub figure_side: Option<String>,
    /// 语句身份哈希 (对话者 + 内容 + 现有配音)
    pub hash: String,
}

/// 语句改动请求
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LineEdit {
    /// 目标行号 (0 起)
    pub line: usize,
    /// 期望的原始内容, 用于写回前的一致性校验; 为 `None` 时跳过校验
    pub expect: Option<String>,
    /// 新的配音引用; `None` 表示移除
    pub vocal: Option<String>,
}

/// 语句改动结果
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct LineEditResult {
    pub line: usize,
    /// 改写后的整行内容
    pub text: String,
}

/// 从场景内容抽取全部对话语句
pub fn parse_say_lines(scene: &str) -> Vec<SayLine> {
    let mut lines = Vec::new();
    let mut current_speaker: Option<String> = None;

    for (index, raw) in scene.lines().enumerate() {
        let output = Sentence::from_str(raw);
        let Sentence::Say(say) = output.sentence else {
            continue;
        };

        let text = say.content.join("|");
        // 空内容占位语句 (`-sayPlaceHolder`, `:;`) 不参与配音
        if text.trim().is_empty() {
            continue;
        }

        // 说话者归属。
        //
        // * `Some(name)` - 显式说话者;
        // * `Some("")` - 显式空说话者 (`:内容;`), 表示旁白, **不继承**;
        // * `None` - 省略说话者的语法糖 (裸 `内容;`), 继承上一条显式说话者。
        let (speaker, speaker_inherited) = match say.speaker {
            Some(speaker) => {
                if !speaker.is_empty() {
                    current_speaker = Some(speaker.clone());
                }
                ((!speaker.is_empty()).then_some(speaker), false)
            }
            None => (current_speaker.clone(), current_speaker.is_some()),
        };

        let (figure_id, figure_side) = match say.figure {
            Some(FigureId::Id(id)) => (Some(id), None),
            Some(FigureId::Side(side)) => (None, Some(side.to_string())),
            None => (None, None),
        };

        let hash = say_hash(speaker.as_deref(), &text, say.vocal.as_deref());
        lines.push(SayLine {
            line: index,
            speaker,
            speaker_inherited,
            text,
            vocal: say.vocal,
            figure_id,
            figure_side,
            hash,
        });
    }

    lines
}

/// 改写一条语句的配音引用, 其余部分重建。
///
/// 说话者与内容原样保留 (与 [`Sentence`] 自身的序列化一致), 仅重建参数部分:
/// 这样才能保证 `-vocal=<值>` **始终显式带键**。
/// `SaySentence` 的 `Display` 会把非保留字的配音引用写成裸参数 (`-anon/a.wav`),
/// 而 `-vocal=` 是 WebGAL 引擎接受的标准写法, 显式写出可避免依赖引擎对裸参数的解释。
///
/// 注释与 `nolint` 标记原样保留, 行内空白风格会被规范化 (与格式化行为一致)。
pub fn rewrite_line(line: &str, vocal: Option<&str>) -> Result<String, String> {
    let info = webgal_language_core::sentence::SentenceInfo::from_str(line);
    let Sentence::Say(say) = &info.sentence else {
        return Err("该行不是对话语句".into());
    };
    Ok(render_say(say, vocal, &info))
}

/// 依据 `SaySentence` 重建整行
fn render_say(say: &SaySentence, vocal: Option<&str>, info: &SentenceInfo<'_>) -> String {
    use std::fmt::Write;

    let mut out = String::new();
    if let Some(speaker) = &say.speaker {
        out.push_str(speaker);
        out.push(':');
    }
    out.push_str(&say.content.join("|"));

    if let Some(vocal) = vocal {
        push_arg(&mut out, "vocal", Some(vocal));
    }
    if let Some(figure) = &say.figure {
        match figure {
            FigureId::Id(id) => push_arg(&mut out, "figureId", Some(id)),
            FigureId::Side(side) => push_arg(&mut out, &side.to_string(), None),
        }
    }
    if say.font_size != FontSize::default() {
        push_arg(&mut out, "fontSize", Some(&say.font_size.to_string()));
    }
    if say.concat {
        push_arg(&mut out, "concat", None);
    }
    if say.notend {
        push_arg(&mut out, "notend", None);
    }
    if let Some(when) = &say.when {
        push_arg(&mut out, "when", Some(when));
    }
    out.push(';');

    if !info.nolints.is_empty() {
        let _ = write!(out, "nolint:{};", info.nolints.join("|"));
    }
    if !info.comment.is_empty() {
        let _ = write!(out, " {}", info.comment);
    }
    out
}

/// 追加一个参数 (`Some` 为 `-name=value`, `None` 为 `-name`)
fn push_arg(out: &mut String, name: &str, value: Option<&str>) {
    use std::fmt::Write;
    match value {
        Some(value) => {
            let _ = write!(out, " -{name}={value}");
        }
        None => {
            let _ = write!(out, " -{name}");
        }
    }
}

/// 语句身份哈希: 对话者 + 内容 + 现有配音
pub fn say_hash(speaker: Option<&str>, text: &str, vocal: Option<&str>) -> String {
    let mut hasher = Sha256::new();
    hasher.update(speaker.unwrap_or("").as_bytes());
    hasher.update([0x1f]);
    hasher.update(text.trim().as_bytes());
    hasher.update([0x1f]);
    hasher.update(vocal.unwrap_or("").as_bytes());
    let digest = hasher.finalize();
    digest
        .iter()
        .take(HASH_LEN / 2)
        .map(|byte| format!("{byte:02x}"))
        .collect()
}

#[cfg(test)]
mod tests {
    // This module is generated by AI.

    use super::*;

    #[test]
    fn parses_dialogue_and_skips_other_statements() {
        let scene = "\
bgm:test.flac;
changeFigure:ext/anon/model.json -id=anon -next;
千早爱音:你爱我吗？ -figureId=anon;
wait:1000;
:爱音躺在沙发上。;
label:loop;
";
        let lines = parse_say_lines(scene);
        assert_eq!(lines.len(), 2);

        assert_eq!(lines[0].line, 2);
        assert_eq!(lines[0].speaker.as_deref(), Some("千早爱音"));
        assert!(!lines[0].speaker_inherited);
        assert_eq!(lines[0].text, "你爱我吗？");
        assert_eq!(lines[0].figure_id.as_deref(), Some("anon"));

        assert_eq!(lines[1].line, 4);
        assert_eq!(lines[1].speaker, None);
        assert!(lines[1].vocal.is_none());
    }

    #[test]
    fn inherits_speaker_from_previous_explicit_line() {
        let scene = "\
长崎素世:小爱音？ -figureId=soyo;
我有什么不对劲的地方吗？;
:素世抿了一口红茶。;
千早爱音:没...;
反正我就是想问问。;
";
        let lines = parse_say_lines(scene);
        assert_eq!(lines.len(), 5);

        // 显式说话者
        assert_eq!(lines[0].speaker.as_deref(), Some("长崎素世"));
        assert!(!lines[0].speaker_inherited);

        // 省略说话者: 继承上一个显式说话者
        assert_eq!(lines[1].speaker.as_deref(), Some("长崎素世"));
        assert!(lines[1].speaker_inherited);

        // 旁白: 显式空说话者, 不继承
        assert_eq!(lines[2].speaker, None);
        assert!(!lines[2].speaker_inherited);

        // 换人后继续继承
        assert_eq!(lines[3].speaker.as_deref(), Some("千早爱音"));
        assert!(!lines[3].speaker_inherited);
        assert_eq!(lines[4].speaker.as_deref(), Some("千早爱音"));
        assert!(lines[4].speaker_inherited);
    }

    #[test]
    fn narration_after_explicit_speaker_is_not_inherited() {
        let scene = "爱音:对话;\n:旁白;\n";
        let lines = parse_say_lines(scene);
        assert_eq!(lines.len(), 2);
        assert_eq!(lines[0].speaker.as_deref(), Some("爱音"));
        // `:旁白;` 是显式空说话者, 不继承前面的爱音
        assert_eq!(lines[1].speaker, None);
        assert!(!lines[1].speaker_inherited);
    }

    #[test]
    fn narration_does_not_reset_inheritance_before_any_speaker() {
        let scene = ":第一句旁白;\n:第二句旁白;\n";
        let lines = parse_say_lines(scene);
        assert_eq!(lines.len(), 2);
        assert!(lines.iter().all(|line| line.speaker.is_none()));
        assert!(lines.iter().all(|line| !line.speaker_inherited));
    }

    #[test]
    fn skips_empty_and_placeholder_lines() {
        let scene = ":;\n: ;\n爱音: -sayPlaceHolder;\n爱音:真的有内容;\n";
        let lines = parse_say_lines(scene);
        assert_eq!(lines.len(), 1);
        assert_eq!(lines[0].text, "真的有内容");
    }

    #[test]
    fn joins_multiline_content() {
        let scene = "爱音:第一段|第二段;\n";
        let lines = parse_say_lines(scene);
        assert_eq!(lines[0].text, "第一段|第二段");
    }

    #[test]
    fn records_existing_vocal_and_side() {
        let scene = "爱音:内容 -vocal=anon/a1.wav -left;\n";
        let lines = parse_say_lines(scene);
        assert_eq!(lines[0].vocal.as_deref(), Some("anon/a1.wav"));
        assert_eq!(lines[0].figure_side.as_deref(), Some("left"));
    }

    #[test]
    fn hash_depends_on_speaker_text_and_vocal() {
        let base = say_hash(Some("爱音"), "内容", None);
        assert_eq!(base, say_hash(Some("爱音"), "内容", None));
        assert_eq!(base.len(), HASH_LEN);
        // 内容首尾空白不影响
        assert_eq!(base, say_hash(Some("爱音"), "  内容  ", None));
        // 说话者变化影响 (身份不稳定场景)
        assert_ne!(base, say_hash(Some("素世"), "内容", None));
        // 内容变化影响
        assert_ne!(base, say_hash(Some("爱音"), "内容2", None));
        // 现有配音变化影响
        assert_ne!(base, say_hash(Some("爱音"), "内容", Some("anon/a.wav")));
        // 旁白与对话者区分
        assert_ne!(base, say_hash(None, "内容", None));
    }

    #[test]
    fn rewrite_sets_vocal_and_keeps_other_parts() {
        let line = "千早爱音:你爱我吗？ -figureId=anon -when=a>1; 这是注释";
        let rewritten = rewrite_line(line, Some("anon/a1b2c3.wav")).unwrap();
        assert!(rewritten.contains("-vocal=anon/a1b2c3.wav"));
        assert!(rewritten.contains("千早爱音:你爱我吗？"));
        assert!(rewritten.contains("-figureId=anon"));
        assert!(rewritten.contains("-when=a>1"));
        assert!(rewritten.contains("这是注释"));
        assert!(rewritten.ends_with(';') || rewritten.contains("; "));
    }

    #[test]
    fn rewrite_replaces_existing_vocal() {
        let line = "爱音:内容 -vocal=old.wav;";
        let rewritten = rewrite_line(line, Some("new.wav")).unwrap();
        assert!(rewritten.contains("-vocal=new.wav"));
        assert!(!rewritten.contains("old.wav"));
    }

    #[test]
    fn rewrite_removes_vocal() {
        let line = "爱音:内容 -vocal=old.wav -figureId=anon;";
        let rewritten = rewrite_line(line, None).unwrap();
        assert!(!rewritten.contains("old.wav"));
        assert!(rewritten.contains("-figureId=anon"));
    }

    #[test]
    fn rewrite_roundtrips_narration() {
        let line = ":爱音躺在沙发上。;";
        let rewritten = rewrite_line(line, Some("narration/a1.wav")).unwrap();
        assert!(rewritten.contains(":爱音躺在沙发上。"));
        assert!(rewritten.contains("-vocal=narration/a1.wav"));
    }

    #[test]
    fn rewrite_rejects_non_dialogue() {
        assert!(rewrite_line("bgm:test.flac;", Some("a.wav")).is_err());
        assert!(rewrite_line("changeFigure:model.json -id=anon;", Some("a.wav")).is_err());
    }

    #[test]
    fn rewrite_preserves_nolint() {
        let line = "爱音:内容 -vocal=old.wav;nolint:WG001; 备注";
        let rewritten = rewrite_line(line, Some("new.wav")).unwrap();
        assert!(rewritten.contains("nolint:WG001"));
        assert!(rewritten.contains("备注"));
        assert!(rewritten.contains("-vocal=new.wav"));
    }

    #[test]
    fn parsed_lines_roundtrip_vocal_through_rewrite() {
        let scene = "爱音:你爱我吗？ -figureId=anon;\n:素世愣住了;\n";
        let lines = parse_say_lines(scene);
        let rewritten = rewrite_line("爱音:你爱我吗？ -figureId=anon;", Some("anon/x.wav")).unwrap();
        let reparsed = parse_say_lines(&rewritten);
        assert_eq!(reparsed.len(), 1);
        assert_eq!(reparsed[0].vocal.as_deref(), Some("anon/x.wav"));
        // 内容与说话者不变
        assert_eq!(reparsed[0].text, lines[0].text);
        assert_eq!(reparsed[0].speaker, lines[0].speaker);
        // 哈希随配音引用变化
        assert_ne!(reparsed[0].hash, lines[0].hash);
    }
}
