// This file is generated by AI.

//! WAV 读写 (基于 `hound`)。
//!
//! GPT-SoVITS 与 WebGAL 侧都使用 WAV, 因此不引入更重的音频解码栈:
//! 读取支持整数 PCM 与 IEEE 浮点, 写出统一为 16 位 PCM。
//! 需要 mp3/flac 时请在 UI 侧转换为 WAV 后再加入参考音频。

use std::io::Cursor;
use std::path::Path;

use hound::{SampleFormat, WavReader, WavSpec, WavWriter};

/// 解码后的音频 (声道交错)
#[derive(Debug, Clone)]
pub struct Audio {
    pub sample_rate: u32,
    pub channels: u16,
    /// 交错存放的样本, 范围约 `[-1.0, 1.0]`
    pub samples: Vec<f32>,
}

#[derive(Debug, thiserror::Error)]
pub enum WavError {
    #[error("读取音频文件失败: {0}")]
    Io(#[from] std::io::Error),
    #[error("不是合法的 WAV 文件: {0}")]
    Format(#[from] hound::Error),
    #[error("不支持的 WAV 编码: {0}")]
    Unsupported(String),
}

type Result<T> = std::result::Result<T, WavError>;

impl Audio {
    /// 帧数 (每声道样本数)
    pub fn frames(&self) -> usize {
        if self.channels == 0 {
            0
        } else {
            self.samples.len() / self.channels as usize
        }
    }

    /// 时长 (秒)
    pub fn duration(&self) -> f64 {
        if self.sample_rate == 0 {
            0.0
        } else {
            self.frames() as f64 / self.sample_rate as f64
        }
    }

    /// 声道平均 (降为单声道)
    pub fn to_mono(&self) -> Audio {
        if self.channels <= 1 {
            return self.clone();
        }
        let channels = self.channels as usize;
        let frames = self.frames();
        let mut samples = Vec::with_capacity(frames);
        for frame in 0..frames {
            let base = frame * channels;
            let sum: f32 = self.samples[base..base + channels].iter().sum();
            samples.push(sum / channels as f32);
        }
        Audio {
            sample_rate: self.sample_rate,
            channels: 1,
            samples,
        }
    }
}

/// 读取 WAV 文件
pub fn read(path: &Path) -> Result<Audio> {
    let bytes = std::fs::read(path)?;
    decode(&bytes)
}

/// 解析 WAV 字节流
pub fn decode(bytes: &[u8]) -> Result<Audio> {
    let mut reader = WavReader::new(Cursor::new(bytes))?;
    let spec = reader.spec();
    if spec.channels == 0 {
        return Err(WavError::Unsupported("声道数为 0".into()));
    }

    let mut samples = Vec::with_capacity(reader.len() as usize);
    match (spec.sample_format, spec.bits_per_sample) {
        (SampleFormat::Float, 32) => {
            for sample in reader.samples::<f32>() {
                samples.push(sample.map_err(WavError::Format)?);
            }
        }
        (SampleFormat::Float, bits) => {
            return Err(WavError::Unsupported(format!("浮点 {bits} 位")));
        }
        (SampleFormat::Int, bits) if bits <= 32 => {
            // hound 会把各整数位深统一缩放到 i32 值域
            let scale = 2f32.powi(bits as i32 - 1);
            for sample in reader.samples::<i32>() {
                samples.push(sample.map_err(WavError::Format)? as f32 / scale);
            }
        }
        (SampleFormat::Int, bits) => {
            return Err(WavError::Unsupported(format!("整数 {bits} 位")));
        }
    }

    Ok(Audio {
        sample_rate: spec.sample_rate,
        channels: spec.channels,
        samples,
    })
}

/// 以 16 位 PCM 单声道写出 WAV 文件
pub fn write_mono_16(path: &Path, sample_rate: u32, samples: &[f32]) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, encode_mono_16(sample_rate, samples))?;
    Ok(())
}

/// 以 16 位 PCM 单声道编码 WAV 字节流
pub fn encode_mono_16(sample_rate: u32, samples: &[f32]) -> Vec<u8> {
    let spec = WavSpec {
        channels: 1,
        sample_rate,
        bits_per_sample: 16,
        sample_format: SampleFormat::Int,
    };
    let mut buffer = Cursor::new(Vec::with_capacity(samples.len() * 2 + 44));
    let mut writer = WavWriter::new(&mut buffer, spec).expect("写入内存缓冲不会失败");
    for &sample in samples {
        let value = (sample.clamp(-1.0, 1.0) * i16::MAX as f32).round() as i16;
        writer.write_sample(value).expect("写入内存缓冲不会失败");
    }
    writer.finalize().expect("写入内存缓冲不会失败");
    buffer.into_inner()
}

#[cfg(test)]
mod tests {
    // This module is generated by AI.

    use super::*;

    fn temp_dir() -> std::path::PathBuf {
        let dir = std::env::temp_dir().join("webgal-ink-wav-test");
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    fn roundtrip(sample_rate: u32, samples: &[f32]) {
        let path = temp_dir().join("roundtrip.wav");
        write_mono_16(&path, sample_rate, samples).unwrap();
        let audio = read(&path).unwrap();
        assert_eq!(audio.sample_rate, sample_rate);
        assert_eq!(audio.channels, 1);
        assert_eq!(audio.frames(), samples.len());
        for (i, (decoded, original)) in audio.samples.iter().zip(samples.iter()).enumerate() {
            // 16 位量化误差
            assert!(
                (decoded - original).abs() < 1e-4,
                "样本 {i} 不一致: {decoded} vs {original}"
            );
        }
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn write_then_read_mono() {
        roundtrip(32000, &[0.0, 0.5, -0.5, 1.0, -1.0, 0.25]);
    }

    #[test]
    fn duration_of_one_second() {
        let path = temp_dir().join("duration.wav");
        write_mono_16(&path, 48000, &vec![0.1f32; 48000]).unwrap();
        let audio = read(&path).unwrap();
        assert!((audio.duration() - 1.0).abs() < 1e-6);
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn encode_then_decode_in_memory() {
        let bytes = encode_mono_16(24000, &[0.0, 0.25, -0.75]);
        let audio = decode(&bytes).unwrap();
        assert_eq!(audio.sample_rate, 24000);
        assert_eq!(audio.channels, 1);
        assert!((audio.samples[1] - 0.25).abs() < 1e-4);
    }

    #[test]
    fn decode_rejects_garbage() {
        assert!(decode(b"not a wav file at all").is_err());
        assert!(decode(b"RIFF\x04\x00\x00\x00WAVE").is_err());
    }

    #[test]
    fn decode_stereo_16() {
        let spec = WavSpec {
            channels: 2,
            sample_rate: 44100,
            bits_per_sample: 16,
            sample_format: SampleFormat::Int,
        };
        let mut buffer = Cursor::new(Vec::new());
        let mut writer = WavWriter::new(&mut buffer, spec).unwrap();
        for value in [i16::MAX, 0, 0, i16::MAX] {
            writer.write_sample(value).unwrap();
        }
        writer.finalize().unwrap();

        let audio = decode(&buffer.into_inner()).unwrap();
        assert_eq!(audio.channels, 2);
        assert_eq!(audio.frames(), 2);
        let mono = audio.to_mono();
        assert_eq!(mono.channels, 1);
        assert!((mono.samples[0] - 0.5).abs() < 1e-3);
    }

    #[test]
    fn decode_float32() {
        let spec = WavSpec {
            channels: 1,
            sample_rate: 32000,
            bits_per_sample: 32,
            sample_format: SampleFormat::Float,
        };
        let mut buffer = Cursor::new(Vec::new());
        let mut writer = WavWriter::new(&mut buffer, spec).unwrap();
        for value in [0.5f32, -0.25] {
            writer.write_sample(value).unwrap();
        }
        writer.finalize().unwrap();

        let audio = decode(&buffer.into_inner()).unwrap();
        assert!((audio.samples[0] - 0.5).abs() < 1e-6);
        assert!((audio.samples[1] + 0.25).abs() < 1e-6);
    }
}
