// This file is generated by AI.

import { spawn, ChildProcess } from 'child_process';
import * as path from 'path';
import {
  createMessageConnection,
  StreamMessageReader,
  StreamMessageWriter,
  MessageConnection,
} from 'vscode-jsonrpc/node';
import { PassThrough } from 'stream';

// 平台 -> 二进制文件名映射
const PLATFORM_BIN_MAP: Record<string, string> = {
  linux: 'webgal-language-server-linux-x86_64',
  darwin: 'webgal-language-server-macos-x86_64',
  win32: 'webgal-language-server-windows-x86_64.exe',
};
if (process.platform === 'darwin' && process.arch === 'arm64') {
  PLATFORM_BIN_MAP.darwin = 'webgal-language-server-macos-aarch64';
}

let proc: ChildProcess | null = null;
let childConnection: MessageConnection | null = null;
let terreConnection: MessageConnection | null = null;

export default {
  name: 'WebGAL Language Server',

  async start() {
    const binName = PLATFORM_BIN_MAP[process.platform];
    if (!binName) {
      throw new Error(`Unsupported platform: ${process.platform}`);
    }

    const binPath = path.join(__dirname, 'bin', binName);
    console.log(`[Terre Adapter] Starting: ${binPath}`);

    // 启动语言服务器子进程，确保 stdio 为 pipe
    proc = spawn(binPath, [], {
      stdio: ['pipe', 'pipe', 'pipe'],
      env: { ...process.env },
    });
    // 使用非空断言，因为 stdio 配置为 pipe，确保流存在
    proc.stderr!.pipe(process.stderr);
    proc.on('exit', code => console.log(`[Terre Adapter] Process exited (${code})`));
    proc.on('error', err => console.error(`[Terre Adapter] Process error:`, err));

    // 创建面向子进程的 MessageConnection
    const childReader = new StreamMessageReader(proc.stdout!);
    const childWriter = new StreamMessageWriter(proc.stdin!);
    childConnection = createMessageConnection(childReader, childWriter);

    // 创建面向 Terre 代理的流 (通过 PassThrough 实现)
    const toTerre = new PassThrough();
    const fromTerre = new PassThrough();
    const terreReader = new StreamMessageReader(fromTerre);
    const terreWriter = new StreamMessageWriter(toTerre);
    terreConnection = createMessageConnection(terreReader, terreWriter);

    // 返回给 Terre 的 reader / writer
    return {
      reader: new StreamMessageReader(fromTerre),
      writer: new StreamMessageWriter(toTerre),
    };
  },

  registerExtensions(host: any) {
    if (!childConnection || !terreConnection) {
      throw new Error('Connections not initialized. Did you call start() first?');
    }

    // 1. 来自 Terre 的请求/通知 -> 转发给子进程
    terreConnection.onRequest((method: string, params: any, token: any) => {
      return childConnection!.sendRequest(method, params, token);
    });
    terreConnection.onNotification((method: string, params: any) => {
      childConnection!.sendNotification(method, params);
    });

    // 2. 来自子进程的请求/通知 -> 拦截自定义协议，其余转发
    childConnection.onRequest(async (method: string, params: any, token: any) => {
      switch (method) {
        case 'workspace/fs/readFile':
          return await host.readFile(params.path);
        case 'workspace/fs/readDirectory':
          return await host.readDirectory(params.path);
        case 'workspace/fs/exists':
          return await host.stat(params.path);
        default:
          return terreConnection!.sendRequest(method, params, token);
      }
    });

    childConnection.onNotification((method: string, params: any) => {
      terreConnection!.sendNotification(method, params);
    });

    // 启动连接
    childConnection.listen();
    terreConnection.listen();

    console.log('[Terre Adapter] Extensions registered with host');
  },

  async stop() {
    if (childConnection) {
      childConnection.dispose();
      childConnection = null;
    }
    if (terreConnection) {
      terreConnection.dispose();
      terreConnection = null;
    }
    if (proc) {
      proc.kill();
      proc = null;
    }
  },
};
