// This file is generated by AI.

// WebGAL 编辑器预览同步协议 (V1) 的最小宿主侧实现。
// 与引擎 `types/editorPreviewProtocol` 对应, 仅保留实时预览所需类型。

export const EDITOR_PREVIEW_PROTOCOL_V1_SUBPROTOCOL = 'webgal-editor-preview-sync.v1';
export const SESSION_REGISTER_PREVIEW_TYPE = 'session.register-preview';

export interface SyncScenePayload {
  sceneName: string;
  sentenceId: number;
  settleMode?: 'normal' | 'immediate';
}

export interface DebugVariable {
  key: string;
  value: string;
  isGlobal?: boolean;
}

export interface RequestEnvelope<TPayload = unknown, TType extends string = string> {
  kind: 'request';
  type: TType;
  requestId: string;
  payload: TPayload;
}

export interface EventEnvelope<TPayload = unknown, TType extends string = string> {
  kind: 'event';
  type: TType;
  payload: TPayload;
}

export type HostEventType = 'preview.ready.updated' | 'stage.snapshot.updated' | 'preview.event.fast-preview-timeout';

export interface PreviewReadyUpdatedPayload {
  ready: boolean;
}

export function createId(): string {
  return `req-${Date.now()}-${Math.random().toString(16).slice(2)}`;
}

export function createRequestEnvelope<TType extends string, TPayload>(
  type: TType,
  requestId: string,
  payload: TPayload
): RequestEnvelope<TPayload, TType> {
  return { kind: 'request', type, requestId, payload };
}

export function isHostEventEnvelope(value: unknown): value is EventEnvelope<PreviewReadyUpdatedPayload, HostEventType> {
  if (typeof value !== 'object' || value === null) return false;
  const v = value as { kind?: unknown; type?: unknown };
  return v.kind === 'event' && typeof v.type === 'string';
}
