pub use config::*;
pub use figure::*;

pub use crate::element::AnimationList; // 重新导出方便使用

mod config;
mod figure;

// -------- lsp --------

#[cfg(feature = "lsp")]
pub use lsp_ext::*;

#[cfg(feature = "lsp")]
mod lsp_ext {
    use path_tree::{PATH_SEPARATORS, name_of};
    use strum::{Display, EnumString};

    /// 资源根目录 (升序)
    pub const RESOURCE_ROOTS: &[&str] = &[
        "animation",
        "background",
        "bgm",
        "figure",
        "scene",
        "video",
        "vocal",
    ];

    /// 资源信息
    #[derive(Debug, Clone, Copy, Default, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct ResourceInfo<'a> {
        pub kind: ResourceKind,
        pub path: &'a str,
        pub extension: Option<&'a str>,
    }

    /// 资源类型
    #[derive(
        Debug, Clone, Copy, Default, PartialEq, Eq, PartialOrd, Ord, Hash, Display, EnumString,
    )]
    #[strum(serialize_all = "camelCase")]
    pub enum ResourceKind {
        Config,
        Scene,
        Animation,
        Background,
        Figure,
        Bgm,
        Vocal,
        Video,
        #[default]
        Other,
    }

    impl<'a> ResourceInfo<'a> {
        /// 依据路径识别资源信息
        ///
        /// # Behavior
        /// * 不进行路径规范化, 包括移除空白字符 / 首尾分隔符, 处理相对路径等.
        /// * 可识别并处理路径分隔符: `/`, `\\`.
        /// * 后缀名以 `.` 作为识别符号但不包含其本身, 形如: `txt`, `png`.
        pub fn from_path(path: &'a str) -> Self {
            let (kind, path) = ResourceKind::from_path(path);
            let extension = extension_of(path);
            Self {
                kind,
                path,
                extension,
            }
        }

        /// 资源是否为目录 (无后缀)
        pub fn is_folder(&self) -> bool {
            self.extension.is_none()
        }

        /// 资源是否为目录 (有后缀)
        pub fn is_file(&self) -> bool {
            self.extension.is_some()
        }

        /// 资源是否为根目录相关类型的文件
        ///
        /// # Behavior
        /// * 目录 (无后缀) 返回 `false`.
        /// * 后缀检查由 [`ResourceKind::is_extension_relevant`] 提供.
        pub fn is_relevant_file(&self) -> bool {
            self.extension
                .is_some_and(|extension| self.kind.is_extension_relevant(extension))
        }
    }

    impl ResourceKind {
        /// 依据路径识别资源类型
        ///
        /// # Returns
        /// 资源类型, 以及其在对应资源根目录下的路径 (或原路径).
        ///
        /// # Behavior
        /// * 不进行路径规范化, 包括移除空白字符 / 首尾分隔符, 处理相对路径等.
        /// * 可识别并处理路径分隔符: `/`, `\\`.
        pub fn from_path(path: &str) -> (Self, &str) {
            let path = path.trim_end_matches(PATH_SEPARATORS);
            if path == "config.txt" {
                return (Self::Config, path);
            }

            match path.split_once(PATH_SEPARATORS).unwrap_or((path, "")) {
                ("scene", path) => (Self::Scene, path),
                ("animation", path) => (Self::Animation, path),
                ("background", path) => (Self::Background, path),
                ("figure", path) => (Self::Figure, path),
                ("bgm", path) => (Self::Bgm, path),
                ("vocal", path) => (Self::Vocal, path),
                ("video", path) => (Self::Video, path),
                _ => (Self::Other, path),
            }
        }

        /// 获取资源类型对应的文件后缀 (升序)
        pub fn extensions(&self) -> &'static [&'static str] {
            match self {
                Self::Config => &["txt"],
                Self::Scene => &["txt"],
                Self::Animation => &["json"],
                Self::Background => &[
                    "bmp", "gif", "jpeg", "jpg", "mkv", "mp4", "png", "svg", "webm", "webp",
                ],
                Self::Figure => &[
                    "bmp", "gif", "jpeg", "jpg", "json", "jsonl", "png", "skel", "svg", "webp",
                    "wmdl",
                ],
                Self::Bgm => &["flac", "mp3", "ogg", "wav"],
                Self::Vocal => &["flac", "mp3", "ogg", "wav"],
                Self::Video => &["mkv", "mp4", "ogg", "webm"],
                Self::Other => &[],
            }
        }

        /// 后缀是否属于指定资源类型
        pub fn is_extension_relevant(&self, extension: &str) -> bool {
            self.extensions().binary_search(&extension).is_ok()
        }
    }

    fn extension_of(path: &str) -> Option<&str> {
        name_of(path)
            .rsplit_once('.')
            .map(|(_, extension)| extension)
    }
}

#[cfg(all(test, feature = "lsp"))]
mod tests {
    // This module is generated by AI.

    use super::*;

    // -------- info --------

    #[test]
    fn test_kind_from_path() {
        let cases = [
            ("config.txt", (ResourceKind::Config, "config.txt")),
            ("scene/start.txt", (ResourceKind::Scene, "start.txt")),
            (
                "animation/idle.json",
                (ResourceKind::Animation, "idle.json"),
            ),
            ("background/bg.png", (ResourceKind::Background, "bg.png")),
            ("figure/char.json", (ResourceKind::Figure, "char.json")),
            ("bgm/music.flac", (ResourceKind::Bgm, "music.flac")),
            ("vocal/voice.wav", (ResourceKind::Vocal, "voice.wav")),
            ("video/movie.mp4", (ResourceKind::Video, "movie.mp4")),
            (
                "unknown/file.txt",
                (ResourceKind::Other, "unknown/file.txt"),
            ),
        ];
        for (input, expected) in cases {
            assert_eq!(ResourceKind::from_path(input), expected);
        }
        // Windows 风格分隔符
        assert_eq!(
            ResourceKind::from_path("scene\\start.txt"),
            (ResourceKind::Scene, "start.txt")
        );
        // 嵌套路径
        assert_eq!(
            ResourceKind::from_path("figure/sub/char.json"),
            (ResourceKind::Figure, "sub/char.json")
        );
    }

    #[test]
    fn test_resource_info_from_path() {
        let info = ResourceInfo::from_path("scene/start.txt");
        assert_eq!(info.kind, ResourceKind::Scene);
        assert_eq!(info.path, "start.txt");
        assert_eq!(info.extension, Some("txt"));
        assert!(info.is_file());
        assert!(!info.is_folder());

        let info = ResourceInfo::from_path("figure/");
        assert_eq!(info.kind, ResourceKind::Figure);
        assert_eq!(info.path, "");
        assert_eq!(info.extension, None);
        assert!(!info.is_file());
        assert!(info.is_folder());
    }

    // -------- extension --------

    #[test]
    fn test_extensions_sorted() {
        for kind in [
            ResourceKind::Config,
            ResourceKind::Scene,
            ResourceKind::Animation,
            ResourceKind::Background,
            ResourceKind::Figure,
            ResourceKind::Bgm,
            ResourceKind::Vocal,
            ResourceKind::Video,
            ResourceKind::Other,
        ] {
            let exts = kind.extensions();
            let mut sorted = exts.to_vec();
            sorted.sort_unstable();
            assert_eq!(
                exts,
                sorted.as_slice(),
                "Extensions for {:?} are not sorted",
                kind
            );
        }
    }

    #[test]
    fn test_is_extension_relevant() {
        let kind = ResourceKind::Background;
        assert!(kind.is_extension_relevant("png"));
        assert!(kind.is_extension_relevant("jpg"));
        assert!(!kind.is_extension_relevant("txt"));
        assert!(!kind.is_extension_relevant("json"));

        let kind = ResourceKind::Figure;
        assert!(kind.is_extension_relevant("json"));
        assert!(kind.is_extension_relevant("wmdl"));
        assert!(kind.is_extension_relevant("png"));
    }
}
