use std::mem;

use tower_lsp::lsp_types::*;
use webgal_model::sentence::Scene;

fn offset_utf16_to_utf8(content: &str, offset: u32) -> u32 {
    let mut utf8_pos: usize = 0;
    let mut utf16_pos: usize = 0;
    for ch in content.chars() {
        let ch_utf16 = ch.len_utf16();
        let ch_utf8 = ch.len_utf8();
        if utf16_pos + ch_utf16 > offset as usize {
            break;
        }
        utf16_pos += ch_utf16;
        utf8_pos += ch_utf8;
    }
    utf8_pos as u32
}

fn offset_utf8_to_utf16(content: &str, offset: u32) -> u32 {
    let offset = offset as usize;
    let mut utf8_pos: usize = 0;
    let mut utf16_pos: usize = 0;
    for ch in content.chars() {
        let next_utf8 = utf8_pos + ch.len_utf8();
        if next_utf8 > offset {
            break;
        }
        utf8_pos = next_utf8;
        utf16_pos += ch.len_utf16();
    }
    utf16_pos as u32
}

pub fn position_utf16_to_utf8(scene: &Scene, position: Position) -> Position {
    let content = scene.sentences()[position.line as usize].content;
    let character = offset_utf16_to_utf8(content, position.character);
    Position {
        character,
        ..position
    }
}

pub fn position_utf8_to_utf16(scene: &Scene, position: Position) -> Position {
    let content = scene.sentences()[position.line as usize].content;
    let character = offset_utf8_to_utf16(content, position.character);
    Position {
        character,
        ..position
    }
}

pub fn range_utf16_to_utf8(scene: &Scene, range: Range) -> Range {
    Range {
        start: position_utf16_to_utf8(scene, range.start),
        end: position_utf16_to_utf8(scene, range.end),
    }
}

pub fn range_utf8_to_utf16(scene: &Scene, range: Range) -> Range {
    Range {
        start: position_utf8_to_utf16(scene, range.start),
        end: position_utf8_to_utf16(scene, range.end),
    }
}

pub fn text_edit_utf8_to_utf16(scene: &Scene, edit: TextEdit) -> TextEdit {
    TextEdit {
        range: range_utf8_to_utf16(scene, edit.range),
        ..edit
    }
}

// -------- service --------

pub fn diagnostics_utf8_to_utf16(scene: &Scene, diagnostics: &mut [Diagnostic]) {
    for diagnostic in diagnostics {
        *diagnostic = diagnostic_utf8_to_utf16(scene, mem::take(diagnostic));
    }
}

pub fn diagnostic_utf8_to_utf16(scene: &Scene, diagnostic: Diagnostic) -> Diagnostic {
    Diagnostic {
        range: range_utf8_to_utf16(scene, diagnostic.range),
        ..diagnostic
    }
}

pub fn highlights_utf8_to_utf16(scene: &Scene, tokens: &mut [SemanticToken]) {
    for token in tokens {
        *token = highlight_utf8_to_utf16(scene, *token);
    }
}

pub fn highlight_utf8_to_utf16(scene: &Scene, token: SemanticToken) -> SemanticToken {
    let content = scene.sentences()[token.delta_line as usize].content;
    let delta_start = offset_utf8_to_utf16(content, token.delta_start);
    let delta_end = offset_utf8_to_utf16(content, token.delta_start + token.length);
    SemanticToken {
        delta_start,
        length: delta_end - delta_start,
        ..token
    }
}

pub fn completions_utf8_to_utf16(scene: &Scene, completions: &mut [CompletionItem]) {
    for completion in completions {
        *completion = completion_utf8_to_utf16(scene, mem::take(completion));
    }
}

pub fn completion_utf8_to_utf16(scene: &Scene, completion: CompletionItem) -> CompletionItem {
    CompletionItem {
        text_edit: completion.text_edit.map(|edit| match edit {
            CompletionTextEdit::Edit(edit) => {
                CompletionTextEdit::Edit(text_edit_utf8_to_utf16(scene, edit))
            }
            _ => unimplemented!(),
        }),
        ..completion
    }
}

pub fn formatting_utf8_to_utf16(scene: &Scene, edits: &mut [TextEdit]) {
    for edit in edits {
        *edit = text_edit_utf8_to_utf16(scene, mem::take(edit));
    }
}

#[cfg(test)]
mod tests {
    // This module is generated by AI.

    use super::*;

    #[test]
    fn offset_utf16_to_utf8_ascii() {
        let s = "hello";
        assert_eq!(offset_utf16_to_utf8(s, 0), 0);
        assert_eq!(offset_utf16_to_utf8(s, 1), 1);
        assert_eq!(offset_utf16_to_utf8(s, 5), 5);
        assert_eq!(offset_utf16_to_utf8(s, 6), 5); // 超出最大偏移, 返回总 UTF-8 长度
    }

    #[test]
    fn offset_utf8_to_utf16_ascii() {
        let s = "hello";
        assert_eq!(offset_utf8_to_utf16(s, 0), 0);
        assert_eq!(offset_utf8_to_utf16(s, 1), 1);
        assert_eq!(offset_utf8_to_utf16(s, 5), 5);
        assert_eq!(offset_utf8_to_utf16(s, 6), 5);
    }

    #[test]
    fn offset_utf16_to_utf8_chinese() {
        let s = "你好世界";
        // 每个中文字符 UTF-16 长度 1, UTF-8 长度 3
        assert_eq!(offset_utf16_to_utf8(s, 0), 0);
        assert_eq!(offset_utf16_to_utf8(s, 1), 3);
        assert_eq!(offset_utf16_to_utf8(s, 2), 6);
        assert_eq!(offset_utf16_to_utf8(s, 3), 9);
        assert_eq!(offset_utf16_to_utf8(s, 4), 12); // 总 UTF-8 长度
    }

    #[test]
    fn offset_utf8_to_utf16_chinese() {
        let s = "你好世界";
        assert_eq!(offset_utf8_to_utf16(s, 0), 0);
        assert_eq!(offset_utf8_to_utf16(s, 3), 1);
        assert_eq!(offset_utf8_to_utf16(s, 6), 2);
        assert_eq!(offset_utf8_to_utf16(s, 9), 3);
        assert_eq!(offset_utf8_to_utf16(s, 12), 4); // 总 UTF-16 长度
    }

    #[test]
    fn offset_utf16_to_utf8_mixed() {
        let s = "a😀b";
        assert_eq!(offset_utf16_to_utf8(s, 0), 0);
        assert_eq!(offset_utf16_to_utf8(s, 1), 1); // 'a' 结束
        assert_eq!(offset_utf16_to_utf8(s, 2), 1); // 低代理项, 映射到字符起始
        assert_eq!(offset_utf16_to_utf8(s, 3), 5); // emoji 结束
        assert_eq!(offset_utf16_to_utf8(s, 4), 6); // 超出
    }

    #[test]
    fn offset_utf8_to_utf16_mixed() {
        let s = "a😀b";
        assert_eq!(offset_utf8_to_utf16(s, 0), 0);
        assert_eq!(offset_utf8_to_utf16(s, 1), 1); // 'a' 结束
        assert_eq!(offset_utf8_to_utf16(s, 5), 3); // emoji 结束 (起始位置 1 + 4 = 5)
        assert_eq!(offset_utf8_to_utf16(s, 6), 4); // 全部结束
        assert_eq!(offset_utf8_to_utf16(s, 7), 4); // 超出
    }
}
