// This file is generated by AI.

//! 变量系统
//!
//! 参照 WebGAL 4.6.3 的变量设计:
//! * 普通变量 - 常驻基底层, 由 `setVar` 等语句写入, 全局可见.
//! * 局部变量 - 每次 `callScene` 调用压入一层作用域, 场景返回时弹出.
//! * 查找链 - 由内向外依次查找局部变量, 最后回退到普通变量.

use std::{collections::HashMap, iter};

use expression::{EvaluationContext, EvaluationError, Value};

/// 多层变量表
///
/// # Behavior
/// * 查找变量按 `局部变量 (从内到外) -> 普通变量` 的顺序.
/// * 写入普通变量始终落在基底层, 不受局部变量影响.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct VariableTable {
    /// 普通变量 (基底层)
    base: HashMap<String, Value>,
    /// 局部变量作用域栈, 每层对应一次 `callScene` 调用
    locals: Vec<HashMap<String, Value>>,
}

impl VariableTable {
    /// 依据查找链读取变量
    pub fn get(&self, name: &str) -> Option<&Value> {
        self.locals
            .iter()
            .rev()
            .find_map(|scope| scope.get(name))
            .or_else(|| self.base.get(name))
    }

    /// 写入普通变量 (基底层)
    pub fn set_base(&mut self, name: String, value: Value) -> Option<Value> {
        self.base.insert(name, value)
    }

    /// 压入一层局部变量作用域 (进入被调用场景)
    pub fn push_locals(&mut self, locals: HashMap<String, Value>) {
        self.locals.push(locals);
    }

    /// 弹出最内层局部变量作用域 (从被调用场景返回)
    pub fn pop_locals(&mut self) -> Option<HashMap<String, Value>> {
        self.locals.pop()
    }

    /// 当前局部变量作用域层数
    pub fn locals_depth(&self) -> usize {
        self.locals.len()
    }

    /// 按查找顺序 (从内到外) 迭代各层, 最后迭代基底层
    pub fn scopes(&self) -> impl Iterator<Item = &HashMap<String, Value>> {
        self.locals.iter().rev().chain(iter::once(&self.base))
    }
}

/// 为变量表引用实现求值上下文
///
/// # Behavior
/// * 变量读取遵循与 [`VariableTable::get`] 相同的查找链.
/// * 函数调用一律返回 [`EvaluationError::UnknownFunction`].
impl EvaluationContext for VariableTable {
    fn get_variable(&self, name: &str) -> Option<Value> {
        self.get(name).cloned()
    }

    fn call_function(&self, name: &str, _arguments: &[Value]) -> Result<Value, EvaluationError> {
        Err(EvaluationError::UnknownFunction(name.to_string()))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn locals(entries: &[(&str, i64)]) -> HashMap<String, Value> {
        entries
            .iter()
            .map(|&(name, value)| (name.to_string(), Value::from(value)))
            .collect()
    }

    // -------- 查找链 --------

    #[test]
    fn get_falls_back_to_base() {
        let mut table = VariableTable::default();
        table.set_base("hp".to_string(), Value::from(50));

        assert_eq!(table.get("hp"), Some(&Value::from(50)));
        assert_eq!(table.get("missing"), None);
    }

    #[test]
    fn get_prefers_innermost_locals() {
        let mut table = VariableTable::default();
        table.set_base("hp".to_string(), Value::from(50));
        table.push_locals(locals(&[("hp", 100), ("name", 1)]));
        table.push_locals(locals(&[("hp", 200)]));

        // 最内层局部变量优先
        assert_eq!(table.get("hp"), Some(&Value::from(200)));
        // 次外层局部变量
        assert_eq!(table.get("name"), Some(&Value::from(1)));
        // 基底层
        assert_eq!(table.get("base_only"), None);
    }

    #[test]
    fn push_pop_locals_restores_scope() {
        let mut table = VariableTable::default();
        table.set_base("hp".to_string(), Value::from(50));
        table.push_locals(locals(&[("hp", 100)]));

        assert_eq!(table.get("hp"), Some(&Value::from(100)));
        assert_eq!(table.locals_depth(), 1);

        // 弹出局部作用域后回退到基底层
        assert_eq!(table.pop_locals(), Some(locals(&[("hp", 100)])));
        assert_eq!(table.locals_depth(), 0);
        assert_eq!(table.get("hp"), Some(&Value::from(50)));
    }

    #[test]
    fn set_base_ignores_locals() {
        let mut table = VariableTable::default();
        table.push_locals(locals(&[("hp", 100)]));
        table.set_base("hp".to_string(), Value::from(200));

        // 局部变量遮蔽普通变量, 但 set_base 直接写入基底层
        assert_eq!(table.get("hp"), Some(&Value::from(100)));
        table.pop_locals();
        assert_eq!(table.get("hp"), Some(&Value::from(200)));
    }

    #[test]
    fn scopes_iterates_innermost_first() {
        let mut table = VariableTable::default();
        table.set_base("a".to_string(), Value::from(1));
        table.push_locals(locals(&[("b", 2)]));
        table.push_locals(locals(&[("c", 3)]));

        let scopes: Vec<_> = table.scopes().collect();
        assert_eq!(scopes.len(), 3);
        assert_eq!(scopes[0].get("c"), Some(&Value::from(3)));
        assert_eq!(scopes[1].get("b"), Some(&Value::from(2)));
        assert_eq!(scopes[2].get("a"), Some(&Value::from(1)));
    }

    // -------- 求值上下文 --------

    #[test]
    fn reference_reads_through_chain() {
        let mut table = VariableTable::default();
        table.set_base("hp".to_string(), Value::from(50));
        table.push_locals(locals(&[("hp", 100)]));

        let context: &VariableTable = &table;
        assert_eq!(context.get_variable("hp"), Some(Value::from(100)));
        assert_eq!(context.get_variable("missing"), None);
    }
}
