// This file is generated by AI.

use std::{fmt::Write, ops, str::FromStr};

use lsp_types::*;
use webgal_language_core::{
    element::{Color, TokenSplit},
    sentence::{Scene, Sentence, SentenceInfo},
    util::span_of,
};

use crate::project::Project;

pub fn document_color_capability() -> ColorProviderCapability {
    ColorProviderCapability::Simple(true)
}

/// 语句中的颜色字面量
///
/// # Arguments
/// * **scene_path** - 场景相对项目根的路径.
///
/// # Behavior
/// * 区间为 **UTF-8** 行列 (相对行首的字节偏移), 可直接交给
///   [`crate::encode::document_colors_utf8_to_utf16`] 转成 LSP 要求的 UTF-16 编码.
/// * 覆盖两类写法:
///   * 语句参数, 形如 `intro:全屏文字 -fontColor=rgba(0, 0, 0, 1);`
///   * 文本拓展样式, 形如 `角色A:[文字](style=color:#FF8800);`
/// * 取值解析不出的位置不报色块 (CSS 颜色名 `red` 等不在 [`Color`] 支持范围内).
pub fn document_color(scene_path: &str, project: &Project) -> Option<Vec<ColorInformation>> {
    let scene = project.resource().scene.get(scene_path)?.as_item()?;
    Some(
        color_literals(scene)
            .into_iter()
            .map(|literal| ColorInformation {
                range: literal_range(&literal),
                color: to_lsp_color(literal.color),
            })
            .collect(),
    )
}

/// 颜色修改建议
///
/// # Arguments
/// * **scene_path** - 场景相对项目根的路径.
/// * **span** - 待修改区间 (UTF-8 行列), 通常是本模块 [`document_color`] 报出的区间.
/// * **color** - 客户端取到的新颜色.
///
/// # Behavior
/// * 参数颜色按语句参数要求的 `rgba(R, G, B, A)` 生成, 改完仍是合法语句
///   (见 `webgal-language-core` 的 `parse_color_css_rgba`).
/// * 文本样式颜色用 hex 生成 (不透明 `#RRGGBB`, 有透明度 `#RRGGBBAA`) ——
///   样式取值里写不出 `)`, 而且 hex 能被重新识别成颜色字面量, 改完色块不会消失.
/// * 区间处没有颜色字面量时返回 `None`.
pub fn color_presentation(
    scene_path: &str,
    span: Range,
    color: lsp_types::Color,
    project: &Project,
) -> Option<Vec<ColorPresentation>> {
    let color = from_lsp_color(color);
    let scene = project.resource().scene.get(scene_path)?.as_item()?;
    let literals = color_literals(scene);
    let literal = literals
        .iter()
        .find(|literal| literal_range(literal) == span)
        .or_else(|| {
            literals
                .iter()
                .find(|literal| overlaps(&literal_range(literal), span))
        })?;

    let text = format_color(color, literal.syntax);
    Some(vec![ColorPresentation {
        label: text.clone(),
        text_edit: Some(TextEdit {
            range: literal_range(literal),
            new_text: text,
        }),
        additional_text_edits: None,
    }])
}

// -------- 收集 --------

/// 颜色参数
///
/// 这些参数在语句里声明为颜色 (见 `webgal-language-core` 的 `IntroSentence`),
/// 取值必须是 `rgba(R, G, B, A)`.
/// 参数名判定与语义高亮的参数名判定同源, 都按名字匹配, 不依赖语句类型.
const COLOR_ARGUMENTS: &[&str] = &["fontColor", "backgroundColor"];

/// 颜色字面量
#[derive(Debug, Clone)]
struct ColorLiteral {
    /// 行号 (从 0 开始)
    line: u32,
    /// 行内区间 (相对行首的字节偏移)
    span: ops::Range<usize>,
    color: Color,
    syntax: ColorSyntax,
}

/// 颜色字面量所在的语法位置
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum ColorSyntax {
    /// 语句参数, 取值需为 `rgba(R, G, B, A)`
    Argument,
    /// 文本拓展样式, 取值是标准 CSS 行内颜色.
    ///
    /// 注意样式取值不能含 `)`: 文本拓展语法在 `](` 后的第一个 `)` 处结束,
    /// 因此 `rgb()` / `rgba()` 写不进样式里.
    Style,
}

/// 收集场景中的全部颜色字面量
fn color_literals(scene: &Scene) -> Vec<ColorLiteral> {
    scene
        .sentences()
        .iter()
        .enumerate()
        .flat_map(|(line, sentence)| {
            sentence_color_literals(sentence)
                .into_iter()
                .map(move |(span, color, syntax)| ColorLiteral {
                    line: line as u32,
                    span,
                    color,
                    syntax,
                })
        })
        .collect()
}

/// 收集单条语句中的颜色字面量 (行内字节区间)
fn sentence_color_literals(
    sentence: &SentenceInfo,
) -> Vec<(ops::Range<usize>, Color, ColorSyntax)> {
    let SentenceInfo {
        primary, sentence, ..
    } = sentence;
    let mut literals = Vec::new();

    // 语句参数, 形如 `-fontColor=rgba(0, 0, 0, 1)`
    for &(name, value) in &primary.arguments {
        let Some(value) = value.filter(|_| COLOR_ARGUMENTS.contains(&name)) else {
            continue;
        };
        // 与语句反序列化用同一个解析器: 报色块的取值一定也是合法取值
        let Some(color) = Color::from_str_rgba(value) else {
            continue;
        };
        literals.push((primary.get_span(value), color, ColorSyntax::Argument));
    }

    // 文本拓展样式, 形如 `[文字](style=color:#FF8800)`.
    // 只有对话内容支持文本拓展, 与 `webgal-simulate` 的解析一致.
    if let Some(content) = primary.content
        && matches!(sentence, Sentence::Say(_))
    {
        let offset = primary.get_span(content).start;
        for text in content.split('|') {
            for token in TokenSplit::new(text) {
                for (_, arguments) in &token.style {
                    for &(name, value) in arguments {
                        if !is_color_style(name) {
                            continue;
                        }
                        // 样式取值是标准 CSS 行内颜色
                        let Some(color) = parse_style_color(value) else {
                            continue;
                        };
                        let span = span_of(content, value);
                        literals.push((
                            offset + span.start..offset + span.end,
                            color,
                            ColorSyntax::Style,
                        ));
                    }
                }
            }
        }
    }

    literals
}

/// 是否为样式里的颜色属性
///
/// CSS 中以 `-color` 结尾的属性都取颜色值 (`color` / `background-color` / `border-color` ...).
fn is_color_style(name: &str) -> bool {
    name == "color" || name.ends_with("-color")
}

/// 解析文本样式里的颜色
///
/// 样式取值是标准 CSS 行内颜色, 因此除 [`Color`] 支持的 `#RRGGBB` / `rgb()` / `rgba()` 外,
/// 还接受 CSS Color 4 的 `#RRGGBBAA` —— 那是样式里唯一能表达透明度的写法
/// (带括号的 `rgb()` / `rgba()` 会被文本拓展语法的 `)` 截断, 见 [`ColorSyntax::Style`]).
fn parse_style_color(value: &str) -> Option<Color> {
    Color::from_str(value).ok().or_else(|| {
        let hex = value.trim().strip_prefix('#')?;
        // 先排除非 ASCII: 下面的按字节切片要求输入是单字节字符
        if hex.len() != 8 || !hex.is_ascii() {
            return None;
        }
        let parse = |range: ops::Range<usize>| u8::from_str_radix(&hex[range], 16).ok();
        Some(Color {
            red: parse(0..2)?,
            green: parse(2..4)?,
            blue: parse(4..6)?,
            alpha: f32::from(parse(6..8)?) / 255.,
        })
    })
}

// -------- 转换 --------

/// 生成颜色的规范写法
///
/// * 语句参数只接受 `rgba(R, G, B, A)`, 与语句反序列化的 `parse_color_css_rgba` 一致.
/// * 文本样式的取值不能含 `)` (文本拓展语法在第一个 `)` 处结束), 因此用 hex 表示:
///   不透明时是 `#RRGGBB`, 有透明度时是 CSS Color 4 的 `#RRGGBBAA`.
fn format_color(color: Color, syntax: ColorSyntax) -> String {
    let mut text = String::new();
    let result = match syntax {
        ColorSyntax::Argument => color.fmt_css_rgba(&mut text),
        ColorSyntax::Style => match alpha_byte(color) {
            u8::MAX => color.fmt_hex_upper(&mut text),
            alpha => write!(
                text,
                "#{:02X}{:02X}{:02X}{alpha:02X}",
                color.red, color.green, color.blue
            ),
        },
    };
    debug_assert!(result.is_ok(), "向字符串写入颜色不会失败");
    text
}

/// 颜色的透明度分量 (`[0, 255]`)
fn alpha_byte(color: Color) -> u8 {
    (color.alpha.clamp(0., 1.) * 255.).round() as u8
}

/// 转换为 LSP 颜色 (分量为 `[0, 1]` 浮点数)
fn to_lsp_color(color: Color) -> lsp_types::Color {
    lsp_types::Color {
        red: f32::from(color.red) / 255.,
        green: f32::from(color.green) / 255.,
        blue: f32::from(color.blue) / 255.,
        alpha: color.alpha,
    }
}

/// 从 LSP 颜色还原 (分量为 `[0, 1]` 浮点数)
///
/// # Behavior
/// * 颜色分量按字节取整.
/// * 透明度保留两位小数: 选择器给出的透明度是任意浮点数, 直接写进语句会变成
///   `rgba(0, 0, 0, 0.37254903)` 这样的长尾.
fn from_lsp_color(color: lsp_types::Color) -> Color {
    let component = |value: f32| (value.clamp(0., 1.) * 255.).round() as u8;
    Color {
        red: component(color.red),
        green: component(color.green),
        blue: component(color.blue),
        alpha: (color.alpha.clamp(0., 1.) * 100.).round() / 100.,
    }
}

/// 字面量的 LSP 区间 (UTF-8 行列)
fn literal_range(literal: &ColorLiteral) -> Range {
    Range {
        start: Position {
            line: literal.line,
            character: literal.span.start as u32,
        },
        end: Position {
            line: literal.line,
            character: literal.span.end as u32,
        },
    }
}

/// 判断两个区间是否重叠 (闭区间)
///
/// 颜色选择器会拿着上一次的区间连续请求: 文本被替换后区间未必与字面量严格相等,
/// 因此先按相等匹配, 退而按重叠匹配.
fn overlaps(span: &Range, other: Range) -> bool {
    span.start <= other.end && other.start <= span.end
}

#[cfg(test)]
mod tests {
    // This module is generated by AI.

    use webgal_language_core::resource::Config;

    use super::*;

    /// 构建单场景测试项目
    fn project(scene: &str) -> Project {
        let mut project = Project::new(Config::default());
        project
            .insert("scene/1.txt", || Ok(scene.to_string()))
            .unwrap();
        project
    }

    /// 场景中报出的颜色字面量: `(行号, 字面量文本)`
    fn literal_texts(scene: &str, project: &Project) -> Vec<(u32, String)> {
        let lines: Vec<_> = scene.lines().collect();
        document_color("1.txt", project)
            .unwrap()
            .into_iter()
            .map(|color| {
                let line = &lines[color.range.start.line as usize];
                let text =
                    &line[color.range.start.character as usize..color.range.end.character as usize];
                (color.range.start.line, text.to_string())
            })
            .collect()
    }

    /// 按 `[0, 1]` 分量构造 LSP 颜色
    fn lsp_color(red: u8, green: u8, blue: u8, alpha: f32) -> lsp_types::Color {
        lsp_types::Color {
            red: f32::from(red) / 255.,
            green: f32::from(green) / 255.,
            blue: f32::from(blue) / 255.,
            alpha,
        }
    }

    // -------- 收集 --------

    #[test]
    fn reports_argument_colors() {
        let scene =
            "intro:全屏文字 -fontColor=rgba(48, 135, 206, 1) -backgroundColor=rgba(0, 0, 0, 0.5);";
        let project = project(scene);

        assert_eq!(
            literal_texts(scene, &project),
            vec![
                (0, "rgba(48, 135, 206, 1)".to_string()),
                (0, "rgba(0, 0, 0, 0.5)".to_string()),
            ]
        );
    }

    #[test]
    fn reports_argument_color_components() {
        let scene = "intro:文字 -fontColor=rgba(48, 135, 206, 0.5);";
        let colors = document_color("1.txt", &project(scene)).unwrap();

        assert_eq!(colors.len(), 1);
        assert_eq!(colors[0].color, lsp_color(48, 135, 206, 0.5));
    }

    #[test]
    fn reports_argument_colors_on_each_line() {
        let scene = "intro:第一行 -fontColor=rgba(255, 0, 0, 1);\nwait:100;\nintro:第二行 -fontColor=rgba(0, 255, 0, 1);";
        let project = project(scene);

        assert_eq!(
            literal_texts(scene, &project),
            vec![
                (0, "rgba(255, 0, 0, 1)".to_string()),
                (2, "rgba(0, 255, 0, 1)".to_string()),
            ]
        );
    }

    #[test]
    fn ignores_argument_colors_in_unsupported_format() {
        // 语句参数只接受 `rgba(R, G, B, A)`: 别的写法是语法错误, 不该报色块
        let scene = "intro:文字 -fontColor=#FF8800 -backgroundColor=rgb(1, 2, 3);";
        let project = project(scene);

        assert!(literal_texts(scene, &project).is_empty());
        assert_eq!(
            document_color("1.txt", &project).unwrap(),
            Vec::<ColorInformation>::new()
        );
    }

    #[test]
    fn reports_style_colors_in_dialogue() {
        let scene = "角色A:你好 [世界](style=color:#FF8800);";
        let project = project(scene);

        assert_eq!(
            literal_texts(scene, &project),
            vec![(0, "#FF8800".to_string())]
        );
    }

    #[test]
    fn reports_style_colors_in_hex_with_alpha() {
        let scene = "角色A:[甲](style=color:#AABBCC)[乙](style=background-color:#11223344);";
        let project = project(scene);

        assert_eq!(
            literal_texts(scene, &project),
            vec![(0, "#AABBCC".to_string()), (0, "#11223344".to_string())]
        );
    }

    #[test]
    fn ignores_parenthesized_style_colors() {
        // 文本拓展语法在 `](` 后的第一个 `)` 处结束, 样式取值里写不出 `rgb()` / `rgba()`
        let scene = "角色A:[甲](style=color:rgb(1, 2, 3))[乙](style=color:rgba(1, 2, 3, 0.5));";
        let project = project(scene);

        assert!(literal_texts(scene, &project).is_empty());
    }

    #[test]
    fn reports_style_colors_after_variable_amount_of_text() {
        // 区间是 UTF-8 字节偏移: 中英文混排时不能按字符数算
        let scene = "角色A:[abc](style=color:#112233) -speaker=角色B;";
        let project = project(scene);

        assert_eq!(
            literal_texts(scene, &project),
            vec![(0, "#112233".to_string())]
        );
    }

    #[test]
    fn ignores_styles_without_color_value() {
        let scene = "角色A:[文字](style=size:large\\; ruby=ふりがな)[颜色](style=color:red);";
        let project = project(scene);

        // CSS 颜色名不在 `Color` 支持范围内
        assert!(literal_texts(scene, &project).is_empty());
    }

    #[test]
    fn ignores_colors_outside_statements() {
        // `applyStyle` 的内容是整段 CSS, 不是颜色字面量; 注释里的颜色同样不报
        let scene = "applyStyle:color:red->color:#FF8800;\n; 这里的 #FF8800 只是注释";
        let project = project(scene);

        assert!(literal_texts(scene, &project).is_empty());
    }

    #[test]
    fn ignores_unknown_scene() {
        let project = project("intro:文字 -fontColor=rgba(0, 0, 0, 1);");

        assert!(document_color("2.txt", &project).is_none());
    }

    // -------- 编辑建议 --------

    #[test]
    fn presents_argument_color_as_rgba() {
        let scene = "intro:文字 -fontColor=rgba(0, 0, 0, 1);";
        let project = project(scene);
        let range = document_color("1.txt", &project).unwrap()[0].range;

        let presentations =
            color_presentation("1.txt", range, lsp_color(255, 136, 0, 1.), &project).unwrap();

        assert_eq!(presentations.len(), 1);
        assert_eq!(presentations[0].label, "rgba(255, 136, 0, 1)");
        let edit = presentations[0].text_edit.clone().unwrap();
        assert_eq!(edit.range, range);
        assert_eq!(edit.new_text, "rgba(255, 136, 0, 1)");
    }

    #[test]
    fn presents_argument_color_with_rounded_alpha() {
        let scene = "intro:文字 -fontColor=rgba(0, 0, 0, 1);";
        let project = project(scene);
        let range = document_color("1.txt", &project).unwrap()[0].range;

        // 选择器给出的透明度是任意浮点数, 写进语句前保留两位小数
        let presentations =
            color_presentation("1.txt", range, lsp_color(255, 136, 0, 0.37254903), &project)
                .unwrap();

        assert_eq!(presentations[0].label, "rgba(255, 136, 0, 0.37)");
    }

    #[test]
    fn presents_opaque_style_color_as_hex() {
        let scene = "角色A:[文字](style=color:#000000);";
        let project = project(scene);
        let range = document_color("1.txt", &project).unwrap()[0].range;

        let presentations =
            color_presentation("1.txt", range, lsp_color(255, 136, 0, 1.), &project).unwrap();

        assert_eq!(presentations[0].label, "#FF8800");
        assert_eq!(
            presentations[0].text_edit.clone().unwrap().new_text,
            "#FF8800"
        );
    }

    #[test]
    fn presents_translucent_style_color_as_hex_with_alpha() {
        let scene = "角色A:[文字](style=color:#FF8800);";
        let project = project(scene);
        let range = document_color("1.txt", &project).unwrap()[0].range;

        let presentations =
            color_presentation("1.txt", range, lsp_color(255, 136, 0, 0.5), &project).unwrap();

        // 样式里写不出 `rgba()`, 透明度只能用 CSS Color 4 的 8 位 hex 表达
        assert_eq!(presentations[0].label, "#FF880080");
    }

    #[test]
    fn presentation_keeps_color_detected() {
        // 改完颜色后色块不能消失: 把建议写回文档, 该区间仍应被识别为颜色字面量
        for scene in [
            "intro:文字 -fontColor=rgba(0, 0, 0, 1);",
            "角色A:[文字](style=color:#000000);",
        ] {
            let original = project(scene);
            let range = document_color("1.txt", &original).unwrap()[0].range;
            let presentations =
                color_presentation("1.txt", range, lsp_color(255, 136, 0, 0.5), &original).unwrap();
            let edit = presentations[0].text_edit.clone().unwrap();

            let start = edit.range.start.character as usize;
            let end = edit.range.end.character as usize;
            let updated = format!("{}{}{}", &scene[..start], edit.new_text, &scene[end..]);

            let updated_project = project(&updated);
            assert_eq!(
                literal_texts(&updated, &updated_project),
                vec![(0, edit.new_text.clone())],
                "改动后的语句: {updated}"
            );
        }
    }

    #[test]
    fn presents_nothing_without_literal() {
        let scene = "intro:文字 -fontColor=rgba(0, 0, 0, 1);";
        let project = project(scene);

        // `intro` 语句类型处没有颜色字面量
        let range = Range {
            start: Position {
                line: 0,
                character: 0,
            },
            end: Position {
                line: 0,
                character: 5,
            },
        };

        assert!(color_presentation("1.txt", range, lsp_color(255, 136, 0, 1.), &project).is_none());
    }

    #[test]
    fn presentation_matches_shifted_range() {
        // 选择器连续请求时会带上"随编辑增长"的区间, 允许按重叠匹配
        let scene = "intro:文字 -fontColor=rgba(0, 0, 0, 1);";
        let project = project(scene);
        let range = document_color("1.txt", &project).unwrap()[0].range;
        let shifted = Range {
            start: range.start,
            end: Position {
                line: range.end.line,
                character: range.end.character + 1,
            },
        };

        assert!(
            color_presentation("1.txt", shifted, lsp_color(255, 136, 0, 1.), &project).is_some()
        );
    }
}
