//! 游戏配置

use std::{collections::HashSet, fmt};

use derive_more::{Deref, DerefMut, From, Into};

/// 配置条目, 可表示配置 / 注释 / 空行
#[derive(Debug, Clone, Default, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct ConfigItem {
    pub name: String,
    pub value: String,
    pub comment: String,
}

impl ConfigItem {
    /// 解析单条配置
    #[allow(clippy::should_implement_trait)]
    pub fn from_str(line: &str) -> Self {
        let line = line.trim();
        let (config, comment) = line.split_once(';').unwrap_or((line, ""));
        let (name, value) = config.split_once(':').unwrap_or((config, ""));
        Self {
            name: name.to_string(),
            value: value.trim_end().to_string(),
            comment: comment.trim_start().to_string(),
        }
    }

    pub fn is_config(&self) -> bool {
        !self.name.is_empty() && !self.value.is_empty()
    }

    pub fn is_comment(&self) -> bool {
        !self.is_config() && !self.comment.is_empty()
    }

    pub fn is_empty(&self) -> bool {
        !self.is_config() && self.comment.is_empty()
    }
}

impl fmt::Display for ConfigItem {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        if self.is_empty() {
            Ok(())
        } else if self.is_comment() {
            write!(f, "; {}", self.comment)
        } else if self.comment.is_empty() {
            write!(f, "{}:{};", self.name, self.value)
        } else {
            write!(f, "{}:{}; {}", self.name, self.value, self.comment)
        }
    }
}

/// 配置列表
#[derive(
    Debug, Clone, Default, PartialEq, Eq, PartialOrd, Ord, Hash, From, Into, Deref, DerefMut,
)]
pub struct Config(Vec<ConfigItem>);

impl Config {
    /// 解析配置列表
    ///
    /// # Behavior
    /// * 跨行配置的解析与 WebGAL 实际行为不符.
    #[allow(clippy::should_implement_trait)]
    pub fn from_str(config: &str) -> Self {
        Self(config.lines().map(ConfigItem::from_str).collect())
    }

    /// 查找指定配置
    ///
    /// 从后往前遍历查找, 配置及其下标.
    pub fn get_config(&self, name: &str) -> Option<(usize, &ConfigItem)> {
        self.iter()
            .enumerate()
            .rev()
            .find(|(_, item)| item.name == name)
    }

    /// 注释重复配置项, 并移除连续空行
    pub fn dedup(&mut self) {
        let mut last_is_empty = true; // 移除首个空行
        let mut configs = HashSet::new();

        self.0.retain_mut(|config| {
            let mut keep = true;

            if config.is_empty() {
                keep &= !last_is_empty;
                last_is_empty = true;
            } else {
                last_is_empty = false;
            }

            if config.is_config() && !configs.insert(config.name.to_string()) {
                *config = ConfigItem {
                    comment: format!("[duplicate] {config}"),
                    ..Default::default()
                }
            }

            keep
        });
    }
}

impl fmt::Display for Config {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        self.iter().try_for_each(|item| writeln!(f, "{item}"))
    }
}

#[cfg(test)]
mod tests {
    // This module is generated by AI.

    use super::*;

    // -------- ConfigItem 基础 --------

    #[test]
    fn config_item_parse_and_display() {
        let item = ConfigItem::from_str("key:value; comment");
        assert_eq!(item.name, "key");
        assert_eq!(item.value, "value");
        assert_eq!(item.comment, "comment");
        assert_eq!(item.to_string(), "key:value; comment");

        let item = ConfigItem::from_str("key:value");
        assert_eq!(item.name, "key");
        assert_eq!(item.value, "value");
        assert_eq!(item.comment, "");
        assert_eq!(item.to_string(), "key:value;");
    }

    #[test]
    fn config_item_flags() {
        let config = ConfigItem::from_str("a:b; c");
        assert!(config.is_config());
        assert!(!config.is_comment());
        assert!(!config.is_empty());

        let comment = ConfigItem::from_str("; just a comment");
        assert!(!comment.is_config());
        assert!(comment.is_comment());
        assert!(!comment.is_empty());

        let empty = ConfigItem::from_str("");
        assert!(!empty.is_config());
        assert!(!empty.is_comment());
        assert!(empty.is_empty());
    }

    // -------- Config 基础 --------

    #[test]
    fn config_from_str_parses_lines() {
        let input = "\
Game_name:test;
; comment line
Game_key:abc;
";
        let config = Config::from_str(input);
        assert_eq!(config.len(), 3);
        assert_eq!(config[0].name, "Game_name");
        assert_eq!(config[0].value, "test");
        assert_eq!(config[1].name, "");
        assert_eq!(config[1].comment, "comment line");
        assert_eq!(config[2].name, "Game_key");
        assert_eq!(config[2].value, "abc");
    }

    #[test]
    fn config_get_config_finds_last_occurrence() {
        let input = "\
key1:1;
key2:2;
key1:3;
";
        let config = Config::from_str(input);
        let (idx, item) = config.get_config("key1").unwrap();
        assert_eq!(idx, 2);
        assert_eq!(item.value, "3");
        assert!(config.get_config("missing").is_none());
    }

    // -------- dedup 功能 --------

    #[test]
    fn config_dedup_removes_duplicate_configs_to_comments() {
        let input = "\
key1:1;
key2:2;
key1:3;
key2:4;
";
        let mut config = Config::from_str(input);
        config.dedup();

        // 只有第一次出现的 key1 和 key2 保留为配置, 其余变为注释
        assert_eq!(config.len(), 4);
        assert!(config[0].is_config());
        assert_eq!(config[0].name, "key1");
        assert_eq!(config[0].value, "1");

        assert!(config[1].is_config());
        assert_eq!(config[1].name, "key2");
        assert_eq!(config[1].value, "2");

        // 重复项变成注释
        assert!(config[2].is_comment());
        assert_eq!(config[2].comment, "[duplicate] key1:3;");
        assert!(config[3].is_comment());
        assert_eq!(config[3].comment, "[duplicate] key2:4;");
    }

    #[test]
    fn config_dedup_removes_consecutive_empty_lines() {
        let input = "\
key1:1;

; comment

key2:2;
";
        let mut config = Config::from_str(input);
        config.dedup();

        // 空行: 初始 last_is_empty=true 会移除首行空行, 连续空行只保留一个
        // 预期: key1, 一个空行, 注释, 一个空行, key2 -> 5 项
        assert_eq!(config.len(), 5);
        assert!(config[0].is_config());
        assert!(config[1].is_empty());
        assert!(config[2].is_comment());
        assert!(config[3].is_empty());
        assert!(config[4].is_config());
    }

    #[test]
    fn config_dedup_removes_leading_and_trailing_empty_lines() {
        let input = "\n\nkey:value;\n\n";
        let mut config = Config::from_str(input);
        config.dedup();

        // 前导空行被移除, 尾随空行只保留一个
        assert_eq!(config.len(), 2);
        assert!(config[0].is_config());
        assert_eq!(config[0].value, "value");
        assert!(config[1].is_empty());
    }

    #[test]
    fn config_dedup_preserves_order() {
        let input = "\
z:1;
a:2;
m:3;
";
        let mut config = Config::from_str(input);
        config.dedup();
        let names: Vec<_> = config.iter().map(|i| i.name.as_str()).collect();
        assert_eq!(names, vec!["z", "a", "m"]);
    }

    // -------- 往返测试 --------

    #[test]
    fn config_display_roundtrip() {
        let input = "\
key1:value1; comment1
key2:value2;
; standalone comment

";
        let config = Config::from_str(input);
        let output = config.to_string();
        assert!(output.contains("key1:value1; comment1"));
        assert!(output.contains("key2:value2;"));
        assert!(output.contains("; standalone comment"));
        assert!(output.contains("\n\n"));
    }
}
