// This file is generated by AI.

import * as vscode from 'vscode';
import {
    Executable,
    LanguageClient,
    LanguageClientOptions,
    RequestType,
    ServerOptions
} from 'vscode-languageclient/node';

type ReadDirParams = { path: string };
type ReadDirResult = { name: string; isFile: boolean }[];
type ReadToStringParams = { path: string };
type ReadToStringResult = string;

const ReadDirRequest = new RequestType<ReadDirParams, ReadDirResult, void>('workspace/fs/readDir');
const ReadToStringRequest = new RequestType<ReadToStringParams, ReadToStringResult, void>('workspace/fs/readToString');

let client: LanguageClient;

export async function activate(context: vscode.ExtensionContext) {
    const traceOutputChannel = vscode.window.createOutputChannel('WebGAL Language Server trace');
    const command = process.env.SERVER_PATH || 'webgal-ls';
    const run: Executable = {
        command,
        options: {
            env: {
                ...process.env,
                RUST_LOG: 'info',
            },
        },
    };
    const serverOptions: ServerOptions = {
        run,
        debug: run,
    };
    const clientOptions: LanguageClientOptions = {
        documentSelector: [
            { scheme: 'file', language: 'webgal' }
        ],
        synchronize: {
            fileEvents: vscode.workspace.createFileSystemWatcher('**/config.txt')
        },
        traceOutputChannel,
    };
    client = new LanguageClient(
        'webgal-language-server',
        'WebGAL Language Server',
        serverOptions,
        clientOptions
    );

    const disposables = [
        client.onRequest(ReadDirRequest, async (params: ReadDirParams) => {
            const uri = vscode.Uri.parse(params.path, true);
            try {
                const entries = await vscode.workspace.fs.readDirectory(uri);
                return entries.map(([name, type]) => ({
                    name,
                    isFile: type === vscode.FileType.File,
                }));
            } catch (e) {
                throw new Error(`Failed to read directory: ${e}`);
            }
        }),

        client.onRequest(ReadToStringRequest, async (params: ReadToStringParams) => {
            const uri = vscode.Uri.parse(params.path, true);
            try {
                const data = await vscode.workspace.fs.readFile(uri);
                return Buffer.from(data).toString('utf8');
            } catch (e) {
                throw new Error(`Failed to read file: ${e}`);
            }
        }),
    ];

    context.subscriptions.push(...disposables);

    await client.start();
}

export function deactivate(): Thenable<void> | undefined {
    return client?.stop();
}
