// This file is generated by AI.

// 配音队列控制器 (模块级单例)。
//
// 设计要点:
// 1. **严格串行**。GSOV 后端是单进程单 worker 且持有全局 prompt 缓存, 并发请求会互相干扰,
//    因此这里保证同一时刻最多一个在途请求。优先级完全在客户端实现。
// 2. **三个队列**。立即队列 (测试 x4)、普通队列 (生成 x32) 各自按角色分组,
//    组内连续执行, 从而避免服务端频繁重载模型; 立即队列整体优先于普通队列。
// 3. **配对**。每条任务在发起时记录参数快照与语句身份哈希, 完成后按 id 回填对应历史项。

import type {
  AudioInfo,
  CacheEntry,
  Character,
  LaunchConfig,
  ModelCandidate,
  SayLine,
  TrimSuggestion,
  VoiceEvent,
} from '../commands/voice';
import { open as openDialog } from '@tauri-apps/plugin-dialog';
import {
  voiceApplyScene,
  voiceCreateCharacter,
  voiceDefaultLaunchConfig,
  voiceDropCache,
  voiceImportCharacter,
  voiceLaunch,
  voiceListCache,
  voiceListCharacters,
  voiceListModels,
  voiceParseScene,
  voiceProbe,
  voiceProbeAudio,
  voiceRealign,
  voiceRemoveCharacter,
  voiceSaveCharacter,
  voiceSetModel,
  voiceShutdown,
  voiceStatus,
  voiceSynthesize,
  voiceTakeLogs,
  voiceTrimSuggestion,
} from '../commands/voice';
import { fs } from '../lib/fs';
import { useAppStore } from '../state/store';
import { estimator, formatEta } from './estimate';
import { matchScene, type CharacterMatch } from './match';
import { charactersRoot, join } from './paths';
import { executionOrder, nextTask as nextQueuedTask, summarize as summarizeQueue } from './queue';
import { loadVoiceSettings, saveVoiceSettings, type VoiceSettings } from './settings';
import {
  GENERATE_SAMPLE_STEPS,
  createId,
  defaultParams,
  paramsKey,
  randomSeed,
  type HistoryEntry,
  type SceneVoiceState,
  type VoiceParams,
  type VoiceTask,
} from './types';

/** 就绪探测的上限与间隔 */
const PROBE_INTERVAL = 1500;
const PROBE_TIMEOUT = 4 * 60 * 1000;

/** 本地文件变更检查间隔 */
const DISK_CHECK_INTERVAL = 8000;

class VoiceController {
  private settings: VoiceSettings = loadVoiceSettings();
  private tasks: VoiceTask[] = [];
  private cards = new Map<string, SceneVoiceState>();
  private characters: Character[] = [];
  private referencePaths = new Map<string, string>();
  private queueRunning = false;

  private store() {
    return useAppStore.getState();
  }

  // -------- 设置 --------

  getSettings(): VoiceSettings {
    return this.settings;
  }

  updateSettings(patch: Partial<VoiceSettings>): void {
    this.settings = { ...this.settings, ...patch };
    saveVoiceSettings(this.settings);
    this.emit();
  }

  // -------- 角色库 --------

  getCharacters(): Character[] {
    return this.characters;
  }

  setCharacters(characters: Character[]): void {
    this.characters = characters;
    this.store().setVoiceCharacters(characters);
    // 角色信息变化会改变匹配结果, 重算所有卡片的归属
    for (const card of this.cards.values()) this.rematch(card);
    void this.primeReferencePaths();
  }

  characterById(id: string | null): Character | null {
    if (!id) return null;
    return this.characters.find((character) => character.id === id) ?? null;
  }

  // -------- 卡片 --------

  getCard(id: string): SceneVoiceState | null {
    return this.cards.get(id) ?? null;
  }

  /** 打开 (或重新聚焦) 一个场景的配音卡: 解析对话并按内容哈希回填历史 */
  async openCard(id: string, scenePath: string, content: string, diskHash: string): Promise<SceneVoiceState> {
    const dialogues = await this.parse(content);
    const previous = this.cards.get(id);

    const card: SceneVoiceState = {
      id,
      scenePath,
      dialogues,
      contentVersion: 1,
      history: previous?.history ?? [],
      selectedHistoryId: previous?.selectedHistoryId ?? null,
      cursorLine: previous?.cursorLine ?? null,
      diskHash,
      matches: new Map(),
    };

    this.cards.set(id, card);
    this.rematch(card);
    this.syncCard(card);
    return card;
  }

  closeCard(id: string): void {
    this.cards.delete(id);
    this.syncCardStore();
  }

  /** 关闭项目时丢弃全部场景卡与队列 (角色库属于全局, 不受影响) */
  resetProject(): void {
    this.cards.clear();
    this.tasks = [];
    this.queueRunning = false;
    const store = this.store();
    store.setSceneVoiceEditors(new Map());
    store.setVoiceCache([]);
    this.emit();
  }

  /** 场景内容变化: 重新解析并保留历史 (对齐由 `realignCard` 负责) */
  async refreshCard(id: string, content: string, contentVersion = 0): Promise<void> {
    const card = this.cards.get(id);
    if (!card) return;
    card.dialogues = await this.parse(content);
    card.contentVersion = contentVersion;
    this.rematch(card);
    this.syncCard(card);
  }

  setCursorLine(id: string, line: number | null): void {
    const card = this.cards.get(id);
    if (!card) return;
    card.cursorLine = line;
    this.syncCard(card);
  }

  /** 依据当前角色列表重算全场景的角色归属 */
  rematch(card: SceneVoiceState): void {
    const overrides = this.store().voiceAssignments[card.scenePath] ?? {};
    const matches = matchScene(card.dialogues, this.characters, overrides);
    card.matches = matches;
  }

  matchesOf(id: string): Map<number, CharacterMatch> | null {
    return this.cards.get(id)?.matches ?? null;
  }

  /** 记录用户的手动归属 (场景级覆盖), 并对后续旁白生效 */
  assignCharacter(scenePath: string, speaker: string | null, characterId: string | null): void {
    const store = this.store();
    const map = { ...(store.voiceAssignments[scenePath] ?? {}) };
    const key = speaker ?? '';
    if (characterId) map[key] = characterId;
    else delete map[key];
    store.setVoiceAssignment(scenePath, map);
    for (const card of this.cards.values()) {
      if (card.scenePath === scenePath) {
        this.rematch(card);
        this.syncCard(card);
      }
    }
  }

  selectedHistory(id: string): HistoryEntry | null {
    const card = this.cards.get(id);
    if (!card?.selectedHistoryId) return null;
    return card.history.find((entry) => entry.id === card.selectedHistoryId) ?? null;
  }

  selectHistory(id: string, entryId: string | null): void {
    const card = this.cards.get(id);
    if (!card) return;
    card.selectedHistoryId = entryId;
    this.syncCard(card);
  }

  // -------- 参数 --------

  /** 当前语句的配音参数: 选中历史项则回填其参数, 否则按角色与默认配置构造 */
  currentParams(id: string): VoiceParams | null {
    const card = this.cards.get(id);
    if (!card || card.cursorLine === null) return null;
    const line = card.dialogues.find((dialogue) => dialogue.line === card.cursorLine);
    if (!line) return null;

    const selected = this.selectedHistory(id);
    const defaults = this.settings.defaults;
    const match = card.matches?.get(line.line);
    const character = this.characterById(selected?.characterId ?? match?.characterId ?? null);

    const base = defaultParams(character, line.text);
    return {
      ...base,
      language: selected?.params.language ?? defaults.language,
      textSplitMethod: selected?.params.textSplitMethod ?? defaults.textSplitMethod,
      temperature: selected?.params.temperature ?? defaults.temperature,
      speedFactor: selected?.params.speedFactor ?? defaults.speedFactor,
      topK: selected?.params.topK ?? defaults.topK,
      topP: selected?.params.topP ?? defaults.topP,
      repetitionPenalty: selected?.params.repetitionPenalty ?? defaults.repetitionPenalty,
      sampleSteps: selected?.params.sampleSteps ?? GENERATE_SAMPLE_STEPS,
      // 文本始终跟随场景 (历史项可能属于改过的文本)
      text: line.text,
    };
  }

  /** 找一个与给定参数完全一致的历史项 (用于判断"是否已是新配置") */
  findMatchingHistory(id: string, params: VoiceParams): HistoryEntry | null {
    const card = this.cards.get(id);
    if (!card) return null;
    const key = paramsKey(params);
    return card.history.find((entry) => paramsKey(entry.params) === key && entry.status !== 'failed') ?? null;
  }

  // -------- 入队 --------

  enqueue(id: string, kind: 'test' | 'generate', params: VoiceParams): VoiceTask | null {
    const card = this.cards.get(id);
    if (!card || card.cursorLine === null) return null;
    const line = card.dialogues.find((dialogue) => dialogue.line === card.cursorLine);
    if (!line) return null;

    const character = this.characterById(params.characterId);
    const reference = character?.references.find((item) => item.hash === params.referenceHash) ?? null;
    const snapshot: VoiceParams = {
      ...params,
      sampleSteps: kind === 'test' ? this.settings.testSampleSteps : params.sampleSteps,
      text: line.text,
    };

    const task: VoiceTask = {
      id: createId('voice-task'),
      kind,
      status: 'pending',
      cardId: id,
      scenePath: card.scenePath,
      line: line.line,
      lineHash: line.hash,
      speaker: line.speaker,
      text: line.text,
      characterId: character?.id ?? null,
      characterName: character?.name ?? '未指定角色',
      params: snapshot,
      createdAt: Date.now(),
    };

    // 历史项与任务一一对应: 任务完成后回填
    const entry: HistoryEntry = {
      id: task.id,
      kind,
      status: 'pending',
      line: line.line,
      speaker: line.speaker,
      text: line.text,
      characterId: task.characterId,
      characterName: task.characterName,
      params: snapshot,
      createdAt: task.createdAt,
      applied: false,
    };
    card.history = [entry, ...card.history];
    card.selectedHistoryId = entry.id;

    this.tasks.push(task);
    this.syncCard(card);
    this.emit();

    // 缺少必要输入时直接失败, 给出可读的提示
    if (!character) {
      this.failTask(task.id, '未选择角色');
    } else if (!reference) {
      this.failTask(task.id, '该角色没有可用的参考音频');
    } else if (!snapshot.text.trim()) {
      this.failTask(task.id, '对话内容为空');
    } else {
      void this.pump();
    }
    return task;
  }

  /** 取消一个未完成的任务 */
  cancel(taskId: string): void {
    const task = this.tasks.find((item) => item.id === taskId);
    if (!task || task.status !== 'pending') return;
    task.status = 'canceled';
    this.updateHistory(task);
    this.emit();
  }

  private failTask(taskId: string, message: string): void {
    const task = this.tasks.find((item) => item.id === taskId);
    if (!task) return;
    task.status = 'failed';
    task.error = message;
    this.updateHistory(task);
    this.emit();
  }

  // -------- 调度 --------

  /** 取下一个待执行任务: 立即队列整体优先, 队列内按角色分组连续执行 */
  private nextTask(): VoiceTask | null {
    return nextQueuedTask(this.tasks);
  }

  private async pump(): Promise<void> {
    if (this.queueRunning) return;
    this.queueRunning = true;
    try {
      for (;;) {
        const task = this.nextTask();
        if (!task) break;
        await this.runTask(task);
      }
    } finally {
      this.queueRunning = false;
      this.emit();
    }
  }

  private async runTask(task: VoiceTask): Promise<void> {
    const character = this.characterById(task.characterId);
    const reference = character?.references.find((item) => item.hash === task.params.referenceHash);
    if (!character || !reference) {
      task.status = 'failed';
      task.error = '角色或参考音频已不存在';
      this.updateHistory(task);
      return;
    }

    const refPath = await this.referencePath(character.id, reference.file);
    task.status = 'running';
    task.startedAt = Date.now();
    this.updateHistory(task);
    this.emit();

    try {
      const result = await voiceSynthesize({
        text: task.params.text,
        textLang: task.params.language,
        refAudioPath: refPath,
        promptText: reference.text,
        promptLang: reference.language,
        sampleSteps: task.params.sampleSteps,
        temperature: task.params.temperature,
        speedFactor: task.params.speedFactor,
        topK: task.params.topK,
        topP: task.params.topP,
        repetitionPenalty: task.params.repetitionPenalty,
        textSplitMethod: task.params.textSplitMethod,
        seed: task.params.seed,
      });

      task.status = 'done';
      task.audioHash = result.entry.hash;
      task.audioPath = result.entry.path;
      task.duration = result.duration;
      task.finishedAt = Date.now();
      estimator.observe(task.kind, task.params.text.length, task.finishedAt - (task.startedAt ?? task.finishedAt));
      this.store().upsertVoiceCache(result.entry);
    } catch (error) {
      task.status = 'failed';
      task.error = error instanceof Error ? error.message : String(error);
      task.finishedAt = Date.now();
    }

    this.updateHistory(task);
    this.emit();
  }

  private updateHistory(task: VoiceTask): void {
    const card = this.cards.get(task.cardId);
    if (!card) return;
    const entry = card.history.find((item) => item.id === task.id);
    if (!entry) return;
    entry.status = task.status;
    entry.audioHash = task.audioHash;
    entry.audioPath = task.audioPath;
    entry.duration = task.duration;
    entry.error = task.error;
    entry.finishedAt = task.finishedAt;
    this.syncCard(card);
  }

  // -------- 应用 / 移除 --------

  /**
   * 把已生成的音频应用到当前语句: 写入 `game/vocal/<角色 id>/<哈希>.wav` 并改写 `-vocal=`。
   *
   * 行号与内容在写回前会与解析时快照校验, 场景若已被改动则中止 (避免改错行)。
   */
  async apply(id: string, entryId: string): Promise<void> {
    const card = this.cards.get(id);
    if (!card) return;
    const entry = card.history.find((item) => item.id === entryId);
    if (!entry?.audioHash || !entry.audioPath) throw new Error('该记录还没有可用的音频');
    if (entry.line === null) throw new Error('该记录尚未对齐到任何语句, 请先从历史中删除');

    const project = this.store().projectPath;
    if (!project) throw new Error('尚未打开项目');

    const dialogue = card.dialogues.find((item) => item.line === entry.line);
    if (!dialogue) throw new Error('该语句已不在场景中, 请重新对齐历史');
    const targetLine = entry.line;

    const character = this.characterById(entry.characterId);
    const dir = character?.id || 'narration';
    const fileName = `${entry.audioHash}.wav`;
    const vocalRoot = `${project.replace(/[\\/]+$/, '')}\\game\\vocal`;
    const targetDir = `${vocalRoot}\\${dir}`;
    await fs.mkdir(targetDir);
    await fs.rename(entry.audioPath, `${targetDir}\\${fileName}`);

    // 改写场景: 用完整的场景内容一次写回, 避免多处编辑产生中间态
    const doc = this.store().documents.find((item) => item.path === card.scenePath);
    const content = doc?.content ?? (await fs.readText(card.scenePath));
    const rewritten = await voiceApplyScene(content, [{ line: targetLine, expect: null, vocal: `${dir}/${fileName}` }]);
    this.store().updateDocument(card.scenePath, { content: rewritten, dirty: true });
    if (this.store().settings.autoSave) {
      await fs.writeText(card.scenePath, rewritten);
      this.store().updateDocument(card.scenePath, { content: rewritten, dirty: false });
    }

    entry.applied = true;
    entry.audioPath = `${targetDir}\\${fileName}`;
    await this.refreshCard(id, rewritten);
    this.syncCard(card);
    this.emit();
  }

  /** 移除当前语句的配音引用 (不动历史记录) */
  async remove(id: string): Promise<void> {
    const card = this.cards.get(id);
    if (!card || card.cursorLine === null) return;
    const line = card.dialogues.find((dialogue) => dialogue.line === card.cursorLine);
    if (!line) return;

    const doc = this.store().documents.find((item) => item.path === card.scenePath);
    const content = doc?.content ?? (await fs.readText(card.scenePath));
    const rewritten = await voiceApplyScene(content, [{ line: line.line, expect: null, vocal: null }]);
    this.store().updateDocument(card.scenePath, { content: rewritten, dirty: true });
    if (this.store().settings.autoSave) {
      await fs.writeText(card.scenePath, rewritten);
      this.store().updateDocument(card.scenePath, { content: rewritten, dirty: false });
    }
    for (const item of card.history) {
      if (item.line === line.line) item.applied = false;
    }
    await this.refreshCard(id, rewritten);
    this.emit();
  }

  /** 删除一条历史记录 (缓存音频保留, 由缓存清理统一管理) */
  dropHistory(id: string, entryId: string): void {
    const card = this.cards.get(id);
    if (!card) return;
    card.history = card.history.filter((entry) => entry.id !== entryId);
    if (card.selectedHistoryId === entryId) card.selectedHistoryId = null;
    this.syncCard(card);
    this.emit();
  }

  dropAllHistory(id: string, kind?: 'test' | 'generate'): void {
    const card = this.cards.get(id);
    if (!card) return;
    card.history = kind ? card.history.filter((entry) => entry.kind !== kind) : [];
    card.selectedHistoryId = null;
    this.syncCard(card);
    this.emit();
  }

  // -------- 场景变更裁决与历史对齐 --------

  /** 记录打开卡片时的磁盘内容哈希 */
  setDiskHash(id: string, hash: string): void {
    const card = this.cards.get(id);
    if (card) card.diskHash = hash;
  }

  /**
   * 重新对齐历史到当前对话列表。
   *
   * 调用时机必须在"用户已裁决本地变更"之后, 否则裁决会再次改变行号使对齐失效。
   */
  async realignCard(id: string): Promise<void> {
    const card = this.cards.get(id);
    if (!card || card.history.length === 0) return;
    const report = await voiceRealign(
      card.history.map((entry) => ({ id: entry.id, speaker: entry.speaker, text: entry.text })),
      card.dialogues.map((dialogue) => ({
        speaker: dialogue.speaker,
        text: dialogue.text,
        index: dialogue.line,
      }))
    );
    const byId = new Map(report.alignments.map((item) => [item.id, item]));
    for (const entry of card.history) {
      const alignment = byId.get(entry.id);
      entry.line = alignment?.index ?? null;
      entry.alignment = alignment?.kind;
      if (entry.line !== null) {
        const dialogue = card.dialogues.find((item) => item.line === entry.line);
        if (dialogue) {
          entry.speaker = dialogue.speaker;
          entry.text = dialogue.text;
        }
      }
    }
    this.syncCard(card);
    this.emit();
  }

  alignmentSummary(id: string): { total: number; unmatched: number } | null {
    const card = this.cards.get(id);
    if (!card) return null;
    return {
      total: card.history.length,
      unmatched: card.history.filter((entry) => entry.line === null).length,
    };
  }

  // -------- GSOV 进程 --------

  private probeTimer: ReturnType<typeof setInterval> | null = null;

  /** 启动 GSOV: 拉起进程 -> 轮询探针直到就绪 */
  async startGsv(config?: LaunchConfig): Promise<void> {
    const launch = config ?? this.settings.launch;
    if (!launch) throw new Error('尚未配置 GPT-SoVITS 整合包路径');
    if (config) this.updateSettings({ launch: config });

    const store = this.store();
    estimator.reset();
    store.setVoiceLogs([]);
    store.setVoiceStatus('starting', null);

    await voiceLaunch(launch, (event: VoiceEvent) => this.consumeEvent(event));

    const deadline = Date.now() + PROBE_TIMEOUT;
    if (this.probeTimer) clearInterval(this.probeTimer);

    await new Promise<void>((resolve, reject) => {
      this.probeTimer = setInterval(() => {
        void (async () => {
          if (Date.now() > deadline) {
            if (this.probeTimer) clearInterval(this.probeTimer);
            this.probeTimer = null;
            this.store().setVoiceStatus('error', '启动超时, 请查看日志');
            reject(new Error('GSOV 启动超时'));
            return;
          }
          try {
            const ready = await voiceProbe(launch.host, launch.port);
            if (ready) {
              if (this.probeTimer) clearInterval(this.probeTimer);
              this.probeTimer = null;
              this.store().setVoiceStatus('ready', null);
              resolve();
            }
          } catch (error) {
            if (this.probeTimer) clearInterval(this.probeTimer);
            this.probeTimer = null;
            const message = error instanceof Error ? error.message : String(error);
            this.store().setVoiceStatus('error', message);
            reject(new Error(message));
          }
        })();
      }, PROBE_INTERVAL);
    });
  }

  async stopGsv(): Promise<void> {
    if (this.probeTimer) {
      clearInterval(this.probeTimer);
      this.probeTimer = null;
    }
    await voiceShutdown();
    estimator.reset();
    this.store().setVoiceStatus('stopped', null);
  }

  /** 应用启动时同步一次状态 (进程可能已在运行) */
  async initialize(): Promise<void> {
    await this.syncStatus();
    try {
      const characters = await voiceListCharacters();
      this.setCharacters(characters);
    } catch {
      // 角色库不可用时保持空列表
    }
    await this.refreshCache();
  }

  /** 重新读取配音缓存列表 */
  async refreshCache(): Promise<void> {
    try {
      const entries = await voiceListCache();
      this.store().setVoiceCache(entries);
    } catch {
      // 缓存目录尚未建立时忽略
    }
  }

  /** 应用启动时同步一次状态 (进程可能已在运行) */
  async syncStatus(): Promise<void> {
    try {
      const status = await voiceStatus();
      this.store().setVoiceStatus(status.status, status.detail);
      const logs = await voiceTakeLogs();
      if (logs.length > 0) this.store().setVoiceLogs(this.store().voiceLogs.concat(logs));
    } catch {
      // 后端未就绪时忽略
    }
  }

  private consumeEvent(event: VoiceEvent): void {
    if (event.type === 'log') {
      this.store().appendVoiceLog(event.line);
    } else {
      this.store().setVoiceStatus(event.status, event.detail);
    }
  }

  // -------- 辅助 --------

  private async parse(content: string): Promise<SayLine[]> {
    return voiceParseScene(content);
  }

  private async referencePath(characterId: string, file: string): Promise<string> {
    return join(await charactersRoot(), characterId, file);
  }

  /** 试听等场景使用的参考音频绝对路径 */
  referencePathFor(characterId: string, file: string): string {
    return this.referencePaths.get(`${characterId}/${file}`) ?? '';
  }

  /** 预热参考音频路径 (角色列表加载后调用; 避免渲染时 await) */
  async primeReferencePaths(): Promise<void> {
    const root = await charactersRoot();
    this.referencePaths.clear();
    for (const character of this.characters) {
      for (const reference of character.references) {
        const key = `${character.id}/${reference.file}`;
        this.referencePaths.set(key, join(root, character.id, reference.file));
      }
    }
    this.emit();
  }

  /** 探测音频属性 */
  async inspectAudio(path: string): Promise<AudioInfo> {
    return voiceProbeAudio(path);
  }

  /** 裁剪建议 (波形对话框用) */
  async trimSuggestion(path: string): Promise<TrimSuggestion> {
    return voiceTrimSuggestion(path);
  }

  /** 探测整合包目录并生成默认启动配置 */
  async detect(root: string): Promise<LaunchConfig> {
    return voiceDefaultLaunchConfig(root);
  }

  /** 扫描整合包内的 v4 权重, 返回可配对的模型候选 */
  async listModels(): Promise<ModelCandidate[]> {
    const root = this.settings.launch?.root;
    if (!root) return [];
    try {
      return await voiceListModels(root);
    } catch {
      return [];
    }
  }

  /**
   * 显式切换服务端权重。
   *
   * 刻意只由用户主动触发: 服务端切换权重会重载模型 (SoVITS v4 需重载底模并合并 LoRA)
   * 并落盘 `tts_infer.yaml`, 属于高代价且带副作用的操作。
   * 队列通过按角色分组让同角色任务连续执行, 正常情况下无需切换。
   */
  async switchModel(gptWeights: string | null, sovitsWeights: string | null): Promise<void> {
    if (!gptWeights && !sovitsWeights) throw new Error('请先填写至少一项权重路径');
    await voiceSetModel(gptWeights, sovitsWeights);
  }

  /** 清理已完成/已取消的任务记录 (历史记录不受影响) */
  clearFinishedTasks(): void {
    this.tasks = this.tasks.filter((task) => task.status === 'pending' || task.status === 'running');
    this.emit();
  }

  /** 保存角色并同步到全局列表 */
  async persistCharacter(character: Character): Promise<Character> {
    const saved = await voiceSaveCharacter(character);
    const rest = this.characters.filter((item) => item.id !== saved.id);
    this.setCharacters([...rest, saved]);
    return saved;
  }

  /** 新建角色 */
  async createCharacter(name: string, aliases: string[], description: string): Promise<Character> {
    const created = await voiceCreateCharacter({ name, aliases, description, language: 'auto' });
    this.setCharacters([...this.characters, created]);
    return created;
  }

  async deleteCharacter(id: string): Promise<void> {
    await voiceRemoveCharacter(id);
    this.setCharacters(this.characters.filter((item) => item.id !== id));
  }

  async importCharacter(): Promise<Character | null> {
    const selected = await openDialog({
      multiple: false,
      filters: [{ name: '角色配置', extensions: ['zip'] }],
    });
    if (typeof selected !== 'string') return null;
    const imported = await voiceImportCharacter(selected);
    this.setCharacters([...this.characters, imported]);
    return imported;
  }

  // -------- 缓存清理 --------

  async clearCache(hashes: string[]): Promise<void> {
    if (hashes.length === 0) return;
    await voiceDropCache(hashes);
    const store = this.store();
    store.setVoiceCache(store.voiceCache.filter((entry) => !hashes.includes(entry.hash)));
  }
  cacheEntry(hash: string): CacheEntry | null {
    return this.store().voiceCache.find((entry) => entry.hash === hash) ?? null;
  }

  // -------- 通知 --------

  /** 队列概览 (供 UI 展示) */
  queueSummary(): {
    pending: number;
    pendingTest: number;
    pendingGenerate: number;
    running: number;
    etaMillis: number;
    etaText: string;
    /** 立即队列对生成任务的预计延后量 */
    immediateDelayMillis: number;
  } {
    const summary = summarizeQueue(this.tasks, (tasks) => estimator.estimateAll(tasks));
    const ordered = executionOrder(this.tasks.filter((task) => task.status === 'pending'));
    const running = this.tasks.filter((task) => task.status === 'running');
    const eta = estimator.estimateAll([...running, ...ordered]);
    return {
      ...summary,
      etaMillis: eta,
      etaText: formatEta(eta),
      immediateDelayMillis: summary.delayMillis,
    };
  }

  allTasks(): VoiceTask[] {
    return this.tasks;
  }

  /** 用户在语句面板改动参数 -> 视为新配置 (旧历史项不受影响) */
  isNewConfiguration(id: string, params: VoiceParams): boolean {
    return this.findMatchingHistory(id, params) === null;
  }

  /** 在已有历史项的配置上创建一个新任务 (不修改历史项本身) */
  retryFromHistory(cardId: string, entryId: string): VoiceTask | null {
    const card = this.cards.get(cardId);
    if (!card) return null;
    const entry = card.history.find((item) => item.id === entryId);
    if (!entry || entry.line === null) return null;
    const line = card.dialogues.find((dialogue) => dialogue.line === entry.line);
    if (!line) return null;

    // 复用原参数, 但文本跟随当前场景内容
    return this.enqueue(cardId, entry.kind, { ...entry.params, text: line.text });
  }

  /** 该场景当前是否处于配音编辑模式 */
  isSceneInVoiceMode(path: string): boolean {
    return this.store().voiceModePaths.includes(path);
  }

  /** 关闭场景卡时的未完成检查 */
  hasUnfinished(id: string): boolean {
    const card = this.cards.get(id);
    if (!card) return false;
    return card.history.some((entry) => entry.status === 'pending' || entry.status === 'running');
  }

  /** 磁盘内容是否与打开时不同 */
  async checkDiskChange(id: string): Promise<boolean> {
    const card = this.cards.get(id);
    if (!card) return false;
    try {
      const content = await fs.readTextLossy(card.scenePath);
      return hashText(normalizeEol(content)) !== card.diskHash;
    } catch {
      return false;
    }
  }

  private syncCard(card: SceneVoiceState): void {
    this.store().setSceneVoiceEditors(new Map(this.cards));
    void card;
  }

  private syncCardStore(): void {
    this.store().setSceneVoiceEditors(new Map(this.cards));
  }

  private emit(): void {
    const store = this.store();
    store.setVoiceTick();
    // 配音工作台选项卡角标: 待处理 + 运行中
    const active = this.tasks.filter((task) => task.status === 'pending' || task.status === 'running').length;
    if (store.voiceQueuePending !== active) store.setVoiceQueuePending(active);
  }
}

/** 内容哈希 (与磁盘比对用, 无需密码学强度) */
export function hashText(text: string): string {
  let hash = 0x811c9dc5;
  for (let index = 0; index < text.length; index++) {
    hash ^= text.charCodeAt(index);
    hash = Math.imul(hash, 0x01000193);
  }
  return (hash >>> 0).toString(16);
}

export function normalizeEol(text: string): string {
  return text.replace(/\r\n/g, '\n');
}

/** 生成默认参数 (供 UI 直接使用) */
export function makeDefaultParams(text: string): VoiceParams {
  return { ...defaultParams(null, text), seed: randomSeed() };
}

export const DISK_CHECK_MS = DISK_CHECK_INTERVAL;

/** 会话级单例 */
export const voiceController = new VoiceController();
