// This file is generated by AI.

// 配音任务耗时估算。
//
// 服务端在推理完成前不提供任何进度, 因此进度只能靠**估算 + 实测校准**:
// 用已完成的任务回归出「固定开销 + 每字符耗时」两个系数, 再据此给出剩余时间。
// 测试 (x4) 与正式生成 (x32) 的耗时量级相差数倍, 必须分别校准。

/** 最小样本数: 少于该数量时沿用先验系数 */
const MIN_SAMPLES = 3;

/** 先验系数 (毫秒): 由 GPT-SoVITS v4 在 CPU 上的实测结果粗略拟合 */
interface Coefficients {
  /** 固定开销 (参考音频处理 / prompt 特征 / 调度) */
  constant: number;
  /** 每字符耗时 */
  perChar: number;
}

const PRIOR: Record<'test' | 'generate', Coefficients> = {
  // x4: 短句约 20s, 27 字约 60s
  test: { constant: 12000, perChar: 1800 },
  // x32: 短句约 60s, 27 字约 280s
  generate: { constant: 30000, perChar: 9000 },
};

/** 一个样本 */
export interface Sample {
  chars: number;
  millis: number;
}

/** 估算所需的最小任务描述 */
export interface EstimateTask {
  kind: 'test' | 'generate';
  params: { text: string };
}

/** 估算器 (每个会话一份; 不持久化, 因为换机器后系数完全不同) */
export class DurationEstimator {
  private samples: Record<'test' | 'generate', Sample[]> = { test: [], generate: [] };

  /** 记录一次真实耗时 */
  observe(kind: 'test' | 'generate', chars: number, millis: number): void {
    if (millis <= 0 || chars < 0) return;
    const bucket = this.samples[kind];
    bucket.push({ chars, millis });
    // 只保留最近的样本, 让系数跟随当前机器/模型状态
    if (bucket.length > 40) bucket.shift();
  }

  /** 当前系数 (样本足够时用最小二乘拟合 `millis = a + b * chars`) */
  coefficients(kind: 'test' | 'generate'): Coefficients {
    const bucket = this.samples[kind];
    if (bucket.length < MIN_SAMPLES) return { ...PRIOR[kind] };

    const n = bucket.length;
    const meanX = bucket.reduce((sum, sample) => sum + sample.chars, 0) / n;
    const meanY = bucket.reduce((sum, sample) => sum + sample.millis, 0) / n;
    const variance = bucket.reduce((sum, sample) => sum + (sample.chars - meanX) ** 2, 0);

    // 字符数几乎一致时无法回归出斜率, 退回先验斜率并只校准截距
    if (variance < 1e-6) {
      const prior = PRIOR[kind];
      return {
        constant: Math.max(1000, meanY - prior.perChar * meanX),
        perChar: prior.perChar,
      };
    }

    const covariance = bucket.reduce((sum, sample) => sum + (sample.chars - meanX) * (sample.millis - meanY), 0);
    const perChar = Math.max(50, covariance / variance);
    const constant = Math.max(1000, meanY - perChar * meanX);
    return { constant, perChar };
  }

  /** 估算单个任务耗时 (毫秒) */
  estimate(kind: 'test' | 'generate', chars: number): number {
    const { constant, perChar } = this.coefficients(kind);
    return constant + perChar * chars;
  }

  /** 估算一组任务的总耗时 (毫秒) */
  estimateAll(tasks: EstimateTask[]): number {
    return tasks.reduce((sum, task) => sum + this.estimate(task.kind, task.params.text.length), 0);
  }

  /** 清空校准数据 (切换机器 / 重启服务后调用) */
  reset(): void {
    this.samples = { test: [], generate: [] };
  }

  /** 供 UI 展示的样本量 */
  sampleCount(kind: 'test' | 'generate'): number {
    return this.samples[kind].length;
  }
}

/** 会话级单例 */
export const estimator = new DurationEstimator();

/** 把毫秒格式化为紧凑的中文时长 */
export function formatDuration(millis: number): string {
  if (!Number.isFinite(millis) || millis <= 0) return '0s';
  const seconds = Math.round(millis / 1000);
  if (seconds < 60) return `${seconds}s`;
  const minutes = Math.floor(seconds / 60);
  const rest = seconds % 60;
  if (minutes < 60) return rest === 0 ? `${minutes}m` : `${minutes}m${rest}s`;
  const hours = Math.floor(minutes / 60);
  return `${hours}h${minutes % 60}m`;
}

/** 剩余时间的粗粒度提示 (队列较长时以分钟为单位) */
export function formatEta(millis: number): string {
  if (!Number.isFinite(millis) || millis <= 0) return '—';
  if (millis < 60_000) return `~${Math.max(1, Math.round(millis / 1000))} 秒`;
  return `~${formatDuration(millis)}`;
}
