// This file is generated by AI.

// 配音界面的 store 订阅钩子。
//
// 抽出来的原因: 场景配音卡的状态**在控制器里被就地修改** (`card.history`、每个历史项
// 的字段), 只有 `setSceneVoiceEditors` 会换掉 Map 的身份。因此:
//
// * 想随"选中了哪条历史记录 / 某条任务完成"重渲染, 就必须订阅**整张 Map** ——
//   只订阅 `map.get(id)` 拿到的是同一个对象引用, zustand 会判定"没变化"直接跳过;
// * `voiceTick` 覆盖那些只 `emit()` 而不 `syncCard()` 的时刻 (例如队列跑空)。

import { useAppStore } from '../state/store';
import type { SceneVoiceState } from './types';

/** 队列变化令牌 (每次 `emit()` 递增) */
export function useVoiceTick(): number {
  return useAppStore((state) => state.voiceTick);
}

/** 一张场景配音卡; 卡片不存在时返回 null */
export function useVoiceCard(cardId: string): SceneVoiceState | null {
  const cards = useAppStore((state) => state.sceneVoiceEditors);
  return cards.get(cardId) ?? null;
}
