// This file is generated by AI.

// 数值参数输入框。
//
// 合成参数一律用数字输入框而不是滑杆:
// * 滑杆**看不到当前值**, 也没法精确输入 —— 而温度 1.05 与 1.10 的差别是听得出来的;
// * 滑杆占一整行, 数字框可以并排, 面板因此能在固定高度里放下全部参数。
//
// 加减用的是 `<input type="number"> 的**原生步进器**(鼠标悬停时出现在输入框右内侧),
// 与设置里的字号输入框完全一致: 自己在一旁摆 − / + 两个按钮既占宽度又与其它输入框
// 长得不一样。步长交给 `step`, 边界交给 `min` / `max`, 因此原生步进器本身就夹在范围内。
//
// 输入过程中不校验 (允许暂时为空、暂时越界), 失焦或回车时才夹到 `tick` 的范围内,
// 因此不会出现"删到一半就被弹回原值"。

import { Input } from '@fluentui/react-components';
import { useEffect, useState } from 'react';

export interface NumberTick {
  min: number;
  max: number;
  step: number;
  default: number;
}

interface Props {
  value: number;
  tick: NumberTick;
  /** 只接受整数 (topK / 种子) */
  integer?: boolean;
  disabled?: boolean;
  onCommit: (value: number) => void;
}

/** 小数位: 由步长决定 (0.05 -> 两位), 整数参数为 0 位 */
function decimalsOf(tick: NumberTick, integer: boolean | undefined): number {
  if (integer) return 0;
  const text = String(tick.step);
  const dot = text.indexOf('.');
  return dot < 0 ? 0 : text.length - dot - 1;
}

export function NumberInput({ value, tick, integer, disabled, onCommit }: Props) {
  const decimals = decimalsOf(tick, integer);
  const [text, setText] = useState(value.toFixed(decimals));

  // 外部值变化 (切换语句 / 换角色) 时同步显示
  useEffect(() => {
    setText(value.toFixed(decimals));
  }, [value, decimals]);

  /** 落定一个数值: 夹到范围内, 回写显示, 与当前值不同才上报 */
  const apply = (raw: number) => {
    if (!Number.isFinite(raw)) {
      setText(value.toFixed(decimals));
      return;
    }
    const clamped = Math.min(tick.max, Math.max(tick.min, integer ? Math.round(raw) : raw));
    setText(clamped.toFixed(decimals));
    if (clamped !== value) onCommit(clamped);
  };

  const commit = () => apply(Number.parseFloat(text));

  return (
    <Input
      className="voice-control"
      type="number"
      min={tick.min}
      max={tick.max}
      step={tick.step}
      value={text}
      disabled={disabled}
      title={`${tick.min} ~ ${tick.max}，步长 ${tick.step}`}
      onChange={(_, data) => setText(data.value)}
      onBlur={commit}
      onKeyDown={(event) => {
        if (event.key === 'Enter') {
          commit();
          (event.target as HTMLInputElement).blur();
        }
      }}
    />
  );
}
