// This file is generated by AI.

// 数值参数输入框。
//
// 合成参数一律用数字输入框而不是滑杆:
// * 滑杆**看不到当前值**, 也没法精确输入 —— 而温度 1.05 与 1.10 的差别是听得出来的;
// * 滑杆占一整行, 数字框可以并排, 面板因此能在固定高度里放下全部参数。
//
// 输入过程中不校验 (允许暂时为空、暂时越界), 失焦或回车时才夹到 `tick` 的范围内,
// 因此不会出现"删到一半就被弹回原值"。

import { Input } from '@fluentui/react-components';
import { useEffect, useState } from 'react';

export interface NumberTick {
  min: number;
  max: number;
  step: number;
  default: number;
}

interface Props {
  value: number;
  tick: NumberTick;
  /** 只接受整数 (topK) */
  integer?: boolean;
  /** 不显示右侧范围提示 (取值范围本身没有意义时, 例如种子) */
  hideRange?: boolean;
  disabled?: boolean;
  onCommit: (value: number) => void;
}

/** 小数位: 由步长决定 (0.05 -> 两位), 整数参数为 0 位 */
function decimalsOf(tick: NumberTick, integer: boolean | undefined): number {
  if (integer) return 0;
  const text = String(tick.step);
  const dot = text.indexOf('.');
  return dot < 0 ? 0 : text.length - dot - 1;
}

export function NumberInput({ value, tick, integer, hideRange, disabled, onCommit }: Props) {
  const decimals = decimalsOf(tick, integer);
  const [text, setText] = useState(value.toFixed(decimals));

  // 外部值变化 (切换语句 / 换角色) 时同步显示
  useEffect(() => {
    setText(value.toFixed(decimals));
  }, [value, decimals]);

  const commit = () => {
    const parsed = Number.parseFloat(text);
    if (!Number.isFinite(parsed)) {
      setText(value.toFixed(decimals));
      return;
    }
    const clamped = Math.min(tick.max, Math.max(tick.min, integer ? Math.round(parsed) : parsed));
    setText(clamped.toFixed(decimals));
    if (clamped !== value) onCommit(clamped);
  };

  return (
    <Input
      className="voice-control"
      value={text}
      disabled={disabled}
      inputMode="decimal"
      contentAfter={hideRange ? undefined : <span className="voice-number-range">{`${tick.min}~${tick.max}`}</span>}
      onChange={(_, data) => setText(data.value)}
      onBlur={commit}
      onKeyDown={(event) => {
        if (event.key === 'Enter') {
          commit();
          (event.target as HTMLInputElement).blur();
        }
      }}
    />
  );
}
