// This file is generated by AI.

// 队列优先级标记 (配音历史与工作台队列共用)。
//
// 「测试」默认进优先队列、「生成」默认进常规队列, 但**排队中的任务可以互相改** ——
// 于是它必须同时满足两件事: 标得出当前档位, 并且在可改的时候能点。
// 因此: 排队中是按钮, 其余状态是同样的外观但不可点 (不隐藏 —— 用户要能看出这条
// 任务现在挂在哪个队列上)。

import { ArrowDownRegular, ArrowUpRegular } from '@fluentui/react-icons';

import { priorityLabel, type TaskPriority } from './types';

interface Props {
  priority: TaskPriority;
  /** 仅排队中的任务给出; 省略表示只展示不可改 */
  onToggle?: () => void;
}

export function PriorityChip({ priority, onToggle }: Props) {
  const label = priorityLabel(priority);
  const icon = priority === 'immediate' ? <ArrowUpRegular /> : <ArrowDownRegular />;
  const className = `priority-chip ${priority}`;

  if (!onToggle) {
    return (
      <span className={className} title={`${label}队列`}>
        {icon}
        {label}
      </span>
    );
  }

  const next = priorityLabel(priority === 'immediate' ? 'normal' : 'immediate');
  return (
    <button
      type="button"
      className={className}
      title={`当前：${label}队列（点击改为${next}）`}
      onClick={(event) => {
        event.stopPropagation();
        onToggle();
      }}
    >
      {icon}
      {label}
    </button>
  );
}
