// This file is generated by AI.

// 配音队列的调度规则 (纯函数)。
//
// 抽成独立模块的原因: 这些规则是功能的正确性核心 (串行、立即优先、按角色分组),
// 但控制器本身依赖 Tauri 与 DOM, 无法直接单测。这里只描述"顺序", 不做任何副作用。
//
// 规则:
// 1. **立即队列整体优先于普通队列**。默认测试任务进立即队列, 生成任务进普通队列;
//    优先级是**任务自己的字段** (`priority`), 因此排队中的任务可以被插队或降级;
// 2. 每个队列内部**按角色分组**: 同一角色的任务连续执行, 避免服务端反复重载模型
//    (切换权重需要重载底模并合并 LoRA, 代价很高);
// 3. 分组按**首次出现的顺序**排列, 不做跨组归并 —— 否则立即任务会被普通任务拖住。

export type TaskKind = 'test' | 'generate';
export type TaskPriority = 'immediate' | 'normal';
export type TaskStatus = 'pending' | 'running' | 'done' | 'failed' | 'canceled';

/** 调度所需的最小任务描述 */
export interface QueueTask {
  id: string;
  kind: TaskKind;
  priority: TaskPriority;
  status: TaskStatus;
  /** 角色 id; null 表示尚未指定角色 */
  characterId: string | null;
  /** 入队时刻 (展示排序用) */
  createdAt?: number;
  /** 结束时刻 (已完成的任务按它倒序排在末尾) */
  finishedAt?: number;
}

/** 同角色的连续任务组 */
export interface TaskGroup<T> {
  characterId: string | null;
  tasks: T[];
}

/** 尚未结束 */
export function isActive(task: Pick<QueueTask, 'status'>): boolean {
  return task.status === 'pending' || task.status === 'running';
}

/**
 * 按角色把任务分组, 保持首次出现顺序。
 *
 * 注意: `characterId` 为 `null` 的任务会被归入同一组 (键为空串),
 * 与"未指定角色"的任务一起连续执行。
 */
export function groupByCharacter<T extends QueueTask>(tasks: T[]): TaskGroup<T>[] {
  const groups = new Map<string, TaskGroup<T>>();
  for (const task of tasks) {
    const key = task.characterId ?? '';
    const existing = groups.get(key);
    if (existing) {
      existing.tasks.push(task);
    } else {
      groups.set(key, { characterId: task.characterId ?? null, tasks: [task] });
    }
  }
  return [...groups.values()];
}

/** 按优先级分组: 先立即队列, 再普通队列; 每组内部按角色分组 */
function orderPending<T extends QueueTask>(tasks: T[]): T[] {
  const immediate = groupByCharacter(tasks.filter((task) => task.priority === 'immediate'));
  const normal = groupByCharacter(tasks.filter((task) => task.priority === 'normal'));
  return [...immediate, ...normal].flatMap((group) => group.tasks);
}

/** 展开为实际执行顺序: 先立即队列, 再普通队列 */
export function executionOrder<T extends QueueTask>(tasks: T[]): T[] {
  return orderPending(tasks.filter((task) => task.status === 'pending'));
}

/** 下一个应当执行的任务; 队列为空时返回 `null` */
export function nextTask<T extends QueueTask>(tasks: T[]): T | null {
  return executionOrder(tasks)[0] ?? null;
}

/**
 * 队列面板的展示顺序。
 *
 * 与执行顺序的区别在于**已结束的任务也留在列表里**, 且必须放在最下面:
 * * 运行中 —— 排最前 (它是此刻唯一在动的东西);
 * * 排队中 —— 按**真实执行顺序**排 (立即优先, 组内按角色), 用户看到的就是将要发生的顺序;
 * * 已结束 —— 追加在末尾, 按**结束时刻从新到旧**, 于是最近完成的那条离队列最近。
 *
 * 不这样排的话, 列表会按"入队顺序"显示: 一条先入队后完成的生成任务会挂在几条
 * 早已完成的测试任务上面, 看起来像还没跑。
 */
export function queueView<T extends QueueTask>(tasks: T[]): T[] {
  const running = tasks.filter((task) => task.status === 'running');
  const pending = orderPending(tasks.filter((task) => task.status === 'pending'));
  const finished = tasks
    .filter((task) => !isActive(task))
    .sort((a, b) => (b.finishedAt ?? b.createdAt ?? 0) - (a.finishedAt ?? a.createdAt ?? 0));
  return [...running, ...pending, ...finished];
}

/** 队列概览 (供 UI 展示) */
export interface QueueSummary {
  pending: number;
  pendingTest: number;
  pendingGenerate: number;
  /** 立即队列中待处理的任务数 (包含被改成"优先"的生成任务) */
  pendingImmediate: number;
  running: number;
  /** 立即队列将把生成任务延后多久 (毫秒, 由调用方估算后传入) */
  delayMillis: number;
}

/** 统计队列状态 */
export function summarize<T extends QueueTask>(tasks: T[], estimate: (tasks: T[]) => number): QueueSummary {
  const pending = tasks.filter((task) => task.status === 'pending');
  const pendingTest = pending.filter((task) => task.kind === 'test');
  const pendingGenerate = pending.filter((task) => task.kind === 'generate');
  const pendingImmediate = pending.filter((task) => task.priority === 'immediate');
  const running = tasks.filter((task) => task.status === 'running');
  return {
    pending: pending.length,
    pendingTest: pendingTest.length,
    pendingGenerate: pendingGenerate.length,
    pendingImmediate: pendingImmediate.length,
    running: running.length,
    // 立即队列先跑, 因此它对普通队列的延后量 = 运行中任务 + 立即队列的总耗时
    delayMillis: estimate([...running, ...orderPending(pendingImmediate)]),
  };
}
