// This file is generated by AI.

// 角色列表: 管理 GSOV 模型 + 参考音频组合。
//
// 列表本身**只展示信息**, 不提供任何就地编辑, 也没有针对单个角色的操作按钮 ——
// 一行里塞满输入框与按钮会造成很大的认知压力。所有编辑都在「编辑角色」对话框里
// 完成 (点卡片即打开); 导出与删除在「选择角色」对话框里。

import { Button, Input } from '@fluentui/react-components';
import { AddRegular, PersonEditRegular, StarFilled } from '@fluentui/react-icons';
import { useEffect, useMemo, useState } from 'react';

import type { Character, ModelCandidate } from '../commands/voice';
import { useAppStore } from '../state/store';
import { voiceController } from './controller';
import { RoleEditDialog } from './RoleEditDialog';
import { RolePickerDialog } from './RolePickerDialog';

export function RoleListPanel() {
  const characters = useAppStore((state) => state.voiceCharacters);
  useAppStore((state) => state.voiceTick);
  const [query, setQuery] = useState('');
  const [pickerOpen, setPickerOpen] = useState(false);
  const [editTarget, setEditTarget] = useState<Character | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [models, setModels] = useState<ModelCandidate[]>([]);

  useEffect(() => {
    voiceController.primeReferencePaths().catch(() => {});
  }, [characters.length]);

  // 扫描整合包内的 v4 权重, 为角色的模型下拉提供候选
  useEffect(() => {
    void voiceController.listModels().then(setModels);
  }, [characters.length]);

  const enabled = useMemo(
    () => characters.filter((character) => character.enabled && matchesQuery(character, query)),
    [characters, query]
  );

  const create = async () => {
    setError(null);
    try {
      const created = await voiceController.createCharacter(`新角色 ${characters.length + 1}`, '');
      // 新建后直接打开编辑对话框, 否则用户看不到自己刚建了什么
      setEditTarget(created);
      setQuery('');
    } catch (caught) {
      setError(caught instanceof Error ? caught.message : String(caught));
    }
  };

  /**
   * 「选择角色」= 取消当前选择, 然后打开挑选对话框。
   *
   * 这两件事本来就是同一个动作的两半: 侧边栏展示的是"已选中的角色",
   * 挑选对话框是"重新决定选哪些"。先清空再挑, 免得用户在对话框里看到的勾选状态
   * 与自己的预期不一致。
   */
  const deselectAndPick = async () => {
    setError(null);
    try {
      await Promise.all(
        characters
          .filter((item) => item.enabled)
          .map((item) => voiceController.persistCharacter({ ...item, enabled: false }))
      );
    } catch (caught) {
      setError(caught instanceof Error ? caught.message : String(caught));
    }
    setPickerOpen(true);
  };

  /** 打开编辑对话框时始终取最新的一份角色数据 */
  const openEditor = (id: string) => {
    const latest = useAppStore.getState().voiceCharacters.find((item) => item.id === id) ?? null;
    setEditTarget(latest);
  };

  return (
    <div className="character-panel">
      <div className="character-toolbar">
        <Input
          className="character-search"
          placeholder="搜索角色…"
          value={query}
          onChange={(_, data) => setQuery(data.value)}
        />
        <Button appearance="primary" icon={<AddRegular />} onClick={() => void create()}>
          新建角色
        </Button>
        {/*
          「选择角色」在打开挑选对话框之前先把所有角色取消勾选 —— 侧边栏里显示的
          本来就只是"已选中的角色", 因此让它们全部退出就是"取消选择"这个动作。
        */}
        <Button
          appearance="secondary"
          icon={<PersonEditRegular />}
          disabled={!characters.some((item) => item.enabled)}
          onClick={() => void deselectAndPick()}
        >
          选择角色
        </Button>
      </div>

      {error && <p className="voice-error">{error}</p>}

      <div className="character-list">
        {characters.length === 0 && (
          <p className="voice-dialog-empty">还没有角色。先「新建角色」或导入一份角色配置。</p>
        )}
        {characters.length > 0 && enabled.length === 0 && (
          <p className="voice-dialog-empty">没有已启用的角色。点「选择角色」勾选需要参与配音的角色。</p>
        )}
        {enabled.map((character) => (
          <div key={character.id} className="character-tile">
            <button
              type="button"
              className="character-tile-main"
              title="点击编辑角色"
              onClick={() => openEditor(character.id)}
            >
              <span className="character-tile-name">
                {character.name}
                {character.starred && <StarFilled className="character-tile-star" />}
              </span>
              <span className="character-tile-meta">
                {character.id} · 参考音频 {character.references.length}
                {character.description.trim() && ` · ${character.description.trim()}`}
              </span>
              <span className="character-tile-models">
                <span className="character-tile-model" title={character.model?.gptWeights ?? '未指定'}>
                  GPT {suffixOf(character.model?.gptWeights)}
                </span>
                <span className="character-tile-model" title={character.model?.sovitsWeights ?? '未指定'}>
                  SoVITS {suffixOf(character.model?.sovitsWeights)}
                </span>
              </span>
            </button>
          </div>
        ))}
      </div>

      <RolePickerDialog open={pickerOpen} onClose={() => setPickerOpen(false)} onError={setError} />

      {editTarget && (
        <RoleEditDialog
          character={editTarget}
          models={models}
          onClose={() => setEditTarget(null)}
          onChanged={() => {
            const latest = useAppStore.getState().voiceCharacters.find((item) => item.id === editTarget.id);
            setEditTarget(latest ?? null);
          }}
          onError={setError}
        />
      )}
    </div>
  );
}

function matchesQuery(character: Character, query: string): boolean {
  if (!query.trim()) return true;
  const needle = query.trim().toLowerCase();
  return character.name.toLowerCase().includes(needle) || character.id.toLowerCase().includes(needle);
}

/** 权重路径的可读后缀 (只取文件名) */
function suffixOf(weights: string | null | undefined): string {
  if (!weights) return '未指定';
  return weights.replace(/\\/g, '/').split('/').pop() ?? weights;
}
