// This file is generated by AI.

// 角色选择对话框: 负责"挑选参与配音的角色", 以及从角色上直接进入**参考音频编辑**。
//
// 勾选启用、星标靠前、导入。点角色名会打开「编辑角色」对话框 (只保留角色信息与参考
// 音频, 不显示 GSOV 权重) —— 站在这里想点开一个角色的唯一理由就是"看看它有哪些参考
// 音频、再补几条", 而去工作台的角色列表里找同一个角色属于多绕一圈。
//
// 权重仍然只在工作台里改: 它是服务端的本机路径, 与"挑选角色"这件事无关。

import { Button, Checkbox, Input } from '@fluentui/react-components';
import {
  ArrowDownloadRegular,
  ArrowUploadRegular,
  DeleteRegular,
  FolderOpenRegular,
  StarFilled,
  StarRegular,
} from '@fluentui/react-icons';
import { save as saveDialog } from '@tauri-apps/plugin-dialog';
import { useEffect, useMemo, useState } from 'react';

import type { Character } from '../commands/voice';
import { voiceExportCharacter } from '../commands/voice';
import { AppDialog } from '../components/AppDialog';
import { useAppStore } from '../state/store';
import { voiceController } from './controller';
import { ListImportDialog } from './ListImportDialog';
import { RoleEditDialog } from './RoleEditDialog';

interface Props {
  open: boolean;
  onClose: () => void;
  onError: (error: string | null) => void;
}

export function RolePickerDialog({ open, onClose, onError }: Props) {
  const characters = useAppStore((state) => state.voiceCharacters);
  const [query, setQuery] = useState('');
  const [message, setMessage] = useState<string | null>(null);
  const [listImportOpen, setListImportOpen] = useState(false);
  const [editTarget, setEditTarget] = useState<Character | null>(null);

  useEffect(() => {
    if (open) {
      setQuery('');
      setMessage(null);
    } else {
      setEditTarget(null);
    }
  }, [open]);

  const visible = useMemo(() => {
    if (!query.trim()) return characters;
    const needle = query.trim().toLowerCase();
    return characters.filter(
      (character) => character.name.toLowerCase().includes(needle) || character.id.toLowerCase().includes(needle)
    );
  }, [characters, query]);

  if (!open) return null;

  const report = (caught: unknown) => onError(caught instanceof Error ? caught.message : String(caught));

  const toggleEnabled = async (character: Character, enabled: boolean) => {
    try {
      await voiceController.updateCharacter(character.id, { enabled });
    } catch (caught) {
      report(caught);
    }
  };

  const toggleStarred = async (character: Character, starred: boolean) => {
    try {
      await voiceController.updateCharacter(character.id, { starred });
    } catch (caught) {
      report(caught);
    }
  };

  /** 导入一份角色 zip (导入后按名称自动配对 GSOV 模型) */
  const importCharacter = async () => {
    setMessage(null);
    try {
      const result = await voiceController.importCharacter();
      if (result) {
        setMessage(
          `已导入角色「${result.character.name}」` +
            (result.paired > 0
              ? '，已按名称自动配对 GSOV 模型'
              : '；没有自动配上 GSOV 模型（名称与整合包内的权重对不上，可手选）')
        );
      }
    } catch (caught) {
      report(caught);
    }
  };

  const remove = async (character: Character) => {
    try {
      await voiceController.deleteCharacter(character.id);
    } catch (caught) {
      report(caught);
    }
  };

  const exportCharacter = async (character: Character) => {
    const destination = await saveDialog({
      defaultPath: `${character.name}.zip`,
      filters: [{ name: 'Zip 压缩包', extensions: ['zip'] }],
    });
    if (typeof destination !== 'string') return;
    await voiceExportCharacter(character.id, destination);
  };

  /** 打开角色编辑时始终取最新的一份数据 */
  const openEditor = (id: string) => {
    setEditTarget(useAppStore.getState().voiceCharacters.find((item) => item.id === id) ?? null);
  };

  return (
    <>
      <AppDialog
        title="选择角色"
        description="勾选参与配音的角色；点角色名可以编辑它的信息与参考音频。"
        size="large"
        height={600}
        compact
        onClose={onClose}
        footer={
          <Button appearance="secondary" onClick={onClose}>
            关闭
          </Button>
        }
      >
        {/* 工具栏: 搜索占满剩余宽度, 两个导入按钮固定宽度, 因此不会换行 */}
        <div className="dialog-toolbar">
          <Input
            className="dialog-toolbar-grow"
            placeholder="搜索角色…"
            value={query}
            onChange={(_, data) => setQuery(data.value)}
          />
          <Button appearance="secondary" icon={<ArrowUploadRegular />} onClick={() => void importCharacter()}>
            导入角色
          </Button>
          <Button
            appearance="secondary"
            icon={<FolderOpenRegular />}
            title="从训练切分产物的文本清单与音频批量导入角色"
            onClick={() => setListImportOpen(true)}
          >
            从清单导入
          </Button>
        </div>

        {message && <p className="dialog-message">{message}</p>}

        <div className="character-grid character-grid-pick dialog-scroll">
          {visible.length === 0 && <p className="voice-dialog-empty">没有匹配的角色。</p>}
          {visible.map((character) => (
            <div key={character.id} className={`character-block${character.enabled ? '' : ' disabled'}`}>
              <Checkbox
                checked={character.enabled}
                onChange={(_, data) => void toggleEnabled(character, Boolean(data.checked))}
                title="是否参与配音"
              />
              <button
                type="button"
                className="character-block-main"
                title="编辑角色信息与参考音频"
                onClick={() => openEditor(character.id)}
              >
                <span className="character-block-name">{character.name}</span>
                <span className="character-block-meta">
                  {character.id} · 参考音频 {character.references.length}
                </span>
              </button>
              <Button
                size="small"
                appearance="subtle"
                title={character.starred ? '取消星标' : '星标靠前'}
                icon={character.starred ? <StarFilled /> : <StarRegular />}
                onClick={() => void toggleStarred(character, !character.starred)}
              />
              <Button
                size="small"
                appearance="subtle"
                title="导出角色"
                icon={<ArrowDownloadRegular />}
                onClick={() => void exportCharacter(character)}
              />
              <Button
                size="small"
                appearance="subtle"
                className="danger-icon"
                title="删除角色"
                icon={<DeleteRegular />}
                onClick={() => void remove(character)}
              />
            </div>
          ))}
        </div>
      </AppDialog>

      {listImportOpen && <ListImportDialog onClose={() => setListImportOpen(false)} onImported={setMessage} />}

      {/*
        从这里点开的是「编辑角色」的**精简版**: 角色信息 + 参考音频列表,
        不显示 GPT-SoVITS 权重 (那是工作台里"这台机器怎么跑推理"的设置)。
        对话框不使用 portal, 因此它叠在本对话框之上, 关掉后仍回到挑选界面。
      */}
      {editTarget && (
        <RoleEditDialog
          character={editTarget}
          models={[]}
          hideModel
          onClose={() => setEditTarget(null)}
          // 对话框把落盘后的那一份交回来 (改名后 id 会变, 不能再按旧 id 去查)
          onChanged={setEditTarget}
          onError={(error) => {
            if (error) report(error);
          }}
        />
      )}
    </>
  );
}
