// This file is generated by AI.

// 本地文件变更裁决对话框。
//
// 场景卡打开期间, 磁盘文件可能被外部修改 (git 切换、外部编辑器、另一个窗口)。
// 检测到变更后必须先由用户裁决, **再**执行历史重新对齐 —— 顺序不能颠倒:
// 用户在 git 合并页里改完内容会再次改变行号, 先对齐会让对齐结果失效。

import { Button } from '@fluentui/react-components';
import { useEffect, useState } from 'react';

import { AppDialog } from '../components/AppDialog';
import { fs } from '../lib/fs';
import { useAppStore } from '../state/store';
import { voiceController } from './controller';
import { hashText, normalizeEol } from './controller';

export type ChangeDecision = 'keep-editor' | 'take-disk' | 'merge-git' | 'backup-and-take-disk';

interface Props {
  open: boolean;
  cardId: string;
  scenePath: string;
  /** 是否处于 git 仓库 (决定是否提供合并选项) */
  inRepository: boolean;
  onResolved: (decision: ChangeDecision) => void;
  onOpenGitMerge: () => void;
}

export function SceneConflictDialog({ open, cardId, scenePath, inRepository, onResolved, onOpenGitMerge }: Props) {
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [diskPreview, setDiskPreview] = useState<string | null>(null);

  useEffect(() => {
    if (!open) {
      setDiskPreview(null);
      setError(null);
      return;
    }
    void fs
      .readTextLossy(scenePath)
      .then((content) => setDiskPreview(content))
      .catch(() => setDiskPreview(null));
  }, [open, scenePath]);

  if (!open) return null;

  /** 用磁盘内容替换编辑器内容 */
  const takeDisk = async () => {
    if (diskPreview === null) return;
    setBusy(true);
    try {
      useAppStore.getState().updateDocument(scenePath, {
        content: diskPreview,
        dirty: false,
      });
      voiceController.setDiskHash(cardId, hashText(normalizeEol(diskPreview)));
      await voiceController.refreshCard(cardId, diskPreview);
      await voiceController.realignCard(cardId);
      onResolved('take-disk');
    } catch (caught) {
      setError(caught instanceof Error ? caught.message : String(caught));
    } finally {
      setBusy(false);
    }
  };

  /** 先备份编辑器内容, 再加载磁盘内容 */
  const backupAndTakeDisk = async () => {
    const current = useAppStore.getState().documents.find((doc) => doc.path === scenePath)?.content;
    if (current === undefined) return;
    setBusy(true);
    try {
      const backup = `${scenePath}.ink-backup.txt`;
      await fs.writeText(backup, current);
      await takeDisk();
      onResolved('backup-and-take-disk');
    } catch (caught) {
      setError(caught instanceof Error ? caught.message : String(caught));
    } finally {
      setBusy(false);
    }
  };

  /** 保留编辑器内容: 磁盘仍是旧的, 卡片标记为与磁盘不一致 */
  const keepEditor = async () => {
    const current = useAppStore.getState().documents.find((doc) => doc.path === scenePath)?.content;
    if (current !== undefined) {
      await voiceController.refreshCard(cardId, current);
      await voiceController.realignCard(cardId);
    }
    onResolved('keep-editor');
  };

  return (
    <AppDialog
      title="场景文件已被外部修改"
      size="medium"
      height={320}
      onClose={() => onResolved('keep-editor')}
      footerLeading={
        <Button
          appearance="secondary"
          disabled={busy || !inRepository}
          title={inRepository ? '打开独立的 git 合并页面' : '当前项目不在 git 仓库中'}
          onClick={onOpenGitMerge}
        >
          用 git 合并
        </Button>
      }
      footer={
        <>
          <Button appearance="secondary" disabled={busy} onClick={() => void backupAndTakeDisk()}>
            备份后加载磁盘
          </Button>
          <Button appearance="primary" disabled={busy || diskPreview === null} onClick={() => void takeDisk()}>
            加载磁盘内容
          </Button>
        </>
      }
    >
      <p className="voice-dialog-hint">
        <code>{scenePath}</code> 在磁盘上发生了变化（例如 git 切换分支或另一处编辑）。 请先决定保留哪一份内容，之后 Ink
        会把配音历史重新对齐到最终的对话列表。
      </p>
      <Button appearance="secondary" disabled={busy} onClick={() => void keepEditor()}>
        保留编辑器内容并继续
      </Button>
      {error && <p className="voice-error">{error}</p>}
    </AppDialog>
  );
}
