// This file is generated by AI.

// 语句配音配置面板 (配音卡操作台左侧)。
//
// 交互约定:
// * 参数编辑**永不禁用**: 一旦改动参数, 该配置即为"新配置", 不影响既有历史记录;
// * 「测试」入立即队列 (x4), 「生成」入普通队列 (x32);
// * 「应用」把选中历史项的音频落盘并改写 `-vocal=`;
//   「移除」只清除当前语句的 `-vocal=` (不删文件、不清历史);
// * 语音之外的参数 (文本) 随场景内容变化, 不随历史项回填。

import { Button, Textarea } from '@fluentui/react-components';
import {
  ArrowSyncRegular,
  CheckmarkRegular,
  ChevronDownRegular,
  DeleteRegular,
  DismissRegular,
  FlashRegular,
  MicRecordRegular,
  SettingsRegular,
} from '@fluentui/react-icons';
import { useEffect, useMemo, useRef, useState } from 'react';

import type { Character, SayLine } from '../commands/voice';
import { Select, toOptions } from '../components/Select';
import { voiceController } from './controller';
import { formatDuration } from './estimate';
import { useVoiceCard } from './hooks';
import { NumberInput, type NumberTick } from './NumberInput';
import { VoiceReferenceDialog } from './VoiceReferenceDialog';
import { GENERATE_SAMPLE_STEPS, LANGUAGE_LABELS, PARAM_TICKS, randomSeed, type VoiceParams } from './types';

interface Props {
  cardId: string;
  dialogue: SayLine;
  characters: Character[];
  refreshToken: number;
  onChanged: () => void;
}

export function SentenceVoicePanel({ cardId, dialogue, characters, refreshToken, onChanged }: Props) {
  const [params, setParams] = useState<VoiceParams | null>(null);
  const [advancedOpen, setAdvancedOpen] = useState(false);
  const [pickerOpen, setPickerOpen] = useState(false);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState<string | null>(null);

  const card = useVoiceCard(cardId);
  const selected = card?.selectedHistoryId
    ? (card.history.find((entry) => entry.id === card.selectedHistoryId) ?? null)
    : null;
  const selectedId = card?.selectedHistoryId ?? null;

  /*
   * 参数来源键: 语句身份 + 选中的历史项。
   *
   * 这两者任一变化都要**重新取一遍参数**。其中"选中的历史项"以前漏了 —— 点别的记录时
   * 面板纹丝不动 (参数是本地状态, 没人去重建它), 看起来像点击没生效。
   *
   * 刻意**不把刷新令牌算进来**: 队列里任何一条任务完成、任何一次列表清理都会让它 +1,
   * 跟着重建就会把用户刚调好、还没生成的那套参数盖回默认值 —— 动一条无关的记录不该
   * 影响面板。
   *
   * 而 `update` 自己会清空选中项, 那一次也不能重建 (同上), 因此它也把这个键一并标成
   * "已同步"。
   */
  const sourceKeyOf = (selection: string | null) => `${dialogue.line}\u001f${dialogue.hash}\u001f${selection ?? ''}`;
  const sourceKey = sourceKeyOf(selectedId);
  const syncedSource = useRef<string | null>(null);

  useEffect(() => {
    if (syncedSource.current === sourceKey) return;
    syncedSource.current = sourceKey;
    setParams(voiceController.currentParams(cardId, dialogue));
    setMessage(null);
  }, [sourceKey, cardId, dialogue]);

  const character = useMemo(
    () => voiceController.characterById(params?.characterId ?? null),
    [params?.characterId, characters, refreshToken]
  );

  const match = card?.matches.get(dialogue.line);
  const matchHint = describeMatch(match?.reason);

  if (!params) return <div className="voice-sentence-panel" />;

  const update = (patch: Partial<VoiceParams>) => {
    setParams({ ...params, ...patch });
    // 参数一改, 视为新配置 -> 取消历史选中 (应用按钮随之禁用)
    setMessage(null);
    voiceController.selectHistory(cardId, null);
    // 这次清空是"改参数"引起的, 不是用户选了别的记录 -> 不要重建
    syncedSource.current = sourceKeyOf(null);
  };

  const isNewConfiguration = voiceController.isNewConfiguration(cardId, params);
  const canApply = Boolean(selected && selected.status === 'done' && selected.audioHash && !isNewConfiguration);
  const running = selected?.status === 'pending' || selected?.status === 'running';
  const hasVocal = Boolean(dialogue.vocal);

  const enqueue = (kind: 'test' | 'generate') => {
    if (!character || character.references.length === 0) {
      setMessage('请先为角色添加参考音频');
      return;
    }
    const reference =
      character.references.find((item) => item.hash === params.referenceHash) ?? character.references[0];
    const task = voiceController.enqueue(cardId, kind, dialogue, { ...params, referenceHash: reference.hash });
    if (task) {
      setMessage(
        kind === 'test'
          ? `已加入优先队列（测试 x${task.params.sampleSteps}）`
          : `已加入常规队列（生成 x${task.params.sampleSteps}）`
      );
      onChanged();
    } else {
      setMessage('入队失败：找不到当前场景卡，请重新打开配音卡');
    }
  };

  const apply = async () => {
    if (!selected) return;
    setBusy(true);
    try {
      await voiceController.apply(cardId, selected.id);
      setMessage('已应用并更新 -vocal=');
      onChanged();
    } catch (error) {
      setMessage(error instanceof Error ? error.message : String(error));
    } finally {
      setBusy(false);
    }
  };

  const remove = async () => {
    setBusy(true);
    try {
      await voiceController.remove(cardId);
      setMessage('已移除本句配音引用');
      onChanged();
    } catch (error) {
      setMessage(error instanceof Error ? error.message : String(error));
    } finally {
      setBusy(false);
    }
  };

  /**
   * 从操作台取消正在跑的这一条。
   *
   * 取消后这条记录会从历史里移除 (任务队列里仍看得到), 因此这里要**主动把参数源标成
   * "已同步"** —— 否则选中项一变, 面板会重新取一遍默认参数, 用户刚调好的那套配置就被
   * 冲掉了。取消的是这次生成, 不是这套配置。
   */
  const cancel = () => {
    if (!selected) return;
    voiceController.cancel(selected.id);
    syncedSource.current = sourceKeyOf(null);
    setMessage('已取消这一条（记录已从本句历史移除，队列里仍可见）');
    onChanged();
  };

  /*
   * 状态行**永远有文字**, 且排在按钮上方。
   *
   * 两件事都是刻意的: 空行既占位又看不出当前是什么状态; 而"新配置/已生成"这类信息
   * 贴在按钮下面时, 读起来像按钮的补充说明 —— 放到上面才能和下面的参数区连成一句。
   */
  const stepLabel = selected ? `${selected.kind === 'test' ? '测试' : '生成'} x${selected.params.sampleSteps}` : '';
  const statusText = running
    ? selected?.status === 'pending'
      ? `已加入队列，等待执行（${stepLabel}）`
      : `正在生成（${stepLabel}）…`
    : isNewConfiguration
      ? '当前为新配置，尚未生成'
      : selected?.status === 'failed'
        ? '这次生成失败了，点开右侧记录可以看完整报错'
        : selected
          ? `当前配置已生成（${stepLabel}${selected.elapsed !== undefined ? ` · 响应 ${formatDuration(selected.elapsed)}` : ''}）`
          : '当前配置与历史记录一致，可直接应用';
  const statusTone = running ? 'run' : isNewConfiguration ? 'new' : selected?.status === 'failed' ? 'fail' : 'ok';

  return (
    <div className="voice-sentence-panel">
      {/*
        设置项独立滚动, 页脚固定: 面板高度是写死的 (见 `.scene-voice-panel`), 展开
        「高级设置」时只有上面这一段滚, 状态行与按钮不会跟着上下跳。
      */}
      <div className="voice-fields">
        {/* 第一行: 角色 / 语言 / 参考音频。参考音频要看清文本与时长, 因此由它占满剩余宽度。 */}
        <div className="voice-row">
          <label className="voice-field voice-field-character">
            <span className="voice-label">角色</span>
            <Select
              value={params.characterId ?? ''}
              title={character ? `${character.name}${matchHint && !selected ? `（${matchHint}）` : ''}` : '未选择角色'}
              placeholder="未选择（点击选择角色）"
              options={characters.map((item) => ({
                value: item.id,
                label: `${item.name}${item.references.length === 0 ? '（无参考音频）' : ''}`,
              }))}
              onChange={(id) => {
                const next = voiceController.characterById(id || null);
                voiceController.assignCharacter(
                  voiceController.getCard(cardId)?.scenePath ?? '',
                  dialogue.speaker,
                  id || null
                );
                update({
                  characterId: id || null,
                  referenceHash: next?.references[0]?.hash ?? null,
                });
              }}
            />
          </label>

          <label className="voice-field voice-field-language">
            <span className="voice-label">语言</span>
            <Select
              value={params.language}
              title="本条对话的合成语言"
              options={toOptions(LANGUAGE_LABELS)}
              onChange={(language) => update({ language })}
            />
          </label>

          <label className="voice-field voice-field-reference">
            <span className="voice-label">参考音频</span>
            {/*
              参考音频用下拉直接选。
              `Select` 是就地展开的浮层, 但参考音频**需要看时长与文本**才能选, 选项里
              放不下这些信息, 因此这里点开即弹出选择对话框 (带搜索与试听), 比
              "只读文字 + 更换按钮"更直接: 那个按钮的文案让人以为要"更换文件"。
            */}
            <button
              type="button"
              className="select-trigger voice-reference-trigger"
              title={referenceLabel(character, params.referenceHash)}
              onClick={() => setPickerOpen(true)}
            >
              <span className="select-label">{referenceLabel(character, params.referenceHash)}</span>
              <ChevronDownRegular className="select-chevron" />
            </button>
          </label>
        </div>

        {/* 第二行: 文本 (独占一行; 它是唯一可能很长的输入) */}
        <label className="voice-field voice-field-text">
          <span className="voice-label">
            文本
            {dialogue.speaker === null && <span className="voice-label-tag">旁白</span>}
          </span>
          <Textarea
            className="voice-control voice-text"
            value={params.text}
            resize="vertical"
            onChange={(_, data) => update({ text: data.value })}
          />
        </label>

        {/* 第三行: 种子 / 温度 / 语速 / 高级设置 */}
        <div className="voice-row">
          <label className="voice-field voice-field-seed">
            <span className="voice-label">种子</span>
            <div className="voice-seed">
              <NumberInput value={params.seed} tick={PARAM_TICKS.seed} integer onCommit={(seed) => update({ seed })} />
              <Button
                size="small"
                appearance="subtle"
                title="换一个随机种子"
                icon={<ArrowSyncRegular />}
                onClick={() => update({ seed: randomSeed() })}
              />
            </div>
          </label>
          <label className="voice-field voice-field-number">
            <span className="voice-label">
              温度
              <span className="voice-label-range">{range(PARAM_TICKS.temperature)}</span>
            </span>
            <NumberInput
              value={params.temperature}
              tick={PARAM_TICKS.temperature}
              onCommit={(temperature) => update({ temperature })}
            />
          </label>
          <label className="voice-field voice-field-number">
            <span className="voice-label">
              语速
              <span className="voice-label-range">{range(PARAM_TICKS.speedFactor)}</span>
            </span>
            <NumberInput
              value={params.speedFactor}
              tick={PARAM_TICKS.speedFactor}
              onCommit={(speedFactor) => update({ speedFactor })}
            />
          </label>
          {/* 高级设置的开关跟在语速右边: 二者相关, 同一行也更紧凑 */}
          <div className="voice-field voice-field-advanced">
            <span className="voice-label">&nbsp;</span>
            <Button
              appearance="subtle"
              size="small"
              icon={<SettingsRegular />}
              onClick={() => setAdvancedOpen((open) => !open)}
            >
              高级设置 {advancedOpen ? '▴' : '▾'}
            </Button>
          </div>
        </div>

        {/* 高级设置收成一行: 面板高度写死, 参数一多行就会把按钮挤出视野 */}
        {advancedOpen && (
          <div className="voice-advanced-body">
            <div className="voice-row">
              <label className="voice-field voice-field-number">
                <span className="voice-label">
                  topK
                  <span className="voice-label-range">{range(PARAM_TICKS.topK)}</span>
                </span>
                <NumberInput
                  value={params.topK}
                  tick={PARAM_TICKS.topK}
                  integer
                  onCommit={(topK) => update({ topK })}
                />
              </label>
              <label className="voice-field voice-field-number">
                <span className="voice-label">
                  topP
                  <span className="voice-label-range">{range(PARAM_TICKS.topP)}</span>
                </span>
                <NumberInput value={params.topP} tick={PARAM_TICKS.topP} onCommit={(topP) => update({ topP })} />
              </label>
              <label className="voice-field voice-field-number">
                <span className="voice-label">
                  重复惩罚
                  <span className="voice-label-range">{range(PARAM_TICKS.repetitionPenalty)}</span>
                </span>
                <NumberInput
                  value={params.repetitionPenalty}
                  tick={PARAM_TICKS.repetitionPenalty}
                  onCommit={(repetitionPenalty) => update({ repetitionPenalty })}
                />
              </label>
              <label className="voice-field voice-field-number">
                <span className="voice-label">采样步数</span>
                <Select
                  value={String(params.sampleSteps)}
                  title="正式生成使用的采样步数"
                  options={[4, 8, 16, 32].map((steps) => ({ value: String(steps), label: `x${steps}` }))}
                  onChange={(value) => update({ sampleSteps: Number.parseInt(value, 10) || GENERATE_SAMPLE_STEPS })}
                />
              </label>
            </div>
          </div>
        )}
      </div>

      {/*
        状态行与按钮同属一块页脚: 与上面的参数区用一条分隔线隔开, 状态行紧贴按钮上方。
      */}
      <div className="voice-footer">
        <div className="voice-status-line">
          <span className={`voice-status-${statusTone}`}>{statusText}</span>
          {message && <span className="voice-message">{message}</span>}
        </div>

        <div className="voice-actions">
          <Button
            appearance="secondary"
            icon={<FlashRegular />}
            disabled={Boolean(busy)}
            onClick={() => enqueue('test')}
          >
            测试 x4
          </Button>
          <Button
            appearance="primary"
            icon={<MicRecordRegular />}
            disabled={Boolean(busy)}
            onClick={() => enqueue('generate')}
          >
            生成 x{params.sampleSteps}
          </Button>
          <span className="voice-actions-spacer" />
          {running ? (
            /* 取消 = 撤下这一条, 用叉; 「移除」才是"从脚本里拿掉", 仍用垃圾桶 */
            <Button
              appearance="secondary"
              icon={<DismissRegular />}
              title="取消（推理无法中断，返回后丢弃结果）"
              onClick={cancel}
            >
              取消
            </Button>
          ) : (
            <Button
              appearance="secondary"
              title="清除当前语句的 -vocal=（不删除音频与历史）"
              icon={<DeleteRegular />}
              disabled={!hasVocal || Boolean(busy)}
              onClick={() => void remove()}
            >
              移除
            </Button>
          )}
          <Button
            appearance="primary"
            icon={<CheckmarkRegular />}
            disabled={!canApply || Boolean(busy)}
            onClick={() => void apply()}
          >
            应用
          </Button>
        </div>
      </div>

      <VoiceReferenceDialog
        open={pickerOpen}
        character={character}
        selectedHash={params.referenceHash}
        onPick={(hash) => {
          update({ referenceHash: hash });
          setPickerOpen(false);
        }}
        onClose={() => setPickerOpen(false)}
        onCharactersChanged={onChanged}
      />
    </div>
  );
}

/** 取值范围 (显示在字段标签右侧; 输入框留给数值本身和加减按钮) */
function range(tick: NumberTick): string {
  return `${tick.min}~${tick.max}`;
}

function referenceLabel(character: Character | null, hash: string | null): string {
  if (!character) return '未选择角色';
  if (character.references.length === 0) return '该角色暂无参考音频';
  const reference = character.references.find((item) => item.hash === hash) ?? character.references[0];
  const preview = reference.text.length > 14 ? `${reference.text.slice(0, 14)}…` : reference.text;
  return `${preview}（${reference.duration.toFixed(1)}s）`;
}

function describeMatch(reason: string | undefined): string {
  switch (reason) {
    case 'figureId':
      return '按立绘匹配';
    case 'name':
      return '按名称匹配';
    case 'narration':
      return '继承旁白';
    default:
      return '';
  }
}
