// This file is generated by AI.

// 任务进度条 (历史记录与工作台队列共用)。
//
// 服务端在推理过程中**不提供任何进度**, 因此进度只能是"已用时间 / 预估时间", 预估
// 由 `estimator` 用实测样本校准 (见 estimate.ts)。据此:
// * 进度条会随时间往前走, 但走到头不等于一定完成 —— 偏慢的任务会停在 100% 等结果;
// * 排队中的任务还没有开始时间, 因此只显示"预计"。
//
// 刷新用秒级定时器, 且**只在任务真的在跑时才启动**: 没有活动任务时不该每秒重渲染。

import { ProgressBar } from '@fluentui/react-components';
import { useEffect, useState } from 'react';

import { estimator, formatDuration, formatEta } from './estimate';

interface Props {
  kind: 'test' | 'generate';
  /** 任务文本 (估算按字符数) */
  text: string;
  /** 开始推理的时刻; 未开始 (排队中) 时省略 */
  startedAt?: number;
}

export function TaskProgress({ kind, text, startedAt }: Props) {
  const now = useTicker(startedAt !== undefined);
  const total = estimator.estimate(kind, text.length);

  if (startedAt === undefined) {
    return (
      <div className="task-progress">
        <span className="task-progress-text">预计 {formatEta(total)}</span>
      </div>
    );
  }

  const elapsed = Math.max(0, now - startedAt);
  const remaining = total - elapsed;
  return (
    <div className="task-progress">
      <ProgressBar value={total > 0 ? Math.min(1, elapsed / total) : 0} />
      <span className="task-progress-text">
        已用 {formatDuration(elapsed)} · {remaining > 0 ? `预计还需 ${formatEta(remaining)}` : '仍在推理…'}
      </span>
    </div>
  );
}

/** 每秒返回一次当前时刻; 没有活动任务时不再跳动 */
function useTicker(active: boolean): number {
  const [now, setNow] = useState(() => Date.now());
  useEffect(() => {
    if (!active) return;
    setNow(Date.now());
    const timer = setInterval(() => setNow(Date.now()), 1000);
    return () => clearInterval(timer);
  }, [active]);
  return now;
}
