// This file is generated by AI.

// 语句配音历史 (配音卡操作台右侧)。
//
// **历史是按"当前这一句对话"组织的**, 不是整个场景共用一份: 换一句对话就该换一批记录,
// 否则左右两边说的不是同一件事 (左边是这一句的配置, 右边却混着一整幕的记录)。
//
// 每条记录对应一次「测试」或「生成」; 排队中 / 生成中的任务可以取消, 排队中的还能改
// 优先级。参数编辑不影响既有记录: 改动参数只会让"当前配置"变成新配置, 历史保持原样。
//
// 卡片布局: 第一行是"这条记录是什么"(类型 / 时间) + 操作图标, 因此操作与基本信息
// **同一行**, 不再单独占一行高度。

import { Button } from '@fluentui/react-components';
import {
  ArrowDownRegular,
  ArrowDownloadRegular,
  ArrowSyncRegular,
  ArrowUpRegular,
  BroomRegular,
  CheckmarkCircleRegular,
  CheckmarkRegular,
  DeleteRegular,
  DismissRegular,
  ErrorCircleRegular,
  FilterDismissRegular,
  FolderOpenRegular,
} from '@fluentui/react-icons';
import { revealItemInDir } from '@tauri-apps/plugin-opener';
import { save as saveDialog } from '@tauri-apps/plugin-dialog';
import { useEffect, useRef, useState } from 'react';

import { voiceController } from './controller';
import { AudioButton } from './AudioButton';
import { errorSummary } from './errorText';
import { formatDuration } from './estimate';
import { useVoiceCard, useVoiceTick } from './hooks';
import { PriorityButton } from './PriorityButton';
import { TaskProgress } from './TaskProgress';
import type { HistoryEntry } from './types';
import { VoiceErrorDialog } from './VoiceErrorDialog';
import { fs } from '../lib/fs';
import { writeFile } from '@tauri-apps/plugin-fs';

interface Props {
  cardId: string;
  /** 当前光标所在对话的行号: 历史只显示这一句的记录 */
  line: number;
  onChanged: () => void;
  onApplied: () => void;
}

interface MenuState {
  x: number;
  y: number;
  entry: HistoryEntry;
}

export function VoiceTakeList({ cardId, line, onChanged, onApplied }: Props) {
  // 订阅队列变化 (卡片本身从 store 读, 因此选中记录 / 任务回填都会触发重渲染)
  const voiceTick = useVoiceTick();
  const card = useVoiceCard(cardId);
  const selectedId = card?.selectedHistoryId ?? null;
  const [menu, setMenu] = useState<MenuState | null>(null);
  const [errorEntry, setErrorEntry] = useState<HistoryEntry | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const close = () => setMenu(null);
    window.addEventListener('click', close);
    window.addEventListener('blur', close);
    return () => {
      window.removeEventListener('click', close);
      window.removeEventListener('blur', close);
    };
  }, []);

  if (!card) return null;

  /** 本句的记录 (历史只针对当前对话) */
  const entries = card.history.filter((entry) => entry.line === line);
  const active = entries.filter((entry) => entry.status === 'pending' || entry.status === 'running');
  const done = entries.filter((entry) => entry.status === 'done');
  const failed = entries.filter((entry) => entry.status === 'failed');
  /** 未能对齐到任何语句的残留记录 (过滤之后它们不在任何列表里, 需要一个清理入口) */
  const unaligned = card.history.filter((entry) => entry.line === null).length;

  const appliedEntry = card.history.find((entry) => entry.line === line && entry.applied) ?? null;

  const togglePriority = (entry: HistoryEntry) => {
    voiceController.setPriority(entry.id, entry.priority === 'immediate' ? 'normal' : 'immediate');
    onChanged();
  };

  const doApply = async (entry: HistoryEntry) => {
    try {
      await voiceController.apply(cardId, entry.id);
      setMessage('已应用并写入 -vocal=');
      onApplied();
    } catch (error) {
      setMessage(error instanceof Error ? error.message : String(error));
    }
  };

  const reveal = async (entry: HistoryEntry) => {
    if (!entry.audioPath) return;
    try {
      await revealItemInDir(entry.audioPath);
    } catch (error) {
      setMessage(error instanceof Error ? error.message : String(error));
    }
  };

  const exportAudio = async (entry: HistoryEntry) => {
    if (!entry.audioPath) return;
    const destination = await saveDialog({
      defaultPath: `${entry.characterName || 'voice'}-${entry.audioHash?.slice(0, 8) ?? 'audio'}.wav`,
      filters: [{ name: 'WAV 音频', extensions: ['wav'] }],
    });
    if (typeof destination !== 'string') return;
    const bytes = await fs.readBytes(entry.audioPath);
    await writeFile(destination, bytes);
    setMessage('已导出音频');
  };

  const renderEntry = (entry: HistoryEntry) => {
    const inFlight = entry.status === 'pending' || entry.status === 'running';
    const isSelected = entry.id === selectedId;
    return (
      <div
        key={entry.id}
        className={`history-item${isSelected ? ' selected' : ''}${entry.status === 'failed' ? ' failed' : ''}`}
        onClick={() => voiceController.selectHistory(cardId, entry.id)}
        onContextMenu={(event) => {
          event.preventDefault();
          setMenu({ x: event.clientX, y: event.clientY, entry });
        }}
      >
        {/* 基本信息与操作图标同一行 */}
        <div className="history-head">
          <span className={`history-kind ${entry.kind}`}>
            {entry.kind === 'test' ? '测试' : '生成'} x{entry.params.sampleSteps}
          </span>
          <span className="history-time">{formatTime(entry.createdAt)}</span>
          {entry.applied && (
            <span className="history-applied" title="已应用到脚本">
              <CheckmarkCircleRegular />
            </span>
          )}

          <span className="history-head-actions" onClick={(event) => event.stopPropagation()}>
            {inFlight ? (
              /*
                生成中的项**不提供播放/删除**: 还没有音频可放, 也不该在跑的时候把记录
                删掉。留下的两件事是"改优先级"(仅排队中, 单图标: 上=提升 / 下=降低)
                与"取消"。
              */
              <>
                {entry.status === 'pending' && (
                  <PriorityButton priority={entry.priority} onToggle={() => togglePriority(entry)} />
                )}
                <Button
                  size="small"
                  appearance="subtle"
                  icon={<DismissRegular />}
                  title={
                    entry.status === 'running' ? '取消（推理无法中断，返回后丢弃结果）' : '取消（还没开始，直接撤下）'
                  }
                  onClick={() => {
                    voiceController.cancel(entry.id);
                    onChanged();
                  }}
                />
              </>
            ) : (
              <>
                {entry.status === 'done' && entry.audioPath && <AudioButton path={entry.audioPath} />}
                <Button
                  size="small"
                  appearance="subtle"
                  icon={<DeleteRegular />}
                  title="删除记录"
                  onClick={() => {
                    voiceController.dropHistory(cardId, entry.id);
                    onChanged();
                  }}
                />
              </>
            )}
          </span>
        </div>

        <div className="history-text">{entry.text || '（空）'}</div>

        <div className="history-meta">
          <span>{entry.characterName || '未指定角色'}</span>
          {entry.alignment === 'speakerChanged' && <span className="history-warn">归属可能已变</span>}
          {entry.params.seed >= 0 && <span>种子 {entry.params.seed}</span>}
          {/* `响应` = 这一次请求的实测往返时间 (任务耗时); 音频时长对配音没有参考价值, 不显示 */}
          {entry.elapsed !== undefined && <span>响应 {formatDuration(entry.elapsed)}</span>}
        </div>

        {inFlight && (
          <div className="history-progress">
            <TaskProgress
              steps={entry.params.sampleSteps}
              text={entry.text}
              startedAt={entry.status === 'running' ? entry.startedAt : undefined}
            />
          </div>
        )}

        {entry.error && (
          /*
            报错只留一行摘要 + 一个入口: GSOV 的原始报错有几十行, 铺在卡片里会把
            整栏撑爆。点这一行打开弹窗看全文 (可复制)。
          */
          <button
            type="button"
            className="error-chip"
            title="查看完整报错"
            onClick={(event) => {
              event.stopPropagation();
              setErrorEntry(entry);
            }}
          >
            <ErrorCircleRegular className="error-chip-icon" />
            <span className="error-chip-text">{errorSummary(entry.error)}</span>
            <span className="error-chip-more">详情</span>
          </button>
        )}
      </div>
    );
  };

  return (
    <div className="voice-history" ref={containerRef}>
      <div className="history-toolbar">
        <span className="history-title">历史</span>
        <span className="history-count">
          {done.length} 已生成
          {active.length > 0 && ` · ${active.length} 进行中`}
          {failed.length > 0 && ` · ${failed.length} 未完成`}
        </span>
        <span className="voice-actions-spacer" />
        {/* 批量清理只留图标 (与工作台队列一致, 文案放悬浮提示); 只作用于**当前这一句** */}
        <Button
          size="small"
          appearance="subtle"
          icon={<FilterDismissRegular />}
          title="删除本句的全部测试记录"
          disabled={!entries.some((entry) => entry.kind === 'test')}
          onClick={() => {
            voiceController.dropHistoryByLine(cardId, line, 'test');
            onChanged();
          }}
        />
        <Button
          size="small"
          appearance="subtle"
          icon={<BroomRegular />}
          title="删除本句的全部记录（不影响已应用的 -vocal=）"
          disabled={entries.length === 0}
          onClick={() => {
            voiceController.dropHistoryByLine(cardId, line);
            onChanged();
          }}
        />
      </div>

      <div className="history-list" data-tick={voiceTick}>
        {entries.length === 0 && (
          <p className="history-empty">本句还没有记录。点击「测试」快速试听，或直接「生成」。</p>
        )}
        {entries.map(renderEntry)}
      </div>

      {unaligned > 0 && (
        <div className="history-unaligned">
          <span>{unaligned} 条记录未能对齐到任何语句</span>
          <Button
            size="small"
            appearance="subtle"
            icon={<BroomRegular />}
            title="删除这些无法对齐的残留记录"
            onClick={() => {
              voiceController.dropUnalignedHistory(cardId);
              onChanged();
            }}
          />
        </div>
      )}

      {appliedEntry && (
        <div className="history-applied-note">当前语句已应用：{appliedEntry.audioHash?.slice(0, 8)}</div>
      )}
      {message && <div className="history-message">{message}</div>}

      {errorEntry && (
        <VoiceErrorDialog
          error={errorEntry.error ?? null}
          description={`${errorEntry.characterName || '未指定角色'} · ${
            errorEntry.kind === 'test' ? '测试' : '生成'
          } x${errorEntry.params.sampleSteps} · ${formatTime(errorEntry.createdAt)}`}
          onClose={() => setErrorEntry(null)}
        />
      )}

      {menu && (
        <div
          className="context-menu"
          style={{ left: menu.x, top: menu.y }}
          onClick={(event) => event.stopPropagation()}
        >
          <button
            disabled={menu.entry.status !== 'done' || menu.entry.applied || menu.entry.line === null}
            onClick={() => {
              void doApply(menu.entry);
              setMenu(null);
            }}
          >
            <CheckmarkRegular /> 应用
          </button>
          <button
            disabled={!menu.entry.audioPath}
            onClick={() => {
              void reveal(menu.entry);
              setMenu(null);
            }}
          >
            <FolderOpenRegular /> 在文件夹中显示
          </button>
          <button
            disabled={!menu.entry.audioPath}
            onClick={() => {
              void exportAudio(menu.entry);
              setMenu(null);
            }}
          >
            <ArrowDownloadRegular /> 导出音频
          </button>
          <button
            disabled={menu.entry.line === null}
            title="用这一条记录的参数重新入队（不改动原记录）"
            onClick={() => {
              const task = voiceController.retryFromHistory(cardId, menu.entry.id);
              setMessage(task ? '已按该参数重新入队' : '该记录已无法对齐到语句，无法重试');
              setMenu(null);
              onChanged();
            }}
          >
            <ArrowSyncRegular /> 以此参数重试
          </button>
          {/* 排队中才有的两项: 未完成时"隐藏"而不是"禁用" —— 禁用项读起来像功能坏了 */}
          {menu.entry.status === 'pending' && (
            <button
              title={`当前：${menu.entry.priority === 'immediate' ? '优先' : '常规'}队列`}
              onClick={() => {
                togglePriority(menu.entry);
                setMenu(null);
              }}
            >
              {menu.entry.priority === 'immediate' ? <ArrowDownRegular /> : <ArrowUpRegular />}
              {menu.entry.priority === 'immediate' ? '降为常规' : '改为优先'}
            </button>
          )}
          {(menu.entry.status === 'pending' || menu.entry.status === 'running') && (
            <button
              onClick={() => {
                voiceController.cancel(menu.entry.id);
                setMenu(null);
                onChanged();
              }}
            >
              <DismissRegular /> 取消
            </button>
          )}
          <button
            className="danger-text"
            onClick={() => {
              voiceController.dropHistory(cardId, menu.entry.id);
              setMenu(null);
              onChanged();
            }}
          >
            <DeleteRegular /> 删除
          </button>
          <button
            className="danger-text"
            onClick={() => {
              voiceController.dropHistoryByLine(cardId, line, 'test');
              setMenu(null);
              onChanged();
            }}
          >
            <FilterDismissRegular /> 删除本句全部测试
          </button>
          <button
            className="danger-text"
            onClick={() => {
              voiceController.dropHistoryByLine(cardId, line);
              setMenu(null);
              onChanged();
            }}
          >
            <BroomRegular /> 删除本句全部
          </button>
        </div>
      )}
    </div>
  );
}

function formatTime(timestamp: number): string {
  const date = new Date(timestamp);
  const pad = (value: number) => String(value).padStart(2, '0');
  return `${pad(date.getMonth() + 1)}-${pad(date.getDate())} ${pad(date.getHours())}:${pad(date.getMinutes())}`;
}
