// This file is generated by AI.

// 路径 / URI 互转。LSP 使用标准 `file:///` URI, 前端文件操作使用系统路径。

/** 系统路径 -> LSP `file:///` URI (非 ASCII 百分号编码)。 */
export function toUri(filePath: string): string {
  if (filePath.startsWith('file://')) return filePath;
  const normalized = filePath.replace(/\\/g, '/');
  // encodeURI 编码空格与非 ASCII, 保留 `/` `:` 等结构字符
  const encoded = encodeURI(normalized);
  if (/^[a-zA-Z]:\//.test(encoded)) {
    return 'file:///' + encoded;
  }
  return 'file://' + encoded;
}

/** LSP `file:///` URI -> 系统路径。 */
export function fromUri(uri: string): string {
  if (!uri.startsWith('file://')) return uri;
  let path = uri.slice('file://'.length);
  try {
    // 用 decodeURIComponent 而非 decodeURI: decodeURI 不解码保留字符,
    // 如 Monaco Uri 序列化的 `c%3A` (盘符冒号) 与文件名中的 `%25`, 会导致路径还原失败。
    path = decodeURIComponent(path);
  } catch {
    // 解码失败时保持原样
  }
  // Windows: file:///C:/... -> C:/... (统一盘符大写, 匹配服务端工作区键)
  path = path.replace(/^\/?([a-zA-Z]):/, (_: string, drive: string) => drive.toUpperCase() + ':');
  return path.replace(/\//g, '\\');
}

/** 规范化路径作为文档/资源匹配键 (Windows 大小写不敏感)。 */
export function canonicalPath(path: string): string {
  return path.replace(/\\/g, '/').replace(/^([a-zA-Z]):/, (_, d: string) => d.toUpperCase() + ':');
}

/** URI -> 规范化键。 */
export function uriKey(uri: string): string {
  return canonicalPath(fromUri(uri));
}

/** 从场景文件路径提取场景名 (相对 `scene/` 目录)。 */
export function sceneNameFromPath(filePath: string): string {
  const normalized = filePath.replace(/\\/g, '/');
  const parts = normalized.split('/');
  const sceneIndex = parts.lastIndexOf('scene');
  if (sceneIndex === -1) return parts[parts.length - 1] ?? '';
  return parts.slice(sceneIndex + 1).join('/');
}
