// This file is generated by AI.

use path_tree::{Folder, Node};

#[test]
fn direct_iter_yields_sorted_children() {
    let mut folder = Folder::new();
    folder.insert("z", Node::Item(3));
    folder.insert("a", Node::Item(1));
    folder.insert("m", Node::Item(2));
    let names: Vec<&str> = folder.iter().map(|(n, _)| n).collect();
    assert_eq!(names, vec!["a", "m", "z"]);
}

#[test]
fn recursive_iter_visits_all_depth_first() {
    let folder = Folder::from_vec(vec![("a/1", 1), ("a/2", 2), ("b/3", 3)]);
    let got: Vec<String> = folder
        .iter_recursively()
        .map(|(p, _)| p.to_string())
        .collect();
    assert_eq!(got, vec!["a", "a/1", "a/2", "b", "b/3"]);
}

#[test]
fn recursive_iter_mut_modifies_values() {
    let mut folder = Folder::from_vec(vec![("a/1", 10), ("a/2", 20), ("b/3", 30)]);
    for (_p, node) in folder.iter_mut_recursively() {
        if let Some(v) = node.as_item_mut() {
            *v += 1;
        }
    }
    assert_eq!(folder.get("a/1").and_then(|n| n.as_item()), Some(&11));
    assert_eq!(folder.get("a/2").and_then(|n| n.as_item()), Some(&21));
    assert_eq!(folder.get("b/3").and_then(|n| n.as_item()), Some(&31));
}

#[test]
fn recursive_iter_on_empty_folder() {
    let folder: Folder<i32> = Folder::new();
    assert!(folder.iter_recursively().next().is_none());
}

#[test]
fn recursive_iter_pending_mechanism() {
    let mut folder = Folder::new();
    folder.insert("a/b", Node::Item(1));
    folder.insert("a/c/d", Node::Item(2));
    let mut it = folder.iter_mut_recursively();
    let first = it.next().unwrap();
    let second = it.next().unwrap();
    let first_norm = first.0.trim_start_matches('/').to_string();
    let second_norm = second.0.trim_start_matches('/').to_string();
    // both items should belong to prefix "a"
    assert!(first_norm.starts_with("a"));
    assert!(second_norm.starts_with("a"));
}

#[test]
fn iter_after_modification() {
    let mut folder = Folder::new();
    folder.insert("x/1", Node::Item(1));
    folder.insert("y/2", Node::Item(2));
    folder.remove("x/1");
    let names: Vec<String> = folder
        .iter_recursively()
        .map(|(p, _)| p.trim_start_matches('/').to_string())
        .collect();
    assert!(!names.iter().any(|s| s == "x/1"));
    assert!(names.iter().any(|s| s == "y/2"));
}

#[test]
fn node_iter_recursively_includes_root() {
    let folder = Folder::from_vec(vec![("a/1", 1), ("a/2", 2)]);
    let node = Node::Folder(folder);
    let paths: Vec<String> = node.iter_recursively().map(|(p, _)| p).collect();
    assert_eq!(paths, vec!["", "a", "a/1", "a/2"]);
}

#[test]
fn node_item_iter_recursively_only_self() {
    let node = Node::Item(42);
    let paths: Vec<String> = node.iter_recursively().map(|(p, _)| p).collect();
    assert_eq!(paths, vec![""]);
}
