// This file is generated by AI.

import { useEffect, useRef, useState } from 'react';
import Editor, { type Monaco } from '@monaco-editor/react';
import { type WasmModule } from './wasm';

interface EditorProps {
    value: string;
    onChange: (value: string) => void;
    onCursorChange?: (line: number) => void;
    wasm?: WasmModule | null;
}

export function SceneEditor({ value, onChange, onCursorChange, wasm }: EditorProps) {
    const editorRef = useRef<Parameters<NonNullable<Parameters<typeof Editor>[0]['onMount']>>[0] | null>(null);
    const monacoRef = useRef<Monaco | null>(null);
    const [isReady, setIsReady] = useState(false);

    const initLanguage = (monaco: Monaco) => {
        const languageId = 'webgal';

        if (monaco.languages.getLanguages().some((lang: { id: string }) => lang.id === languageId)) {
            return;
        }

        monaco.languages.register({
            id: languageId,
            extensions: ['.txt'],
            aliases: ['WebGAL', 'WebGAL Script'],
            mimetypes: ['application/webgalscript'],
        });

        monaco.languages.setLanguageConfiguration(languageId, {
            comments: { lineComment: ';' },
            brackets: [
                ['{', '}'],
                ['[', ']'],
                ['(', ')'],
            ],
            autoClosingPairs: [
                { open: '{', close: '}' },
                { open: '[', close: ']' },
                { open: '(', close: ')' },
            ],
        });

        const tokenTypes = wasm?.highlight_token_types?.() ?? [];
        const legend = {
            tokenTypes,
            tokenModifiers: [],
        };

        monaco.languages.registerDocumentSemanticTokensProvider(languageId, {
            getLegend: () => legend,
            provideDocumentSemanticTokens() {
                try {
                    const result = wasm?.highlightScene?.();
                    if (!result || result.length === 0) {
                        return { data: new Uint32Array(), resultId: null };
                    }
                    return { data: result, resultId: null };
                } catch (e) {
                    console.error('Highlight error:', e);
                    return { data: new Uint32Array(), resultId: null };
                }
            },
            releaseDocumentSemanticTokens() {
                // no-op
            },
        });
    };

    const handleMount = (editor: Parameters<NonNullable<Parameters<typeof Editor>[0]['onMount']>>[0], monaco: Monaco) => {
        editorRef.current = editor;
        monacoRef.current = monaco;
        monaco.editor.setTheme('vs-dark');
        setIsReady(true);

        if (wasm?.highlightScene) {
            initLanguage(monaco);
        }

        const model = editor.getModel();
        if (model) {
            monaco.editor.setModelLanguage(model, 'webgal');
        }
    };

    useEffect(() => {
        if (!editorRef.current) {
            return;
        }

        const disposable = editorRef.current.onDidChangeCursorPosition((event) => {
            onCursorChange?.(event.position.lineNumber - 1);
        });

        return () => disposable.dispose();
    }, [onCursorChange]);

    useEffect(() => {
        if (!wasm?.highlightScene || !monacoRef.current || !isReady) {
            return;
        }
        const alreadyRegistered = monacoRef.current.languages
            .getLanguages()
            .some((lang: { id: string }) => lang.id === 'webgal');
        if (!alreadyRegistered) {
            initLanguage(monacoRef.current);
        }

        const editor = editorRef.current;
        if (editor) {
            const model = editor.getModel();
            if (model) {
                // 强制刷新语义高亮
                monacoRef.current.editor.setModelLanguage(model, 'plaintext');
                monacoRef.current.editor.setModelLanguage(model, 'webgal');
                (editor as any).updateOptions({ 'semanticHighlighting.enabled': true });
            }
        }
    }, [wasm, isReady]);

    return (
        <Editor
            height="100%"
            language="webgal"
            theme="vs-dark"
            value={value}
            onChange={(nextValue) => onChange(nextValue ?? '')}
            onMount={handleMount}
            options={{
                minimap: { enabled: false },
                automaticLayout: true,
                fontSize: 14,
                wordWrap: 'on',
                'semanticHighlighting.enabled': true,
            }}
        />
    );
}
