// This file is generated by AI.

import Editor, { type Monaco } from '@monaco-editor/react';

interface EditorProps {
    value: string;
    onChange: (value: string) => void;
    onCursorChange?: (line: number) => void;
}

export function SceneEditor({ value, onChange, onCursorChange }: EditorProps) {
    const handleMount = (editor: Parameters<NonNullable<Parameters<typeof Editor>[0]['onMount']>>[0], monaco: Monaco) => {
        editor.onDidChangeCursorPosition((event) => {
            onCursorChange?.(event.position.lineNumber - 1);
        });
        monaco.editor.setTheme('vs-dark');
    };

    return (
        <Editor
            height="100%"
            language="plaintext"
            theme="vs-dark"
            value={value}
            onChange={(nextValue) => onChange(nextValue ?? '')}
            onMount={handleMount}
            options={{
                minimap: { enabled: false },
                automaticLayout: true,
                fontSize: 14,
                wordWrap: 'on',
            }}
        />
    );
}
