// This file is generated by AI.

import { useEffect, useRef } from 'react';
import Editor, { type Monaco } from '@monaco-editor/react';

interface EditorProps {
    value: string;
    onChange: (value: string) => void;
    onCursorChange?: (line: number) => void;
}

export function SceneEditor({ value, onChange, onCursorChange }: EditorProps) {
    const editorRef = useRef<Parameters<NonNullable<Parameters<typeof Editor>[0]['onMount']>>[0] | null>(null);

    const handleMount = (editor: Parameters<NonNullable<Parameters<typeof Editor>[0]['onMount']>>[0], monaco: Monaco) => {
        editorRef.current = editor;
        monaco.editor.setTheme('vs-dark');
    };

    useEffect(() => {
        if (!editorRef.current) {
            return;
        }

        const disposable = editorRef.current.onDidChangeCursorPosition((event) => {
            onCursorChange?.(event.position.lineNumber - 1);
        });

        return () => disposable.dispose();
    }, [onCursorChange]);

    return (
        <Editor
            height="100%"
            language="plaintext"
            theme="vs-dark"
            value={value}
            onChange={(nextValue) => onChange(nextValue ?? '')}
            onMount={handleMount}
            options={{
                minimap: { enabled: false },
                automaticLayout: true,
                fontSize: 14,
                wordWrap: 'on',
            }}
        />
    );
}
