// This file is generated by AI.

// Tauri 命令封装 (GPT-SoVITS 配音工作流)。
//
// 与后端 `service/voice` 模块一一对应。队列层的串行约束在前端 (`voice/controller.ts`) 保证。

import { Channel, invoke } from '@tauri-apps/api/core';

// -------- 类型 --------

export type GsvStatus = 'stopped' | 'starting' | 'ready' | 'error';

export type LaunchMode =
  | { kind: 'embedded'; program: string }
  | { kind: 'python'; program: string }
  | { kind: 'command'; program: string; args: string[] };

export interface LaunchConfig {
  /** 整合包根目录 (同时作为工作目录) */
  root: string;
  mode: LaunchMode;
  host: string;
  port: number;
  /** 控制脚本 (相对整合包根) */
  script: string;
  /** 推理配置 (相对整合包根) */
  inferConfig: string;
  extraArgs: string[];
}

export interface DetectedRuntime {
  valid: boolean;
  embeddedPython: string | null;
  hasEmbeddedPython: boolean;
  hasScript: boolean;
  hasInferConfig: boolean;
  issues: string[];
}

export type VoiceEvent = { type: 'log'; line: string } | { type: 'status'; status: GsvStatus; detail: string | null };

export interface VoiceStatus {
  status: GsvStatus;
  detail: string | null;
  baseUrl: string | null;
}

export interface SayLine {
  line: number;
  speaker: string | null;
  speakerInherited: boolean;
  text: string;
  vocal: string | null;
  figureId: string | null;
  figureSide: string | null;
  hash: string;
}

export interface LineEdit {
  line: number;
  expect: string | null;
  vocal: string | null;
}

export interface LineEditResult {
  line: number;
  text: string;
}

export interface AudioInfo {
  path: string;
  sampleRate: number;
  channels: number;
  duration: number;
  tooShort: boolean;
  tooLong: boolean;
}

export interface TrimRange {
  start: number;
  end: number;
  fromSilence: boolean;
}

export interface TrimSuggestion {
  suggested: TrimRange;
  speechRange: TrimRange | null;
  duration: number;
  withinLimit: boolean;
}

export interface Waveform {
  columns: number;
  duration: number;
  mins: number[];
  maxs: number[];
}

export interface NormalizedRef {
  path: string;
  hash: string;
  duration: number;
  sampleRate: number;
  padded: boolean;
  trimmed: boolean;
}

export interface ModelChoice {
  gptWeights?: string | null;
  sovitsWeights?: string | null;
}

export interface ReferenceAudio {
  file: string;
  hash: string;
  duration: number;
  sampleRate: number;
  text: string;
  language: string;
  tags: string[];
  createdAt: number;
}

export interface Character {
  id: string;
  name: string;
  aliases: string[];
  description: string;
  language: string;
  references: ReferenceAudio[];
  model: ModelChoice | null;
  starred: boolean;
  enabled: boolean;
  createdAt: number;
  updatedAt: number;
}

export interface NewCharacter {
  name: string;
  aliases: string[];
  description: string;
  language: string;
}

export interface CacheEntry {
  hash: string;
  path: string;
  size: number;
  modifiedAt: number;
}

export interface VocalReference {
  vocal: string;
  path: string;
  scene: string;
  line: number;
  exists: boolean;
}

export interface SynthesizeRequest {
  text: string;
  textLang: string;
  refAudioPath: string;
  promptText: string;
  promptLang: string;
  sampleSteps: number;
  temperature: number;
  speedFactor: number;
  topK: number;
  topP: number;
  repetitionPenalty: number;
  textSplitMethod?: string;
  seed?: number;
}

export interface SynthesizeResult {
  entry: CacheEntry;
  duration: number;
  sampleRate: number;
}

export interface HistoryKey {
  id: string;
  speaker: string | null;
  text: string;
}

export interface DialogueKey {
  speaker: string | null;
  text: string;
  index: number;
}

export type AlignmentKind = 'exact' | 'speakerChanged' | 'ordered' | 'unmatched';

export interface Alignment {
  id: string;
  index: number | null;
  kind: AlignmentKind;
}

export interface AlignmentReport {
  alignments: Alignment[];
  exact: number;
  speakerChanged: number;
  ordered: number;
  unmatched: number;
}

// -------- 启动器 --------

export function voiceDetectRuntime(root: string): Promise<DetectedRuntime> {
  return invoke<DetectedRuntime>('voice_detect_runtime', { root });
}

export function voiceDefaultLaunchConfig(root: string): Promise<LaunchConfig> {
  return invoke<LaunchConfig>('voice_default_launch_config', { root });
}

export function voiceLaunch(config: LaunchConfig, onEvent: (event: VoiceEvent) => void): Promise<void> {
  const channel = new Channel<VoiceEvent>();
  channel.onmessage = onEvent;
  return invoke<void>('voice_launch', { config, onEvent: channel });
}

export function voiceShutdown(): Promise<void> {
  return invoke<void>('voice_shutdown');
}

export function voiceStatus(): Promise<VoiceStatus> {
  return invoke<VoiceStatus>('voice_status');
}

export function voiceTakeLogs(): Promise<string[]> {
  return invoke<string[]>('voice_take_logs');
}

/** 就绪探测: 返回 true 表示 API 已可服务 (状态同步置为 ready)。 */
export function voiceProbe(host?: string, port?: number): Promise<boolean> {
  return invoke<boolean>('voice_probe', { host, port });
}

// -------- 推理 --------

export function voiceSynthesize(request: SynthesizeRequest): Promise<SynthesizeResult> {
  return invoke<SynthesizeResult>('voice_synthesize', { request });
}

/** 显式切换 GSOV 权重 (高代价操作, 由用户主动触发)。 */
export function voiceSetModel(gptWeights?: string | null, sovitsWeights?: string | null): Promise<void> {
  return invoke<void>('voice_set_model', { gptWeights, sovitsWeights });
}

// -------- 场景 --------

export function voiceParseScene(content: string): Promise<SayLine[]> {
  return invoke<SayLine[]>('voice_parse_scene', { content });
}

export function voiceApplyScene(content: string, edits: LineEdit[]): Promise<string> {
  return invoke<string>('voice_apply_scene', { content, edits });
}

export function voiceApplyLines(content: string, edits: LineEdit[]): Promise<LineEditResult[]> {
  return invoke<LineEditResult[]>('voice_apply_lines', { content, edits });
}

// -------- 音频 --------

export function voiceProbeAudio(path: string): Promise<AudioInfo> {
  return invoke<AudioInfo>('voice_probe_audio', { path });
}

export function voiceTrimSuggestion(path: string): Promise<TrimSuggestion> {
  return invoke<TrimSuggestion>('voice_trim_suggestion', { path });
}

export function voiceWaveform(path: string): Promise<Waveform> {
  return invoke<Waveform>('voice_waveform', { path });
}

export function voiceNormalizeReference(
  source: string,
  destination: string,
  start?: number,
  end?: number
): Promise<NormalizedRef> {
  return invoke<NormalizedRef>('voice_normalize_reference', { source, destination, start, end });
}

/** 读取音频为 data URL (试听用)。 */
export function voiceReadAudio(path: string): Promise<string> {
  return invoke<string>('voice_read_audio', { path });
}

// -------- 角色库 --------

export function voiceListCharacters(): Promise<Character[]> {
  return invoke<Character[]>('voice_list_characters');
}

export function voiceLoadCharacter(id: string): Promise<Character> {
  return invoke<Character>('voice_load_character', { id });
}

export function voiceSaveCharacter(character: Character): Promise<Character> {
  return invoke<Character>('voice_save_character', { character });
}

export function voiceRemoveCharacter(id: string): Promise<void> {
  return invoke<void>('voice_remove_character', { id });
}

export function voiceCreateCharacter(input: NewCharacter): Promise<Character> {
  return invoke<Character>('voice_create_character', { input });
}

export function voiceAddReference(
  id: string,
  source: string,
  text: string,
  language: string,
  tags: string[],
  start?: number,
  end?: number
): Promise<Character> {
  return invoke<Character>('voice_add_reference', { id, source, text, language, tags, start, end });
}

export function voiceRemoveReference(id: string, hash: string): Promise<Character> {
  return invoke<Character>('voice_remove_reference', { id, hash });
}

export function voiceExportCharacter(id: string, destination: string): Promise<void> {
  return invoke<void>('voice_export_character', { id, destination });
}

export function voiceImportCharacter(source: string): Promise<Character> {
  return invoke<Character>('voice_import_character', { source });
}

// -------- 缓存 / 引用扫描 / 对齐 --------

export function voiceListCache(): Promise<CacheEntry[]> {
  return invoke<CacheEntry[]>('voice_list_cache');
}

export function voiceStoreCache(source: string): Promise<CacheEntry> {
  return invoke<CacheEntry>('voice_store_cache', { source });
}

export function voiceDropCache(hashes: string[]): Promise<number> {
  return invoke<number>('voice_drop_cache', { hashes });
}

export function voiceScanReferences(project: string): Promise<VocalReference[]> {
  return invoke<VocalReference[]>('voice_scan_references', { project });
}

export function voiceRealign(history: HistoryKey[], dialogues: DialogueKey[]): Promise<AlignmentReport> {
  return invoke<AlignmentReport>('voice_realign', { history, dialogues });
}
