// This file is partially generated by AI.

//! 标识符收集
//!
//! 从语句规则与变量表出发, 收集符号在项目中的出现位置 (定义与引用), 供引用查询, 资源链接,
//! 重命名等功能复用.
//!
//! # 与识别层的关系
//! * 识别层 [`recognize_ident`](super::recognize::recognize_ident) 回答"光标处是什么符号";
//! * 本模块回答"某符号出现在哪里", 两套规则各自独立但覆盖同一组位置
//!   (`sentence_collection_matches_recognition` 测试会给出一致性检查).
//!
//! # 变量
//! 变量由实时维护的变量表提供 (见 [`crate::project::VariableTable`]), 不参与语句收集.

use std::ops;

use derive_more::{Deref, Into, IntoIterator};
use lsp_types::*;
use path_tree::{canonicalize, join};
use webgal_language_core::{
    element::ChoiceSplit,
    resource::{FigureKind, ResourceKind},
    sentence::{
        Scene, Sentence, SentenceInfo, is_call_scene_variable_argument, is_implicit_vocal_argument,
    },
    util::span_of,
};

use crate::{
    project::Project,
    service::{references::recognize::Ident, variable_location_to_range},
};

/// 引用位置列表
///
/// 每个元素为标识符所在的场景路径 (相对场景根目录) 及语句内区间.
#[derive(Debug, Clone, Default, Eq, PartialEq, Into, IntoIterator, Deref)]
pub struct ReferenceList(Vec<(String, Range)>);

impl ReferenceList {
    pub fn to_locations(&self, project_root: &str) -> Vec<Location> {
        let scene_root = join(project_root, "scene");
        self.iter()
            .map(|(scene, span)| Location {
                uri: join(&scene_root, scene).parse().unwrap(),
                range: *span,
            })
            .collect()
    }
}

// -------- 收集工具 --------

/// 标识符出现位置
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct IdentOccurrence<'a> {
    /// 符号
    pub ident: Ident<'a>,
    /// 名称在语句中的区间 (UTF-8 字节)
    pub span: ops::Range<usize>,
    /// 是否为定义位置
    pub definition: bool,
}

impl IdentOccurrence<'_> {
    /// 语句内出现位置 -> LSP 区间
    pub(super) fn to_range(&self, line: usize) -> Range {
        Range {
            start: Position {
                line: line as u32,
                character: self.span.start as u32,
            },
            end: Position {
                line: line as u32,
                character: self.span.end as u32,
            },
        }
    }
}

/// 收集语句中出现的标识符
///
/// # Returns
/// 语句内的出现位置, 按语句类型 / 主参数 / 参数名 / 参数值 / 分支跳转目标的顺序.
///
/// # Behavior
/// * 变量由变量表提供, 不在此列;
/// * 需要校验存在性的位置 (`setAnimation` / `-enter` / `-exit` / `choose` 目标) 只在符号存在时收集,
///   与识别层保持一致.
pub fn collect_sentence_idents<'a>(
    info: &'a SentenceInfo<'a>,
    project: &Project,
) -> Vec<IdentOccurrence<'a>> {
    let mut idents = Vec::new();
    collect_command_idents(info, &mut idents);
    collect_content_idents(info, project, &mut idents);
    collect_argument_idents(info, project, &mut idents);
    collect_choose_idents(info, project, &mut idents);
    idents
}

/// 收集场景中出现的标识符
///
/// # Returns
/// (语句行号, 出现位置) 列表.
pub fn collect_scene_idents<'a>(
    scene: &'a Scene,
    project: &Project,
) -> Vec<(usize, IdentOccurrence<'a>)> {
    scene
        .sentences()
        .iter()
        .enumerate()
        .flat_map(|(line, info)| {
            collect_sentence_idents(info, project)
                .into_iter()
                .map(move |occurrence| (line, occurrence))
        })
        .collect()
}

/// 收集项目中出现的标识符
///
/// # Returns
/// (场景路径, 语句行号, 出现位置) 列表.
pub fn collect_project_idents<'a>(
    project: &'a Project,
) -> Vec<(String, usize, IdentOccurrence<'a>)> {
    let mut idents = Vec::new();
    for (scene_path, node) in project.resource().scene.iter_recursively() {
        let Some(scene) = node.as_item() else {
            continue;
        };
        for (line, occurrence) in collect_scene_idents(scene, project) {
            idents.push((scene_path.clone(), line, occurrence));
        }
    }
    idents
}

// -------- 引用查询 --------

/// 收集项目内指定标识符的定义
///
/// # Returns
/// * 资源没有脚本内的定义位置 (其定义即资源文件本身), 返回 `None`;
/// * 变量不在变量表中时返回 `None`;
/// * 名称为空的标识符不构成可查询符号, 返回 `None`.
pub fn collect_ident_definition(ident: Ident, project: &Project) -> Option<ReferenceList> {
    match ident {
        Ident::Resource(..) => None,

        // 变量由实时维护的变量表提供定义
        Ident::Variable(name) => Some(ReferenceList(
            project
                .variable()
                .get(name)?
                .definitions
                .iter()
                .map(|definition| &definition.location)
                .map(|location| (location.scene.clone(), variable_location_to_range(location)))
                .collect(),
        )),

        ident if ident.name().is_empty() => None,

        ident => Some(ReferenceList(
            collect_project_idents(project)
                .into_iter()
                .filter(|(_, _, occurrence)| occurrence.ident == ident && occurrence.definition)
                .map(|(scene, line, occurrence)| (scene, occurrence.to_range(line)))
                .collect(),
        )),
    }
}

/// 收集项目内指定标识符的引用
///
/// # Behavior
/// * 变量由实时维护的变量表提供引用 (含定义位置);
/// * 其余标识符遍历所有场景收集全部出现位置 (含定义位置).
///
/// # Returns
/// 变量不在变量表中, 或名称为空时返回 `None`.
pub fn collect_ident_references(ident: Ident, project: &Project) -> Option<ReferenceList> {
    match ident {
        Ident::Variable(name) => Some(ReferenceList(
            project
                .variable()
                .get(name)?
                .iter_references()
                .map(|location| (location.scene.clone(), variable_location_to_range(location)))
                .collect(),
        )),

        ident if ident.name().is_empty() => None,

        ident => Some(ReferenceList(
            collect_project_idents(project)
                .into_iter()
                .filter(|(_, _, occurrence)| occurrence.ident == ident)
                .map(|(scene, line, occurrence)| (scene, occurrence.to_range(line)))
                .collect(),
        )),
    }
}

// -------- 语句收集 --------

/// 记录一个出现位置
///
/// # Panics
/// 名称需为语句的子串 (标识符均取自语句本身或语句的切片).
fn push_ident<'a>(
    line: &str,
    idents: &mut Vec<IdentOccurrence<'a>>,
    ident: Ident<'a>,
    definition: bool,
) {
    idents.push(IdentOccurrence {
        span: span_of(line, ident.name()),
        ident,
        definition,
    });
}

/// 收集语句类型位上的标识符 (对话人物)
///
/// # Behavior
/// * 无主参数时语句类型即对话正文, 与 `say` 语句类型一样不构成对话人物;
/// * 语句类型位整体为变量插值时按变量处理 (由变量表提供).
fn collect_command_idents<'a>(info: &'a SentenceInfo<'a>, idents: &mut Vec<IdentOccurrence<'a>>) {
    let command = info.primary.command;
    if !matches!(info.sentence, Sentence::Say(_))
        || info.primary.content.is_none()
        || command == "say"
        || is_interpolation(command)
    {
        return;
    }

    // 对话人物没有声明位置, 其全部出现位置都视为定义
    push_ident(info.content, idents, Ident::Speaker(command), true);
}

/// 收集主参数上的标识符
fn collect_content_idents<'a>(
    info: &'a SentenceInfo<'a>,
    project: &Project,
    idents: &mut Vec<IdentOccurrence<'a>>,
) {
    let line = info.content;
    let Some(content) = info.primary.content else {
        return;
    };

    match &info.sentence {
        // 主参数为文本 / 表达式: 其中的变量由变量表提供
        Sentence::Say(_)
        | Sentence::Intro(_)
        | Sentence::Return(_)
        | Sentence::SetVariable(_)
        | Sentence::GetUserInput(_)
        | Sentence::Choose(_) => {}

        // 常规演出
        Sentence::ChangeBackground(s) if s.background.is_some() => push_ident(
            line,
            idents,
            Ident::Resource(ResourceKind::Background, content),
            false,
        ),
        Sentence::ChangeFigure(s) if s.figure.is_some() => push_ident(
            line,
            idents,
            // 立绘路径可能带有 `?type=` 后缀
            Ident::Resource(ResourceKind::Figure, FigureKind::from_path(content).1),
            false,
        ),
        Sentence::Bgm(s) if s.bgm.is_some() => push_ident(
            line,
            idents,
            Ident::Resource(ResourceKind::Bgm, content),
            false,
        ),
        Sentence::PlayVideo(_) => push_ident(
            line,
            idents,
            Ident::Resource(ResourceKind::Video, content),
            false,
        ),
        Sentence::PlayEffect(s) if s.vocal.is_some() => push_ident(
            line,
            idents,
            Ident::Resource(ResourceKind::Vocal, content),
            false,
        ),

        // 特殊演出
        Sentence::MiniAvatar(s) if s.avatar.is_some() => push_ident(
            line,
            idents,
            Ident::Resource(ResourceKind::Figure, content),
            false,
        ),

        // 场景与分支
        Sentence::SetAnimation(_) if project.resource().contains_animation(content) => push_ident(
            line,
            idents,
            Ident::Resource(ResourceKind::Animation, content),
            false,
        ),
        Sentence::CallScene(_) | Sentence::ChangeScene(_) => push_ident(
            line,
            idents,
            Ident::Resource(ResourceKind::Scene, content),
            false,
        ),
        Sentence::Label(_) => push_ident(line, idents, Ident::Label(content), true),
        Sentence::JumpLabel(_) => push_ident(line, idents, Ident::Label(content), false),

        // 鉴赏
        Sentence::UnlockCg(_) => push_ident(
            line,
            idents,
            Ident::Resource(ResourceKind::Background, content),
            false,
        ),
        Sentence::UnlockBgm(_) => push_ident(
            line,
            idents,
            Ident::Resource(ResourceKind::Bgm, content),
            false,
        ),

        _ => {}
    }
}

/// 收集参数上的标识符 (参数名与参数值)
fn collect_argument_idents<'a>(
    info: &'a SentenceInfo<'a>,
    project: &Project,
    idents: &mut Vec<IdentOccurrence<'a>>,
) {
    let line = info.content;

    for &(name, value) in &info.primary.arguments {
        // 对话的隐式语音参数: 参数名即语音名
        if matches!(info.sentence, Sentence::Say(_)) && is_implicit_vocal_argument(name) {
            push_ident(
                line,
                idents,
                Ident::Resource(ResourceKind::Vocal, name),
                false,
            );
        }

        let Some(value) = value else {
            continue;
        };

        match &info.sentence {
            // 变量: 由变量表提供 (`writeReturnTo` 与传参名都是变量定义)
            _ if name == "when" => {}
            Sentence::CallScene(_) if is_call_scene_variable_argument(name) => {}
            Sentence::CallScene(_) if name == "writeReturnTo" => {}

            // 动画: 动画目录下的实际位置带有 `.json` 后缀
            _ if matches!(name, "enter" | "exit") => {
                if project.resource().contains_animation(value) {
                    push_ident(
                        line,
                        idents,
                        Ident::Resource(ResourceKind::Animation, value),
                        false,
                    );
                }
            }

            // 鉴赏
            _ if name == "series" => push_ident(line, idents, Ident::Series(value), true),
            _ if name == "unlockname" => push_ident(line, idents, Ident::Unlockname(value), true),
            Sentence::UnlockCg(_) | Sentence::UnlockBgm(_) if name == "name" => {
                push_ident(line, idents, Ident::Unlockname(value), false)
            }

            // 对话
            Sentence::Say(_) if name == "speaker" => {
                push_ident(line, idents, Ident::Speaker(value), true)
            }
            Sentence::Say(_) if name == "vocal" => push_ident(
                line,
                idents,
                Ident::Resource(ResourceKind::Vocal, value),
                false,
            ),
            Sentence::Say(_) if name == "figureId" => {
                push_ident(line, idents, Ident::Object(value), false)
            }

            // 立绘
            Sentence::ChangeFigure(_) if name == "id" => {
                push_ident(line, idents, Ident::Object(value), true)
            }
            Sentence::ChangeFigure(_)
                if matches!(
                    name,
                    "mouthOpen" | "mouthHalfOpen" | "mouthClose" | "eyesOpen" | "eyesClose"
                ) =>
            {
                push_ident(
                    line,
                    idents,
                    Ident::Resource(ResourceKind::Figure, value),
                    false,
                )
            }

            // 音效 / 背景 / 舞台对象
            Sentence::PlayEffect(_) if name == "id" => {
                push_ident(line, idents, Ident::Sound(value), true)
            }
            Sentence::Intro(_) if name == "backgroundImage" => push_ident(
                line,
                idents,
                Ident::Resource(ResourceKind::Background, value),
                false,
            ),
            Sentence::SetAnimation(_)
            | Sentence::SetComplexAnimation(_)
            | Sentence::SetTransform(_)
            | Sentence::SetTempAnimation(_)
            | Sentence::SetTransition(_)
                if name == "target" =>
            {
                push_ident(line, idents, Ident::Object(value), false)
            }

            _ => {}
        }
    }
}

/// 收集分支跳转目标上的标识符 (场景或标签)
fn collect_choose_idents<'a>(
    info: &'a SentenceInfo<'a>,
    project: &Project,
    idents: &mut Vec<IdentOccurrence<'a>>,
) {
    let Sentence::Choose(_) = info.sentence else {
        return;
    };
    let Some(content) = info.primary.content else {
        return;
    };

    let resource = project.resource();
    for target in ChoiceSplit::new(content).filter_map(|choice| choice.target) {
        if resource.scene.contains(target)
            || canonicalize(target).is_some_and(|path| resource.scene.contains(&path))
        {
            push_ident(
                info.content,
                idents,
                Ident::Resource(ResourceKind::Scene, target),
                false,
            );
        } else if project.ident().label.contains(&target.to_string()) {
            push_ident(info.content, idents, Ident::Label(target), false);
        }
    }
}

/// 语句类型位是否为整体变量插值
fn is_interpolation(command: &str) -> bool {
    command
        .strip_prefix('{')
        .and_then(|rest| rest.strip_suffix('}'))
        .is_some_and(|name| !name.contains(['{', '}']))
}

#[cfg(test)]
mod tests {
    use webgal_language_core::resource::{Config, ResourceKind};

    use crate::service::{
        definition,
        references::{recognize::recognize_ident, references},
    };

    use super::*;

    /// 构建测试项目
    fn project(scenes: &[(&str, &str)]) -> Project {
        let mut project = Project::new(Config::default());
        for (path, content) in scenes {
            project
                .insert(&format!("scene/{path}"), || Ok(content.to_string()))
                .unwrap();
        }
        project
    }

    /// 构建测试项目: (相对项目根的文件路径, 文件内容)
    fn project_files(files: &[(&str, &str)]) -> Project {
        let mut project = Project::new(Config::default());
        for (path, content) in files {
            project.insert(path, || Ok(content.to_string())).unwrap();
        }
        project
    }

    fn position(line: u32, character: u32) -> Position {
        Position { line, character }
    }

    /// 定位名称在场景某行中的首次出现位置
    fn name_at(scene: &str, line: u32, name: &str) -> Position {
        let text = scene.lines().nth(line as usize).expect("行应在场景中");
        position(line, text.find(name).expect("名称应在语句中") as u32)
    }

    /// 定位名称在场景某行中的区间
    fn name_span(scene: &str, line: u32, name: &str) -> Range {
        let Position { line, character } = name_at(scene, line, name);
        Range {
            start: position(line, character),
            end: position(line, character + name.len() as u32),
        }
    }

    /// 收集定义位置
    fn collect_definitions(project: &Project, scene: &str, at: Position) -> Vec<(String, Range)> {
        definition(scene, at, project)
            .unwrap_or_default()
            .into_iter()
            .collect()
    }

    /// 收集引用位置
    fn collect_references(project: &Project, scene: &str, at: Position) -> Vec<(String, Range)> {
        references(scene, at, project)
            .unwrap_or_default()
            .into_iter()
            .collect()
    }

    /// 按场景与区间排序 (用于与收集顺序无关的比较)
    fn sorted(mut locations: Vec<(String, Range)>) -> Vec<(String, Range)> {
        let key = |(scene, range): &(String, Range)| {
            (
                scene.clone(),
                range.start.line,
                range.start.character,
                range.end.line,
                range.end.character,
            )
        };
        locations.sort_by_key(|location| key(location));
        locations
    }

    // -------- 变量 --------

    #[test]
    fn variable_uses_variable_table() {
        let scene = "setVar:hp=100;\nsay:hello -when=hp;";
        let project = project(&[("1.txt", scene)]);
        let at = name_at(scene, 1, "hp");
        let location = |range| ("1.txt".to_string(), range);

        assert_eq!(
            collect_definitions(&project, "1.txt", at),
            vec![location(name_span(scene, 0, "hp"))]
        );
        assert_eq!(
            collect_references(&project, "1.txt", at),
            vec![
                location(name_span(scene, 0, "hp")),
                location(name_span(scene, 1, "hp")),
            ]
        );
    }

    #[test]
    fn unknown_variable_is_not_collected() {
        // `hp` 从未被定义, 不进入变量表, 此时不识别为变量
        let scene = "say:hello -when=hp;";
        let project = project(&[("1.txt", scene)]);
        let at = name_at(scene, 0, "hp");

        assert!(definition("1.txt", at, &project).is_none());
        assert!(references("1.txt", at, &project).is_none());
    }

    // -------- 标签 --------

    #[test]
    fn label_definition_is_label_sentence() {
        let scene = "label:start;\njumpLabel:start;";
        let project = project(&[("1.txt", scene)]);
        let at = name_at(scene, 0, "start");
        let location = |range| ("1.txt".to_string(), range);

        assert_eq!(
            collect_definitions(&project, "1.txt", at),
            vec![location(name_span(scene, 0, "start"))]
        );
        // 引用包含定义位置
        assert_eq!(
            collect_references(&project, "1.txt", at),
            vec![
                location(name_span(scene, 0, "start")),
                location(name_span(scene, 1, "start")),
            ]
        );
    }

    #[test]
    fn label_without_definition_is_empty() {
        let scene = "jumpLabel:nowhere;";
        let project = project(&[("1.txt", scene)]);
        let at = name_at(scene, 0, "nowhere");

        assert!(collect_definitions(&project, "1.txt", at).is_empty());
        assert_eq!(collect_references(&project, "1.txt", at).len(), 1);
    }

    // -------- 舞台对象 --------

    #[test]
    fn object_definition_is_id_argument() {
        let scene = concat!(
            "changeFigure:model.json -id=chara;\n",
            r#"setTransform:{"position":{"x":0}} -target=chara;"#,
            "\n",
            "say:你好 -figureId=chara;",
        );
        let project = project(&[("1.txt", scene)]);
        let at = name_at(scene, 1, "chara"); // `-target` 参数值
        let location = |line| ("1.txt".to_string(), name_span(scene, line, "chara"));

        assert_eq!(
            collect_definitions(&project, "1.txt", at),
            vec![location(0)]
        );
        assert_eq!(
            collect_references(&project, "1.txt", at),
            vec![location(0), location(1), location(2)]
        );
    }

    // -------- 音效 --------

    #[test]
    fn sound_definition_is_id_argument() {
        let scene = "playEffect:sfx.wav -id=hit;";
        let project = project(&[("1.txt", scene)]);
        let at = name_at(scene, 0, "hit");
        let expected = vec![("1.txt".to_string(), name_span(scene, 0, "hit"))];

        assert_eq!(collect_definitions(&project, "1.txt", at), expected);
        assert_eq!(collect_references(&project, "1.txt", at), expected);
    }

    // -------- 对话人物 --------

    #[test]
    fn speaker_occurrences_are_all_definitions() {
        let scene = "chara:你好;\n你好 -speaker=chara;";
        let project = project(&[("1.txt", scene)]);
        let at = name_at(scene, 0, "chara");
        let expected = vec![
            ("1.txt".to_string(), name_span(scene, 0, "chara")),
            ("1.txt".to_string(), name_span(scene, 1, "chara")),
        ];

        assert_eq!(collect_definitions(&project, "1.txt", at), expected);
        assert_eq!(collect_references(&project, "1.txt", at), expected);
    }

    // -------- 鉴赏 --------

    #[test]
    fn unlockname_definition_is_unlockname_argument() {
        let scene = "changeBg:bg.png -unlockname=home -series=cg;\nunlockCg:cg.png -name=home;";
        let project = project(&[("1.txt", scene)]);
        let at = name_at(scene, 0, "home");
        let location = |line| ("1.txt".to_string(), name_span(scene, line, "home"));

        assert_eq!(
            collect_definitions(&project, "1.txt", at),
            vec![location(0)]
        );
        assert_eq!(
            collect_references(&project, "1.txt", at),
            vec![location(0), location(1)]
        );
    }

    #[test]
    fn series_definition_is_series_argument() {
        let scene = "changeBg:bg.png -unlockname=home -series=cg;";
        let project = project(&[("1.txt", scene)]);
        let at = name_at(scene, 0, "cg");
        let expected = vec![("1.txt".to_string(), name_span(scene, 0, "cg"))];

        assert_eq!(collect_definitions(&project, "1.txt", at), expected);
        assert_eq!(collect_references(&project, "1.txt", at), expected);
    }

    // -------- 分支选项 --------

    #[test]
    fn choose_scene_target_is_collected() {
        let scene = "choose:去往A:2.txt|留在这里:3.txt;";
        let other = "changeScene:2.txt;";
        let project = project(&[("1.txt", scene), ("2.txt", other), ("3.txt", "")]);
        let at = name_at(scene, 0, "2.txt");

        // 场景资源没有脚本内定义位置, 引用包含分支目标与切换语句
        assert_eq!(collect_definitions(&project, "1.txt", at), Vec::new());
        assert_eq!(
            sorted(collect_references(&project, "1.txt", at)),
            sorted(vec![
                ("1.txt".to_string(), name_span(scene, 0, "2.txt")),
                ("2.txt".to_string(), name_span(other, 0, "2.txt")),
            ])
        );
    }

    #[test]
    fn choose_label_target_is_collected() {
        let scene = "label:start;\nchoose:去往A:start|留在这里:2.txt;";
        let project = project(&[("1.txt", scene), ("2.txt", "")]);
        let at = name_at(scene, 1, "start");

        assert_eq!(
            collect_definitions(&project, "1.txt", at),
            vec![("1.txt".to_string(), name_span(scene, 0, "start"))]
        );
        assert_eq!(
            collect_references(&project, "1.txt", at),
            vec![
                ("1.txt".to_string(), name_span(scene, 0, "start")),
                ("1.txt".to_string(), name_span(scene, 1, "start")),
            ]
        );
    }

    // -------- 资源 --------

    #[test]
    fn resource_has_no_definition() {
        let scene = "changeBg:bg.png;";
        let project = project(&[("1.txt", scene)]);
        let at = name_at(scene, 0, "bg.png");

        assert_eq!(collect_definitions(&project, "1.txt", at), Vec::new());
        assert_eq!(
            collect_references(&project, "1.txt", at),
            vec![("1.txt".to_string(), name_span(scene, 0, "bg.png"))]
        );
    }

    #[test]
    fn scene_resource_references_across_all_scenes() {
        let first = "changeScene:1.txt;";
        let second = "callScene:1.txt;";
        let project = project(&[("1.txt", first), ("2.txt", second)]);
        let locations = collect_references(&project, "1.txt", name_at(first, 0, "1.txt"));

        assert_eq!(
            sorted(locations),
            sorted(vec![
                ("1.txt".to_string(), name_span(first, 0, "1.txt")),
                ("2.txt".to_string(), name_span(second, 0, "1.txt")),
            ])
        );
    }

    // -------- 边界 --------

    #[test]
    fn empty_name_is_not_collectable() {
        let project = project(&[("1.txt", "changeBg:bg.png;")]);

        assert!(collect_ident_definition(Ident::Speaker(""), &project).is_none());
        assert!(collect_ident_references(Ident::Speaker(""), &project).is_none());

        let path = Ident::Resource(ResourceKind::Background, "");
        assert!(collect_ident_references(path, &project).is_none());
    }

    #[test]
    fn label_definition_keeps_first_scene_order() {
        let first = "label:start;";
        let second = "jumpLabel:start;";
        let project = project(&[("1.txt", first), ("2.txt", second)]);
        let definitions = collect_definitions(&project, "2.txt", name_at(second, 0, "start"));

        assert_eq!(
            definitions,
            vec![("1.txt".to_string(), name_span(first, 0, "start"))]
        );
    }

    // -------- 语句收集 --------

    /// 语句收集的期望: (符号, 名称, 是否定义)
    type ExpectedIdent<'a> = (Ident<'a>, &'a str, bool);

    /// 构建带资源文件的测试项目
    fn resource_project(line: &str) -> Project {
        project_files(&[
            ("scene/1.txt", line),
            ("background/bg.png", "[]"),
            ("background/cg.png", "[]"),
            ("figure/chara.skel", "[]"),
            ("figure/open.png", "[]"),
            ("bgm/theme.mp3", "[]"),
            ("vocal/sfx.wav", "[]"),
            ("video/op.mp4", "[]"),
            ("animation/fadeIn.json", "[]"),
            ("animation/fadeOut.json", "[]"),
            ("scene/2.txt", ""),
        ])
    }

    /// 断言语句收集结果
    fn assert_sentence_idents(line: &str, project: &Project, expected: &[ExpectedIdent]) {
        let scene = Scene::from_str(line);
        let actual: Vec<_> = collect_sentence_idents(&scene.sentences()[0], project)
            .into_iter()
            .map(|occurrence| {
                (
                    occurrence.ident,
                    &line[occurrence.span.clone()],
                    occurrence.definition,
                )
            })
            .collect();

        assert_eq!(actual, expected, "line: {line:?}");
    }

    #[test]
    fn collects_sentence_idents() {
        // 常规演出: 主参数与 `-enter` / `-exit` 均按资源收集
        let line = "changeBg:bg.png -enter=fadeIn -unlockname=home -series=cg;";
        assert_sentence_idents(
            line,
            &resource_project(line),
            &[
                (
                    Ident::Resource(ResourceKind::Background, "bg.png"),
                    "bg.png",
                    false,
                ),
                (
                    Ident::Resource(ResourceKind::Animation, "fadeIn"),
                    "fadeIn",
                    false,
                ),
                (Ident::Unlockname("home"), "home", true),
                (Ident::Series("cg"), "cg", true),
            ],
        );

        // 立绘: 主参数去掉 `?type=` 后缀, `-id` 为对象定义, 表情参数为立绘资源
        let line = "changeFigure:chara.skel?type=spine -id=chara -mouthOpen=open.png;";
        assert_sentence_idents(
            line,
            &resource_project(line),
            &[
                (
                    Ident::Resource(ResourceKind::Figure, "chara.skel"),
                    "chara.skel",
                    false,
                ),
                (Ident::Object("chara"), "chara", true),
                (
                    Ident::Resource(ResourceKind::Figure, "open.png"),
                    "open.png",
                    false,
                ),
            ],
        );

        // 对话: 语句类型与 `-speaker` 都是人物, 隐式语音参数名与 `-vocal` 都是语音
        let line = "chara:你好 -speaker=chara -vocal=sfx.wav -figureId=chara -sad;";
        assert_sentence_idents(
            line,
            &resource_project(line),
            &[
                (Ident::Speaker("chara"), "chara", true),
                (Ident::Speaker("chara"), "chara", true),
                (
                    Ident::Resource(ResourceKind::Vocal, "sfx.wav"),
                    "sfx.wav",
                    false,
                ),
                (Ident::Object("chara"), "chara", false),
                (Ident::Resource(ResourceKind::Vocal, "sad"), "sad", false),
            ],
        );

        // 其余语句: 音效 ID / 舞台对象 / 场景 / 标签 / 动画
        let line = "playEffect:sfx.wav -id=hit;";
        assert_sentence_idents(
            line,
            &resource_project(line),
            &[
                (
                    Ident::Resource(ResourceKind::Vocal, "sfx.wav"),
                    "sfx.wav",
                    false,
                ),
                (Ident::Sound("hit"), "hit", true),
            ],
        );

        let line = "unlockCg:cg.png -name=home -series=cg;";
        assert_sentence_idents(
            line,
            &resource_project(line),
            &[
                (
                    Ident::Resource(ResourceKind::Background, "cg.png"),
                    "cg.png",
                    false,
                ),
                (Ident::Unlockname("home"), "home", false),
                (Ident::Series("cg"), "cg", true),
            ],
        );

        let line = "setTransform:{} -target=fig-center;";
        assert_sentence_idents(
            line,
            &resource_project(line),
            &[(Ident::Object("fig-center"), "fig-center", false)],
        );

        let line = "setAnimation:fadeIn -target=fig-center;";
        assert_sentence_idents(
            line,
            &resource_project(line),
            &[
                (
                    Ident::Resource(ResourceKind::Animation, "fadeIn"),
                    "fadeIn",
                    false,
                ),
                (Ident::Object("fig-center"), "fig-center", false),
            ],
        );

        let line = "label:start;";
        assert_sentence_idents(
            line,
            &resource_project(line),
            &[(Ident::Label("start"), "start", true)],
        );

        let line = "jumpLabel:start;";
        assert_sentence_idents(
            line,
            &resource_project(line),
            &[(Ident::Label("start"), "start", false)],
        );
    }

    #[test]
    fn collects_variables_by_table_only() {
        // 变量不参与语句收集 (由变量表提供)
        let line = "setVar:hp=1;";
        assert_sentence_idents(line, &resource_project(line), &[]);

        let line = "say:你好 {hp} -when=hp;";
        assert_sentence_idents(line, &resource_project(line), &[]);
    }

    #[test]
    fn collects_choose_targets() {
        let line = "label:start;\nchoose:去往A:2.txt|留在这里:start|不知道:nowhere;";
        let project = resource_project(line);

        // 场景存在时按场景, 标签存在时按标签, 都没有则不收集
        assert_sentence_idents(
            "choose:去往A:2.txt|留在这里:start|不知道:nowhere;",
            &project,
            &[
                (
                    Ident::Resource(ResourceKind::Scene, "2.txt"),
                    "2.txt",
                    false,
                ),
                (Ident::Label("start"), "start", false),
            ],
        );
    }

    #[test]
    fn requires_existing_resource_for_collection() {
        // 动画不存在时不收集 (与识别层一致)
        let line = "setAnimation:missing -target=fig-center;";
        assert_sentence_idents(
            line,
            &resource_project(line),
            &[(Ident::Object("fig-center"), "fig-center", false)],
        );

        let line = "changeBg:bg.png -enter=missing;";
        assert_sentence_idents(
            line,
            &resource_project(line),
            &[(
                Ident::Resource(ResourceKind::Background, "bg.png"),
                "bg.png",
                false,
            )],
        );
    }

    #[test]
    fn skips_speaker_for_dialogue_text() {
        // 无主参数时语句类型是对话正文; `say` 语句类型与整体插值同样不构成人物
        let line = "你好 -speaker=chara;";
        assert_sentence_idents(
            line,
            &resource_project(line),
            &[(Ident::Speaker("chara"), "chara", true)],
        );

        let line = "say:你好;";
        assert_sentence_idents(line, &resource_project(line), &[]);

        let line = "{name}:你好;";
        assert_sentence_idents(line, &resource_project(line), &[]);
    }

    // -------- 场景与项目收集 --------

    #[test]
    fn collects_scene_and_project_idents() {
        let first = "label:start;\nchangeBg:bg.png;";
        let second = "jumpLabel:start;\nbgm:theme.mp3;";
        let project = project_files(&[
            ("scene/1.txt", first),
            ("scene/2.txt", second),
            ("background/bg.png", "[]"),
            ("bgm/theme.mp3", "[]"),
        ]);

        let scene = project
            .resource()
            .scene
            .get("1.txt")
            .and_then(|node| node.as_item())
            .unwrap();
        let lines: Vec<_> = collect_scene_idents(scene, &project)
            .into_iter()
            .map(|(line, occurrence)| (line, occurrence.ident))
            .collect();
        assert_eq!(
            lines,
            vec![
                (0, Ident::Label("start")),
                (1, Ident::Resource(ResourceKind::Background, "bg.png")),
            ]
        );

        // 项目级收集: 按文件夹顺序遍历场景
        let labels: Vec<_> = collect_project_idents(&project)
            .into_iter()
            .filter(|(_, _, occurrence)| matches!(occurrence.ident, Ident::Label(_)))
            .map(|(scene, line, occurrence)| (scene, line, occurrence.definition))
            .collect();
        assert_eq!(
            labels,
            vec![
                ("1.txt".to_string(), 0, true),
                ("2.txt".to_string(), 0, false),
            ]
        );
    }

    // -------- 与识别层的一致性 --------

    /// 语句收集与识别层必须覆盖同一组位置 (变量由变量表提供, 不在两者之列)
    #[test]
    fn sentence_collection_matches_recognition() {
        let lines = [
            "setVar:hp=1;",
            "changeBg:bg.png -enter=fadeIn -exit=fadeOut -unlockname=home -series=cg;",
            "changeFigure:chara.skel?type=spine -id=chara -mouthOpen=open.png;",
            "bgm:theme.mp3;",
            "playVideo:op.mp4;",
            "playEffect:sfx.wav -id=hit;",
            "miniAvatar:open.png;",
            "chara:你好 -speaker=chara -vocal=sfx.wav -figureId=chara -sad -when=hp;",
            "intro:文本 -backgroundImage=bg.png;",
            "unlockCg:cg.png -name=home -series=cg;",
            "unlockBgm:theme.mp3 -name=home;",
            "setAnimation:fadeIn -target=fig-center;",
            "setTransform:{} -target=fig-center;",
            "changeScene:2.txt;",
            "callScene:2.txt -hp=1 -writeReturnTo=result;",
            "choose:去往A:2.txt|留在这里:start|不知道:nowhere;",
            "label:start;",
            "jumpLabel:start;",
            "say:你好 {hp};",
            "; 注释",
        ];
        let source = lines.join("\n");
        let project = resource_project(&source);
        let scene = project
            .resource()
            .scene
            .get("1.txt")
            .and_then(|node| node.as_item())
            .unwrap();

        for line_index in 0..lines.len() {
            // 语句文本取自场景本身 (与识别层共享同一份内存)
            let text = scene.sentences()[line_index].content;

            // 识别层: 逐字符位置探测, 忽略由变量表提供的变量
            let mut recognized: Vec<(Ident, ops::Range<usize>)> = Vec::new();
            for offset in (0..=text.len()).filter(|offset| text.is_char_boundary(*offset)) {
                let Some(ident) = recognize_ident(
                    "1.txt",
                    Position {
                        line: line_index as u32,
                        character: offset as u32,
                    },
                    &project,
                ) else {
                    continue;
                };
                if matches!(ident, Ident::Variable(_)) {
                    continue;
                }
                recognized.push((ident, span_of(text, ident.name())));
            }
            recognized.sort_by_key(|(ident, span)| (*ident, span.start, span.end));
            recognized.dedup();

            // 收集层
            let mut collected: Vec<_> =
                collect_sentence_idents(&scene.sentences()[line_index], &project)
                    .into_iter()
                    .map(|occurrence| (occurrence.ident, occurrence.span))
                    .collect();
            collected.sort_by_key(|(ident, span)| (*ident, span.start, span.end));
            collected.dedup();

            assert_eq!(recognized, collected, "line {line_index}: {text:?}");
        }
    }
}
