// This file is generated by AI.

//! 符号重命名
//!
//! 与引用查询共用同一份判定: 光标处的符号由识别层给出, 待替换位置由收集层给出,
//! 因此"能查到引用的位置"都能被重命名.
//!
//! # Behavior
//! * 变量由实时维护的变量表提供 (定义与引用), 其余符号遍历所有场景收集全部出现位置;
//! * 资源是项目内的文件, 重命名需要改动文件系统, 不在本模块范围内.

use lsp_types::*;
use path_tree::Node;
use webgal_language_core::util::span_of;

use crate::{
    project::Project,
    service::references::{
        collect::{ReferenceList, collect_ident_references},
        recognize::{Ident, recognize_ident},
    },
};

/// 重命名能力
pub fn rename_capability() -> OneOf<bool, RenameOptions> {
    OneOf::Right(RenameOptions {
        // 由服务端判定光标处是否可重命名 (资源等符号不支持)
        prepare_provider: Some(true),
        work_done_progress_options: Default::default(),
    })
}

/// 准备重命名
///
/// # Returns
/// 光标处符号的名称区间与当前名称 (供客户端作为输入框的占位内容).
///
/// # Errors
/// 光标处不是可重命名的符号时返回 [`RenameError::Unsupported`].
pub fn prepare_rename(
    scene_path: &str,
    position: Position,
    project: &Project,
) -> Result<(Range, String), RenameError> {
    let (ident, range) = locate_ident(scene_path, position, project)?;
    Ok((range, ident.name().to_string()))
}

/// 重命名
///
/// # Returns
/// 项目中所有需要替换的位置 (与[查找引用](crate::service::references)同源).
///
/// # Errors
/// * 光标处不是可重命名的符号: [`RenameError::Unsupported`];
/// * 新名称不合法: [`RenameError::InvalidName`];
/// * 已存在同名同类符号: [`RenameError::Conflict`].
///
/// # Behavior
/// * 新名称与原名相同时返回空列表 (客户端据此提示"无更改");
/// * 资源不支持重命名 (见模块说明).
pub fn rename(
    scene_path: &str,
    position: Position,
    new_name: &str,
    project: &Project,
) -> Result<ReferenceList, RenameError> {
    let (ident, _) = locate_ident(scene_path, position, project)?;
    if ident.name() == new_name {
        return Ok(ReferenceList::default());
    }
    validate_name(&ident, new_name)?;

    // 同名同类符号已存在: 拒绝, 避免无声地合并两个符号
    if collect_ident_references(ident.with_name(new_name), project)
        .is_some_and(|locations| !locations.is_empty())
    {
        return Err(RenameError::Conflict(new_name.to_string()));
    }

    collect_ident_references(ident, project).ok_or(RenameError::Unsupported)
}

/// 重命名错误
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum RenameError {
    /// 光标处的符号不支持重命名
    #[error("此处不支持重命名")]
    Unsupported,
    /// 新名称不合法
    #[error("新名称不合法: {0}")]
    InvalidName(String),
    /// 新名称与已有符号冲突
    #[error("已存在同名符号: {0}")]
    Conflict(String),
}

// -------- 符号定位与校验 --------

/// 定位光标处的可重命名符号及其名称区间
fn locate_ident<'a>(
    scene_path: &str,
    position: Position,
    project: &'a Project,
) -> Result<(Ident<'a>, Range), RenameError> {
    let ident = recognize_ident(scene_path, position, project).ok_or(RenameError::Unsupported)?;
    // 资源即文件, 改名需要同时改动文件系统
    if matches!(ident, Ident::Resource(..)) {
        return Err(RenameError::Unsupported);
    }

    let info = project
        .resource()
        .scene
        .get(scene_path)
        .and_then(Node::as_item)
        .and_then(|scene| scene.sentences().get(position.line as usize))
        .ok_or(RenameError::Unsupported)?;

    // 名称是语句原始字符串的子串
    let span = span_of(info.content, ident.name());
    Ok((
        ident,
        Range {
            start: Position {
                line: position.line,
                character: span.start as u32,
            },
            end: Position {
                line: position.line,
                character: span.end as u32,
            },
        },
    ))
}

/// 校验新名称
///
/// # Behavior
/// * 统一禁止换行 / `;` / `|`: 它们会改变语句结构;
/// * 变量出现在表达式与插值中, 额外禁止空白与表达式分隔符;
/// * 标签出现在 `choose` 的 `提示:目标` 中, 额外禁止 `:`;
/// * 参数值位置 (人物 / 对象 ID / 音效 ID / 系列 / 鉴赏名称) 额外禁止 `=` 与花括号, 且不允许首尾空白.
fn validate_name(ident: &Ident, new_name: &str) -> Result<(), RenameError> {
    if new_name.is_empty() {
        return Err(RenameError::InvalidName("名称不能为空".to_string()));
    }
    if new_name
        .chars()
        .any(|ch| ch.is_control() || matches!(ch, ';' | '|'))
    {
        return Err(RenameError::InvalidName(
            "名称不能包含换行, `;` 或 `|`".to_string(),
        ));
    }

    let invalid = match *ident {
        Ident::Variable(_) => new_name
            .chars()
            .any(|ch| ch.is_whitespace() || "=+-*/%<>!&()[]{},\":".contains(ch)),
        Ident::Label(_) => new_name.contains(':'),
        _ => new_name.trim() != new_name || new_name.contains('=') || new_name.contains(['{', '}']),
    };
    if invalid {
        return Err(RenameError::InvalidName(format!(
            "名称 `{new_name}` 含有非法字符"
        )));
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use webgal_language_core::resource::{Config, ResourceKind};

    use super::*;

    /// 构建测试项目: (相对项目根的文件路径, 文件内容)
    fn project(files: &[(&str, &str)]) -> Project {
        let mut project = Project::new(Config::default());
        for (path, content) in files {
            project.insert(path, || Ok(content.to_string())).unwrap();
        }
        project
    }

    fn position(line: u32, character: u32) -> Position {
        Position { line, character }
    }

    /// 定位名称在场景某行中的首次出现位置
    fn at(scene: &str, line: u32, name: &str) -> Position {
        at_nth(scene, line, name, 0)
    }

    /// 定位名称在场景某行中的第 n 次出现位置 (从 0 开始)
    fn at_nth(scene: &str, line: u32, name: &str, nth: usize) -> Position {
        let text = scene.lines().nth(line as usize).expect("行应在场景中");
        let start = text.match_indices(name).nth(nth).expect("名称应在语句中").0;
        position(line, start as u32)
    }

    /// 定位名称在场景某行中的区间
    fn range_of(scene: &str, line: u32, name: &str) -> Range {
        range_of_nth(scene, line, name, 0)
    }

    /// 定位名称在场景某行中第 n 次出现的区间
    fn range_of_nth(scene: &str, line: u32, name: &str, nth: usize) -> Range {
        let Position { line, character } = at_nth(scene, line, name, nth);
        Range {
            start: position(line, character),
            end: position(line, character + name.len() as u32),
        }
    }

    /// 重命名结果
    fn rename_at(
        project: &Project,
        scene: &str,
        at: Position,
        new_name: &str,
    ) -> Vec<(String, Range)> {
        rename(scene, at, new_name, project)
            .unwrap_or_else(|error| panic!("重命名失败: {error}"))
            .into_iter()
            .collect()
    }

    // -------- 准备重命名 --------

    #[test]
    fn prepares_name_range_and_placeholder() {
        let scene = "label:start;";
        let label = project(&[("scene/1.txt", scene)]);
        assert_eq!(
            prepare_rename("1.txt", at(scene, 0, "start"), &label),
            Ok((range_of(scene, 0, "start"), "start".to_string()))
        );

        // 变量与人物同样返回自身区间
        let scene = "chara:你好;\nsetVar:hp=100;";
        let others = project(&[("scene/1.txt", scene)]);
        assert_eq!(
            prepare_rename("1.txt", at(scene, 0, "chara"), &others),
            Ok((range_of(scene, 0, "chara"), "chara".to_string()))
        );
        assert_eq!(
            prepare_rename("1.txt", at(scene, 1, "hp"), &others),
            Ok((range_of(scene, 1, "hp"), "hp".to_string()))
        );
    }

    #[test]
    fn rejects_resource_and_non_symbol() {
        let scene = "changeBg:bg.png;\n; 注释\nwait:100;";
        let project = project(&[("scene/1.txt", scene)]);

        // 资源是文件, 不支持脚本内重命名
        assert_eq!(
            prepare_rename("1.txt", at(scene, 0, "bg.png"), &project),
            Err(RenameError::Unsupported)
        );
        // 注释与语句类型不是符号
        assert_eq!(
            prepare_rename("1.txt", position(1, 3), &project),
            Err(RenameError::Unsupported)
        );
        assert_eq!(
            prepare_rename("1.txt", position(2, 2), &project),
            Err(RenameError::Unsupported)
        );
    }

    // -------- 变量 --------

    #[test]
    fn renames_variable_definition_and_references() {
        let scene = "setVar:hp=100;\nsay:hello -when=hp;\nsay:{hp};";
        let project = project(&[("scene/1.txt", scene)]);

        assert_eq!(
            rename_at(&project, "1.txt", at(scene, 0, "hp"), "生命"),
            vec![
                ("1.txt".to_string(), range_of(scene, 0, "hp")),
                ("1.txt".to_string(), range_of(scene, 1, "hp")),
                ("1.txt".to_string(), range_of(scene, 2, "hp")),
            ]
        );
    }

    #[test]
    fn renames_variable_arguments_of_call_scene() {
        // 传参名与 writeReturnTo 都是变量定义
        let scene = "callScene:2.txt -hp=5 -writeReturnTo=result;";
        let project = project(&[
            ("scene/1.txt", scene),
            ("scene/2.txt", "setVar:hp=1;\nreturn:hp;"),
        ]);

        assert_eq!(
            rename_at(&project, "1.txt", at(scene, 0, "hp"), "生命"),
            vec![
                ("1.txt".to_string(), range_of(scene, 0, "hp")),
                (
                    "2.txt".to_string(),
                    range_of("setVar:hp=1;\nreturn:hp;", 0, "hp")
                ),
                (
                    "2.txt".to_string(),
                    range_of("setVar:hp=1;\nreturn:hp;", 1, "hp")
                ),
            ]
        );
    }

    // -------- 标签 --------

    #[test]
    fn renames_label_across_scenes() {
        let first = "label:start;";
        let second = "jumpLabel:start;\nchoose:去往:start|离开:2.txt;";
        let project = project(&[("scene/1.txt", first), ("scene/2.txt", second)]);

        assert_eq!(
            rename_at(&project, "1.txt", at(first, 0, "start"), "开局"),
            vec![
                ("1.txt".to_string(), range_of(first, 0, "start")),
                ("2.txt".to_string(), range_of(second, 0, "start")),
                ("2.txt".to_string(), range_of(second, 1, "start")),
            ]
        );
    }

    // -------- 舞台对象与音效 --------

    #[test]
    fn renames_object_id() {
        let scene = "changeFigure:chara.png -id=chara;\nsay:你好 -figureId=chara;\nsetTransform:{} -target=chara;";
        let project = project(&[("scene/1.txt", scene), ("figure/chara.png", "[]")]);

        // 光标须落在 `-id` 参数值上 (主参数是资源, 不支持重命名)
        assert_eq!(
            rename_at(&project, "1.txt", at_nth(scene, 0, "chara", 1), "主角"),
            vec![
                ("1.txt".to_string(), range_of_nth(scene, 0, "chara", 1)),
                ("1.txt".to_string(), range_of(scene, 1, "chara")),
                ("1.txt".to_string(), range_of(scene, 2, "chara")),
            ]
        );
        assert_eq!(
            prepare_rename("1.txt", at(scene, 0, "chara"), &project),
            Err(RenameError::Unsupported)
        );
    }

    #[test]
    fn renames_sound_id() {
        let scene = "playEffect:sfx.wav -id=hit;";
        let project = project(&[("scene/1.txt", scene), ("vocal/sfx.wav", "[]")]);

        assert_eq!(
            rename_at(&project, "1.txt", at(scene, 0, "hit"), "命中"),
            vec![("1.txt".to_string(), range_of(scene, 0, "hit"))]
        );
    }

    // -------- 人物与鉴赏 --------

    #[test]
    fn renames_speaker_series_and_unlockname() {
        let scene = "chara:你好 -speaker=chara;\nchangeBg:bg.png -unlockname=home -series=cg;\nunlockCg:cg.png -name=home;";
        let project = project(&[
            ("scene/1.txt", scene),
            ("background/bg.png", "[]"),
            ("background/cg.png", "[]"),
        ]);

        assert_eq!(
            rename_at(&project, "1.txt", at(scene, 0, "chara"), "主角"),
            vec![
                ("1.txt".to_string(), range_of_nth(scene, 0, "chara", 0)),
                ("1.txt".to_string(), range_of_nth(scene, 0, "chara", 1)),
            ]
        );
        assert_eq!(
            rename_at(&project, "1.txt", at(scene, 1, "cg"), "鉴赏"),
            vec![("1.txt".to_string(), range_of(scene, 1, "cg"))]
        );
        assert_eq!(
            rename_at(&project, "1.txt", at(scene, 1, "home"), "主页"),
            vec![
                ("1.txt".to_string(), range_of(scene, 1, "home")),
                ("1.txt".to_string(), range_of(scene, 2, "home")),
            ]
        );
    }

    // -------- 校验与冲突 --------

    #[test]
    fn rejects_invalid_name() {
        let scene = "setVar:hp=1;\nlabel:start;\nchara:你好;";
        let project = project(&[("scene/1.txt", scene)]);

        for (line, name, new_name) in [
            (0, "hp", ""),
            (0, "hp", "两 个词"),
            (0, "hp", "hp=1"),
            (0, "hp", "hp;"),
            (1, "start", "a:b"),
            (2, "chara", "chara|b"),
        ] {
            let error = rename("1.txt", at(scene, line, name), new_name, &project).unwrap_err();
            assert!(
                matches!(error, RenameError::InvalidName(_)),
                "line {line}: {new_name:?} -> {error:?}"
            );
        }
    }

    #[test]
    fn rejects_name_conflict() {
        let scene = "label:start;\nlabel:end;";
        let project = project(&[("scene/1.txt", scene)]);

        assert_eq!(
            rename("1.txt", at(scene, 0, "start"), "end", &project),
            Err(RenameError::Conflict("end".to_string()))
        );
        // 未被使用的名称不冲突
        assert!(rename("1.txt", at(scene, 0, "start"), "new", &project).is_ok());
    }

    #[test]
    fn same_name_needs_no_edit() {
        let scene = "label:start;";
        let project = project(&[("scene/1.txt", scene)]);

        assert_eq!(
            rename_at(&project, "1.txt", at(scene, 0, "start"), "start"),
            Vec::new()
        );
    }

    #[test]
    fn rejects_rename_of_resource() {
        let scene = "changeBg:bg.png;";
        let project = project(&[("scene/1.txt", scene), ("background/bg.png", "[]")]);

        assert_eq!(
            rename("1.txt", at(scene, 0, "bg.png"), "new.png", &project),
            Err(RenameError::Unsupported)
        );
    }

    #[test]
    fn rejects_unknown_variable() {
        // `mp` 不在变量表中: 光标处识别不出符号
        let scene = "say:hello -when=mp;";
        let project = project(&[("scene/1.txt", scene)]);

        assert_eq!(
            rename("1.txt", at(scene, 0, "mp"), "生命", &project),
            Err(RenameError::Unsupported)
        );
        assert_eq!(
            prepare_rename("1.txt", at(scene, 0, "mp"), &project),
            Err(RenameError::Unsupported)
        );
    }

    // -------- 边界 --------

    #[test]
    fn missing_scene_is_unsupported() {
        let project = project(&[("scene/1.txt", "label:start;")]);
        assert_eq!(
            prepare_rename("2.txt", position(0, 6), &project),
            Err(RenameError::Unsupported)
        );
    }

    #[test]
    fn resource_ident_is_never_renamable() {
        // 名称访问与同类构造不应改变符号类型
        let ident = Ident::Resource(ResourceKind::Background, "bg.png");
        assert_eq!(ident.name(), "bg.png");
        assert_eq!(
            ident.with_name("new.png"),
            Ident::Resource(ResourceKind::Background, "new.png")
        );
    }
}
