use std::fmt::{self, Write};

use ouroboros::self_referencing;

use crate::{
    sentence::{Error, FromPrimary, PrimarySentence, Sentence},
    util::write_joined,
};

// -------- sentence --------

/// 语句信息 (LSP)
///
/// 从语句字符串构建, 包含语句内容, 注释, nolint 标记以及解析错误.
#[derive(Debug)]
pub struct SentenceInfo<'a> {
    // 语句内容
    pub content: &'a str,
    pub primary: PrimarySentence<'a>,
    pub sentence: Sentence,
    // 注释和标记
    pub comment: &'a str,
    pub nolints: Vec<&'a str>,
    // 解析错误
    pub errors: Vec<Error>,
}

impl<'a> SentenceInfo<'a> {
    /// 从语句字符串构建
    ///
    /// 形如: `changeFigure:none -id=soyo -next;nolint:WG001; 立绘退场`
    #[allow(clippy::should_implement_trait)]
    pub fn from_str(line: &'a str) -> Self {
        let primary = PrimarySentence::from_str(line);
        let mut errors = Vec::new();
        let sentence = Sentence::from_primary(&primary, &mut errors);
        let (nolints, comment) = split_nolints(primary.comment);
        Self {
            content: line,
            primary,
            sentence,
            comment,
            nolints,
            errors,
        }
    }

    pub fn is_empty(&self) -> bool {
        let Self {
            sentence,
            comment,
            nolints,
            ..
        } = self;
        matches!(sentence, Sentence::Comment(_)) && comment.is_empty() && nolints.is_empty()
    }

    /// 查找指定 nolint 是否存在
    ///
    /// # Behavior
    /// * 此函数假设 `nolints` 有序.
    pub fn contains_nolint(&self, name: &str) -> bool {
        self.nolints.binary_search(&name).is_ok()
    }
}

impl fmt::Display for SentenceInfo<'_> {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        if self.is_empty() {
            return Ok(());
        }
        self.sentence.fmt(f)?;
        if !self.nolints.is_empty() {
            f.write_str("nolint:")?;
            write_joined(f, self.nolints.iter(), "|")?;
            f.write_char(';')?;
        }
        if !self.comment.is_empty() {
            write!(f, " {}", self.comment)?;
        }
        Ok(())
    }
}

/// 分割注释和 nolint 标记
///
/// nolints 标记会进行排序.
/// 仅识别格式规范的 nolint 标记, 形如: `nolint:WG001|WG003; comment`.
pub fn split_nolints(comment: &str) -> (Vec<&str>, &str) {
    let comment = match comment.strip_prefix("nolint:") {
        Some(comment) => comment,
        None => return (Vec::default(), comment.trim()),
    };
    let (nolints, comment) = comment.split_once(';').unwrap_or((comment, ""));
    let mut nolints: Vec<_> = nolints.split('|').map(str::trim).collect();
    nolints.sort();
    (nolints, comment.trim())
}

// -------- scene --------

/// 场景信息 (LSP)
///
/// 持有场景的完整字符串, 以及解析后的每条语句及其信息.
#[derive(Debug)]
pub struct Scene(SceneData);

#[self_referencing]
#[derive(Debug)]
struct SceneData {
    pub content: String,
    #[borrows(content)]
    #[covariant]
    pub sentences: Vec<SentenceInfo<'this>>,
}

impl Scene {
    /// 从场景字符串构建
    #[allow(clippy::should_implement_trait)]
    pub fn from_str<S: Into<String>>(scene: S) -> Self {
        let content = scene.into();
        Self(SceneData::new(content, |content| {
            content.lines().map(SentenceInfo::from_str).collect()
        }))
    }

    pub fn content(&self) -> &str {
        self.0.borrow_content()
    }

    pub fn sentences(&self) -> &[SentenceInfo<'_>] {
        self.0.borrow_sentences()
    }
}

impl fmt::Display for Scene {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.sentences()
            .iter()
            .try_for_each(|sentence| writeln!(f, "{sentence}"))
    }
}

impl<S: AsRef<str>> From<S> for Scene {
    fn from(value: S) -> Self {
        Self::from_str(value.as_ref())
    }
}

#[cfg(test)]
mod tests {
    // This module is generated by AI.

    use super::*;

    // -------- split_nolints --------

    #[test]
    fn split_nolints_no_marker() {
        let (nolints, comment) = split_nolints(" just a comment");
        assert!(nolints.is_empty());
        assert_eq!(comment, "just a comment");
    }

    #[test]
    fn split_nolints_with_comment() {
        let (nolints, comment) = split_nolints("nolint:WG003|WG001; comment");
        assert_eq!(nolints, vec!["WG001", "WG003"]);
        assert_eq!(comment, "comment");
    }

    // -------- SentenceInfo --------

    #[test]
    fn sentence_info_basic() {
        let line = "changeBg:bg.png -next;";
        let info = SentenceInfo::from_str(line);
        assert_eq!(info.content, line);
        assert_eq!(info.primary.command, "changeBg");
        assert!(info.errors.is_empty());
        assert!(info.nolints.is_empty());
        assert_eq!(info.comment, "");
    }

    #[test]
    fn sentence_info_with_comment() {
        let line = "changeBg:bg.png; this is a comment";
        let info = SentenceInfo::from_str(line);
        assert_eq!(info.comment, "this is a comment");
    }

    #[test]
    fn sentence_info_with_nolint() {
        let line = "changeBg:bg.png;nolint:WG001; extra";
        let info = SentenceInfo::from_str(line);
        assert_eq!(info.nolints, vec!["WG001"]);
        assert_eq!(info.comment, "extra");
    }

    #[test]
    fn sentence_info_contains_nolint() {
        let line = "changeBg:bg.png;nolint:WG001|WG003;";
        let info = SentenceInfo::from_str(line);
        assert!(info.contains_nolint("WG001"));
        assert!(info.contains_nolint("WG003"));
        assert!(!info.contains_nolint("WG999"));
    }

    #[test]
    fn sentence_info_display() {
        let line = "changeBg:bg.png -next;nolint:WG001; comment";
        let info = SentenceInfo::from_str(line);
        assert_eq!(
            info.to_string(),
            "changeBg:bg.png -next;nolint:WG001; comment"
        );
    }

    // -------- Scene --------

    #[test]
    fn scene_basic() {
        let content = "changeBg:bg.png;\nwait:1000;\n";
        let scene = Scene::from_str(content);
        assert_eq!(scene.content(), content);
        assert_eq!(scene.sentences().len(), 2);
    }

    #[test]
    fn scene_display() {
        let content = "changeBg:bg.png;\nwait:1000;\n";
        let scene = Scene::from_str(content);
        assert_eq!(scene.to_string(), content);
    }

    #[test]
    fn scene_empty() {
        let scene = Scene::from_str("");
        assert_eq!(scene.content(), "");
        assert!(scene.sentences().is_empty());
        assert_eq!(scene.to_string(), "");
    }

    #[test]
    fn scene_empty_lines() {
        let scene = Scene::from_str("\n\n");
        assert_eq!(scene.content(), "\n\n");
        assert_eq!(scene.sentences().len(), 2);
        assert_eq!(scene.to_string(), "\n\n");
    }
}
