[package]
name = "json-language-service"
version = "0.2.0"
edition.workspace = true
readme.workspace = true
description = "JSON 基础语言服务"

authors.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
lsp = ["dep:lsp-types"] # LSP 类型转换

[dependencies]
lsp-types = { workspace = true, optional = true }
