// This file is generated by AI.

// LSP 客户端握手缓冲: 连接就绪前发出的消息既不丢也不发, 而是按序攒着, 握完手一次冲出。
//
// 背景 (issue: 打开项目立刻看场景没有高亮): 语言服务在 initialize 完成前不处理任何请求与通知
// (tower-lsp 直接回 -32002 或丢弃), 而旧实现此时直接丢帧 —— 语义高亮请求的 Promise 再也没有
// 结果, Monaco 的 provider 就此停住, 直到切标签页重建编辑器。

import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

const mocks = vi.hoisted(() => ({
  invoke: vi.fn(async (command: string) => (command === 'start_server' ? 45123 : [])),
}));

vi.mock('@tauri-apps/api/core', () => ({ invoke: mocks.invoke }));

import { LspClient } from '../src/lsp/client';

/** 只实现客户端真正用到的那部分 WebSocket */
class FakeSocket {
  static readonly CONNECTING = 0;
  static readonly OPEN = 1;
  static readonly CLOSING = 2;
  static readonly CLOSED = 3;
  static instances: FakeSocket[] = [];

  readyState = FakeSocket.CONNECTING;
  binaryType = 'arraybuffer';
  readonly frames: string[] = [];
  onopen: (() => void) | null = null;
  onmessage: ((event: { data: unknown }) => void) | null = null;
  onclose: (() => void) | null = null;
  onerror: (() => void) | null = null;

  constructor(readonly url: string) {
    FakeSocket.instances.push(this);
  }

  send(frame: Uint8Array): void {
    this.frames.push(new TextDecoder().decode(frame));
  }

  open(): void {
    this.readyState = FakeSocket.OPEN;
    this.onopen?.();
  }

  /** 服务端回一条消息 (LSP stdio 帧: Content-Length 头 + JSON 体) */
  reply(message: unknown): void {
    const body = new TextEncoder().encode(JSON.stringify(message));
    const header = new TextEncoder().encode(`Content-Length: ${body.length}\r\n\r\n`);
    const frame = new Uint8Array(header.length + body.length);
    frame.set(header, 0);
    frame.set(body, header.length);
    this.onmessage?.({ data: frame.buffer });
  }

  /** 已发出的 JSON-RPC 消息 */
  messages(): { method?: string; id?: number; params?: unknown }[] {
    return this.frames.map((frame) => JSON.parse(frame.slice(frame.indexOf('\r\n\r\n') + 4)));
  }

  methods(): string[] {
    return this.messages().map((message) => message.method ?? '<response>');
  }
}

const SCENE = 'C:\\project\\game\\scene\\start.txt';

/** 让 microtask 队列跑完 */
const tick = () => new Promise((resolve) => setTimeout(resolve, 0));

/** 建立连接并完成握手, 返回假 socket 与 `start()` 的 promise */
async function connect(client: LspClient): Promise<FakeSocket> {
  const started = client.start();
  await tick();
  const socket = FakeSocket.instances[0];
  socket.open();
  const initialize = socket.messages()[0];
  socket.reply({ jsonrpc: '2.0', id: initialize.id, result: { capabilities: {} } });
  await started;
  return socket;
}

describe('LspClient 握手缓冲', () => {
  beforeEach(() => {
    mocks.invoke.mockReset();
    mocks.invoke.mockImplementation(async (command: string) => (command === 'start_server' ? 45123 : []));
    FakeSocket.instances = [];
    vi.stubGlobal('WebSocket', FakeSocket);
  });

  afterEach(() => {
    vi.unstubAllGlobals();
  });

  it('握手完成前的 didOpen 与请求先排队，握手后按序冲出并结算', async () => {
    const client = new LspClient();
    const started = client.start();
    await tick();
    const socket = FakeSocket.instances[0];

    // 连接还没建立, 编辑器已经挂载: didOpen 与语义高亮请求都发出去了
    client.openDocument(SCENE, 'wait:1;');
    const tokens = client.semanticTokens(SCENE);
    expect(socket.frames).toHaveLength(0);

    socket.open();
    // 握手请求必须绕开缓冲, 否则缓冲永远等不到释放它的那条消息
    expect(socket.methods()).toEqual(['initialize']);

    socket.reply({ jsonrpc: '2.0', id: socket.messages()[0].id, result: { capabilities: {} } });
    await started;
    expect(socket.methods()).toEqual([
      'initialize',
      'initialized',
      'textDocument/didOpen',
      'textDocument/semanticTokens/full',
    ]);

    // 回包一到就结算: 编辑器不需要重建就能拿到高亮
    socket.reply({ jsonrpc: '2.0', id: socket.messages()[3].id, result: { data: [1, 2, 3] } });
    await expect(tokens).resolves.toEqual([1, 2, 3]);
  });

  it('颜色能力: 色块查询与改写方案按 LSP 形状收发', async () => {
    const client = new LspClient();
    const socket = await connect(client);

    const range = { start: { line: 0, character: 18 }, end: { line: 0, character: 37 } };
    const color = { red: 1, green: 0.5333333, blue: 0, alpha: 1 };

    // 色块: textDocument/documentColor 只带文档 URI
    const colors = client.documentColors(SCENE);
    const colorRequest = socket.messages().find((message) => message.method === 'textDocument/documentColor');
    expect(colorRequest?.params).toEqual({ textDocument: { uri: 'file:///C:/project/game/scene/start.txt' } });
    socket.reply({ jsonrpc: '2.0', id: colorRequest?.id, result: [{ range, color }] });
    await expect(colors).resolves.toEqual([{ range, color }]);

    // 改写: textDocument/colorPresentation 带上新颜色与待替换区间
    const presentations = client.colorPresentations(SCENE, color, range);
    const presentationRequest = socket
      .messages()
      .find((message) => message.method === 'textDocument/colorPresentation');
    expect(presentationRequest?.params).toMatchObject({ color, range });
    socket.reply({
      jsonrpc: '2.0',
      id: presentationRequest?.id,
      result: [{ label: '#FF8800', textEdit: { range, newText: '#FF8800' } }],
    });
    await expect(presentations).resolves.toEqual([{ label: '#FF8800', textEdit: { range, newText: '#FF8800' } }]);
  });

  it('握手完成后发出的消息直接送出，不再进缓冲', async () => {
    const client = new LspClient();
    const socket = await connect(client);

    client.openDocument(SCENE, 'wait:1;');
    expect(socket.methods()).toEqual(['initialize', 'initialized', 'textDocument/didOpen']);
  });

  it('后端起不来时，排队中的请求当场失败而不是永远等下去', async () => {
    mocks.invoke.mockRejectedValueOnce(new Error('boom'));
    const client = new LspClient();
    await client.start();
    expect(FakeSocket.instances).toHaveLength(0);

    await expect(client.hover(SCENE, { line: 0, character: 0 })).rejects.toThrow('语言服务未启动');
  });

  it('握手失败时不再假装可用：后续请求立刻失败', async () => {
    const client = new LspClient();
    void client.start();
    await tick();
    const socket = FakeSocket.instances[0];
    socket.open();
    socket.reply({
      jsonrpc: '2.0',
      id: socket.messages()[0].id,
      error: { code: -32002, message: 'Server not initialized' },
    });
    await tick();

    await expect(client.hover(SCENE, { line: 0, character: 0 })).rejects.toThrow('语言服务握手失败');
  });

  it('握手途中断线：排队中的请求被结算，不会一直等重连', async () => {
    const client = new LspClient();
    void client.start();
    await tick();
    const socket = FakeSocket.instances[0];
    socket.open();

    // 握手还没完成, 请求排在缓冲里
    const tokens = client.semanticTokens(SCENE);
    vi.useFakeTimers();
    socket.readyState = FakeSocket.CLOSED;
    socket.onclose?.();
    await expect(tokens).rejects.toThrow('LSP 连接已断开');
    vi.clearAllTimers(); // 重连定时器不必真的跑
    vi.useRealTimers();
  });

  it('断线重连后，断线期间攒下的 didOpen 仍然补发', async () => {
    const client = new LspClient();
    const socket = await connect(client);

    client.openDocument(SCENE, 'wait:1;');
    expect(socket.methods()).toContain('textDocument/didOpen');

    // 连接断了: 通知留在缓冲里, 重连握手完成后补发
    vi.useFakeTimers();
    socket.readyState = FakeSocket.CLOSED;
    socket.onclose?.();
    client.openDocument(SCENE, 'wait:2;');
    await vi.advanceTimersByTimeAsync(1000); // 一秒后自动重连
    vi.useRealTimers();

    const reconnected = FakeSocket.instances[1];
    reconnected.open();
    reconnected.reply({ jsonrpc: '2.0', id: reconnected.messages()[0].id, result: { capabilities: {} } });
    await tick();

    const reopened = reconnected.messages().filter((message) => message.method === 'textDocument/didOpen');
    expect(reopened).toHaveLength(1);
    expect((reopened[0].params as { textDocument: { text: string } }).textDocument.text).toBe('wait:2;');
  });
});
