// This file is generated by AI.

// 预览全屏的窗口侧补正: 状态折算与动作顺序。
//
// 这里钉住的是那个绕不开的顺序 —— 补正"最大化窗口进全屏留下的黑边"时, 必须先退出窗口全屏再
// 离开最大化: 反过来的话 tao 的 `unmaximize()` 会在全屏状态下走 `SW_RESTORE`, 把全屏一起缩没
// (tauri-apps/tao#1087 的第 4 步)。顺序错了代码上看不出来, 只有实测才知道。

import { describe, expect, it } from 'vitest';

import {
  applyPreviewFullscreenAction,
  previewFullscreenTransition,
  type PreviewFullscreenStatus,
  type PreviewFullscreenWindow,
} from '../src/preview/fullscreen';

const IDLE: PreviewFullscreenStatus = { mirrored: false, corrected: false };

/** 假窗口: 只记录调用顺序。 */
function createFakeWindow(): { calls: string[]; win: PreviewFullscreenWindow } {
  const calls: string[] = [];
  return {
    calls,
    win: {
      setFullscreen: (value: boolean) => {
        calls.push(`setFullscreen(${value})`);
        return Promise.resolve();
      },
      unmaximize: () => {
        calls.push('unmaximize');
        return Promise.resolve();
      },
      maximize: () => {
        calls.push('maximize');
        return Promise.resolve();
      },
    },
  };
}

describe('previewFullscreenTransition', () => {
  it('普通窗口进入全屏: 只把窗口设成全屏', () => {
    const next = previewFullscreenTransition(IDLE, { fullscreenActive: true, windowWasMaximized: false });
    expect(next).toEqual({ mirrored: true, corrected: false, action: { kind: 'enter-fullscreen' } });
  });

  it('最大化窗口进入全屏: 补正, 并记住退出时要还原', () => {
    const next = previewFullscreenTransition(IDLE, { fullscreenActive: true, windowWasMaximized: true });
    expect(next).toEqual({ mirrored: true, corrected: true, action: { kind: 'correct-maximized' } });
  });

  it('补正过之后退出: 还原最大化', () => {
    const entered = previewFullscreenTransition(IDLE, { fullscreenActive: true, windowWasMaximized: true });
    const left = previewFullscreenTransition(entered, { fullscreenActive: false, windowWasMaximized: false });
    expect(left).toEqual({ mirrored: false, corrected: false, action: { kind: 'restore-maximized' } });
  });

  it('没补正过退出: 只取消窗口全屏', () => {
    const entered = previewFullscreenTransition(IDLE, { fullscreenActive: true, windowWasMaximized: false });
    const left = previewFullscreenTransition(entered, { fullscreenActive: false, windowWasMaximized: false });
    expect(left).toEqual({ mirrored: false, corrected: false, action: { kind: 'leave-fullscreen' } });
  });

  it('状态没变时什么都不做', () => {
    const entered = previewFullscreenTransition(IDLE, { fullscreenActive: true, windowWasMaximized: true });
    const again = previewFullscreenTransition(entered, { fullscreenActive: true, windowWasMaximized: true });
    expect(again).toEqual({ mirrored: true, corrected: true, action: { kind: 'none' } });

    const idle = previewFullscreenTransition(IDLE, { fullscreenActive: false, windowWasMaximized: true });
    expect(idle).toEqual({ mirrored: false, corrected: false, action: { kind: 'none' } });
  });

  it('还原过的最大化不会被第二次退出事件重复还原', () => {
    const entered = previewFullscreenTransition(IDLE, { fullscreenActive: true, windowWasMaximized: true });
    const left = previewFullscreenTransition(entered, { fullscreenActive: false, windowWasMaximized: true });
    expect(previewFullscreenTransition(left, { fullscreenActive: false, windowWasMaximized: true })).toEqual({
      mirrored: false,
      corrected: false,
      action: { kind: 'none' },
    });
  });
});

describe('applyPreviewFullscreenAction', () => {
  it('none 不动窗口', async () => {
    const { calls, win } = createFakeWindow();
    await applyPreviewFullscreenAction(win, { kind: 'none' });
    expect(calls).toEqual([]);
  });

  it('普通窗口进出全屏', async () => {
    const { calls, win } = createFakeWindow();
    await applyPreviewFullscreenAction(win, { kind: 'enter-fullscreen' });
    await applyPreviewFullscreenAction(win, { kind: 'leave-fullscreen' });
    expect(calls).toEqual(['setFullscreen(true)', 'setFullscreen(false)']);
  });

  it('补正最大化窗口: 先退全屏, 再离开最大化, 最后重新进全屏', async () => {
    const { calls, win } = createFakeWindow();
    await applyPreviewFullscreenAction(win, { kind: 'correct-maximized' });
    expect(calls).toEqual(['setFullscreen(false)', 'unmaximize', 'setFullscreen(true)']);
  });

  it('还原最大化: 先退全屏再最大化', async () => {
    const { calls, win } = createFakeWindow();
    await applyPreviewFullscreenAction(win, { kind: 'restore-maximized' });
    expect(calls).toEqual(['setFullscreen(false)', 'maximize']);
  });

  it('最大化窗口完整走一轮: 补正三步 + 还原两步', async () => {
    const { calls, win } = createFakeWindow();
    let status: PreviewFullscreenStatus = IDLE;

    const enter = previewFullscreenTransition(status, { fullscreenActive: true, windowWasMaximized: true });
    status = { mirrored: enter.mirrored, corrected: enter.corrected };
    await applyPreviewFullscreenAction(win, enter.action);

    const leave = previewFullscreenTransition(status, { fullscreenActive: false, windowWasMaximized: true });
    status = { mirrored: leave.mirrored, corrected: leave.corrected };
    await applyPreviewFullscreenAction(win, leave.action);

    expect(calls).toEqual([
      'setFullscreen(false)',
      'unmaximize',
      'setFullscreen(true)',
      'setFullscreen(false)',
      'maximize',
    ]);
    expect(status).toEqual({ mirrored: false, corrected: false });
  });
});
