// This file is generated by AI.

// 配音设置读取的回归测试。
//
// 重点是"存储里的旧默认值不能盖住代码里的新默认值": 推理参数的默认值曾经是
// topK 5 / topP 1 / 重复惩罚 1.35, 后来改成 40 / 0.9 / 1.2 —— 但老用户的
// localStorage 里还存着旧值, 于是"默认值改了却没生效"。现在存储里只保留界面上真正
// 可编辑的那一项 (默认语言)。

import { afterEach, describe, expect, it } from 'vitest';

import { loadVoiceSettings } from '../src/voice/settings';
import { DEFAULT_VOICE_DEFAULTS } from '../src/voice/types';

const STORAGE_KEY = 'webgal-ink.voice';

/** 用一份固定内容替换 localStorage (测试环境没有它) */
function stubStorage(value: string | null): void {
  (globalThis as unknown as { localStorage: unknown }).localStorage = {
    getItem: (key: string) => (key === STORAGE_KEY ? value : null),
    setItem: () => {},
    removeItem: () => {},
    clear: () => {},
    key: () => null,
    length: value === null ? 0 : 1,
  };
}

afterEach(() => {
  delete (globalThis as unknown as { localStorage?: unknown }).localStorage;
});

describe('loadVoiceSettings', () => {
  it('没有存储时用代码里的默认值', () => {
    stubStorage(null);
    const settings = loadVoiceSettings();
    expect(settings.defaults.topK).toBe(40);
    expect(settings.defaults.topP).toBe(0.9);
    expect(settings.defaults.repetitionPenalty).toBe(1.2);
    expect(settings.defaults).toEqual(DEFAULT_VOICE_DEFAULTS);
  });

  it('存储里的旧推理参数不会盖住代码里的默认值', () => {
    stubStorage(
      JSON.stringify({
        launch: null,
        defaults: { language: 'ja', topK: 5, topP: 1, repetitionPenalty: 1.35, temperature: 0.5 },
      })
    );
    const settings = loadVoiceSettings();
    // 代码里的默认值说了算
    expect(settings.defaults.topK).toBe(40);
    expect(settings.defaults.topP).toBe(0.9);
    expect(settings.defaults.repetitionPenalty).toBe(1.2);
    expect(settings.defaults.temperature).toBe(DEFAULT_VOICE_DEFAULTS.temperature);
    // 界面上可编辑的那一项照旧读存储
    expect(settings.defaults.language).toBe('ja');
  });

  it('启动配置与测试步数照旧从存储读取', () => {
    stubStorage(JSON.stringify({ launch: { root: 'C:\\gsov' }, testSampleSteps: 8 }));
    const settings = loadVoiceSettings();
    expect(settings.launch?.root).toBe('C:\\gsov');
    expect(settings.testSampleSteps).toBe(8);
  });

  it('存储内容损坏时回退到默认值', () => {
    stubStorage('{ 半截 JSON');
    expect(loadVoiceSettings().defaults).toEqual(DEFAULT_VOICE_DEFAULTS);
  });
});
