// This file is generated by AI.

// 参数身份与报错显示的处理规则测试。
//
// 这里钉住两条曾经出过问题的规则:
// 1. **默认种子必须可重复**。种子以前在"取当前参数"时现随机, 于是刷新令牌一变种子
//    就换掉 —— 测试记录里是 3274716390, 紧接着的生成用的却是另一个种子。
// 2. **报错只留一行摘要**。GSOV 的原始报错几十行, 铺在历史卡片里会把整栏撑爆。

import { describe, expect, it } from 'vitest';

import type { SayLine } from '../src/commands/voice';
import { errorDetail, errorHint, errorSummary } from '../src/voice/errorText';
import { paramsKey, seedForDialogue, type VoiceParams } from '../src/voice/types';

function say(text: string, speaker: string | null = '爱音', line = 0): SayLine {
  return { line, lineCount: 1, speaker, speakerInherited: false, text, vocal: null, figure: null, hash: `${line}` };
}

describe('seedForDialogue', () => {
  it('同一条对话永远得到同一个种子 (查询不产生随机)', () => {
    const dialogue = say('爱音躺在沙发上，如往常一样翻看着手机。');
    const first = seedForDialogue(dialogue);
    for (let index = 0; index < 20; index++) expect(seedForDialogue(dialogue)).toBe(first);
  });

  it('落回服务端接受的非负 32 位范围', () => {
    const seeds = Array.from({ length: 200 }, (_, index) => seedForDialogue(say(`第${index}句台词`)));
    for (const seed of seeds) {
      expect(Number.isInteger(seed)).toBe(true);
      expect(seed).toBeGreaterThanOrEqual(0);
      expect(seed).toBeLessThanOrEqual(0xffffffff);
    }
    // 不同台词基本不该撞到同一个种子
    expect(new Set(seeds).size).toBeGreaterThan(190);
  });

  it('台词或对话者不同即为不同种子', () => {
    expect(seedForDialogue(say('第一句'))).not.toBe(seedForDialogue(say('第二句')));
    expect(seedForDialogue(say('同一句', '爱音'))).not.toBe(seedForDialogue(say('同一句', '素世')));
  });
});

describe('paramsKey', () => {
  const base: VoiceParams = {
    characterId: 'anon',
    referenceHash: 'ref-1',
    language: 'auto',
    text: '台词',
    seed: 3274716390,
    temperature: 1,
    speedFactor: 1,
    topK: 5,
    topP: 1,
    repetitionPenalty: 1.35,
    sampleSteps: 32,
  };

  it('采样步数不属于配置身份 (测试 x4 与生成 x32 是同一套配置)', () => {
    expect(paramsKey({ ...base, sampleSteps: 4 })).toBe(paramsKey({ ...base, sampleSteps: 32 }));
  });

  it('种子、文本、角色、参考音频的改动都会改变身份', () => {
    expect(paramsKey({ ...base, seed: base.seed + 1 })).not.toBe(paramsKey(base));
    expect(paramsKey({ ...base, text: '别的台词' })).not.toBe(paramsKey(base));
    expect(paramsKey({ ...base, characterId: 'soyo' })).not.toBe(paramsKey(base));
    expect(paramsKey({ ...base, referenceHash: 'ref-2' })).not.toBe(paramsKey(base));
    expect(paramsKey({ ...base, temperature: 1.2 })).not.toBe(paramsKey(base));
  });

  it('文本两端空白不改变身份', () => {
    expect(paramsKey({ ...base, text: '  台词  ' })).toBe(paramsKey(base));
  });
});

/*
 * 一份真实报错 (缺 NLTK 资源): 颜色转义是被日志层剥掉 ESC 后残留的形式,
 * 横幅是整行星号, 中间还夹着空行与搜索路径列表。
 */
const NLTK_ERROR = [
  'GSOV 返回错误 (400): **********************************************************************',
  '  Resource [93maveraged_perceptron_tagger_eng[0m not found.',
  '  Please use the NLTK Downloader to obtain the resource:',
  '',
  '  >>> import nltk',
  "  >>> nltk.download('averaged_perceptron_tagger_eng')",
  '  For more information see: https://www.nltk.org/data.html',
  '',
  '  Attempted to load [93mtaggers/averaged_perceptron_tagger_eng[0m',
  '  Searched in:',
  "    - 'C:\\Users\\Li_MASTER/nltk_data'",
  "    - 'C:\\Users\\Li_MASTER\\.conda\\envs\\gpt-sovits\\nltk_data'",
  '**********************************************************************',
].join('\r\n');

describe('errorSummary', () => {
  it('压成一行并带上真正有用的信息', () => {
    const summary = errorSummary(NLTK_ERROR);
    expect(summary).not.toContain('\n');
    expect(summary).not.toContain('*');
    expect(summary).not.toContain('[93m');
    expect(summary).toContain('averaged_perceptron_tagger_eng not found');
  });

  it('超长时截断, 保证卡片只有一行', () => {
    const summary = errorSummary('错'.repeat(400));
    expect(summary.length).toBe(96);
    expect(summary.endsWith('…')).toBe(true);
  });

  it('空报错回落到固定文案', () => {
    expect(errorSummary('')).toBe('生成失败');
    expect(errorSummary('\n\n')).toBe('生成失败');
  });
});

describe('errorDetail', () => {
  it('保留换行与路径, 去掉颜色与横幅', () => {
    const detail = errorDetail(NLTK_ERROR);
    expect(detail.split('\n').length).toBeGreaterThan(4);
    expect(detail).toContain("nltk.download('averaged_perceptron_tagger_eng')");
    expect(detail).toContain("'C:\\Users\\Li_MASTER/nltk_data'");
    expect(detail).not.toContain('[0m');
    expect(detail.split('\n').some((line) => /^\*+$/.test(line.trim()))).toBe(false);
  });
});

describe('errorHint', () => {
  it('缺 NLTK 资源时给出可直接执行的命令', () => {
    expect(errorHint(NLTK_ERROR)).toContain('python -m nltk.downloader averaged_perceptron_tagger_eng');
  });

  it('其他报错不给提示', () => {
    expect(errorHint('GSOV 返回错误 (500): connection refused')).toBeNull();
  });
});
