// This file is generated by AI.

import * as vscode from 'vscode';
import {
    Executable,
    LanguageClient,
    LanguageClientOptions,
    RequestType
} from 'vscode-languageclient/node';

type ExistsParams = { path: string };
type ExistsResult = { exists: boolean; isDirectory: boolean };
type ReadDirectoryParams = { path: string };
type ReadDirectoryResult = { name: string; isDirectory: boolean }[];
type ReadFileParams = { path: string };
type ReadFileResult = string;

const ExistsRequest = new RequestType<ExistsParams, ExistsResult, void>('workspace/fs/exists');
const ReadDirectoryRequest = new RequestType<ReadDirectoryParams, ReadDirectoryResult, void>('workspace/fs/readDirectory');
const ReadFileRequest = new RequestType<ReadFileParams, ReadFileResult, void>('workspace/fs/readFile');

let client: LanguageClient;

export async function activate(context: vscode.ExtensionContext) {
    // 使用纯文本格式 debug 日志
    const run: Executable = {
        command: process.env.SERVER_PATH || 'webgal-language-server',
        args: ['--log-level', 'debug', '--log-format', 'plain'],
    };

    const clientOptions: LanguageClientOptions = {
        documentSelector: [{ scheme: 'file', language: 'webgal' }],
        // 输出通道便于查看 stderr
        outputChannel: vscode.window.createOutputChannel('WebGAL LSP', { log: true }),
    };

    client = new LanguageClient('webgal-language-server', 'WebGAL LSP', { run, debug: run }, clientOptions);

    // 注册文件系统扩展请求
    context.subscriptions.push(
        client.onRequest(ReadDirectoryRequest, async (params) => {
            const uri = vscode.Uri.parse(params.path, true);
            const entries = await vscode.workspace.fs.readDirectory(uri);
            return entries.map(([name, type]) => ({ name, isDirectory: type === vscode.FileType.Directory }));
        }),
        client.onRequest(ReadFileRequest, async (params) => {
            const uri = vscode.Uri.parse(params.path, true);
            const data = await vscode.workspace.fs.readFile(uri);
            return Buffer.from(data).toString('utf8');
        }),
        client.onRequest(ExistsRequest, async (params) => {
            const uri = vscode.Uri.parse(params.path, true);
            try {
                const stat = await vscode.workspace.fs.stat(uri);
                return {
                    exists: true,
                    isDirectory: stat.type === vscode.FileType.Directory,
                };
            } catch (error) {
                // 文件不存在或其他错误 (如权限) 视为不存在
                return {
                    exists: false,
                    isDirectory: false,
                };
            }
        })
    );

    await client.start();
}

export function deactivate() {
    return client?.stop();
}
