// This file is generated by AI.

import * as vscode from 'vscode';
import { Executable, LanguageClient, LanguageClientOptions, RequestType } from 'vscode-languageclient/node';

type StatParams = { uri: string };
type StatResult = {
  type: 'file' | 'directory' | 'symbolicLink' | 'unknown';
  size: number;
  mtime?: number;
  ctime?: number;
} | null;
type ReadDirectoryParams = { uri: string };
type ReadDirectoryResult = {
  uri: string;
  name: string;
  type: 'file' | 'directory' | 'symbolicLink' | 'unknown';
  size?: number;
  mtime?: number;
}[];
type ReadFileParams = { uri: string; encoding: 'utf-8' | 'base64' };
type ReadFileResult = {
  content: string;
  encoding: 'utf-8' | 'base64';
  size?: number;
  mtime?: number;
  etag?: string;
};

const StatRequest = new RequestType<StatParams, StatResult, void>('workspace/fs/stat');
const ReadDirectoryRequest = new RequestType<ReadDirectoryParams, ReadDirectoryResult, void>(
  'workspace/fs/readDirectory'
);
const ReadFileRequest = new RequestType<ReadFileParams, ReadFileResult, void>('workspace/fs/readFile');

let client: LanguageClient;

export async function activate(context: vscode.ExtensionContext) {
  // 使用纯文本格式 debug 日志
  const run: Executable = {
    command: process.env.SERVER_PATH || 'webgal-language-server',
    args: ['--log-level', 'debug', '--log-format', 'plain'],
  };

  const clientOptions: LanguageClientOptions = {
    documentSelector: [{ scheme: 'file', language: 'webgal' }],
    // 输出通道便于查看 stderr
    outputChannel: vscode.window.createOutputChannel('WebGAL LSP', { log: true }),
  };

  client = new LanguageClient('webgal-language-server', 'WebGAL LSP', { run, debug: run }, clientOptions);

  // 注册文件系统扩展请求
  context.subscriptions.push(
    client.onRequest(StatRequest, async (params) => {
      const uri = vscode.Uri.parse(params.uri, true);
      try {
        const stat = await vscode.workspace.fs.stat(uri);
        return {
          type: stat.type === vscode.FileType.Directory ? 'directory' : 'file',
          size: stat.size,
          mtime: stat.mtime,
          ctime: stat.ctime,
        };
      } catch {
        return null;
      }
    }),
    client.onRequest(ReadDirectoryRequest, async (params) => {
      const uri = vscode.Uri.parse(params.uri, true);
      const entries = await vscode.workspace.fs.readDirectory(uri);
      return entries.map(([name, type]) => ({
        uri: vscode.Uri.joinPath(uri, name).toString(true),
        name,
        type: type === vscode.FileType.Directory ? 'directory' : 'file',
      }));
    }),
    client.onRequest(ReadFileRequest, async (params) => {
      const uri = vscode.Uri.parse(params.uri, true);
      const data = await vscode.workspace.fs.readFile(uri);
      if (params.encoding === 'base64') {
        return { content: Buffer.from(data).toString('base64'), encoding: 'base64' };
      }
      return { content: Buffer.from(data).toString('utf8'), encoding: 'utf-8' };
    })
  );

  await client.start();
}

export function deactivate() {
  return client?.stop();
}
