// This file is generated by AI.

// 语义高亮的取值策略 (纯函数, 便于测试)。
//
// 为什么需要它: 语言服务在"项目还没加载完"时对本项目文件的 `semantic_tokens_full` 只会回空
// (`workspace` 里还找不到这个项目, 见 webgal-language-server 的 semantic_tokens_full), 而
// Monaco 收到 null 就认定该 model 的语义 token 已经拿到, **不会再问第二次** —— 于是"打开项目
// 立刻看场景"就永远不着色, 直到用户切标签页重建编辑器。
//
// 因此这里不信任第一次的空答案: 在预算内反复问; 超时、出错或始终为空就退回本地高亮 ——
// Tauri 的 `highlight_scene_all` 与语言服务调用的是同一个 `highlight()`、同一份 token 图例,
// 只是不需要项目上下文 (直接解析编辑器里这份文本)。

export interface SemanticTokensOptions {
  /** 语言服务: 返回 null 表示"服务端还不知道这个文件" */
  lsp: () => Promise<number[] | null>;
  /** 本地兜底: 后端直接高亮整篇文本 */
  local: () => Promise<number[]>;
  /** 愿意为语言服务的答案等多久 */
  budgetMs: number;
  /** 预算内的重试间隔 */
  retryMs: number;
  /** Monaco 已取消这次请求 (model 变了 / 编辑器关了): 结果反正要丢弃, 立刻停手 */
  isCancelled?: () => boolean;
  /** 便于测试注入时钟 */
  now?: () => number;
  sleep?: (ms: number) => Promise<void>;
}

/**
 * 取一份场景的语义高亮。
 *
 * 语言服务先答"空"并不罕见 (项目还在扫), 所以只有**非空**答案才算数; 预算走完就交给本地高亮。
 * 本地高亮也失败时返回 null, 由调用方按"没有结果"处理。
 */
export async function resolveSemanticTokens(options: SemanticTokensOptions): Promise<number[] | null> {
  const { lsp, local, budgetMs, retryMs, isCancelled, now = () => Date.now(), sleep = delay } = options;
  const deadline = now() + budgetMs;

  for (;;) {
    let tokens: number[] | null;
    try {
      tokens = await lsp();
    } catch {
      // 连接断开 / 服务端拒绝: 剩下的预算等不来任何东西
      break;
    }
    if (tokens && tokens.length > 0) return tokens;
    if (isCancelled?.()) return null;
    if (now() >= deadline) break;
    await sleep(retryMs);
  }

  try {
    return await local();
  } catch {
    return null;
  }
}

function delay(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
