// This file is generated by AI.

// Monaco 编辑器 + LSP 集成: 注册语言与各 provider, 管理文档同步与诊断 markers。
//
// 悬停 Markdown 与补全 snippet ($0/$1) 均由 Monaco 原生渲染, 无需手动转换。

import * as monaco from 'monaco-editor';
import EditorWorker from 'monaco-editor/esm/vs/editor/editor.worker?worker';

import { toUri } from '../lib/uri';
import { useAppStore } from '../state/store';
import {
  lspClient,
  type LspCompletionItem,
  type LspDiagnostic,
  type LspHover,
  type LspRange,
  type LspTextEdit,
} from './client';

// Monaco 内部模块 (无公开类型声明): 用于在启动时把补全详情面板设为默认展开
// (expandSuggestionDocs 标志默认 false, 会导致补全项文档不显示)。
// 注意: StorageScope/StorageTarget 是编译期内联的 TS 枚举, 不作为运行时导出, 这里直接使用其数值。
// @ts-expect-error -- Monaco 内部模块, 无类型声明
import { IStorageService } from 'monaco-editor/esm/vs/platform/storage/common/storage.js';
// @ts-expect-error -- Monaco 内部模块, 无类型声明
import { StandaloneServices } from 'monaco-editor/esm/vs/editor/standalone/browser/standaloneServices.js';

// 配置 Monaco worker (Vite 打包); webgal 为自定义语言, 仅需基础 editor worker
self.MonacoEnvironment = {
  getWorker: () => new EditorWorker(),
};

export const LANGUAGE_ID = 'webgal';

// 服务端 completionProvider.triggerCharacters (见 crates/webgal-language-service/src/service/complete.rs):
// 输入这些符号时自动触发补全 (Monaco 原生支持 provider 级 triggerCharacters)。
export const TRIGGER_CHARACTERS = [':', '-', '=', '/', '\\', '"'];

// Monaco model -> 原始系统路径。
// 不能依赖 `model.uri.toString()` 往返还原路径: Monaco 的 Uri 会把
// `file:///C:/...` 序列化为 `file:///c%3A/...` (盘符小写 + 冒号百分号编码),
// 无法还原回原始路径, 导致 provider 向 LSP 发送错误的 URI。
const modelPathMap = new WeakMap<monaco.editor.ITextModel, string>();

function pathOfModel(model: monaco.editor.ITextModel): string | null {
  return modelPathMap.get(model) ?? null;
}

const SEMANTIC_TOKEN_TYPES = [
  'type',
  'variable',
  'parameter',
  'property',
  'enumMember',
  'function',
  'keyword',
  'comment',
  'string',
  'number',
  'regexp',
  'operator',
];

const LSP_KIND_TO_MONACO: Record<number, monaco.languages.CompletionItemKind> = {
  1: monaco.languages.CompletionItemKind.Text,
  2: monaco.languages.CompletionItemKind.Method,
  3: monaco.languages.CompletionItemKind.Function,
  4: monaco.languages.CompletionItemKind.Constructor,
  5: monaco.languages.CompletionItemKind.Field,
  6: monaco.languages.CompletionItemKind.Variable,
  7: monaco.languages.CompletionItemKind.Class,
  8: monaco.languages.CompletionItemKind.Interface,
  9: monaco.languages.CompletionItemKind.Module,
  10: monaco.languages.CompletionItemKind.Property,
  11: monaco.languages.CompletionItemKind.Unit,
  12: monaco.languages.CompletionItemKind.Value,
  13: monaco.languages.CompletionItemKind.Enum,
  14: monaco.languages.CompletionItemKind.Keyword,
  15: monaco.languages.CompletionItemKind.Snippet,
  16: monaco.languages.CompletionItemKind.Color,
  17: monaco.languages.CompletionItemKind.File,
  18: monaco.languages.CompletionItemKind.Reference,
  19: monaco.languages.CompletionItemKind.Folder,
  20: monaco.languages.CompletionItemKind.EnumMember,
  21: monaco.languages.CompletionItemKind.Constant,
  22: monaco.languages.CompletionItemKind.Struct,
  23: monaco.languages.CompletionItemKind.Event,
  24: monaco.languages.CompletionItemKind.Operator,
  25: monaco.languages.CompletionItemKind.TypeParameter,
};

function toMonacoRange(range: LspRange): monaco.Range {
  return new monaco.Range(range.start.line + 1, range.start.character + 1, range.end.line + 1, range.end.character + 1);
}

function hoverText(hover: LspHover): string {
  const contents = hover.contents;
  if (typeof contents === 'string') return contents;
  if (Array.isArray(contents)) return contents.map((c) => c.value).join('\n\n');
  return contents.value;
}

function toCompletionItem(item: LspCompletionItem, fallbackRange: monaco.IRange): monaco.languages.CompletionItem {
  const edit = item.textEdit;
  const isSnippet = item.insertTextFormat === 2;
  const insertText = edit && 'newText' in edit ? edit.newText : (item.insertText ?? item.label);
  const range = edit && 'range' in edit ? toMonacoRange(edit.range) : fallbackRange;
  // 服务端把"详细描述"放在 labelDetails.description, 映射到条目右部 (Monaco detail)
  const detail = item.detail ?? item.labelDetails?.description ?? undefined;
  // 文档: 兼容字符串与 MarkupContent {kind, value}, 以 markdown 形式呈现
  const rawDoc = item.documentation;
  const docValue = typeof rawDoc === 'string' ? rawDoc : rawDoc?.value;
  return {
    label: item.label,
    kind:
      item.kind !== undefined
        ? (LSP_KIND_TO_MONACO[item.kind] ?? monaco.languages.CompletionItemKind.Text)
        : monaco.languages.CompletionItemKind.Text,
    detail,
    documentation: docValue ? { value: docValue, isTrusted: false } : undefined,
    insertText,
    insertTextRules: isSnippet ? monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet : undefined,
    range,
  };
}

function toMarker(d: LspDiagnostic): monaco.editor.IMarkerData {
  const severity =
    d.severity === 1
      ? monaco.MarkerSeverity.Error
      : d.severity === 2
        ? monaco.MarkerSeverity.Warning
        : d.severity === 4
          ? monaco.MarkerSeverity.Hint
          : monaco.MarkerSeverity.Info;
  return {
    severity,
    message: d.message,
    source: d.source,
    startLineNumber: d.range.start.line + 1,
    startColumn: d.range.start.character + 1,
    endLineNumber: d.range.end.line + 1,
    endColumn: d.range.end.character + 1,
  };
}

function toMonacoTextEdit(edit: LspTextEdit): monaco.languages.TextEdit {
  return { range: toMonacoRange(edit.range), text: edit.newText };
}

// 语义高亮需要显式启用: 内置 vs/vs-dark 主题的 `semanticHighlighting` 恒为 false,
// 且内置主题缺少 parameter/property/enumMember/function/operator 等规则,
// 因此自定义主题并为全部 12 种语义 token 类型定义颜色。
//
// 颜色 = 按 VS Code 官方的"语义 token -> TextMate 作用域"映射 (tokenClassificationRegistry.js)
// 在主题 tokenColors 上解析出的结果, 与 WebGAL_Terre 中 LSP 语义高亮覆盖 TextMate 后的实际效果一致:
//   type→entity.name.type / variable→variable.other.readwrite / parameter→variable.parameter /
//   property→variable.other.property / enumMember→variable.other.enummember / function→entity.name.function /
//   keyword→keyword.control / comment→comment / string→string / number→constant.numeric /
//   regexp→constant.regexp / operator→keyword.operator
// 深色对应 vscode-dark-modern.json (Dark+), 浅色对应 monokai-light-vs.json (Monokai Light)。
const WEBGAL_TOKEN_COLORS: Record<string, string> = {
  type: '4ec9b0',
  variable: '9cdcfe',
  parameter: '9cdcfe',
  property: '9cdcfe',
  enumMember: '4fc1ff',
  function: 'dcdcaa',
  keyword: '569cd6',
  comment: '6a9955',
  string: 'ce9178',
  number: 'b5cea8',
  regexp: '646695',
  operator: 'd4d4d4',
};

const WEBGAL_TOKEN_COLORS_LIGHT: Record<string, string> = {
  type: '267f99',
  variable: '001080',
  parameter: '001080',
  property: '001080',
  enumMember: '0070c1',
  function: '795e26',
  keyword: '0000ff',
  comment: '008000',
  string: 'a31515',
  number: '098658',
  regexp: '684d99',
  operator: '000000',
};

function defineWebgalThemes(): void {
  const toRules = (colors: Record<string, string>) =>
    Object.entries(colors).map(([token, foreground]) => ({ token, foreground }));
  monaco.editor.defineTheme('webgal-dark', {
    base: 'vs-dark',
    inherit: true,
    rules: toRules(WEBGAL_TOKEN_COLORS),
    colors: {},
  });
  monaco.editor.defineTheme('webgal-light', {
    base: 'vs',
    inherit: true,
    rules: toRules(WEBGAL_TOKEN_COLORS_LIGHT),
    colors: {},
  });
}

let setupDone = false;

export function setupMonaco(): void {
  if (setupDone) return;
  setupDone = true;

  // 补全详情面板默认展开: Monaco 的 `expandSuggestionDocs` 存储标志默认 false,
  // 导致补全项的 documentation 面板收起。直接写入 standalone 存储服务设为 true,
  // 让详情面板从一开始就展开 (无需用户按 Ctrl+Space)。
  try {
    const storage = StandaloneServices.get(IStorageService) as {
      store: (key: string, value: unknown, scope: unknown, target: unknown) => void;
    };
    // expandSuggestionDocs: 0 = StorageScope.PROFILE, 0 = StorageTarget.USER
    storage.store('expandSuggestionDocs', true, 0, 0);
  } catch {
    // 内部 API 变化时静默忽略, 不影响编辑器
  }

  defineWebgalThemes();
  monaco.languages.register({ id: LANGUAGE_ID });

  monaco.languages.registerDocumentSemanticTokensProvider(LANGUAGE_ID, {
    getLegend: () => ({ tokenTypes: SEMANTIC_TOKEN_TYPES, tokenModifiers: [] }),
    provideDocumentSemanticTokens: async (model) => {
      const path = pathOfModel(model);
      if (!path) return null;
      try {
        const data = await lspClient.semanticTokens(path);
        if (!data || data.length === 0) return null;
        return { data: new Uint32Array(data) };
      } catch {
        return null;
      }
    },
    releaseDocumentSemanticTokens: () => {},
  });

  monaco.languages.registerCompletionItemProvider(LANGUAGE_ID, {
    triggerCharacters: TRIGGER_CHARACTERS,
    provideCompletionItems: async (model, position) => {
      const path = pathOfModel(model);
      if (!path) return { suggestions: [] };
      const word = model.getWordUntilPosition(position);
      const fallbackRange = new monaco.Range(
        position.lineNumber,
        word.startColumn,
        position.lineNumber,
        word.endColumn
      );
      try {
        const items = await lspClient.completion(path, {
          line: position.lineNumber - 1,
          character: position.column - 1,
        });
        if (!items || items.length === 0) return { suggestions: [] };
        return { suggestions: items.map((item) => toCompletionItem(item, fallbackRange)) };
      } catch {
        return { suggestions: [] };
      }
    },
  });

  monaco.languages.registerHoverProvider(LANGUAGE_ID, {
    provideHover: async (model, position) => {
      const path = pathOfModel(model);
      if (!path) return null;
      try {
        const hover = await lspClient.hover(path, {
          line: position.lineNumber - 1,
          character: position.column - 1,
        });
        if (!hover || !hover.contents) return null;
        const text = hoverText(hover);
        if (!text.trim()) return null;
        return {
          range: hover.range
            ? toMonacoRange(hover.range)
            : new monaco.Range(position.lineNumber, position.column, position.lineNumber, position.column),
          contents: [{ value: text, isTrusted: false }],
        };
      } catch {
        return null;
      }
    },
  });

  monaco.languages.registerDocumentFormattingEditProvider(LANGUAGE_ID, {
    provideDocumentFormattingEdits: async (model) => {
      const path = pathOfModel(model);
      if (!path) return null;
      try {
        const edits = await lspClient.formatting(path);
        if (!edits || edits.length === 0) return null;
        return edits.map(toMonacoTextEdit);
      } catch {
        return null;
      }
    },
  });
}

export function setMonacoTheme(dark: boolean): void {
  monaco.editor.setTheme(dark ? 'webgal-dark' : 'webgal-light');
}

/** 打开文档对应的 model (已存在则重置内容, 保证重新打开读到最新磁盘内容)。 */
export function openModel(path: string, content: string): monaco.editor.ITextModel {
  const uri = monaco.Uri.parse(toUri(path));
  let model = monaco.editor.getModel(uri);
  if (!model) {
    model = monaco.editor.createModel(content, LANGUAGE_ID, uri);
  } else if (model.getValue() !== content) {
    model.setValue(content);
  }
  modelPathMap.set(model, path);
  return model;
}

/** 关闭文档时销毁对应 model。 */
export function disposeModel(path: string): void {
  const uri = monaco.Uri.parse(toUri(path));
  monaco.editor.getModel(uri)?.dispose();
}

/** 绑定文档同步 (didOpen / didChange / didClose) 与内容回写, 返回解绑函数。 */
export function bindModel(
  model: monaco.editor.ITextModel,
  path: string,
  onContentChange: (text: string) => void
): () => void {
  lspClient.openDocument(path, model.getValue());
  const changeSub = model.onDidChangeContent(() => {
    const text = model.getValue();
    lspClient.changeDocument(path, text, model.getVersionId());
    onContentChange(text);
  });
  const disposeSub = model.onWillDispose(() => {
    lspClient.closeDocument(path);
  });
  return () => {
    changeSub.dispose();
    disposeSub.dispose();
    lspClient.closeDocument(path);
  };
}

/** 把 store 中该文档的诊断写入 Monaco markers。 */
export function applyDiagnostics(model: monaco.editor.ITextModel, path: string): void {
  const diags = useAppStore.getState().diagnostics[path] ?? [];
  monaco.editor.setModelMarkers(model, LANGUAGE_ID, diags.map(toMarker));
}
