// This file is generated by AI.

// 诊断列表 (底部托盘形式): 从编辑区与状态栏之间升起, 不遮挡代码 —— 适合"点一条改一条"。
//
// 托盘是编辑区里的一个普通 flex 子项, 不是浮层: 它把编辑区顶矮而不是盖住它, 因此不需要
// 处理定位、裁剪与层级 (项目里的自绘弹层都在绕这些问题)。

import { Button } from '@fluentui/react-components';
import { CopyRegular, DismissRegular } from '@fluentui/react-icons';
import { useEffect } from 'react';

import { DiagnosticsFilterBar, DiagnosticsList, useDiagnosticsView } from './view';

export function DiagnosticsTray({ onClose }: { onClose: () => void }) {
  const view = useDiagnosticsView();

  // Esc 收起。上面盖着对话框时不动 (那是那个对话框的 Esc)。
  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key !== 'Escape' || event.isComposing) return;
      if (document.querySelector('.modal-surface')) return;
      onClose();
    };
    window.addEventListener('keydown', onKeyDown);
    return () => window.removeEventListener('keydown', onKeyDown);
  }, [onClose]);

  return (
    <section className="diag-dock" aria-label="诊断">
      <div className="diag-dock-head">
        <span className="diag-dock-title">诊断</span>
        <span className="diag-dock-description">{view.description}</span>
        <span className="diag-dock-spacer" />
        <Button
          size="small"
          appearance="secondary"
          icon={<CopyRegular />}
          disabled={view.visibleCount === 0}
          onClick={view.copyResult}
        >
          {view.copied === 'result' ? '已复制' : '复制结果'}
        </Button>
        <Button
          size="small"
          appearance="subtle"
          icon={<DismissRegular />}
          title="收起诊断"
          aria-label="收起诊断"
          onClick={onClose}
        />
      </div>
      <DiagnosticsFilterBar view={view} />
      <DiagnosticsList view={view} />
    </section>
  );
}
