// This file is generated by AI.

// 诊断列表的视图层: 筛选条 + 按文件分组的问题列表。
//
// 弹窗与底部托盘**共用**这一份 (见 `DiagnosticsDialog` / `DiagnosticsTray`): 两者的区别
// 只是外壳 (标题栏在哪、复制按钮放哪), 列表本身没有任何理由长得不一样。
//
// 状态放在 `useDiagnosticsView` 这一个 hook 里, 两个外壳各自调用一次并把它交给下面两个
// 组件 —— 而不是让列表组件自己持有状态, 否则"复制结果"按钮 (在外壳里) 拿不到筛选后的数据。

import { Button, Checkbox, Input } from '@fluentui/react-components';
import {
  CheckmarkRegular,
  ChevronDownRegular,
  ChevronRightRegular,
  CopyRegular,
  ErrorCircleRegular,
  InfoRegular,
  LightbulbRegular,
  SearchRegular,
  WarningRegular,
} from '@fluentui/react-icons';
import { useCallback, useEffect, useMemo, useRef, useState, type ReactNode } from 'react';

import { openFile } from '../project';
import { useAppStore } from '../state/store';
import {
  buildDiagnosticsExport,
  codeStats,
  collectProjectDiagnostics,
  countBySeverity,
  countEntries,
  defaultFilter,
  describeDiagnostics,
  filterDiagnosticFiles,
  isFilterPerturbed,
  presentSeverities,
  SEVERITY_LABELS,
  SEVERITY_ORDER,
  type CodeStat,
  type DiagnosticEntry,
  type DiagnosticFile,
  type DiagnosticFilter,
  type Severity,
} from './model';

const SEVERITY_ICONS: Record<Severity, ReactNode> = {
  1: <ErrorCircleRegular />,
  2: <WarningRegular />,
  3: <InfoRegular />,
  4: <LightbulbRegular />,
};

/** 组头角标的类名后缀 (沿用文件树里同一套颜色: `.diag-badge.diag-error` 等) */
const BADGE_NAMES: Record<Severity, string> = {
  1: 'error',
  2: 'warn',
  3: 'info',
  4: 'hint',
};

/** 复制反馈的停留时长 */
const COPIED_MS = 1600;

export interface DiagnosticsViewState {
  /** 标题下方那行小字 (弹窗) / 标题旁那行 (托盘): 项目 · 场景数 · 问题数 (已隐藏数) */
  description: string;
  /** 数据里出现过的级别与每个级别的条数 */
  severityStats: { severity: Severity; count: number }[];
  codes: CodeStat[];
  filter: DiagnosticFilter;
  visibleFiles: DiagnosticFile[];
  /** 当前显示的条数 */
  visibleCount: number;
  /** 被筛选条件挡掉的条数 */
  hiddenCount: number;
  /** 列表为空时显示的主句; `null` 表示空是筛选造成的, 由列表给出提示 */
  emptyText: string | null;
  /** 当前是否有任何筛选条件偏离默认 (决定要不要给出"清除筛选") */
  filtered: boolean;
  /** 刚刚复制成功的目标: 'result' 或某个文件路径 */
  copied: string | null;
  toggleSeverity: (severity: Severity) => void;
  toggleCode: (code: string) => void;
  setAllCodes: (on: boolean) => void;
  setQuery: (query: string) => void;
  resetFilter: () => void;
  copyResult: () => void;
  copyFile: (file: DiagnosticFile) => void;
  openEntry: (entry: DiagnosticEntry) => void;
}

/**
 * 诊断列表的数据与筛选状态。
 *
 * `filter` 为 `null` 表示"还用着默认条件" —— 默认条件依赖数据 (项目里出现了哪些级别),
 * 而数据是异步到的, 因此不能在一开始就把它固化成 state。
 */
export function useDiagnosticsView(): DiagnosticsViewState {
  const diagnostics = useAppStore((s) => s.diagnostics);
  const projectPath = useAppStore((s) => s.projectPath);
  const projectName = useAppStore((s) => s.projectName);
  const lspStatus = useAppStore((s) => s.lspStatus);

  const collected = useMemo(() => collectProjectDiagnostics(diagnostics, projectPath), [diagnostics, projectPath]);
  const [userFilter, setUserFilter] = useState<DiagnosticFilter | null>(null);
  const fallback = useMemo(() => defaultFilter(collected.files), [collected]);
  const filter = userFilter ?? fallback;

  const codes = useMemo(() => codeStats(collected.files), [collected]);
  const severityStats = useMemo(() => {
    const counts = new Map<Severity, number>();
    for (const file of collected.files) {
      for (const entry of file.entries) counts.set(entry.severity, (counts.get(entry.severity) ?? 0) + 1);
    }
    return presentSeverities(collected.files).map((severity) => ({ severity, count: counts.get(severity) ?? 0 }));
  }, [collected]);

  const visibleFiles = useMemo(() => filterDiagnosticFiles(collected.files, filter), [collected, filter]);
  const visibleCount = countEntries(visibleFiles);
  const totalCount = countEntries(collected.files);
  const hiddenCount = totalCount - visibleCount;

  const filtered = isFilterPerturbed(filter, fallback);

  const patch = (next: Partial<DiagnosticFilter>) => setUserFilter({ ...filter, ...next });

  const toggleSeverity = (severity: Severity) => {
    const on = filter.severities.includes(severity);
    const severities = on
      ? filter.severities.filter((item) => item !== severity)
      : [...filter.severities, severity].sort((a, b) => a - b);
    patch({ severities });
  };

  const toggleCode = (code: string) => {
    // `codes === null` 表示"尚未限定": 第一次点某个码时从"全选"开始算
    const current = filter.codes ?? codes.map((item) => item.code);
    const next = current.includes(code) ? current.filter((item) => item !== code) : [...current, code];
    patch({ codes: next });
  };

  const setAllCodes = (on: boolean) => patch({ codes: on ? codes.map((item) => item.code) : [] });
  const setQuery = (query: string) => patch({ query });
  const resetFilter = () => setUserFilter(null);

  // ---- 复制 ----
  const [copied, setCopied] = useState<string | null>(null);
  const timer = useRef<number | null>(null);
  useEffect(
    () => () => {
      if (timer.current !== null) window.clearTimeout(timer.current);
    },
    []
  );

  const copyText = useCallback((text: string, key: string) => {
    void navigator.clipboard
      .writeText(text)
      .then(() => {
        setCopied(key);
        if (timer.current !== null) window.clearTimeout(timer.current);
        timer.current = window.setTimeout(() => setCopied(null), COPIED_MS);
      })
      .catch((error) => console.error('复制诊断失败', error));
  }, []);

  const copyResult = useCallback(() => {
    copyText(
      buildDiagnosticsExport({
        projectName: projectName ?? '未命名项目',
        scope: { kind: 'project' },
        files: visibleFiles,
      }),
      'result'
    );
  }, [copyText, projectName, visibleFiles]);

  const copyFile = useCallback(
    (file: DiagnosticFile) => {
      copyText(
        buildDiagnosticsExport({
          projectName: projectName ?? '未命名项目',
          scope: { kind: 'file', path: file.path },
          files: [file],
        }),
        file.path
      );
    },
    [copyText, projectName]
  );

  // ---- 跳转 ----
  const openEntry = useCallback((entry: DiagnosticEntry) => {
    /*
     * 必须走 `openFile` 而不是 `openSceneTab`: 前者才会把文件读进 `documents`。
     * 只开卡的话, 那个场景从没被打开过, 编辑区会一直停在"正在读取场景…"上 ——
     * store 里只有选项卡, 没有内容可渲染。
     */
    const store = useAppStore.getState();
    // 先记请求再读盘: 读盘是异步的, 编辑器挂载时这条请求已经在了
    store.requestReveal(entry.path, entry.line, entry.column);
    void openFile(entry.path).catch((error) => console.error('打开诊断所在场景失败', error));
  }, []);

  /*
   * 标题下那一行小字, 外加"列表为空时该说什么"。
   *
   * 不写项目名: 这段文字出现在对话框/托盘的标题正下方, 而它们本来就只可能属于当前这个
   * 项目 —— 同一屏里再说一遍项目叫什么, 只是把最该一眼看到的两个数字挤到后面去。
   * 条数跟着当前筛选走, 所以"X 条问题（Y 条已隐藏）"永远是真的; 而一条结果都还没收到时
   * 干脆不给数字 (见 `describeDiagnostics`), 免得那个 "0" 被当成"项目没问题"。
   */
  const described = useMemo(
    () =>
      describeDiagnostics({
        scenes: collected.scenes,
        total: totalCount,
        visible: visibleCount,
        hidden: hiddenCount,
        lspStatus,
      }),
    [collected.scenes, totalCount, visibleCount, hiddenCount, lspStatus]
  );

  return {
    description: described.description,
    emptyText: described.emptyText,
    severityStats,
    codes,
    filter,
    visibleFiles,
    visibleCount,
    hiddenCount,
    filtered,
    copied,
    toggleSeverity,
    toggleCode,
    setAllCodes,
    setQuery,
    resetFilter,
    copyResult,
    copyFile,
    openEntry,
  };
}

/** 一行筛选条: 级别开关 + 诊断码浮层 + 关键词 */
export function DiagnosticsFilterBar({ view }: { view: DiagnosticsViewState }) {
  const [codesOpen, setCodesOpen] = useState(false);
  const codesRef = useRef<HTMLDivElement>(null);

  // 点外部 / Esc 收起浮层 (与项目里的自绘 Select 同款行为, 不用 portal)
  useEffect(() => {
    if (!codesOpen) return;
    const onPointerDown = (event: PointerEvent) => {
      if (!codesRef.current?.contains(event.target as Node)) setCodesOpen(false);
    };
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') {
        event.stopPropagation();
        setCodesOpen(false);
      }
    };
    window.addEventListener('pointerdown', onPointerDown, true);
    window.addEventListener('keydown', onKeyDown, true);
    return () => {
      window.removeEventListener('pointerdown', onPointerDown, true);
      window.removeEventListener('keydown', onKeyDown, true);
    };
  }, [codesOpen]);

  const allCodes = view.codes.map((stat) => stat.code);
  const selectedCodes = view.filter.codes ?? allCodes;

  return (
    <div className="diag-bar">
      {view.severityStats.map(({ severity, count }) => {
        const on = view.filter.severities.includes(severity);
        return (
          <button
            key={severity}
            type="button"
            className={`diag-severity${on ? ' on' : ''}`}
            aria-pressed={on}
            title={on ? `不再显示${SEVERITY_LABELS[severity]}` : `显示${SEVERITY_LABELS[severity]}`}
            onClick={() => view.toggleSeverity(severity)}
          >
            <span className={`diag-severity-dot diag-sev-${severity}`} />
            {SEVERITY_LABELS[severity]}
            <span className="diag-severity-count">{count}</span>
          </button>
        );
      })}

      {view.codes.length > 1 ? <span className="diag-bar-divider" /> : null}

      {view.codes.length > 1 ? (
        <div className="diag-codes" ref={codesRef}>
          <button
            type="button"
            className={`diag-codes-trigger${codesOpen ? ' open' : ''}`}
            aria-expanded={codesOpen}
            onClick={() => setCodesOpen((open) => !open)}
          >
            诊断码
            <span className="diag-codes-trigger-count">
              {selectedCodes.length}/{allCodes.length}
            </span>
            <ChevronDownRegular />
          </button>

          {codesOpen ? (
            <div className="diag-codes-panel" role="listbox" aria-label="诊断码">
              <div className="diag-codes-panel-head">
                <span>诊断码</span>
                <button type="button" className="diag-link" onClick={() => view.setAllCodes(true)}>
                  全选
                </button>
                <button type="button" className="diag-link" onClick={() => view.setAllCodes(false)}>
                  清空
                </button>
              </div>
              <div className="diag-codes-panel-body">
                {view.codes.map((stat) => (
                  <div className="diag-code-item" key={stat.code}>
                    <Checkbox checked={selectedCodes.includes(stat.code)} onChange={() => view.toggleCode(stat.code)} />
                    <span className={`diag-code-name diag-sev-${stat.severity}`}>{stat.code}</span>
                    <span className="diag-code-count">{stat.count}</span>
                  </div>
                ))}
              </div>
            </div>
          ) : null}
        </div>
      ) : null}

      <Input
        className="diag-search"
        size="small"
        placeholder="筛选消息或文件…"
        value={view.filter.query}
        contentBefore={<SearchRegular />}
        onChange={(_, data) => view.setQuery(data.value)}
      />

      {/*
        条件偏离默认时给一条退路: 描述行会说"X 条已隐藏", 但没有它就只能靠回忆自己关过
        哪些级别 / 敲过什么关键词。空列表里那个同名按钮够不到这种情况 (列表还剩几条时
        它根本不显示)。
      */}
      {view.filtered ? (
        <Button className="diag-clear" size="small" appearance="subtle" onClick={view.resetFilter}>
          清除筛选
        </Button>
      ) : null}
    </div>
  );
}

/**
 * 按文件分组的问题列表 (可折叠组、点行跳转、组头复制该文件)。
 *
 * `onOpened` 由外壳决定: 弹窗形式跳完就把自己收起来 —— 它盖住了编辑区, 留着也没用;
 * 托盘形式一直开着, 那正是"点一条改一条"需要的。
 */
export function DiagnosticsList({ view, onOpened }: { view: DiagnosticsViewState; onOpened?: () => void }) {
  const [collapsed, setCollapsed] = useState<string[]>([]);

  const toggleCollapsed = (path: string) =>
    setCollapsed((current) => (current.includes(path) ? current.filter((item) => item !== path) : [...current, path]));

  if (view.visibleFiles.length === 0) {
    return (
      <div className="diag-list dialog-scroll">
        <div className="diag-empty">
          {/*
            主句由 `describeDiagnostics` 给出 ("还没有收到诊断结果" / "没有发现问题")。
            它返回 null 说明数据里确实有问题, 只是被筛选挡光了 —— 那时才该劝人清除筛选。
          */}
          <p>{view.emptyText ?? '没有符合当前筛选的诊断'}</p>
          {view.emptyText === null ? (
            <Button size="small" appearance="secondary" onClick={view.resetFilter}>
              清除筛选
            </Button>
          ) : null}
        </div>
      </div>
    );
  }

  return (
    <div className="diag-list dialog-scroll">
      {view.visibleFiles.map((file) => {
        const isCollapsed = collapsed.includes(file.path);
        const index = file.scene.lastIndexOf('/');
        // 角标与行同源: 数的是这一组**当前列出的**条目, 四个级别一个不落
        const counts = countBySeverity(file.entries);
        return (
          <div className="diag-group" key={file.path}>
            <div
              className="diag-group-head"
              role="button"
              tabIndex={0}
              aria-expanded={!isCollapsed}
              onClick={() => toggleCollapsed(file.path)}
              onKeyDown={(event) => {
                if (event.key === 'Enter' || event.key === ' ') {
                  event.preventDefault();
                  toggleCollapsed(file.path);
                }
              }}
            >
              {isCollapsed ? <ChevronRightRegular /> : <ChevronDownRegular />}
              <span className="diag-group-path">
                <span className="diag-group-dir">{file.scene.slice(0, index + 1)}</span>
                {file.scene.slice(index + 1)}
              </span>
              <span className="diag-group-counts">
                {SEVERITY_ORDER.map((severity) =>
                  counts[severity] > 0 ? (
                    <span key={severity} className={`diag-badge diag-${BADGE_NAMES[severity]}`}>
                      {counts[severity]}
                    </span>
                  ) : null
                )}
              </span>
              <button
                type="button"
                className="diag-group-copy"
                title="复制此文件的诊断 (JSON)"
                aria-label="复制此文件的诊断"
                onClick={(event) => {
                  event.stopPropagation();
                  view.copyFile(file);
                }}
              >
                {view.copied === file.path ? <CheckmarkRegular /> : <CopyRegular />}
              </button>
            </div>

            {isCollapsed
              ? null
              : file.entries.map((entry) => (
                  <button
                    type="button"
                    className="diag-row"
                    key={`${entry.line}:${entry.column}:${entry.code}`}
                    title={entry.message}
                    onClick={() => {
                      view.openEntry(entry);
                      onOpened?.();
                    }}
                  >
                    <span className="diag-pos">
                      {entry.line}:{entry.column}
                    </span>
                    <span className={`diag-row-icon diag-sev-${entry.severity}`}>{SEVERITY_ICONS[entry.severity]}</span>
                    <span className="diag-msg">{entry.message}</span>
                    <span className="diag-code">{entry.code}</span>
                  </button>
                ))}
          </div>
        );
      })}
    </div>
  );
}
