// This file is generated by AI.

// 项目编辑页: 顶栏 + 左侧(预览 + 场景/资源) + 右侧(选项卡/编辑器/状态栏)。

import { Button } from '@fluentui/react-components';
import {
  ArrowLeftRegular,
  PanelLeftContractRegular,
  PanelLeftExpandRegular,
  SettingsRegular,
  WeatherMoonRegular,
  WeatherSunnyRegular,
} from '@fluentui/react-icons';
import { useState } from 'react';

import { closeProject } from '../project';
import { useAppStore } from '../state/store';
import { confirmClose } from '../unsaved';
import { CodeEditor } from './CodeEditor';
import { EditorTabs } from './EditorTabs';
import { PreviewPanel } from './PreviewPanel';
import { ResourceBrowser } from './ResourceBrowser';
import { SceneBrowser } from './SceneBrowser';
import { StatusBar } from './StatusBar';

export function EditorPage() {
  const projectName = useAppStore((s) => s.projectName);
  const documents = useAppStore((s) => s.documents);
  const activePath = useAppStore((s) => s.activePath);
  const theme = useAppStore((s) => s.theme);
  const updateSettings = useAppStore((s) => s.updateSettings);
  const setSettingsOpen = useAppStore((s) => s.setSettingsOpen);

  const [sidebarVisible, setSidebarVisible] = useState(true);
  const [sidebarTab, setSidebarTab] = useState<'scenes' | 'resources'>('scenes');

  const activeDoc = documents.find((d) => d.path === activePath) ?? null;

  const toggleTheme = () => updateSettings({ theme: theme === 'dark' ? 'light' : 'dark' });

  return (
    <div className="editor-page">
      <div className="top-bar">
        <Button
          appearance="subtle"
          icon={<ArrowLeftRegular />}
          title="关闭项目"
          onClick={() => confirmClose(() => closeProject())}
        />
        <span className="project-name">{projectName ?? '未命名项目'}</span>

        <span className="top-bar-spacer" />

        <Button
          appearance="subtle"
          icon={theme === 'dark' ? <WeatherSunnyRegular /> : <WeatherMoonRegular />}
          title="切换主题"
          onClick={toggleTheme}
        />
        <Button appearance="subtle" icon={<SettingsRegular />} title="设置" onClick={() => setSettingsOpen(true)} />
      </div>

      <div className="editor-main">
        {sidebarVisible ? (
          <div className="sidebar">
            <div className="sidebar-preview">
              <PreviewPanel />
            </div>
            <div className="sidebar-tabs">
              <button className={sidebarTab === 'scenes' ? 'active' : ''} onClick={() => setSidebarTab('scenes')}>
                场景
              </button>
              <button className={sidebarTab === 'resources' ? 'active' : ''} onClick={() => setSidebarTab('resources')}>
                资源
              </button>
              <button className="sidebar-collapse" title="折叠侧栏" onClick={() => setSidebarVisible(false)}>
                <PanelLeftContractRegular />
              </button>
            </div>
            <div className="sidebar-content">{sidebarTab === 'scenes' ? <SceneBrowser /> : <ResourceBrowser />}</div>
          </div>
        ) : (
          <button className="sidebar-expand" title="展开侧栏" onClick={() => setSidebarVisible(true)}>
            <PanelLeftExpandRegular />
          </button>
        )}

        <div className="editor-workspace">
          <EditorTabs />
          <div className="editor-area">
            {activeDoc ? (
              <CodeEditor doc={activeDoc} />
            ) : (
              <div className="editor-empty">从左侧选择或打开一个场景开始编辑</div>
            )}
          </div>
          <StatusBar />
        </div>
      </div>
    </div>
  );
}
