// This file is generated by AI.

// 引擎管理 (内联组件, 用于设置对话框"引擎"页): 添加/移除引擎 (引用式存储, 不复制)。
//
// 与"模板"页同一套排版与交互: 引用磁盘上的目录而不是把引擎拷进应用数据目录,
// 用户自己升级引擎时这里跟着变。

import { open } from '@tauri-apps/plugin-dialog';
import { Button } from '@fluentui/react-components';
import { AddRegular, DeleteRegular, FolderOpenRegular } from '@fluentui/react-icons';
import { useState } from 'react';

import { makeEngineEntry } from '../lib/engine';
import { validateEngine } from '../lib/engineDir';
import { useAppStore } from '../state/store';

export function EngineManager() {
  const settings = useAppStore((s) => s.settings);
  const updateSettings = useAppStore((s) => s.updateSettings);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  const addEngine = async () => {
    setError(null);
    const dir = await open({ directory: true, title: '选择 WebGAL 引擎目录' });
    if (typeof dir !== 'string') return;
    setBusy(true);
    const result = await validateEngine(dir);
    setBusy(false);
    if (!result.valid) {
      setError(result.error ?? '无效的引擎目录');
      return;
    }
    if (settings.engines.some((engine) => engine.path === dir)) {
      setError('该引擎已添加');
      return;
    }
    updateSettings({
      engines: [
        ...settings.engines,
        makeEngineEntry(dir, { name: result.name, version: result.version, manifestId: result.manifestId }),
      ],
    });
  };

  const removeEngine = (id: string) =>
    updateSettings({ engines: settings.engines.filter((engine) => engine.id !== id) });

  return (
    <div className="manager-section">
      <div className="manager-section-head">
        <h3 className="manager-section-title">引擎</h3>
        <Button appearance="primary" icon={<AddRegular />} disabled={busy} onClick={() => void addEngine()}>
          添加引擎
        </Button>
      </div>

      {settings.engines.length === 0 ? (
        <span className="muted">尚未添加引擎 (项目需自包含 index.html)</span>
      ) : (
        <>
          <ul className="manager-list">
            {settings.engines.map((engine) => (
              <li key={engine.id} className="manager-item" title={engine.path}>
                <FolderOpenRegular />
                <div className="manager-item-content">
                  <div className="manager-item-heading">
                    <span className="manager-item-name">{engine.name}</span>
                    <span className="manager-item-version">{engine.version ? `v${engine.version}` : '版本未知'}</span>
                  </div>
                  <span className="manager-item-path">{engine.path}</span>
                </div>
                <button className="manager-item-remove" title="移除" onClick={() => removeEngine(engine.id)}>
                  <DeleteRegular />
                </button>
              </li>
            ))}
          </ul>
          <p className="manager-hint">引擎在"项目"页里逐个项目选择；目录里带 index.html 的项目用项目内置引擎。</p>
        </>
      )}

      {error ? <p className="prompt-error">{error}</p> : null}
    </div>
  );
}
