// This file is generated by AI.

// Git 差异编辑器: 使用 Monaco DiffEditor 并排展示文件差异 (只读)。
// 采用 WebGAL 语义高亮与 VS Code 风格差异视图 (概览标尺 / 可拖拽分割 / 行内指示),
// 字号等设置与场景编辑器保持同步。

import * as monaco from 'monaco-editor';
import { useEffect, useRef, useState } from 'react';

import { gitCommitDiff, gitDiff, type GitFileDiff } from '../commands/git';
import { LANGUAGE_ID } from '../lsp/monaco';
import { useAppStore, type DiffTab } from '../state/store';

export function GitDiffEditor({ tab }: { tab: DiffTab }) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [message, setMessage] = useState<string | null>(null);

  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;
    const projectPath = useAppStore.getState().projectPath;
    if (!projectPath) return;

    let cancelled = false;
    let diffEditor: monaco.editor.IStandaloneDiffEditor | null = null;

    setMessage(null);
    void (async () => {
      let diff: GitFileDiff;
      try {
        diff =
          tab.kind === 'commit' && tab.commitId
            ? await gitCommitDiff(projectPath, tab.file, tab.commitId)
            : await gitDiff(projectPath, tab.file, tab.kind === 'staged' ? 'staged' : 'unstaged');
      } catch (e) {
        if (!cancelled) setMessage(`加载差异失败：${String(e)}`);
        return;
      }
      if (cancelled) return;
      if (diff.binary) {
        setMessage('二进制文件，无法展示文本差异');
        return;
      }

      const settings = useAppStore.getState().settings;
      const original = monaco.editor.createModel(
        diff.original,
        LANGUAGE_ID,
        monaco.Uri.from({ scheme: 'inmemory', authority: 'git-diff', path: `/${diff.originalLabel}` })
      );
      const modified = monaco.editor.createModel(
        diff.modified,
        LANGUAGE_ID,
        monaco.Uri.from({ scheme: 'inmemory', authority: 'git-diff', path: `/${diff.modifiedLabel}` })
      );
      diffEditor = monaco.editor.createDiffEditor(container, {
        readOnly: true,
        automaticLayout: true,
        renderSideBySide: true,
        // 空间不足时不折叠为内联, 固定左右分栏
        useInlineViewWhenSpaceIsLimited: false,
        enableSplitViewResizing: true,
        renderOverviewRuler: true,
        renderIndicators: true,
        diffAlgorithm: 'advanced',
        originalEditable: false,
        fontFamily: settings.editorFontFamily,
        fontSize: settings.editorFontSize,
        minimap: { enabled: settings.editorMinimap },
        wordWrap: settings.editorWordWrap ? 'on' : 'off',
        // 显式启用语义高亮 (与 CodeEditor 一致; diff 构造选项类型未声明该键, 故断言)
        'semanticHighlighting.enabled': true,
      } as monaco.editor.IStandaloneDiffEditorConstructionOptions);
      diffEditor.setModel({ original, modified });
    })();

    // 设置变化时热更新
    const settingsSub = useAppStore.subscribe((state, prev) => {
      const s = state.settings;
      const p = prev.settings;
      if (
        !diffEditor ||
        (s.editorFontFamily === p.editorFontFamily &&
          s.editorFontSize === p.editorFontSize &&
          s.editorWordWrap === p.editorWordWrap &&
          s.editorMinimap === p.editorMinimap)
      ) {
        return;
      }
      diffEditor.updateOptions({
        fontFamily: s.editorFontFamily,
        fontSize: s.editorFontSize,
        minimap: { enabled: s.editorMinimap },
        wordWrap: s.editorWordWrap ? 'on' : 'off',
      });
    });

    return () => {
      cancelled = true;
      settingsSub();
      if (diffEditor) {
        // 先销毁编辑器 (解除其对 model 的引用), 再销毁 model, 顺序不可反
        const model = diffEditor.getModel();
        diffEditor.dispose();
        if (model) {
          model.original.dispose();
          model.modified.dispose();
        }
      }
    };
  }, [tab.id]);

  return (
    <div className="git-diff-editor">
      <div ref={containerRef} className="git-diff-editor-host" />
      {message ? <div className="git-diff-editor-message">{message}</div> : null}
    </div>
  );
}
