// This file is generated by AI.

// 场景浏览器: 展示 game/scene 目录, 点击打开场景文件。
// 支持新建场景/文件夹、重命名、删除 (联动已打开选项卡) 与"在文件管理器中打开"。

import {
  CopyRegular,
  DeleteRegular,
  DocumentAddRegular,
  FolderAddRegular,
  OpenFolderRegular,
  RenameRegular,
} from '@fluentui/react-icons';
import { open } from '@tauri-apps/plugin-dialog';
import { revealItemInDir } from '@tauri-apps/plugin-opener';
import { useState } from 'react';

import {
  copyEntryToDirectory,
  browserRelativePath,
  createFile,
  createFolder,
  deletePath,
  ensureSceneExtension,
  renamePath,
  validateName,
} from '../fileops';
import { fs } from '../lib/fs';
import { openFile } from '../project';
import { useAppStore } from '../state/store';
import { ContextMenu } from './ContextMenu';
import { FileBadges } from './FileBadges';
import { FileTree, type FileNode } from './FileTree';
import { ConfirmDialog, NameInputDialog } from './SceneFileDialogs';

type PromptState = { mode: 'newFile' | 'newFolder'; dir: string } | { mode: 'rename'; node: FileNode };

export function SceneBrowser() {
  const projectPath = useAppStore((s) => s.projectPath);
  // 场景浏览器高亮"当前正在编辑的场景": 即活动选项卡为场景类时对应的路径
  const activePath = useAppStore((s) => {
    const tab = s.tabs.find((item) => item.id === s.activeTabId);
    return tab?.kind === 'scene' ? tab.path : null;
  });

  const [refreshKey, setRefreshKey] = useState(0);
  const [menu, setMenu] = useState<{ node: FileNode; x: number; y: number } | null>(null);
  const [prompt, setPrompt] = useState<PromptState | null>(null);
  const [deleting, setDeleting] = useState<FileNode | null>(null);

  if (!projectPath) return <div className="resource-browser empty">未打开项目</div>;

  const targetName = (raw: string, isDir: boolean) => (isDir ? raw : ensureSceneExtension(raw));

  const openMenu = (node: FileNode, e: React.MouseEvent) => {
    e.preventDefault();
    setMenu({ node, x: e.clientX, y: e.clientY });
  };

  const buildBlankMenu = (currentDir: string) => [
    {
      key: 'newScene',
      label: '新建场景',
      icon: <DocumentAddRegular />,
      onClick: () => setPrompt({ mode: 'newFile', dir: currentDir }),
    },
    {
      key: 'importResource',
      label: '添加资源',
      icon: <DocumentAddRegular />,
      onClick: () => void importFilesToDir(currentDir),
    },
    {
      key: 'newFolder',
      label: '新建文件夹',
      icon: <FolderAddRegular />,
      onClick: () => setPrompt({ mode: 'newFolder', dir: currentDir }),
    },
    {
      key: 'reveal',
      label: '在文件管理器中打开',
      icon: <OpenFolderRegular />,
      onClick: () => void revealItemInDir(currentDir),
    },
  ];

  const handleBlankMenu = (currentDir: string, e: React.MouseEvent<HTMLDivElement>) => {
    e.preventDefault();
    setMenu({
      node: { name: '', path: currentDir, rel: '', isDirectory: true, kind: 'other' },
      x: e.clientX,
      y: e.clientY,
    });
  };

  const importFilesToDir = async (dir: string) => {
    const picked = await open({ multiple: true });
    if (!picked) return;
    const list = Array.isArray(picked) ? picked : [picked];
    for (const path of list) {
      const target = await copyEntryToDirectory(path, dir);
      if (target) void revealItemInDir(target);
    }
    setRefreshKey((k) => k + 1);
  };

  const handleDropFiles = async (currentDir: string, event: React.DragEvent<HTMLDivElement>) => {
    const paths = Array.from(event.dataTransfer.files)
      .map((file) => (file as File & { path?: string }).path)
      .filter(Boolean) as string[];
    const fallback = event.dataTransfer.getData('text/uri-list');
    if (paths.length === 0 && fallback) {
      for (const uri of fallback.split(/\r?\n/)) {
        if (uri.startsWith('file://')) {
          paths.push(decodeURIComponent(uri.replace(/^file:\/\//, '').replace(/^\\\?\\/, '')));
        }
      }
    }
    for (const source of paths) {
      await copyEntryToDirectory(source, currentDir);
    }
    if (paths.length > 0) setRefreshKey((k) => k + 1);
  };

  /** 新建/重命名的目标路径与重名校验 */
  const resolveTarget = (raw: string, forNode?: FileNode): { path: string; self: boolean } | { error: string } => {
    const formatErr = validateName(raw);
    if (formatErr) return { error: formatErr };
    if (prompt?.mode === 'rename' && forNode) {
      const finalName = targetName(raw, forNode.isDirectory);
      const target = `${forNode.path.replace(/[\\/]+$/, '')}\\${finalName}`;
      const self = target.replace(/\\/g, '/').toLowerCase() === forNode.path.replace(/\\/g, '/').toLowerCase();
      return { path: target, self };
    }
    if (prompt?.mode === 'newFile' || prompt?.mode === 'newFolder') {
      const finalName = prompt.mode === 'newFile' ? ensureSceneExtension(raw) : raw.trim();
      return { path: `${prompt.dir.replace(/[\\/]+$/, '')}\\${finalName}`, self: false };
    }
    return { error: '无效操作' };
  };

  const validateTarget = async (raw: string): Promise<string | null> => {
    const resolved = resolveTarget(raw, prompt?.mode === 'rename' ? prompt.node : undefined);
    if ('error' in resolved) return resolved.error;
    if (resolved.self) return null; // 仅大小写变化等, 允许
    const exists = await fs.exists(resolved.path);
    return exists.exists ? '同名文件或文件夹已存在' : null;
  };

  const submitPrompt = async (raw: string): Promise<string | null> => {
    if (!prompt) return null;
    try {
      if (prompt.mode === 'rename') {
        const resolved = resolveTarget(raw, prompt.node);
        if ('error' in resolved) return resolved.error;
        await renamePath(prompt.node.path, resolved.path);
      } else if (prompt.mode === 'newFile') {
        const full = await createFile(prompt.dir, ensureSceneExtension(raw));
        void openFile(full); // 新建场景后自动打开
      } else {
        await createFolder(prompt.dir, raw);
      }
      setRefreshKey((k) => k + 1);
      setPrompt(null);
      return null;
    } catch (e) {
      return String(e);
    }
  };

  const submitDelete = async (): Promise<string | null> => {
    if (!deleting) return null;
    try {
      await deletePath(deleting.path);
      setRefreshKey((k) => k + 1);
      setDeleting(null);
      return null;
    } catch (e) {
      return String(e);
    }
  };

  /** 删除确认文案: 提示将被关闭的已打开选项卡 (含未保存警告) */
  const deleteMessage = (() => {
    if (!deleting) return '';
    const documents = useAppStore.getState().documents;
    const norm = deleting.path.replace(/\\/g, '/').toLowerCase();
    const affected = documents.filter((d) => {
      const dn = d.path.replace(/\\/g, '/').toLowerCase();
      return dn === norm || dn.startsWith(norm + '/');
    });
    const kind = deleting.isDirectory ? '目录' : '文件';
    let msg = `确定要删除${kind}“${deleting.name}”吗？将移入回收站，可稍后恢复。`;
    if (affected.length > 0) {
      const dirty = affected.filter((d) => d.dirty).length;
      msg += `\n该${kind}下有 ${affected.length} 个已打开的场景选项卡将被关闭`;
      if (dirty > 0) msg += `，其中 ${dirty} 个有未保存的更改（将丢失）`;
      msg += '。';
    }
    return msg;
  })();

  const promptProps = (() => {
    if (!prompt) return null;
    if (prompt.mode === 'rename') {
      return {
        title: '重命名',
        label: '新名称',
        initialValue: prompt.node.name,
        selectStem: true,
        hint: prompt.node.isDirectory ? undefined : '场景文件未填写扩展名时自动补 .txt',
      };
    }
    if (prompt.mode === 'newFile') {
      return {
        title: '新建场景',
        label: '场景文件名称',
        initialValue: '新建场景.txt',
        hint: '未填写扩展名时自动补 .txt，创建后自动打开',
      };
    }
    return {
      title: '新建文件夹',
      label: '文件夹名称',
      initialValue: '新建文件夹',
    };
  })();

  return (
    <div className="scene-browser">
      <FileTree
        rootPath={`${projectPath}\\game\\scene`}
        selectedPath={activePath}
        refreshKey={refreshKey}
        onItemContextMenu={openMenu}
        badge={(node) => <FileBadges path={node.path} />}
        menu={buildBlankMenu}
        onBlankContextMenu={handleBlankMenu}
        onDropFiles={handleDropFiles}
        onOpen={(file) => {
          void openFile(file.path);
        }}
      />

      {menu ? (
        <ContextMenu
          x={menu.x}
          y={menu.y}
          items={
            menu.node.path === '' || menu.node.name === ''
              ? [
                  {
                    key: 'newScene',
                    label: '新建场景',
                    icon: <DocumentAddRegular />,
                    onClick: () => setPrompt({ mode: 'newFile', dir: menu.node.path }),
                  },
                  {
                    key: 'importResource',
                    label: '添加资源',
                    icon: <DocumentAddRegular />,
                    onClick: () => void importFilesToDir(menu.node.path),
                  },
                  {
                    key: 'newFolder',
                    label: '新建文件夹',
                    icon: <FolderAddRegular />,
                    onClick: () => setPrompt({ mode: 'newFolder', dir: menu.node.path }),
                  },
                  {
                    key: 'reveal',
                    label: '在资源管理器中打开',
                    icon: <OpenFolderRegular />,
                    onClick: () => void revealItemInDir(menu.node.path),
                  },
                ]
              : [
                  {
                    key: 'copyRelativePath',
                    label: '复制相对路径',
                    icon: <CopyRegular />,
                    onClick: async () => {
                      const rel = browserRelativePath(projectPath, menu.node.path);
                      await navigator.clipboard.writeText(rel);
                    },
                  },
                  {
                    key: 'reveal',
                    label: '在文件管理器中打开',
                    icon: <OpenFolderRegular />,
                    onClick: () => void revealItemInDir(menu.node.path),
                  },
                  {
                    key: 'rename',
                    label: '重命名',
                    icon: <RenameRegular />,
                    onClick: () => setPrompt({ mode: 'rename', node: menu.node }),
                  },
                  {
                    key: 'delete',
                    label: '删除',
                    icon: <DeleteRegular />,
                    danger: true,
                    onClick: () => setDeleting(menu.node),
                  },
                ]
          }
          onClose={() => setMenu(null)}
        />
      ) : null}

      {prompt && promptProps ? (
        <NameInputDialog
          title={promptProps.title}
          label={promptProps.label}
          initialValue={promptProps.initialValue}
          selectStem={promptProps.selectStem}
          hint={promptProps.hint}
          submitLabel={prompt.mode === 'rename' ? '重命名' : '创建'}
          validate={validateTarget}
          onSubmit={submitPrompt}
          onClose={() => setPrompt(null)}
        />
      ) : null}

      {deleting ? (
        <ConfirmDialog
          title={`删除${deleting.isDirectory ? '文件夹' : '文件'}`}
          message={deleteMessage}
          confirmLabel="删除"
          danger
          onConfirm={submitDelete}
          onClose={() => setDeleting(null)}
        />
      ) : null}
    </div>
  );
}
