// This file is generated by AI.

// 设置对话框: 左侧分类导航 + 右侧设置项 (通用 / 编辑器)。
//
// 使用自绘模态层 (position: fixed + 点击遮罩关闭), 不依赖弹层类 UI 组件,
// 避免在 WebView 中弹层定位/动画异常导致的白屏与闪动问题。
// 主题切换统一由顶栏/欢迎页的按钮完成; 预览开关在预览面板工具栏上。

import { open } from '@tauri-apps/plugin-dialog';
import { Button, Input, Switch } from '@fluentui/react-components';
import { FolderOpenRegular } from '@fluentui/react-icons';
import { useState } from 'react';

import { useAppStore } from '../state/store';
import type { Settings } from '../lib/settings';

type SettingsCategory = 'general' | 'editor';

const CATEGORIES: { id: SettingsCategory; label: string }[] = [
  { id: 'general', label: '通用' },
  { id: 'editor', label: '编辑器' },
];

export function SettingsDialog() {
  const settingsOpen = useAppStore((s) => s.settingsOpen);
  const setSettingsOpen = useAppStore((s) => s.setSettingsOpen);
  const settings = useAppStore((s) => s.settings);
  const updateSettings = useAppStore((s) => s.updateSettings);
  const [category, setCategory] = useState<SettingsCategory>('general');

  if (!settingsOpen) return null;

  const pickEngine = async () => {
    const dir = await open({ directory: true, title: '选择 WebGAL 引擎目录' });
    if (typeof dir === 'string') updateSettings({ enginePath: dir });
  };

  const updateNumber = (key: 'editorFontSize' | 'editorTabSize', raw: string, min: number, max: number) => {
    const n = Number(raw);
    if (!Number.isFinite(n)) return;
    updateSettings({ [key]: Math.min(max, Math.max(min, Math.round(n))) } as Partial<Settings>);
  };

  return (
    <div className="modal-backdrop" onClick={() => setSettingsOpen(false)}>
      <div className="modal-surface settings-surface" onClick={(e) => e.stopPropagation()}>
        <h2 className="modal-title">设置</h2>

        <div className="settings-layout">
          <nav className="settings-nav">
            {CATEGORIES.map((c) => (
              <button
                key={c.id}
                className={`settings-nav-item${category === c.id ? ' active' : ''}`}
                onClick={() => setCategory(c.id)}
              >
                {c.label}
              </button>
            ))}
          </nav>

          <div className="settings-content">
            {category === 'general' && (
              <div className="settings-group">
                <h3 className="settings-group-title">通用</h3>

                <div className="settings-field">
                  <span className="settings-label">WebGAL 引擎目录</span>
                  <div className="engine-path-row">
                    <Input value={settings.enginePath ?? ''} readOnly placeholder="未设置 (项目需自包含 index.html)" />
                    <Button icon={<FolderOpenRegular />} onClick={() => void pickEngine()}>
                      选择…
                    </Button>
                  </div>
                </div>

                <div className="settings-field">
                  <Button appearance="secondary" onClick={() => updateSettings({ recentProjects: [] })}>
                    清除最近项目
                  </Button>
                </div>
              </div>
            )}

            {category === 'editor' && (
              <div className="settings-group">
                <h3 className="settings-group-title">编辑器</h3>

                <div className="settings-field">
                  <Switch
                    checked={settings.autoSave}
                    onChange={(_, data) => updateSettings({ autoSave: data.checked })}
                    label="自动保存"
                  />
                </div>

                <div className="settings-field">
                  <span className="settings-label">字体</span>
                  <Input
                    value={settings.editorFontFamily}
                    placeholder="FiraCode, SourceHanSans, Consolas, monospace"
                    onChange={(_, data) => updateSettings({ editorFontFamily: data.value })}
                  />
                </div>

                <div className="settings-field settings-field-inline">
                  <span className="settings-label">字号</span>
                  <Input
                    type="number"
                    min={8}
                    max={48}
                    value={String(settings.editorFontSize)}
                    onChange={(_, data) => updateNumber('editorFontSize', data.value, 8, 48)}
                  />
                </div>

                <div className="settings-field">
                  <Switch
                    checked={settings.editorWordWrap}
                    onChange={(_, data) => updateSettings({ editorWordWrap: data.checked })}
                    label="自动换行"
                  />
                </div>

                <div className="settings-field">
                  <Switch
                    checked={settings.editorMinimap}
                    onChange={(_, data) => updateSettings({ editorMinimap: data.checked })}
                    label="迷你地图"
                  />
                </div>

                <div className="settings-field settings-field-inline">
                  <span className="settings-label">制表符大小</span>
                  <Input
                    type="number"
                    min={2}
                    max={8}
                    value={String(settings.editorTabSize)}
                    onChange={(_, data) => updateNumber('editorTabSize', data.value, 2, 8)}
                  />
                </div>
              </div>
            )}
          </div>
        </div>

        <div className="modal-actions">
          <Button appearance="primary" onClick={() => setSettingsOpen(false)}>
            关闭
          </Button>
        </div>
      </div>
    </div>
  );
}
