// This file is generated by AI.

//! WebGAL 内联表达式求值库
//!
//! 解析并求值 WebGAL 脚本中的内联表达式, 例如 `setVar:var=expr` 中的 `expr`
//! 与语句的 `-when=expr` 条件.
//!
//! # Behavior
//! * 求值不维护任何变量或函数状态, 全部由调用者通过 [`EvaluationContext`] 提供.
//! * 值只有数值, 布尔与字符串三种, 不支持对象与数组. 数值区分整数与浮点数, 整数结果保持整数表示.
//! * 不内置任何函数, `random` 等由调用者注册.
//! * 刻意不支持赋值, 成员访问, `$` 内置变量域等 WebGAL / JS 特性, 作为规范.
//!
//! # 表达式语法
//! * 字面量: 数字 (`1`, `1.5`, `.5`, `1e3`), 字符串 (`'...'` / `"..."`, 含转义), `true` / `false`.
//! * 标识符: `[a-zA-Z_][a-zA-Z0-9_]*`, 用作变量引用或函数名; 其余裸词 (如 `人物名称`) 回退为字符串.
//! * 运算符: 一元 `!` `-` `+`; 二元 `+ - * / %`, `== != < > <= >=`, `&& ||` (短路); 三元 `cond ? a : b`.
//! * 括号与函数调用: `f(a, b)`.

use std::str::FromStr;

pub use error::{Error, EvaluationError, ParseError, ParseErrorKind, Result};
pub use evaluate::{EmptyEvaluationContext, EvaluationContext};
pub use parse::{EmptyTypeContext, Expression, TypeContext};
pub use value::{Number, Value, ValueKind};

mod error;
mod evaluate;
mod parse;
mod value;

/// 解析并求值一步完成
///
/// 等价于 [`Expression`] 的 [`FromStr`] 解析后调用 [`Expression::evaluate`], 适合一次性求值;
/// 需要对同一表达式使用不同上下文多次求值时, 请使用 [`Expression`].
///
/// # Examples
///
/// ```
/// use expression::{Error, EvaluationContext, EvaluationError, Value, evaluate};
///
/// /// 调用者提供的上下文: 变量与函数
/// struct Ctx;
///
/// impl EvaluationContext for Ctx {
///     fn get_variable(&self, name: &str) -> Option<Value> {
///         match name {
///             "hp" => Some(Value::from(70)),
///             "name" => Some(Value::from("主角")),
///             _ => None,
///         }
///     }
///
///     fn call_function(&self, name: &str, arguments: &[Value]) -> Result<Value, EvaluationError> {
///         match name {
///             "random" => Ok(Value::from(3)), // random 的语义由调用者决定
///             _ => Err(EvaluationError::UnknownFunction(name.into())),
///         }
///     }
/// }
///
/// # fn main() -> Result<(), Error> {
/// assert_eq!(evaluate("hp - 30", &Ctx)?, Value::from(40));
/// assert_eq!(evaluate("name + \"先生\"", &Ctx)?, Value::from("主角先生"));
/// assert_eq!(evaluate("hp > 0 && name != \"\"", &Ctx)?, Value::from(true));
/// assert_eq!(evaluate("random(1, 10)", &Ctx)?, Value::from(3));
/// # Ok(())
/// # }
/// ```
pub fn evaluate(source: &str, context: &dyn EvaluationContext) -> Result<Value> {
    Expression::from_str(source)?
        .evaluate(context)
        .map_err(Error::Evaluation)
}

/// 无上下文求值
///
/// 表达式只能使用字面量与运算符, 引用变量或调用函数时返回 `None`.
pub fn evaluate_constantly(source: &str) -> Option<Value> {
    Expression::from_str(source)
        .ok()?
        .evaluate(&EmptyEvaluationContext)
        .ok()
}
