//! 工作区多项目管理与路由

use std::sync::Arc;

use anyhow::{Result, anyhow};
use derive_more::{From, Into};
use path_tree::{Entry, Folder, Node, PATH_SEPARATORS, join, split_path_once};
use tokio::sync::RwLock;

use crate::project::Project;

/// WebGAL 项目工作区管理
#[derive(Debug, Default)]
pub struct Workspace {
    projects: Folder<Arc<RwLock<Project>>>,
}

impl Workspace {
    pub fn new() -> Self {
        Self::default()
    }

    /// 获取资源所在项目
    ///
    /// # Arguments
    /// * **path** - 资源规范 URI.
    ///
    /// # Behavior
    /// * 相对路径 (`.`, `..`) 将被视为目录名, 而不执行跳跃.
    pub fn get(&self, path: &str) -> Option<GetProjectResult> {
        let (root, mut remain) = split_root(path);
        remain = remain.trim_start_matches(PATH_SEPARATORS);

        let mut folder = &self.projects;
        if !root.is_empty() {
            folder = folder.get(root)?.as_folder()?;
        }

        while !remain.is_empty() {
            let (name, next_remain) = split_path_once(remain);
            remain = next_remain.unwrap_or("");

            match folder.get(name) {
                Some(Node::Item(project)) => {
                    let len = path.len() - remain.len();

                    return Some(GetProjectResult {
                        project_path: path[..len].trim_end_matches(PATH_SEPARATORS).to_string(),
                        resource_path: remain.trim_end_matches(PATH_SEPARATORS).to_string(),
                        project: project.clone(),
                    });
                }

                Some(Node::Folder(next)) => {
                    folder = next;
                }

                _ => break,
            }
        }

        None
    }

    /// 插入项目
    ///
    /// # Arguments
    /// * **path** - 项目根目录规范 URI.
    ///
    /// # Errors
    /// 插入位置父目录或子目录已存在项目时报错 (禁止嵌套).
    ///
    /// # Behavior
    /// * 相对路径 (`.`, `..`) 将被视为目录名, 而不执行跳跃.
    pub fn insert(&mut self, path: &str, project: Project) -> Result<Arc<RwLock<Project>>> {
        let path = canonicalize(path);
        let entry = match self
            .projects
            .entry(&path)
            .map_err(|_| anyhow!("项目 `{path}` 不能嵌套于其他项目下"))?
        {
            Entry::Occupied(_) => return Err(anyhow!("项目 `{path}` 下不能有嵌套子项目")),
            Entry::Vacant(v) => v,
        };
        let project = Arc::new(RwLock::new(project));
        entry.insert_entry(Node::Item(project.clone()));
        Ok(project)
    }

    /// 删除项目
    ///
    /// # Arguments
    /// * **path** - 项目根目录规范 URI.
    ///
    /// # Behavior
    /// * 相对路径 (`.`, `..`) 将被视为目录名, 而不执行跳跃.
    pub fn remove(&mut self, path: &str) -> Option<Arc<RwLock<Project>>> {
        let path = canonicalize(path);
        let entry = self.projects.entry(&path).ok()?;
        if let Entry::Occupied(o) = entry
            && o.get().is_item()
        {
            Some(o.remove().into_item().unwrap())
        } else {
            None
        }
    }

    /// 移除根目录下的全部项目
    ///
    /// # Arguments
    /// * **root** - 目录规范 URI.
    ///
    /// # Behavior
    /// * 相对路径 (`.`, `..`) 将被视为目录名, 而不执行跳跃.
    pub fn remove_all_under(&mut self, root: &str) -> Option<Node<Arc<RwLock<Project>>>> {
        let root = canonicalize(root);
        self.projects.remove(&root)
    }
}

#[derive(Debug, Clone, Default, From, Into)]
pub struct GetProjectResult {
    /// 项目根目录的 URI
    pub project_path: String,
    /// 资源相对于项目根目录的路径
    pub resource_path: String,
    pub project: Arc<RwLock<Project>>,
}

fn split_root(path: &str) -> (&str, &str) {
    path.split_once("://").unwrap_or(("", path))
}

/// 整理规范 URI (形如 `root://...`) 为 `root/...`
fn canonicalize(path: &str) -> String {
    let (root, path) = split_root(path);
    join(root, path)
}

#[cfg(test)]
mod tests {
    // This module is generated by AI.

    use super::*;

    // -------- helpers --------

    fn make_project() -> Project {
        Project::default()
    }

    fn insert_project(ws: &mut Workspace, uri: &str) -> Arc<RwLock<Project>> {
        ws.insert(uri, make_project()).unwrap()
    }

    // -------- insert and get --------

    #[test]
    fn test_insert_and_get_simple() {
        let mut ws = Workspace::new();
        let proj_arc = insert_project(&mut ws, "file:///C:/game");

        let result = ws.get("file:///C:/game/scene/start.txt").unwrap();
        assert_eq!(result.project_path, "file:///C:/game");
        assert_eq!(result.resource_path, "scene/start.txt");
        assert!(Arc::ptr_eq(&result.project, &proj_arc));
    }

    #[test]
    fn test_get_project_root_itself() {
        let mut ws = Workspace::new();
        let proj_arc = insert_project(&mut ws, "file:///C:/game");

        let result = ws.get("file:///C:/game").unwrap();
        assert_eq!(result.project_path, "file:///C:/game");
        assert_eq!(result.resource_path, "");
        assert!(Arc::ptr_eq(&result.project, &proj_arc));
    }

    #[test]
    fn test_get_with_trailing_slash() {
        let mut ws = Workspace::new();
        insert_project(&mut ws, "file:///C:/game");

        let result = ws.get("file:///C:/game/scene/start.txt/").unwrap();
        // Trailing slash should be stripped from resource_path
        assert_eq!(result.resource_path, "scene/start.txt");
    }

    #[test]
    fn test_insert_without_scheme() {
        let mut ws = Workspace::new();
        insert_project(&mut ws, "C:/game");

        let result = ws.get("C:/game/scene/start.txt").unwrap();
        assert_eq!(result.project_path, "C:/game");
        assert_eq!(result.resource_path, "scene/start.txt");
    }

    // -------- nested projects are disallowed --------

    #[test]
    fn test_insert_nested_project_disallowed() {
        let mut ws = Workspace::new();
        // Insert parent project
        insert_project(&mut ws, "file:///C:/workspace");
        // Attempt to insert child project should fail
        let result = ws.insert("file:///C:/workspace/sub", make_project());
        assert!(result.is_err());
    }

    #[test]
    fn test_insert_parent_over_child_disallowed() {
        let mut ws = Workspace::new();
        // Insert child project first
        insert_project(&mut ws, "file:///C:/workspace/sub");
        // Attempt to insert parent project should also fail
        let result = ws.insert("file:///C:/workspace", make_project());
        assert!(result.is_err());
    }

    // -------- not found --------

    #[test]
    fn test_get_not_found() {
        let mut ws = Workspace::new();
        insert_project(&mut ws, "file:///C:/game");

        assert!(ws.get("file:///D:/other").is_none());
        assert!(ws.get("file:///C:/gam").is_none());

        let result = ws.get("file:///C:/game/../outside").unwrap();
        assert_eq!(result.resource_path, "../outside");
    }

    // -------- remove --------

    #[test]
    fn test_remove_project() {
        let mut ws = Workspace::new();
        insert_project(&mut ws, "file:///C:/game");

        let removed = ws.remove("file:///C:/game");
        assert!(removed.is_some());

        assert!(ws.get("file:///C:/game/scene/start.txt").is_none());
    }

    #[test]
    fn test_remove_all_under() {
        let mut ws = Workspace::new();
        // Insert two projects under the same root (but not nested)
        insert_project(&mut ws, "file:///C:/root/proj1");
        insert_project(&mut ws, "file:///C:/root/proj2");

        let removed_node = ws.remove_all_under("file:///C:/root");
        assert!(removed_node.is_some());

        assert!(ws.get("file:///C:/root/proj1/scene/a.txt").is_none());
        assert!(ws.get("file:///C:/root/proj2/scene/b.txt").is_none());
    }
}
