// This file is generated by AI.

// 选项卡序列的纯函数。
//
// 抽出来的原因: 新增/关闭/重排的顺序规则容易被后续改动破坏, 而这些规则都是
// "给定序列与操作, 得出新序列与新的活动项"的纯逻辑, 适合单测覆盖。

import type { WorkbenchTabItem } from './model';

/** 把新选项卡插到活动选项卡之后 (与其他编辑器一致); 无活动项则追加到末尾 */
export function insertTab(
  tabs: WorkbenchTabItem[],
  tab: WorkbenchTabItem,
  activeId: string | null
): {
  tabs: WorkbenchTabItem[];
  activeId: string;
} {
  const existing = tabs.findIndex((item) => item.id === tab.id);
  if (existing >= 0) {
    // 已存在: 只更新内容并激活, 不改变位置
    const next = [...tabs];
    next[existing] = tab;
    return { tabs: next, activeId: tab.id };
  }
  if (activeId === null) {
    return { tabs: [...tabs, tab], activeId: tab.id };
  }
  const at = tabs.findIndex((item) => item.id === activeId);
  if (at < 0) {
    return { tabs: [...tabs, tab], activeId: tab.id };
  }
  const next = [...tabs];
  next.splice(at + 1, 0, tab);
  return { tabs: next, activeId: tab.id };
}

/**
 * 关闭选项卡。
 *
 * 关闭活动项时优先激活它**右侧**的邻居 (与浏览器一致), 没有则取左侧。
 */
export function closeTab(
  tabs: WorkbenchTabItem[],
  id: string,
  activeId: string | null
): { tabs: WorkbenchTabItem[]; activeId: string | null } {
  const at = tabs.findIndex((item) => item.id === id);
  if (at < 0) return { tabs, activeId };
  const next = tabs.filter((item) => item.id !== id);
  if (activeId !== id) return { tabs: next, activeId };
  if (next.length === 0) return { tabs: next, activeId: null };
  const fallback = next[Math.min(at, next.length - 1)];
  return { tabs: next, activeId: fallback.id };
}

/**
 * 把 `id` 移动到 `toIndex` 位置。
 *
 * 与场景浏览器等处的语义一致: `toIndex` 是**目标槽位**, 而非"插入到第几项之前"。
 */
export function moveTab(tabs: WorkbenchTabItem[], id: string, toIndex: number): WorkbenchTabItem[] {
  const from = tabs.findIndex((item) => item.id === id);
  if (from < 0) return tabs;
  const clamped = Math.max(0, Math.min(toIndex, tabs.length - 1));
  if (from === clamped) return tabs;
  const next = [...tabs];
  const [tab] = next.splice(from, 1);
  next.splice(clamped, 0, tab);
  return next;
}

/** 关闭某一类选项卡 (退出项目时清理) */
export function removeTabsByKind(tabs: WorkbenchTabItem[], kind: WorkbenchTabItem['kind']): WorkbenchTabItem[] {
  return tabs.filter((tab) => tab.kind !== kind);
}
